### ISSUE TITLE
Flow Runs fail with DBAPIError (sqlalchemy) - QueryCanceledError

### ISSUE THREAD

**Issue by prefectcboyd** [PrefectHQ/prefect#8435] opened 2023-02-07 16:50 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Flow runs for a number of users are experiencing errors for previously successful flow runs. 
At the moment, there does not seem to be a consistent them in when, or how the error is generated.
It is erratic in both timing, reproduction, and flow.
The issue has been reported on at least `2.7.10` and `2.7.11`, potentially more.

Community Tracking Threads:
https://prefect-community.slack.com/archives/CL09KU1K7/p1675390311559929
https://prefect-community.slack.com/archives/CL09KU1K7/p1675454691145409?thread_ts=1675449149.527989&cid=CL09KU1K7
https://prefect-community.slack.com/archives/CL09KU1K7/p1675296054694959

### Reproduction

```python3
## Unknown at this point in time how to reproduce.
```

### Error

```python3
Task run '6a621f32-e889-4b37-a271-b38294142f4b' received abort during orchestration: Error validating state: DBAPIError("(sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.QueryCanceledError'>: canceling statement due to statement timeout") Task run is in RUNNING state.

MissingResult: State data is missing. Typically, this occurs when result persistence is disabled and the state has been retrieved from the API.
```

### Versions

```Text
prefect version
Version:             2.7.11
API version:         0.8.4
Python version:      3.9.14
Git commit:          6b27b476
Built:               Thu, Feb 2, 2023 7:22 PM
OS/Arch:             darwin/arm64
Profile:             internal_kube
Server type:         cloud
```

**Comment by ccueto36** [comment] 2023-02-07 22:56
See below WARNING that occurs right before the ERROR stated on the issue. Below traceback example of failed flow run today:


```python
**WARNING**
Task run '61240192-4c30-4f72-bf80-cf73e974b617' received abort during orchestration: Error validating state: DBAPIError("(sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.QueryCanceledError'>: canceling statement due to statement timeout") Task run is in RUNNING state.

**ERROR**
Traceback (most recent call last):
  File "C:\scripts\prefect2\lib\site-packages\prefect\engine.py", line 640, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "C:\scripts\prefect2\lib\site-packages\prefect\utilities\asyncutils.py", line 154, in run_sync_in_interruptible_worker_thread
    async with anyio.create_task_group() as tg:
  File "C:\scripts\prefect2\lib\site-packages\anyio\_backends\_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "C:\scripts\prefect2\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\scripts\prefect2\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\scripts\prefect2\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\scripts\prefect2\lib\site-packages\prefect\utilities\asyncutils.py", line 135, in capture_worker_thread_and_result
    result = __fn(*args, **kwargs)
  File "C:\WINDOWS\TEMP\tmpsio1cx9jprefect\flows\Python\Azure\fetch_aad_groups.py", line 113, in get_azure_aad_groups
    write_results_to_snowflake(groups_with_members)
  File "C:\scripts\prefect2\lib\site-packages\prefect\tasks.py", line 448, in __call__
    return enter_task_run_engine(
  File "C:\scripts\prefect2\lib\site-packages\prefect\engine.py", line 930, in enter_task_run_engine
    return run_async_from_worker_thread(begin_run)
  File "C:\scripts\prefect2\lib\site-packages\prefect\utilities\asyncutils.py", line 177, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "C:\scripts\prefect2\lib\site-packages\anyio\from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "C:\scripts\prefect2\lib\site-packages\anyio\_backends\_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "C:\python310\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\scripts\prefect2\lib\site-packages\prefect\engine.py", line 1079, in get_task_call_return_value
    return await future._result()
  File "C:\scripts\prefect2\lib\site-packages\prefect\futures.py", line 237, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "C:\scripts\prefect2\lib\site-packages\prefect\states.py", line 101, in _get_state_result
    raise MissingResult(
prefect.exceptions.MissingResult: State data is missing. Typically, this occurs when result persistence is disabled and the state has been retrieved from the API.```

**Comment by skohlleffel** [comment] 2023-02-09 17:06
We've seen the above issue outlined by @ccueto36. The issue is not specific to one flow and is not reproducible. The task runs fail with the raised `MissingResult` error.

However, we've more recently started seeing an issue where a small minority of our task runs in one of our flows warn with the following:
`Task run 'daeb49e7-08ba-489b-be12-a0955f34d909' received abort during orchestration: Error validating state: DBAPIError("(sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.QueryCanceledError'>: canceling statement due to statement timeout") Task run is in RUNNING state.`

However, an error isn't raised, so the task remains in a `running` state, but doesn't complete execution. The flow itself timed out after a period of time.

#### Task Run Example
![image](https://user-images.githubusercontent.com/56320461/217852460-de79d59a-7ac3-4ba3-a971-ae4335f92459.png)

#### Task Definition
![image](https://user-images.githubusercontent.com/56320461/217858125-78befbf2-62be-403b-bfd2-7ff25dcbb4f9.png)

The above task executes a query in Snowflake. Immediately before the query is executed in Snowflake, we log the query for debugging purposes. I checked Snowflake and the query was never submitted for execution. So, the task ran into an issue sometime between printing the query and executing the query. It shouldn't take more than a minute to execute and, in the past, we haven't run into any issues. This flow submits ~1000 of these task runs concurrently and about 5% of those runs ran into this issue.

**Comment by taljaards** [comment] 2023-02-13 07:31
I believe this is fixed by https://github.com/PrefectHQ/prefect/pull/8425#issuecomment-1425995162?

https://prefect-community.slack.com/archives/CL09KU1K7/p1676051970044899?thread_ts=1675449149.527989&cid=CL09KU1K7:
![image](https://user-images.githubusercontent.com/6089256/218396621-cf6cd253-790c-44c4-a6bd-2bc96f591fcc.png)

**Comment by madkinsz** [comment] 2023-02-13 15:25
Thanks @taljaards

**Closed by madkinsz** 2023-02-13 15:25 UTC
Labels: bug, priority:high, status:in-progress
