### ISSUE TITLE
Subflows fired with `run_deployment` cause parent to be incorrectly marked as failed - if they crash but then succeed

### ISSUE THREAD

**Issue by klayhb** [PrefectHQ/prefect#10620] opened 2023-09-04 15:00 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When firing flow runs using `run_deployment` from within some parent flow (at least in k8s infra) - the child flows might **crash** (for example due to K8s eviction, or other arbitrary causes), upon which they are typically retried by the infra (depending on config). 

However,  it seems that Prefect immediately considers this as a (terminal) failure of the subflow.

In the UI itself, we later see the subflow as green (`Completed`) since it was rerun successfully by the infra, but the parent flow is overall in a failed state (way before the subflow finishes)

### Reproduction

```python3
@flow
def parent_flow():
   fut = await run_deployment('my_cool_subflow/my_cool_deployment')
   return [fut.state]
```

then manually evict the running subflow at the infra level but let k8s retry it and succeed

### Error

```python3
Finished in state Failed('1/1 states failed.')
```

### Versions

```Text
Version:             2.11.3
API version:         0.8.4
Python version:      3.9.18
Git commit:          3a400865
Built:               Thu, Aug 3, 2023 3:24 PM
OS/Arch:             darwin/x86_64
Profile:             default
Server type:         cloud
```

### Additional context

Our actual agent (and jobs) are running 2.11.4 i believe.
If it matters - the subflow uses a RayTaskRunner (local, not distributed)

For top-level flows - Prefect seems to normally recognize that Crashes aren't failures and simply acknowledges if/when the infra decides to rerun the job in another pod or container (i'm guessing using the **watch** functionality).
For subflows, this doesn't seem to be happening, so we get this weird "hybrid" situation where the "operation succeeded but the patient died" (i.e. - the job itself was performed successfully and even recognized as such, but the "initiator" of it fails to understand this)

**Comment by WillRaphaelson** [comment] 2023-09-05 15:46
Im not sure ont he exact path forward here, but I do think there's some reconciliation of state that can/should happen here if a subflow ultimately succeeds.

**Comment by klayhb** [comment] 2023-09-05 16:04
Our problem is less with the final state of the parent flow, and more with
the fact it's generating false alarms for us on non-failures ,

(we have an automation that fires a notification to our slack on flow
failure )

Since prefect already uses the job watch I guess it could simply use it to
know if the k8s exhausted it retries or not..?  ( I don't know , I'm not an
expert on k8s)

**Comment by chrisguidry** [comment] 2023-09-14 20:33
Hi @klayhb, can you share what your infrastructure job template looks like?  Where are you setting the 6 attempts?

**Comment by klayhb** [comment] 2023-09-14 21:28
hi @chrisguidry  -
we (the data team here that uses Prefect) are not actually setting the 6 attempts, I believe that's the default in our K8s cluster.

this is what the template looks like:

```json
{
  "kind": "Job",
  "spec": {
    "template": {
      "spec": {
        "containers": [
          {
            "env": [],
            "name": "prefect-job"
          }
        ],
        "completions": 1,
        "parallelism": 1,
        "restartPolicy": "Never"
      }
    }
  },
  "apiVersion": "batch/v1"
}
```

it took us a while (since we're not fluent in k8s) to figure out that the `restartPolicy` relates to the pod and NOT to the job. So, the job WILL get restart with this config, up to the (default) `backoffLimit` (which happens to be 6).
We are fine with that behavior,  since it's useful that infra issues will appear (correctly) as Crashes in Prefect and will be retried at the infra level,

Our issue is just with the fact that because Crash is considered a terminal state, this causes the anomalous behavior I described above. I think the correct interpretation for Crash should actually NOT be a terminal state, or - alternatively, a new intermediate state like "InfraRetry" or whatever should be established to prevent flows from incorrectly being marked as "failed" when they actually succeeded.

**Comment by urimandujano** [comment] 2023-09-15 15:52
@klayhb, can you share these details to help me replicate the problem you're seeing:

- how are you submitting the jobs to K8s? Are you using [prefect-kubernetes](https://prefecthq.github.io/prefect-kubernetes/)?
- if yes to the above, can you share which version of prefect-kubernetes you're using via `pip show prefect-kubernetes`?
- can you share what the parent flow/subflow errors look like?

**Comment by klayhb** [comment] 2023-09-18 08:23
@urimandujano  

- no, we have a k8s Prefect agent and it runs the flows for us as KubernetesJob, but we don't seem to be using `prefect-kubernetes` but rather the core Prefect infrastructure:
https://github.com/PrefectHQ/prefect/blob/main/src/prefect/infrastructure/kubernetes.py
-  there is no error - the pod just crashes at the infra level (for example due to an eviction, we don't really know since we haven't managed to "catch" it red-handed yet and we have limited access to our k8s cluster as a data team) - and then the job is restarted (again, at the **infra** level) in another pod and then succeeds. 
- the parent flow from its perspective just sees a Crashed state subflow and then returns its state,  while in the background the "real" subflow continues to run a 2nd time and succeeds but without any parent being aware of this.

**Comment by urimandujano** [comment] 2023-09-21 19:45
Hey there! I've been having some trouble replicating this issue. My setup looks like this:

- prefect agent (v 2.11.3)
- prefect client triggering flow runs (v 2.11.3)
- a parent flow triggering a deployment run using `run_deployment` 
  - the deployment uses a `KubernetesJob` as its infrastructure
  - the `KubernetesJob` is using the image `prefecthq/prefect:2.11-python3.8`
- K8s client+server v1.27.2

I've tried manually deleting pods from the running job and having the pods evicted due to OOM issues, and in both cases the parent flow correctly waits on the subflow's final result (including retries) before reporting itself as successful/failed. What's interesting to me is that even when I messed with the running pods, the subflow was not marked as crashed or failed.

Is there any more info you can share to help replicate this? It would be helpful to confirm the prefect agent version, prefect client version (if the parent flow is kicked off manually), the K8s version, and if there's any custom image being used in the job.  It would also help to know the types of things happening that cause the crash -- maybe your Infra team has insight into this?

**Comment by klayhb** [comment] 2023-09-21 23:06
Hi, I could give more details after the holiday here , but - when you say
retries , you mean k8s retries or prefect retries ?

**Comment by urimandujano** [comment] 2024-02-27 22:59
Hi @klayhb, let me know if you're still seeing this issue and can provide more details about how to reproduce? In the meantime I'm going to close this.

**Closed by urimandujano** 2024-02-27 22:59 UTC
Labels: bug
