### ISSUE TITLE
Flow Run fails with Unexpected error: SystemError('unknown opcode')

### ISSUE THREAD

**Issue by JacobDorM** [PrefectHQ/prefect#3635] opened 2020-11-10 06:49 UTC
## Description

**Python file in my IDE VScode:**
from prefect import Task, Flow

class AddTask(Task):

    def __init__(self, default: int, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.default= default

    def run(self, x: int, y: int=None) -> int:
        if y is None:
            y = self.default
        print(x + y)
        return x + y

add = AddTask(default=1)

with Flow("My first flow!") as f:
    first_result = add(1, y=2)
    second_result = add(x=first_result, y=100)

f.register(project_name="Hello")

**Flow run SUCCESS- locally:**
[2020-11-10 08:14:02+0200] INFO - prefect.FlowRunner | Beginning Flow run for 'My first flow!'
[2020-11-10 08:14:02+0200] INFO - prefect.TaskRunner | Task 'AddTask': Starting task run...
3
[2020-11-10 08:14:02+0200] INFO - prefect.TaskRunner | Task 'AddTask': Finished task run for task with final state: 'Success'
[2020-11-10 08:14:02+0200] INFO - prefect.TaskRunner | Task 'AddTask': Starting task run...
103
[2020-11-10 08:14:02+0200] INFO - prefect.TaskRunner | Task 'AddTask': Finished task run for task with final state: 'Success'
[2020-11-10 08:14:02+0200] INFO - prefect.FlowRunner | Flow run SUCCESS: all reference tasks succeeded

**Flow run in http://localhost:8080:**
**AddTask failed:**
Unexpected error: SystemError('unknown opcode')
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\prefect\engine\runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "c:\python38\lib\site-packages\prefect\engine\task_runner.py", line 845, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "c:\python38\lib\site-packages\prefect\utilities\executors.py", line 298, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "C:\Users\Dor\Desktop\Self-develop\enterprenuer\exp0se\learning\ETL\frameworks\prefect\code\firstSteps\tasks\taskClasses.py", line 12, in run
    if y is None:
SystemError: unknown opcode

## Expected Behavior
My flow to run and complete successfully
(Note: flow run successfully when run locally)

## Reproduction
Unexpected error: SystemError('unknown opcode')
if y is None: SystemError: unknown opcode

## Environment
Python 3.9.0
Prefect 0.13.14

**Comment by joshmeek** [comment] 2020-11-10 14:32
@JacobDorM I am unable to reproduce this currently. I tried 3.8 and 3.9 and both appear to work for me (MacOS). I noticed that you said your environment is running `3.9.0` however your logs suggest that it's using `c:\python38\lib\` and that has potential to be a cause if you're building your flow in one version and attempting to run in another version of python.

**Comment by jcrist** [comment] 2021-01-06 15:31
Yeah, this is the error you'd get if you were mixing versions of python across an execution environment. You'll want to ensure that the version of Python that you register a flow with is the same as the version you execute it with.

Closing, feel free to open a new issue if you have further issues.

**Closed by jcrist** 2021-01-06 15:31 UTC
