### ISSUE TITLE
Optional fields from Pydantic 2 model are displayed strange in Flow parameter input form

### ISSUE THREAD

**Issue by toro-berlin** [PrefectHQ/prefect#12023] opened 2024-02-19 12:21 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Pydantic 2 handles optional fields differently compared to Pydantic 1. This results in a strange way of displaying the corresponding input form on the flow parameter input page.

### Reproduction

Code 
```
from typing import Optional

from pydantic import BaseModel, Field


class ParameterModel(BaseModel):
    timeout: Optional[int] = Field(
        title="Timeout",
        description="Timout description.",
        default=None,
    )


if __name__ == "__main__":
    print(ParameterModel.schema())
```

Pydantic 1 Schema
```
{
    "title": "ParameterModel",
    "type": "object",
    "properties": {
        "timeout": {
            "title": "Timeout",
            "description": "Timout description.",
            "type": "integer",
        }
    },
}
```

Pydantic 2 Schema
```
{
    "properties": {
        "timeout": {
            "anyOf": [{"type": "integer"}, {"type": "null"}],
            "default": None,
            "description": "Timout description.",
            "title": "Timeout",
        }
    },
    "title": "ParameterModel",
    "type": "object",
}
```

### Error

The way of displaying the input form field is confusing and not easy to get. We expect the same behavior as before for the optional field: No option to change the type, one line of input.

![image](https://github.com/PrefectHQ/prefect/assets/120258756/d91ec669-90b0-4b8c-939c-c3aee55bd25b)

### Browsers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Additional context

I found this thread in the Pydantic issues about it: https://github.com/pydantic/pydantic/issues/7161

**Comment by urimandujano** [comment] 2024-02-20 15:59
Pydantic v2 is [using a standardized version in its schemas](https://docs.pydantic.dev/latest/concepts/json_schema/) which is the main reason it's different than Pydantic v1. This is showing up in the UI but we _could_ gloss over this difference by updating the v2 schema into a v1 format before sending the schemas over. That could tie us over until we fully deprecate pydantic v1. The alternative is the update the UI to render both, which would make deprecation easier later on.

**Comment by pleek91** [comment] 2024-02-20 16:05
Technically what the ui is rendering is correct I believe since the schema being produced is an `anyOf` of two separate definitions. You can pass an integer or none. 

That being said I think we can improve the ui here. We're actively working on a round of enhancements to deployment parameter forms and I'll look at improving the ui here as part of that work.

**Comment by toro-berlin** [comment] 2024-02-21 07:32
Thanks for having a look! It's great to hear that you are already working on improving the parameter forms - I am excited about the release.

You are definitely right: What is rendered by the Prefect UI is technically correct and makes the type more transparent.

Flow operators handling Prefect flows (parameterize, start, monitor, etc.) are not familiar with the details of Pydantic models and schemas. For them, the UI changed, and they needed guidance on how to use the form from now on.

One idea: Have a checkbox next to the input field where you can (de-)activate the input field, deactivated=Null, activated=integer.

**Comment by pleek91** [comment] 2024-02-28 16:51
@toro-berlin our enhanced deployment parameters ui is available in cloud and will soon be available in open source. But we ended up not changing this much. Because a parameter could be types as `int | None` and have no default value set, we need to allow users to specify whether they would like to use an `int` or `None` as the value for their parameter. However we did add a feature to allow omitting any optional field from the parameters which ensures the default value is used. This is what it looks like for the reproduction you gave. You'll also notice that the buttons say `int` and `None` to match the python types rather than `integer` and `null` like it did previously. Hopefully this helps, but let me know if you have any feedback here


![Image](https://github.com/PrefectHQ/prefect/assets/6200442/9b22fbc5-1e02-4401-b626-ff84a48e3a0f)

**Comment by toro-berlin** [comment] 2024-03-05 06:24
Hey @pleek91,

It makes sense to me - thanks for providing background. Having the same type names helps on our side. `None` is more descriptive and explainable than `null`. 

For clarification:
- If users select "None", `None` will be passed to the flow function.
- If users select "Omit value", nothing will be passed to the flow function. The flow function will use the default value defined in the Pydantic model or flow function - the value can differ from `None`.

**Comment by pleek91** [comment] 2024-03-21 16:15
@toro-berlin sorry for not getting back to you. You are correct about your clarifications. Thank you for your help and feedback on this! I'm going to close this issue. But please let us know if you have any problems.

**Closed by pleek91** 2024-03-21 16:15 UTC
Labels: bug, ui
