### ISSUE TITLE
prefect-databricks jobs_runs_submit_and_wait_for_completion possible regression

### ISSUE THREAD

**Issue by srsapient** [PrefectHQ/prefect#15180] opened 2024-09-03 13:13 UTC
### Bug summary

We are using `flows.jobs_runs_submit_and_wait_for_completion()` from `prefect-databricks`.

We are trying to upgrade prefect-databricks from 0.2.3 to 0.2.4+ (ideally 0.2.9) and we noticed that method parameter `job_submission_handler` that is available in 0.2.3 has disappeared starting from 0.2.4.

- 0.2.3 --> https://github.com/PrefectHQ/prefect-databricks/blob/v0.2.3/prefect_databricks/flows.py#L71
- 0.2.4 --> https://github.com/PrefectHQ/prefect/blob/prefect-databricks-0.2.4/src/integrations/prefect-databricks/prefect_databricks/flows.py#L58
- 0.2.9 --> https://github.com/PrefectHQ/prefect/blob/prefect-databricks-0.2.9/src/integrations/prefect-databricks/prefect_databricks/flows.py#L63

We noticed that the parameter is still available in `jobs_runs_submit_by_id_and_wait_for_completion`

Is this something expected?

### Version info (`prefect version` output)

```Text
2.20.4
```

**Comment by NicholasFiorentini** [comment] 2024-09-03 13:18
It looks like this is a regression introduced by the migration from the standalone repository to the Prefect monorepo.

**Comment by zzstoatzz** [comment] 2024-09-03 14:05
hi @srsapient - thank you for the issue! @NicholasFiorentini appears to be correct here

I've opened the PRs linked above to restore `job_submission_handler` to both 2.x and 3.x versions of `jobs_runs_submit_and_wait_for_completion` - I'll go ahead and get that released asap

**Comment by zzstoatzz** [comment] 2024-09-03 14:57
hi @srsapient and @NicholasFiorentini - `prefect-databricks==0.2.10` is released
<img width="1492" alt="image" src="https://github.com/user-attachments/assets/60b79a0d-ad6c-463a-bfa9-8b07d6aa715e">

let me know if you see anything unexpected

**Closed by zzstoatzz** 2024-09-03 14:57 UTC
Labels: bug
