### ISSUE TITLE
Auth error when registering a flow with s3 storage

### ISSUE THREAD

**Issue by n-batalha** [PrefectHQ/prefect#3100] opened 2020-08-06 11:19 UTC
## Description

When I create a pipeline with s3 storage, I get an auth error. ~~Potential reason is flagged below under `Environment`~~

I made it reproducible with the script below, save it as `example.py`, make your env vars available:

```
export AWS_ACCESS_KEY_ID=REDACTED
export AWS_SECRET_ACCESS_KEY=REDACTED
export AWS_SESSION_TOKEN=REDACTED
```

I also have `export PREFECT__CONTEXT__SECRETS__AWS_CREDENTIALS='{"ACCESS_KEY": "REDACTED", "SECRET_ACCESS_KEY": "REDACTED"}'` although [the docs say](https://docs.prefect.io/orchestration/execution/storage_options.html#aws-s3) that we should use the normal config for boto .

Now run:

```
import os

import boto3
from prefect import Parameter, Flow, task
from prefect.environments import LocalEnvironment
from prefect.environments.storage import S3


# testing boto directly
s3 = boto3.resource("s3")

for bucket in s3.buckets.all():
    print(bucket.name)



# testing boto via Prefect
@task
def say_hello(person: str) -> None:
    print("Hello, {}!".format(person))


with Flow("Say hi!") as flow:
    name = Parameter("name")
    say_hello(name)


storage = S3(bucket="REDACTED")
# also tried, after setting AWS_CREDENTIALS:
# storage = S3(bucket="REDACTED", secrets=["AWS_CREDENTIALS"])


flow.storage = storage

flow.environment = LocalEnvironment(
    metadata={"image": "REDACTED"}
)

flow.register()
```

I get:

```
  File "example.py", line 36, in <module>
    flow.register()
  File "/Users/nbatalha/Library/Caches/pypoetry/virtualenvs/pipelines-P6yz7rn1-py3.8/lib/python3.8/site-packages/prefect/core/flow.py", line 1575, in register
    registered_flow = client.register(
  File "/Users/nbatalha/Library/Caches/pypoetry/virtualenvs/pipelines-P6yz7rn1-py3.8/lib/python3.8/site-packages/prefect/client/client.py", line 677, in register
    serialized_flow = flow.serialize(build=build)  # type: Any
  File "/Users/nbatalha/Library/Caches/pypoetry/virtualenvs/pipelines-P6yz7rn1-py3.8/lib/python3.8/site-packages/prefect/core/flow.py", line 1429, in serialize
    storage = self.storage.build()  # type: Optional[Storage]
  File "/Users/nbatalha/Library/Caches/pypoetry/virtualenvs/pipelines-P6yz7rn1-py3.8/lib/python3.8/site-packages/prefect/environments/storage/s3.py", line 184, in build
    raise err
  File "/Users/nbatalha/Library/Caches/pypoetry/virtualenvs/pipelines-P6yz7rn1-py3.8/lib/python3.8/site-packages/prefect/environments/storage/s3.py", line 177, in build
    self._boto3_client.upload_fileobj(
  File "/Users/nbatalha/Library/Caches/pypoetry/virtualenvs/pipelines-P6yz7rn1-py3.8/lib/python3.8/site-packages/boto3/s3/inject.py", line 539, in upload_fileobj
    return future.result()
  File "/Users/nbatalha/Library/Caches/pypoetry/virtualenvs/pipelines-P6yz7rn1-py3.8/lib/python3.8/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/Users/nbatalha/Library/Caches/pypoetry/virtualenvs/pipelines-P6yz7rn1-py3.8/lib/python3.8/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/Users/nbatalha/Library/Caches/pypoetry/virtualenvs/pipelines-P6yz7rn1-py3.8/lib/python3.8/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/Users/nbatalha/Library/Caches/pypoetry/virtualenvs/pipelines-P6yz7rn1-py3.8/lib/python3.8/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/Users/nbatalha/Library/Caches/pypoetry/virtualenvs/pipelines-P6yz7rn1-py3.8/lib/python3.8/site-packages/s3transfer/upload.py", line 692, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/Users/nbatalha/Library/Caches/pypoetry/virtualenvs/pipelines-P6yz7rn1-py3.8/lib/python3.8/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/nbatalha/Library/Caches/pypoetry/virtualenvs/pipelines-P6yz7rn1-py3.8/lib/python3.8/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
```

## Expected Behavior

Flow is uploaded

## Reproduction

See above. If you need I can provide `poetry.lock`.

## Environment

~~**NOTE how the boto env vars are not listed below**, that could be the issue.~~

```
prefect diagnostics
{
  "config_overrides": {
    "server": {
      "telemetry": {
        "enabled": true
      }
    }
  },
  "env_vars": [
    "PREFECT__LOGGING__LEVEL",
    "PREFECT__CONTEXT__SECRETS__CRUNCHBASE_API_KEY",
    "PREFECT__CLOUD__AUTH_TOKEN",
    "PREFECT__CONTEXT__SECRETS__AWS_CREDENTIALS"
  ],
  "system_information": {
    "platform": "macOS-10.15.6-x86_64-i386-64bit",
    "prefect_version": "0.12.6",
    "python_version": "3.8.3"
  }
}
```

**Comment by joshmeek** [comment] 2020-08-06 11:40
Hi @n-batalha what happens if you initialize boto3 client directly and call `upload_fileobj` to put something in your bucket? The error suggests that this isn't something to do with prefect but with your access key.

**Comment by n-batalha** [comment] 2020-08-06 11:42
@joshmeek the same credentials work to upload, I use it to store Prefect results in s3 and for a direct `boto` upload.

**Comment by n-batalha** [comment] 2020-08-06 11:46
@joshmeek to be 100% sure I edited the reproducible example above to do an upload in the same bucket, works.

**Comment by joshmeek** [comment] 2020-08-06 11:53
🤔  be sure that you aren't unintentionally reading AWS credentials from one of the other default locations that boto3 uses https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html

FWIW I ran your code exactly and had no issue uploading to a bucket:

```
➜ python s3storagetest.py
...my buckets printed here...
Result check: OK
[2020-08-06 11:51:08] INFO - prefect.S3 | Uploading say-hi/2020-08-06t11-51-08-712556-00-00 to my-bucket
Flow: https://cloud.prefect.io/tenant-name/flow/flow-id
```

**Comment by n-batalha** [comment] 2020-08-06 12:34
@joshmeek good heads up. I believe the env vars take precedence so it should work for both. 

The docs state that the same setup is required as boto, but there is a bit going on here:

* https://github.com/PrefectHQ/prefect/blob/master/src/prefect/environments/storage/s3.py#L201-L203
* https://github.com/PrefectHQ/prefect/blob/d31e5b01d35487aceb0bb8c0c7b8d4db23fdd131/src/prefect/utilities/aws.py#L10-L63

Removing `.aws` had no impact (still fails), but removing the `PREFECT__CONTEXT__SECRETS__AWS_CREDENTIALS` env var allows the script above to run. I can see the env var above being picked up for the boto creds, as opposed to leaving it to boto entirely. 

I am leaving this open as it should work when both `PREFECT__CONTEXT__SECRETS__AWS_CREDENTIALS` and the boto env vars are present?

**Comment by n-batalha** [comment] 2020-08-06 12:37
Btw, debugging I can see that the `PREFECT__CONTEXT__SECRETS__AWS_CREDENTIALS` values are correctly parsed in [here](https://github.com/PrefectHQ/prefect/blob/d31e5b01d35487aceb0bb8c0c7b8d4db23fdd131/src/prefect/utilities/aws.py#L10-L63) and the values themselves seem fine. They are pulled from the other env vars via:

```
export PREFECT__CONTEXT__SECRETS__AWS_CREDENTIALS='{"ACCESS_KEY": "'${AWS_ACCESS_KEY_ID}'", "SECRET_ACCESS_KEY": "'${AWS_SECRET_ACCESS_KEY}'"}'
```

**Comment by joshmeek** [comment] 2020-08-14 14:10
Glad you got the script to run! I am unable to reproduce an error with setting `PREFECT__CONTEXT__SECRETS__AWS_CREDENTIALS` and all seems to work fine for me. Since it's a local secret you are setting try also setting `PREFECT__CLOUD__USE_LOCAL_SECRETS=True` and see if that helps.

**Comment by joshmeek** [comment] 2020-12-29 19:25
Closing for now, feel free to reopen if this is still an issue

**Closed by joshmeek** 2020-12-29 19:25 UTC
