### ISSUE TITLE
Caching Issue: Hash key stays the same between retries but task still re-executes.

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#10774] opened 2023-09-20 21:31 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

A user created a custom cache key function:

```python
import prefect
from prefect.tasks import task_input_hash
import random
​
​
def custom_input_hash(context, parameters):
    hash_key = f"{context.task_run.flow_run_id}-{task_input_hash(context, parameters)}-apple{random.randint(0, 1)}"
    prefect.get_run_logger().info(f"Hash Key: {hash_key}")
    return hash_key
```

^They are seeing that even if the hash key changes, the task does not execute and shows a cached state.

### Reproduction

```python3
Deploy this flow then run this flow then keep running it as a retry.


import prefect
from prefect.tasks import task_input_hash
import random
​
​
def custom_input_hash(context, parameters):
    hash_key = f"{context.task_run.flow_run_id}-{task_input_hash(context, parameters)}-apple{random.randint(0, 1)}"
    prefect.get_run_logger().info(f"Hash Key: {hash_key}")
    return hash_key​

@prefect.task(cache_key_fn=custom_input_hash, persist_result=True)
def test_task():
    prefect.get_run_logger().info("hello!")
    return "something"
​
​
@prefect.task(cache_key_fn=custom_input_hash, persist_result=True)
def test_task_2():
    raise ValueError("This task always fails.")
    return "something"
​
​
@prefect.flow()
def test_flow():
    test_future = test_task.submit()
    test_future_2 = test_task_2.submit(wait_for=[test_future])
​
​
if __name__ == "__main__":
    test_flow()
```

### Error

```python3
The state of the task appears to remain in caching.
```

### Versions

```Text
Version:             2.11.5
API version:         0.8.4
Python version:      3.9.16
Git commit:          a597971f
Built:               Thu, Aug 24, 2023 2:14 PM
OS/Arch:             darwin/arm64
Profile:             cloud
Server type:         cloud
```

**Comment by wxu794** [comment] 2023-09-25 15:36
I was able to reproduce the issue on a simpler example: 

`import prefect
import random


def custom_cache_key_fn(context, parameters):
    cache = f"fdas8h23r9f0hv8vd9hsdf32r32frerqqq{random.randint(0, 1)}"
    prefect.get_run_logger().info(cache)
    return cache


@prefect.task(persist_result=True, cache_key_fn=custom_cache_key_fn)
def sample_task():
    print("Task Completed!")


@prefect.flow
def sample_flow():
    sample_task()


if __name__ == "__main__":
    sample_flow()
`

It produced the following hash keys and results:
fdas8h23r9f0hv8vd9hsdf32r32frerqqq1 Completed() first run
fdas8h23r9f0hv8vd9hsdf32r32frerqqq1 Cached(type=COMPLETED) retry
fdas8h23r9f0hv8vd9hsdf32r32frerqqq1 Cached(type=COMPLETED) retry
fdas8h23r9f0hv8vd9hsdf32r32frerqqq1 Cached(type=COMPLETED) retry
fdas8h23r9f0hv8vd9hsdf32r32frerqqq0 Cached(type=COMPLETED) retry

The last one shouldn't be cached since the hash key is different than the others

**Comment by serinamarie** [comment] 2023-11-02 01:26
Just to clarify, this is specific to flow run retries?

Also, is the title of this issue correct? Based on what @wxu794 is saying, it sounds like when the hash key changes between retries the task isn't executed?

**Comment by figuernd** [comment] 2023-12-07 18:00
I think the title is backwards, should be: "Task cache is used even when hash key changes"

I am also experiencing this issue. This is happening both with a custom `cache_key_fn` and the provided `task_input_hash`. As far as I can tell hash keys have no effect whatsoever and retries on successful tasks will always use the cache.

Using Prefect version 2.14.2.

**Comment by figuernd** [comment] 2023-12-07 20:13
Upgraded to 2.14.9, issue still present.

**Comment by desertaxle** [comment] 2023-12-20 15:47
From what I see in this thread, task run caching is working as expected. Task run cache keys are kept indefinitely by default and apply across flow runs. To prevent a cache entry from being used in perpetuity, you can provide a `cache_experiation` kwarg to have the cache entry only be used for a given time period. To invalidate existing cache entries, you can also [refresh the task run cache](https://docs.prefect.io/latest/concepts/tasks/#refreshing-the-cache). 

@wxu794 I couldn't reproduce your issue from a fresh cache and recommend clearing your task run cache to see if the issue persists.

@figuernd The task run cache is not used for flow run retries for tasks completed successfully on a previous run. Those completed tasks will always return their original result and not execute on a flow run retry.

I'm going to close this issue because this is all expected behavior. If you run into any other issues, feel free to respond in this thread or open a new issue!

**Closed by desertaxle** 2023-12-20 15:47 UTC
Labels: bug, from:sales

**Comment by figuernd** [comment] 2023-12-20 15:55
@desertaxle I'm very confused. The entire point of a cache key is to determine if a successful task should be rerun or not. What other possible purpose could they have?

From the documentation:
`To determine whether a task run should retrieve a cached state, we use "cache keys". A cache key is a string value that indicates if one run should be considered identical to another. When a task run with a cache key finishes, we attach that cache key to the state. When each task run starts, Prefect checks for states with a matching cache key. If a state with an identical key is found, Prefect will use the cached state instead of running the task again.`
https://docs.prefect.io/latest/concepts/tasks/#caching

The docs make it clear that the task should be run again if the cache key does not match, but the issue remains that the cache is used regardless of the computed key value. The key has no effect.

**Comment by desertaxle** [comment] 2023-12-20 16:01
@figuernd That is true in all cases **except** during a flow run retry. Tasks completed in a previous flow run attempt are not retried even if the task cache key changes. In all other cases, the run will be executed if there is no valid cache key for a task run. If you see other behavior, please share an MRE and we'll start investigating a fix!

**Comment by figuernd** [comment] 2023-12-20 16:10
I see. Then I'll see if I can change our workflow to use copy-to-new-run then instead of retries. The caching documentation does not seem to differentiate between retries and other runs, so this behavior is unexpected for at least a few of us. Thanks.
