### ISSUE TITLE
The storage block of the deployment.yaml file (typically lines 25-30) does not update to reflect the storage block specified in the deployment build cli command. 

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#6249] opened 2022-08-05 12:12 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The storage block of the deployment.yaml file (typically lines 25-30) does not update to reflect the storage block specified in the deployment build cli command. 

### Reproduction

```python
`prefect deployment build --name s3-deployment --tag s3 --infra process --storage-block s3/taylor-s3-block my_flow_code.py:demo_flow`

Run the above build command specifying an s3 block after the --storage-block flag. You should then see green text saying:
 flow 'My Demo Flow'
Manifest created at '/Users/taylorcurran/prj/demos/taylor-demo/demos/vanilla_flow/demo_flow-manifest.json'.
Successfully uploaded 17 files to s3://taylor-code-storage-3
Deployment YAML created at 
'/Users/taylorcurran/prj/demos/taylor-demo/demos/vanilla_flow/demo_flow-deployment.yaml'. 

THEN... go into the newly created deployment.yaml file and inspect the storage block, note: located underneath the do not edit comment. You will see that the block type is incorrectly listed as being of `local-file-system` when it should say s3.
```
storage:
  basepath: /Users/local/path/vanilla_flow
  _is_anonymous: true
  _block_document_name: anonymous-d---7
  _block_document_id: a---8
  _block_type_slug: local-file-system
```
^This will give you a 409 error if you try to run `prefect deployment apply`
I then when in an manually corrected the storage block lines of the yaml file by specifying:

storage:
  bucket_path: taylor-code-storage-3
  _is_anonymous: true
  _block_document_name: taylor-s3-block-take2
  _block_document_id: 3---2
  _block_type_slug: s3

Note the change from basepath to bucket_path... and it worked beautifully!

When I ran the prefect deployment apply command I got the green output:
```
Successfully loaded 'my-purple-deployment'
Deployment 'My Demo Flow/my-purple-deployment' successfully created with id 
'6---0'.
```
```

### Error

```prefect.exceptions.PrefectHTTPStatusError: Client error '409 Conflict' for url 'https://api.prefect.cloud/api/accounts/350ec2c4-5686-40af-9f1b-339832340f8e/workspaces/60983d73-26f4-4c82-aeff-53b6e9e2204b/deployments/'
Response: {'detail': 'Error creating deployment. Could not find storage block with id: a032aef2-da1f-4d4c-8eff-4d68ee3518b8. This usually occurs when applying a deployment specification that was built against a different Prefect database / workspace.'}
For more information check: https://httpstatuses.com/409
```
The error is that they did not find the local storage block which makes sense because I only created an s3 storage block. If you look into the deployment.yaml that was created during the build step, you will see that the block type is incorrectly listed as being of `local-file-system` when it should say s3.

### Versions

```

2.0.2
```

### Additional context

Thanks guys <3

**Comment by cicdw** [comment] 2022-08-21 19:22
@taylor-curran can you try to reproduce on `main` and let me know if this is still an issue?  I couldn't reproduce

**Comment by cicdw** [comment] 2022-08-24 22:47
Closing as this appears to be resolved - please reopen if not

**Closed by cicdw** 2022-08-24 22:47 UTC
Labels: bug, priority:high, component:deployment
