### ISSUE TITLE
Malformed response received from Cloud

### ISSUE THREAD

**Issue by mblau-leaffilter** [PrefectHQ/prefect#4030] opened 2021-01-28 15:36 UTC
## Description

When creating a flow to run on Docker Storage my image fails to build with a  "raise ClientError(
prefect.utilities.exceptions.ClientError: Malformed response received from Cloud - please ensure that you have an API token properly configured."

## Expected Behavior

What I would expect is for it to successfully build, which is what happens when I set ignore_healthchecks = True

## Reproduction

This is my flow code. that fails with the Malformed response error.
```
with Flow("example",
            storage = Docker(dockerfile="/path/to/Dockerfile"
)) as flow:
    main()
flow.run_config = DockerRun(image = "image_name:latest")
flow.register(project_name="test")

```

## Environment

```
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.4.0-65-generic-x86_64-with-glibc2.29",
    "prefect_backend": "server",
    "prefect_version": "0.14.1",
    "python_version": "3.8.5"
  }
}

```

**Comment by joshmeek** [comment] 2021-01-28 15:38
@mblau-leaffilter Can you post the traceback of where the ClientError is being raised?

**Comment by mblau-leaffilter** [comment] 2021-01-28 15:47
@joshmeek here you go:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 450, in _request
    json_resp = response.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/prefect/healthcheck.py", line 147, in <module>
    flows = cloudpickle_deserialization_check(flow_file_paths)
  File "/opt/prefect/healthcheck.py", line 40, in cloudpickle_deserialization_check
    flows.append(cloudpickle.load(f))
  File "/app/integration.py", line 340, in <module>
    flow.register(project_name="test")
  File "/usr/local/lib/python3.8/site-packages/prefect/core/flow.py", line 1665, in register
    registered_flow = client.register(
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 773, in register
    project = self.graphql(query_project).data.project  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 297, in graphql
    result = self.post(
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 212, in post
    response = self._request(
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 453, in _request
    raise ClientError(
prefect.utilities.exceptions.ClientError: Malformed response received from Cloud - please ensure that you have an API token properly configured.
```

**Comment by joshmeek** [comment] 2021-01-28 15:50
This looks to be that you are placing a file manually into your image under `/app/integration.py` and in that file it contains a register call. Is this file that you are currently running called integration.py and if so are you also copying it into the docker image manually? If not and you are copying in a different file called integration.py you should remove the register call.

**Comment by mblau-leaffilter** [comment] 2021-01-28 15:56
@joshmeek it is the same file I am running. When I remove the COPY from the Dockerfile I get

```
/opt/prefect/healthcheck.py:147: UserWarning: Flow uses module which is not importable. Refer to documentation on how to import custom modules https://docs.prefect.io/api/latest/storage.html#docker
  flows = cloudpickle_deserialization_check(flow_file_paths)

Beginning health checks...
System Version check: OK
Traceback (most recent call last):
  File "/opt/prefect/healthcheck.py", line 147, in <module>
    flows = cloudpickle_deserialization_check(flow_file_paths)
  File "/opt/prefect/healthcheck.py", line 40, in cloudpickle_deserialization_check
    flows.append(cloudpickle.load(f))
ModuleNotFoundError: No module named 'integration'

```
It is only when I add it back in does that message go away and I instead get the malformed response received from Cloud. Removing the flow.register() call with the COPY integration.py in the dockerfile it again yields the malformed response received from Cloud error.

**Comment by joshmeek** [comment] 2021-01-28 16:03
Can you post the contents of your file or some reproducible example? It seems like you have some circular import going on inside the integration file.

**Comment by mblau-leaffilter** [comment] 2021-01-28 16:11
@joshmeek I ran into circular imports as an issue when I was working through this last evening. Integration.py does a wildcard import on change_password.py, which change_password.py does a wildcard import on integration.py. Before I had the change_password file do a more specific import but then python itself was complaining about circular imports.  This is the relevant import section from integration.py:

```

from change_password import *
#import change_password
import prefect
from prefect.storage import Docker
from prefect.run_configs import DockerRun
from prefect import task, Flow
```

and this is the section from change_password:

```
from datetime import date
from os import environ
import requests
import logging
from integration import *
```

**Comment by joshmeek** [comment] 2021-01-28 16:23
Yeah you're most likely going to need to rearrange your files to get the imports to work because this is going to cause issues in the meantime. I guess one alternative you can take is removing the register call from the integration.py file and using the CLI command `prefect register flow --file integration.py -p ProjectNameHere`

**Comment by niakki** [comment] 2021-04-02 13:56
Hello,

I get this error while running prefect client on docker (on my local machine) which is communicating with prefect server and it is deployed on another GCP compute instance (prefect server is initiated using cmd `prefect server start` and `prefect backend server` is also enabled). 

However, I can register the workflow.py via my local machine (both via CLI or programmatically) but the same on the docker container gives the error.
![Screen Shot 2021-04-02 at 19 18 40](https://user-images.githubusercontent.com/36913184/113421179-3ec92f00-93e8-11eb-9285-40bb24232c26.png)

Anyone facing a similar issue while registering a flow programmatically while running the code on docker or otherwise, please share your feedback. 

I appreciate the help & support.

**Comment by madkinsz** [comment] 2021-04-02 14:56
Hey @niakki -- this is definitely caused by your flow attempting to use the `cloud` backend instead of `server`. If you're using a `DockerAgent` this was fixed in https://github.com/PrefectHQ/prefect/pull/4076 but if you're launching your own container then you'll need to update the config there as well. If it still doesn't work, can you give the output of `prefect diagnostics` on the machine you're writing the flow on _and_ the machine/container where the flow is erroring?

**Comment by niakki** [comment] 2021-04-05 10:24
thank you @madkinsz! so the issue was with an environment variable which was not configured in the docker container (from where we were trying to register the flow). To solve the issue all we had to do was to set `PREFECT__SERVER__HOST: http://<prefect server ip>`

This we figured with the help of `prefect diagnostics`

I appreciate all the help and support 👍

**Closed** 2021-05-24 20:04 UTC
