### ISSUE TITLE
"-core" package with minimal conda dependencies

### ISSUE THREAD

**Issue by mcg1969** [PrefectHQ/prefect#2339] opened 2020-04-15 19:16 UTC
## Current behavior
I've noticed that `conda create -n env prefect` installs a kitchen sink of packages whether I actually need them or not. Some initial analysis suggests it is `dask` that is pulling them in.

## Proposed behavior
I wonder if it would be possible to allow `prefect` by default to depend only on `dask-core`, obviously with some functionality not present. Or perhaps a second package, say called `prefect-core`, that depends on the smaller subset.

My ideal would be to have a package that has just enough of prefect's dependencies to support an agent with local execution. In that case, dask is theoretically not even imported, but dask-core is quite lightweight.

I'm just a little concerned that the more dependencies prefect has the higher the likelihood that they might cause conflicts with other workflows.

**Comment by jcrist** [comment] 2020-04-16 16:31
Yeah, prefect only relies on the dask core features, so the conda recipe should rely on `dask-core` instead of `dask`. I'll push a fix to the conda-forge recipe. It looks like this was intended, but used pip syntax instead (I'm surprised that didn't error in conda-build?): https://github.com/conda-forge/prefect-feedstock/blob/master/recipe/meta.yaml#L28.

**Comment by jcrist** [comment] 2020-04-16 16:41
https://github.com/conda-forge/prefect-feedstock/pull/39

**Comment by jcrist** [comment] 2020-04-16 21:07
We've updated the conda-forge recipe to move to `dask-core`, and updated the requirements in both spots to drop a few unneeded dependencies. This should reduce the standard install size somewhat. There's still a few things installed by default that not ever prefect user will need (e.g. a the `docker` api client), but that's a separate issue.

Closing, as I believe this to be resolved.

**Closed by jcrist** 2020-04-16 21:07 UTC
Labels: feature request
