### ISSUE TITLE
Retry submitting flow runs to infrastructure upon failure

### ISSUE THREAD

**Issue by yaronlevi** [PrefectHQ/prefect#10302] opened 2023-07-26 07:47 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

We are using Prefect Cloud and ECS Tasks Infra.

A CRON Flow that runs each 15 min, suddenly crashed [on one of the runs.](https://app.prefect.cloud/account/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspace/8ff919f1-a2c3-4660-9ab5-66b57758d46d/flow-runs/flow-run/af40195a-526f-4684-b18c-9bbba0b2cc1c)

![CleanShot 2023-07-26 at 10 39 59@2x](https://github.com/PrefectHQ/prefect/assets/5398977/dbff81bd-df68-475c-a169-fa197f943971)

![CleanShot 2023-07-26 at 10 40 37@2x](https://github.com/PrefectHQ/prefect/assets/5398977/ad1d23ac-7577-4584-900e-abd55e366a67)

This specific Flow runs every 15 minutes, and the particular Run that crashed may not have severe consequences. However, this could occur with a single, sensitive Run that is scheduled to run once per month.

Is this crash something that could be fixed by making some part of Prefect's backend regarding ECS Tasks more robust?

Thanks.

### Reproduction

```python3
Prefect Cloud + ECS Tasks Infra
```

### Versions

```Text
Prefect Cloud + ECS Tasks Infra
```

**Comment by WillRaphaelson** [comment] 2023-07-26 14:51
hey @yaronlevi - hard to know what happened here. Can you see if there are any informative logs on the ECS side? Was a task or container spun up?

**Comment by yaronlevi** [comment] 2023-07-27 09:06
@WillRaphaelson Can't seem to find any logs.

I took the run id:

![CleanShot 2023-07-27 at 12 04 25@2x](https://github.com/PrefectHQ/prefect/assets/5398977/7f3e5052-a580-48ab-8de7-e38b4ba1e32c)

And searched for it in the Task that runs the agent:

![CleanShot 2023-07-27 at 12 05 39@2x](https://github.com/PrefectHQ/prefect/assets/5398977/e478487c-04e8-4977-8f03-f156494882be)

No results...

**Comment by WillRaphaelson** [comment] 2023-08-01 15:05
Took to slack to gather details.

**Comment by WillRaphaelson** [comment] 2023-08-01 17:04
per slack DM, we're going to close this out for now as its hard to debug and there are others options via work pools and workers

**Comment by RiteshTiwari19** [comment] 2023-08-01 21:18
This issue happens on many other infrastructure blocks such as Azure Container Instance, Kubernetes Cluster, and as mentioned here ECS. More often than not the error occurs because prefect is unable to get a response from the Infrastructure provider on the status of the job.

We use Prefect to run flows quite frequently (multiple flows running every 5 minutes), and we see this error occurring 5-6 times a day. The problem is not the issue itself -given the nature of the dependency on the availability of Infrastructure (there could be many issues such as Network issue when communicating with the Infrastructure provider, IP address not available for container (ACI), etc) - the main issue is that prefect does not retry Crashed flows (specially that occur due to infrastructure failure). 

In these cases, the container never get started in the first place, so any retry settings placed in the code is redundant.

Here is the log for one such job that failed on a Kubernetes Cluster:

`ERROR   | prefect.agent - Failed to submit flow run '9e96406e-c64e-49ff-b112-b7d6343cdb41' to infrastructure.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 1378, in getresponse
    response.begin()
  File "/usr/local/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/prefect/agent.py", line 500, in _submit_run_and_capture_errors
    result = await infrastructure.run(task_status=task_status)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/infrastructure/kubernetes.py", line 300, in run
    job = await run_sync_in_worker_thread(self._create_job, manifest)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/utilities/asyncutils.py", line 91, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/infrastructure/kubernetes.py", line 737, in _create_job
    job = batch_client.create_namespaced_job(self.namespace, job_manifest)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api/batch_v1_api.py", line 210, in create_namespaced_job
    return self.create_namespaced_job_with_http_info(namespace, body, **kwargs)  # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api/batch_v1_api.py", line 309, in create_namespaced_job_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 391, in request
    return self.rest_client.POST(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kubernetes/client/rest.py", line 276, in POST
    return self.request("POST", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kubernetes/client/rest.py", line 169, in request
    r = self.pool_manager.request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 1378, in getresponse
    response.begin()
  File "/usr/local/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

| INFO    | prefect.agent - Completed submission of flow run '9e96406e-c64e-49ff-b112-b7d6343cdb41'
| INFO    | prefect.agent - Reported flow run '9e96406e-c64e-49ff-b112-b7d6343cdb41' as crashed: Flow run could not be submitted to infrastructure`

**Comment by RiteshTiwari19** [comment] 2023-08-01 21:23
If Prefect could just retry submitting the flow run that were failed due to intermittent infrastructure issues, this problem would be fixed. This particular issue is hindering us from moving to production with Prefect. We have tried multiple infrastructure blocks (Kubernetes, ACI) etc, but this issue is present everywhere.

While it might seem that it's an intermittent, but if you run the flows frequently, this issue pops up at least 5-6 times in a 24 hour period.

**Comment by yaronlevi** [comment] 2023-08-02 13:13
@RiteshTiwari19 When push work pools will be out of Beta, I will switch to it, and continue to monitor if the issue remains.
I will update here.

**Comment by WillRaphaelson** [comment] 2023-08-03 18:18
Thank you, while its not directly related, we've also accepted #10211 to retry on crash where possible.

**Comment by WillRaphaelson** [comment] 2024-07-16 17:48
closing in favor of #10211

**Closed by WillRaphaelson** 2024-07-16 17:48 UTC
Labels: enhancement
