### ISSUE TITLE
Incorrect duration of tasks >1day in UI

### ISSUE THREAD

**Issue by howardcornwell** [PrefectHQ/prefect#2836] opened 2020-06-22 11:53 UTC
## Description
Tasks with durations of over 1 day are displayed incorrectly in the UI. See the below screenshot for a task that started & ended on different days.

<img width="459" alt="Screenshot 2020-06-22 at 09 20 21" src="https://user-images.githubusercontent.com/62056801/85284259-c4e23d80-b486-11ea-848b-60475a9c5d62.png">

The flow duration is also missing in the flow's _runs_ page:

<img width="1344" alt="Screenshot 2020-06-22 at 12 51 52" src="https://user-images.githubusercontent.com/62056801/85284503-39b57780-b487-11ea-995f-c17d61639ff7.png">

## Expected Behavior
Task duration should read ~1day 18hours, not <1s.

**Comment by joshmeek** [comment] 2020-06-22 13:17
Thanks for opening @howardcornwell! The no duration being shown on the flow runs page is definitely related to #2262 because some bug is causing it to display as <1s. cc @zhen0

**Comment by zhen0** [comment] 2020-06-22 14:46
Thanks @joshmeek and @howardcornwell - this is a duplicate of https://github.com/PrefectHQ/cloud-web-ui/issues/1566.  I'll bump that issue to make sure we look into this.

**Closed by zhen0** 2020-06-22 14:46 UTC
Labels: bug, server, ui

**Comment by joshmeek** [comment] 2020-06-22 15:43
Thanks @zhen0!
