### ISSUE TITLE
Flow created from Graphql API is not running

### ISSUE THREAD

**Issue by mohamedashique1993** [PrefectHQ/prefect#3617] opened 2020-11-05 07:13 UTC
## Description

We created the project and then we started with creating the flow with graphql mutation end point. Flow is getting created but it is not running.

As mentioned in your docs, we took the flow creation metadata from serialize() method and passed to the endpoint.
Steps to reproduce:

**Step 1:**
**Code to Take the serialize metadata**
`from prefect import task
from prefect import Flow
import json

@task
def execute():
    print("Executing the task")

with Flow("insight_flow") as insight_flow:
    token = execute()

print(insight_flow.serialize())
print("-------")
print(json.dumps(insight_flow.serialize()))`

**Step 2:** 
We escaped the string and passed the serialize() output to graphql endpoint
`mutation {
create_flow(input:{
project_id: "e24f59a0-c937-4bd3-a948-1152903db7ff",
serialized_flow: "{\"name\": \"insight_flow\", \"type\": \"prefect.core.flow.Flow\", \"schedule\": null, \"parameters\": [], \"tasks\": [{\"retry_delay\": null, \"tags\": [], \"max_retries\": 0, \"trigger\": {\"fn\": \"prefect.triggers.all_successful\", \"kwargs\": {}}, \"outputs\": \"typing.Any\", \"timeout\": null, \"skip_on_upstream_skip\": true, \"inputs\": {}, \"name\": \"execute\", \"auto_generated\": false, \"type\": \"prefect.tasks.core.function.FunctionTask\", \"cache_validator\": {\"fn\": \"prefect.engine.cache_validators.never_use\", \"kwargs\": {}}, \"cache_key\": null, \"slug\": \"execute-1\", \"cache_for\": null, \"__version__\": \"0.13.11\"}], \"edges\": [], \"reference_tasks\": [], \"environment\": {\"metadata\": {}, \"labels\": [], \"__version__\": \"0.13.11\", \"type\": \"LocalEnvironment\"}, \"run_config\": null, \"__version__\": \"0.13.11\", \"storage\": null}"
}) {
id
}
}`

**Step 3:**
Now flow got created successfully and we can view in UI but the flow is not running. we have agent which is querying for the flows created from script but the flow created from graphql is not running.

Refer the screenshot for flow is not running
<img width="1579" alt="Screenshot 2020-11-05 at 12 26 28 PM" src="https://user-images.githubusercontent.com/73984137/98209067-5351ea00-1f64-11eb-97de-402b267b940d.png">

## Expected Behavior

We wanted the flow to run.

## Reproduction

Please refer above

**Comment by joshmeek** [comment] 2020-11-05 15:23
Hi @mohamedashique1993 does your agent happen to have any labels on it that it is querying for? Judging by the screenshot your flow does not have any labels and that could be the culprit. If you could provide more information on the agent you spun up that would help troubleshoot.

**Comment by sattsb** [comment] 2020-11-05 20:25
I work with @mohamedashique1993 , the agent has the following labels.

 azure-flow-storage , dna-prefect, gcs-flow-storage, github-flow-storage, gitlab-flow-storage, s3-flow-storage, webhook-flow-storage

The documentation at this location https://docs.prefect.io/orchestration/concepts/flows.html#registration
did not imply the need for a label during create_flow api mutation

**Comment by joshmeek** [comment] 2020-11-05 20:29
Yeah that makes sense then as to why it is not being picked up. By default using the `flow.register` command some default labels are added to the flow based on your storage mechanism. Since you are calling the mutation directly you are not attaching labels to the flow. There are two options, either [add some labels to your flow's environment](https://docs.prefect.io/orchestration/execution/overview.html#labels) or start your local agent with the `--no-storage-labels` flag.

**Comment by sattsb** [comment] 2020-11-05 21:38
Tried with label attribute in flow with the following serialized flow with label, 

`{\"name\": \"Assurance5\", \"type\": \"prefect.core.flow.Flow\", \"schedule\": null, \"parameters\": [], \"tasks\": [{\"slug\": \"get_auth_token-1\", \"name\": \"get_auth_token\", \"type\": \"prefect.tasks.core.function.FunctionTask\", \"cache_key\": null, \"max_retries\": 0, \"skip_on_upstream_skip\": true, \"inputs\": {}, \"retry_delay\": null, \"timeout\": null, \"auto_generated\": false, \"cache_validator\": {\"fn\": \"prefect.engine.cache_validators.never_use\", \"kwargs\": {}}, \"outputs\": \"typing.Any\", \"trigger\": {\"fn\": \"prefect.triggers.all_successful\", \"kwargs\": {}}, \"cache_for\": null, \"tags\": [], \"__version__\": \"0.13.11\"}], \"edges\": [], \"reference_tasks\": [], \"environment\": {\"metadata\": {}, \"labels\": [\"SBM-93PY\"], \"__version__\": \"0.13.11\", \"type\": \"LocalEnvironment\"}, \"run_config\": null, \"__version__\": \"0.13.11\", \"storage\": null}`

When executing flow run, Agent threw this error

`[2020-11-05 21:33:47,873] ERROR - agent | Error while deploying flow: ValidationError({'_schema': 'Invalid data type: None'})`

**Comment by mohamedashique1993** [comment] 2020-11-06 08:47
Please find the attached screenshot for the same.
<img width="1550" alt="Screenshot 2020-11-06 at 2 15 30 PM" src="https://user-images.githubusercontent.com/73984137/98345493-c037b380-203a-11eb-9cee-b75e81b27079.png">

**Comment by joshmeek** [comment] 2020-11-06 15:06
Hmm the fact that the flow metadata has `null` for storage I think that may be an issue (it is assumed that flows always have a storage type and it defaults to Local). How are you generating this metadata? `flow.serialize()`?

**Comment by mohamedashique1993** [comment] 2020-11-09 08:11
We are generating the flow via flow.serialize().

I tried with local storage and docker storage as well. both ran into error.

Local storage code:
`from prefect import task
from prefect import Flow
import json
from prefect.environments import LocalEnvironment
from prefect.environments.storage import Local

@task
def execute():
    print("Executing the task")


with Flow("insight_flow_2") as insight_flow:
    token = execute()

insight_flow.environment = LocalEnvironment(labels=["s3-flow-storage", "MOHAMA-M-9003", "github-flow-storage"])
insight_flow.storage = Local()
print(insight_flow.serialize())`

flow.serialize output:
`{"name": "insight_flow_3", "type": "prefect.core.flow.Flow", "schedule": null, "parameters": [], "tasks": [{"slug": "execute-1", "inputs": {}, "auto_generated": false, "name": "execute", "retry_delay": null, "cache_for": null, "cache_key": null, "cache_validator": {"fn": "prefect.engine.cache_validators.never_use", "kwargs": {}}, "trigger": {"fn": "prefect.triggers.all_successful", "kwargs": {}}, "skip_on_upstream_skip": true, "type": "prefect.tasks.core.function.FunctionTask", "timeout": null, "max_retries": 0, "outputs": "typing.Any", "tags": [], "__version__": "0.13.11"}], "edges": [], "reference_tasks": [], "environment": {"metadata": {}, "labels": ["s3-flow-storage", "github-flow-storage", "MOHAMA-M-9003"], "__version__": "0.13.11", "type": "LocalEnvironment"}, "run_config": null, "__version__": "0.13.11", "storage": {"flows": {}, "stored_as_script": false, "secrets": [], "path": null, "directory": "/Users/mohama/.prefect/flows", "__version__": "0.13.11", "type": "Local"}}`


<img width="1436" alt="Screenshot 2020-11-09 at 1 40 34 PM" src="https://user-images.githubusercontent.com/73984137/98515523-303f7700-2291-11eb-86c1-4f69f650441f.png">

**Comment by joshmeek** [comment] 2020-11-09 15:23
Could you try passing `build=True` to the `flow.serialize()`? That error looks like the flow isn't being saved to the local storage path (which happens on build).

**Comment by mohamedashique1993** [comment] 2020-11-10 06:37
Hi ,
I tried with flow.serialize(build=true) and obtained the metadata and created the flow but still facing the same issue.

mutation {
create_flow(input:{
project_id: "e24f59a0-c937-4bd3-a948-1152903db7ff",
serialized_flow: "{\"name\": \"insight_flow_5\", \"type\": \"prefect.core.flow.Flow\", \"schedule\": null, \"parameters\": [], \"tasks\": [{\"cache_validator\": {\"fn\": \"prefect.engine.cache_validators.never_use\", \"kwargs\": {}}, \"skip_on_upstream_skip\": true, \"timeout\": null, \"cache_key\": null, \"type\": \"prefect.tasks.core.function.FunctionTask\", \"inputs\": {}, \"trigger\": {\"fn\": \"prefect.triggers.all_successful\", \"kwargs\": {}}, \"max_retries\": 0, \"auto_generated\": false, \"name\": \"execute\", \"slug\": \"execute-1\", \"cache_for\": null, \"outputs\": \"typing.Any\", \"tags\": [], \"retry_delay\": null, \"__version__\": \"0.13.11\"}], \"edges\": [], \"reference_tasks\": [], \"environment\": {\"metadata\": {}, \"labels\": [\"s3-flow-storage\", \"github-flow-storage\", \"MOHAMA-M-9003\"], \"__version__\": \"0.13.11\", \"type\": \"LocalEnvironment\"}, \"run_config\": null, \"__version__\": \"0.13.11\", \"storage\": {\"path\": null, \"stored_as_script\": false, \"directory\": \"\/Users\/mohama\/.prefect\/flows\", \"secrets\": [], \"flows\": {\"insight_flow_2\": \"\/Users\/mohama\/.prefect\/flows\/insight-flow-5.prefect\"}, \"__version__\": \"0.13.11\", \"type\": \"Local\"}}"
}) {
  id
}
}


When we try to run the flow:
 Last State Message
[10 Nov 2020 12:03pm]: Failed to load and execute Flow's environment: KeyError('insight_flow_5')

**Comment by joshmeek** [comment] 2020-11-10 14:24
That error looks like something in the flow is trying to import from `/Users/mohama/`, are you trying to import local modules to use with your flow? Also, what's the use case for calling the graphql create flow mutation directly as opposed to just using `flow.register` or `prefect register flow -f my_flow.py`?

**Comment by mohamedashique1993** [comment] 2020-11-10 14:41
As you have mentioned we tried with flow.serialize(build=true) thats the reason `/Users/mohama/` is coming as part of `flow.serialize()` when we trying to get metadata.

**Use-case for GraphQL scenario:**
We don't want to provide the application teams the access to our prefect server. Thats the reason we are trying communicate via graphql for flow creation.

**Comment by joshmeek** [comment] 2020-11-10 15:00
Yeah `/Users/mohama/` is the expected behavior for having that in the storage metadata since you are saving the flow to a local directory using local storage. Are you by any chance calling `flow.serialize(build=True)` on one machine and running the agent on the other? If you are then you will need to use a storage option different than Local (since local stores the flow on the local machine's disk).

**Comment by mohamedashique1993** [comment] 2020-11-18 13:25
Are you by any chance calling flow.serialize(build=True) on one machine and running the agent on the other? 
Response: No, we are running the script from my local machine, obtained the metadata and used the graphql api to create another flow with metadata obtained by running the script.

**Comment by joshmeek** [comment] 2020-11-19 14:51
> No, we are running the script from my local machine, obtained the metadata and used the graphql api to create another flow with metadata obtained by running the script.

So the flow object (the pickled flow, not the metadata) is being stored on the same machine that the agent is running on?

**Comment by mohamedashique1993** [comment] 2020-12-17 09:21
> > No, we are running the script from my local machine, obtained the metadata and used the graphql api to create another flow with metadata obtained by running the script.
> 
> So the flow object (the pickled flow, not the metadata) is being stored on the same machine that the agent is running on?

Yes its running on the same machine. I created the flow and ran the script in my local and then obtained the metadata. Later on the same machine i called the graphql endpoint with metadata to create the flow. Flow is getting created but its not running.

**Comment by joshmeek** [comment] 2020-12-17 14:08
Hey @mohamedashique1993 it seems like this issue has morphed into something storage based from what it was originally intended (getting a flow to start running when calling the graphql API directly). Since that issue has been "resolved" I'm going to close this thread for now. If you wouldn't mind, could you open a new issue with the new problem you are facing with details of what you are attempting and a reproducible example. As an aside it would probably also be beneficial to update to the most recent release (`0.14.0`).

**Closed by joshmeek** 2020-12-17 14:08 UTC
