### ISSUE TITLE
Auto-generated subflow names do not match UI

### ISSUE THREAD

**Issue by komodovaran** [PrefectHQ/prefect#8428] opened 2023-02-06 20:52 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

The auto-generated animal names shown in the UI don't match up with the logs. They _do_ however match in the list view.

### Reproduction

Any nested subflow will do:

```python
@flow(name="job_1")
def job_1():
    pass

@flow(name="master_flow")
def master_flow():
    job_1()
```

### Error

Mismatch in timeline:

<img width="906" alt="Screenshot 2023-02-06 at 21 40 41" src="https://user-images.githubusercontent.com/20357875/217080401-20438fa8-ac5b-46e0-b811-f01e0e307bff.png">

Match in list view:

<img width="368" alt="Screenshot 2023-02-06 at 21 51 21" src="https://user-images.githubusercontent.com/20357875/217082836-dc87e655-671b-47d4-8602-7f7799cb764c.png">

### Browers

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.7.11
API version:         0.8.4
Python version:      3.10.5
Git commit:          6b27b476
Built:               Thu, Feb 2, 2023 7:22 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         hosted
```
```


### Additional context

_No response_

**Comment by madkinsz** [comment] 2023-02-06 22:50
@komodovaran is this a duplicate of https://github.com/PrefectHQ/prefect/issues/8180?

**Comment by komodovaran** [comment] 2023-02-07 07:57
> @komodovaran is this a duplicate of #8180?

Yes, seems so

**Closed** 2023-02-07 21:41 UTC
Labels: bug, status:duplicate, ui
