### ISSUE TITLE
Bulk deletion of flows in the UI

### ISSUE THREAD

**Issue by SeifHediya** [PrefectHQ/prefect#6025] opened 2022-07-19 03:26 UTC
## Description
A dealbreaker that deterred me from using v2.0 (since it has async support) is not having bulk selection of flows to delete them. It's cumbersome to delete one by one, especially if you have a lot of flow runs. Having this feature would be great to enhance the UX.

**Comment by zhen0** [comment] 2022-07-19 20:44
@billpalombi - maybe one for further consideration. I think this would need api changes too.

**Comment by zhen0** [comment] 2022-07-19 20:46
Also a duplicate of #6000

**Comment by billpalombi** [comment] 2022-07-20 15:47
This is on the roadmap for the latter half of this year. I'll report back when we take this work up.

**Comment by SeifHediya** [comment] 2022-07-23 16:03
This is fantastic! Thank you @billpalombi @zhen0

**Comment by zhen0** [comment] 2022-11-01 14:57
@billpalombi @brigidgliwa - whatever we decide for deployment multi delete could we add here also?

**Comment by brigidgliwa** [comment] 2022-11-03 14:04
Use the same design from https://github.com/PrefectHQ/prefect/issues/7363

Figma: https://www.figma.com/file/WQwcuqBAxug8JqLigWaztu/Designs?node-id=2119%3A24809
<img width="1326" alt="01-Deployments Delete" src="https://user-images.githubusercontent.com/104096908/199741662-1dd2a53a-0125-4248-8838-a8759da5d3cc.png">
<img width="1326" alt="02-Deployments Delete" src="https://user-images.githubusercontent.com/104096908/199741684-ee955557-8836-4d66-96bc-b0193b31ed7a.png">

**Comment by billpalombi** [comment] 2022-11-03 14:15
@brigidgliwa - While the scope of this ticket is specific to bulk deletion, users will want to take other actions in bulk in the future, including but not limited to:
- applying labels
- pausing/activating

Presumably, we would add additional buttons above the table for each action. If we put them next to the delete button in this design, they would push the search bar further to the left. Should we instead put the button to the left of the search bar so that it doesn't move when items are selected in bulk?

**Comment by brigidgliwa** [comment] 2022-11-03 14:22
That makes sense to me...I put it on the right to stay consistent with what we have on the flow runs page but if we will have multiple actions I think we should make the change across all pages

**Comment by billpalombi** [comment] 2022-11-03 14:23
Yeah lets definitely design for a future with multiple actions.

**Comment by zhen0** [comment] 2022-11-14 13:51
Is this one ready for development or did we want to update the design to consider multiple actions? @brigidgliwa @billpalombi

**Comment by brigidgliwa** [comment] 2022-11-14 14:37
I talked to Marichka about the original design and she had concerns that the animation might look odd coming in from the left. I've been thinking about this and some of our tables already have a lot of info in the top line so I was thinking we could do something like this where the top bar shows the number of selected items and the actions available (see below). With this design, we potentially lose the ability to search/filter unless we also include that in the selected state and just remove the sorting feature. Since this is a larger change than just switching the side the button is on, @zhen0 I'm curious if you think we should implement the trash can icon like it is on the flow runs page and then when we have more actions make a larger design change or make the change now.

<img width="773" alt="Screen Shot 2022-11-14 at 9 30 13 AM" src="https://user-images.githubusercontent.com/104096908/201685752-113b4774-85f5-4e08-9999-803240cc991a.png">

**Comment by billpalombi** [comment] 2022-11-14 19:52
@brigidgliwa for what its worth, I think we should explore adding a count of selected items, as in the image you attached, now. We should make the connection between the items selected and the action being taken as explicit as possible.

**Comment by zhen0** [comment] 2022-11-16 03:01
Thanks @brigidgliwa Are you suggesting we'd lose the search/sort altogether or only when selecting items? I don't think we'd want to remove those altogether so we'd need to think through how those and the count etc fit together.

**Comment by brigidgliwa** [comment] 2022-11-16 03:17
@zhen0 I definitely think we should keep search/sort but when selecting items we need space for the buttons so I was saying we could potentially remove search/sort when items are selected but I'm ideally trying to think of a design that incorporates the buttons, number of items selected, and search/sort

**Comment by brigidgliwa** [comment] 2022-11-22 22:54
I updated the design to show the number of selected items and the actions right next to it (very similar to how GitHub does it). Search and filters will still be shown but sort will not.

<img width="1326" alt="02-Deployments Delete" src="https://user-images.githubusercontent.com/104096908/203437715-c54c53ac-c65e-437a-a516-87400d760cfe.png">

**Comment by zhen0** [comment] 2022-11-23 14:46
Thanks @brigidgliwa!

Since the action here is mainly in the table I'll flag that https://github.com/PrefectHQ/prefect/issues/7363 is a very similar piece of work and it might make sense to do them together.

**Comment by marichka-offen** [comment] 2022-12-01 19:58
@brigidgliwa, @billpalombi, @zhen0 I think we need to rethink where to put the delete button, and potentially make it independent of the table. If I have a lot of flows and scroll all the way to the bottom to delete a couple there, I'm not going to see that delete button appear all the way on top. The same goes for the flowRuns cards on the dashboard, there's nothing that tells me there's a button for me on top, + scrolling back and forth is not a good UX

![Image](https://user-images.githubusercontent.com/40467112/205147551-78404c51-6f65-414f-9cae-9f49e8e29912.png)

**Comment by brigidgliwa** [comment] 2022-12-01 20:06
@marichka-offen would having a sticky header fix the problem you are talking about?

**Comment by marichka-offen** [comment] 2022-12-01 20:15
@brigidgliwa I don't think so, but I might be wrong because I don't know. The main reason I don't think so is that dashboard with flowRuns doesn't have a header to stick. Also, I don't have experience with applying this to tables, so I'll refer this question to @pleek91 and @brandonreid

**Comment by zhen0** [comment] 2022-12-02 03:15
I don't think we need to be overly concerned about this @marichka-offen - adding multi-delete is a great step forward and the design that Brigid has suggested here is similar to the one in github.  

If you look at a table in github (e.g. a list of issues) you can check a box and need to scroll back up to figure out the related action.  That feels ok to me. 

![Image](https://user-images.githubusercontent.com/40272060/205206630-85a67d43-f9a7-4bc7-9ac4-81fa199f6b6b.png)

**Comment by brandonreid** [comment] 2022-12-02 14:51
I believe we can make the header sticky, as @marichka-offen is suggesting, really easily with CSS that applies when bulk actions are visible

Here's a quick demo:
https://user-images.githubusercontent.com/6776415/205319986-1186d10e-fa04-4c56-8fa7-71b68fc522c9.mov

**Comment by billpalombi** [comment] 2022-12-02 15:31
I think the sticky header idea is a good one to explore. Regardless, we can proceed with the design we have and explore modifications to it as we build or after shipping it.

**Closed** 2022-12-05 17:46 UTC
Labels: ui, v2, priority:high
