### ISSUE TITLE
UI displays 'Every year' for any RruleSchedule

### ISSUE THREAD

**Issue by vdytyniak-exos** [PrefectHQ/prefect#7456] opened 2022-11-07 10:00 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

UI does not display correctly the RruleSchedule.

### Reproduction

RRuleSchedule(
    rrule='RDATE:20221020T204000Z,20221020T230000Z'
)

<img width="462" alt="image" src="https://user-images.githubusercontent.com/94358054/200281752-e39d8229-6c5c-42ce-a59b-8b985e530a6b.png">

### Error

UI displays the provided rule as 'Every year' on Deployments page.

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.6.5
API version:         0.8.3
Python version:      3.10.5
Git commit:          9fc2658f
Built:               Thu, Oct 27, 2022 2:24 PM
OS/Arch:             darwin/x86_64
Server type:         cloud
```

### Additional context

https://github.com/PrefectHQ/prefect/issues/7155

**Comment by zhen0** [comment] 2022-11-08 19:28
Possibly a duplicate of https://github.com/PrefectHQ/prefect/issues/6740?

**Comment by zhen0** [comment] 2022-11-16 16:48
https://github.com/jakubroztocil/rrule/issues/558

**Closed** 2022-11-16 21:50 UTC
Labels: bug, status:duplicate, ui

**Comment by vdytyniak-exos** [comment] 2022-11-17 07:55
> jakubroztocil/rrule#558

Actually dates behind this rule are correct and flow is running as expected, but label still says 'Every year'.
