### ISSUE TITLE
Agent silently stops picking up jobs with Client error '403 Forbidden'

### ISSUE THREAD

**Issue by vholmer** [PrefectHQ/prefect#7323] opened 2022-10-26 08:07 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Occasionally when not running any jobs, like in the middle of the night, the agent throws the following exception when trying to ping the prefect api:

```
PrefectHTTPStatusError: Client error '403 Forbidden' for url
'https://api.prefect.cloud/api/accounts/<ACCOUNTGUID>/wor
kspaces/<WORKSPACEGUID>/work_queues/<WORKQUEUEGUID>/get_runs'
```

At /usr/local/lib/python3.8/dist-packages/prefect/client/base.py:125. Submitting any flows after this exception leads to them being visible in the Prefect cloud web interface as "Scheduled" or "Late". Basically the agent completely stops working after this, but it doesn't actually crash.

Ideally they shouldn't throw this exception at all, the agents shouldn't just stop working randomly.
Pragmatically, however, they shouldn't just throw this exception and keep existing in some kind of limbo requiring a manual restart. I think it'd be better if they just properly died, allowing for e.g. a daemon to restart the agent automatically, if you're running the agent on a VM like me.

### Reproduction

Run a Prefect 2.5.0 agent on an Ubuntu Azure VM (Standard_D2s_v3) for extended period of time

### Error

```python3
PrefectHTTPStatusError: Client error '403 Forbidden' for url
'https://api.prefect.cloud/api/accounts/<ACCOUNTGUID>/wor
kspaces/<WORKSPACEGUID>/work_queues/<WORKQUEUEGUID>/get_runs'
```

At /usr/local/lib/python3.8/dist-packages/prefect/client/base.py:125

### Versions

```Text
Version:             2.5.0
API version:         0.8.2
Python version:      3.8.10
Git commit:          eac37918
Built:               Thu, Oct 6, 2022 12:41 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.31.1
```

### Additional Context

My current workaround is just to check for any 'Scheduled' or 'Late' flows that should be running. If I see them, I ssh into the VM and manually restart the agent after which it works as intended.

**Comment by KayJey-Krayen** [comment] 2022-10-26 08:18
I am also observing similar error but also sometimes without Client error '403 Forbidden' .
The agent just stops picking up on the flows and  on the prefect ui , the flows are marked as late or pending . 
When I manually ssh into the terminal , all flows gets resumed using an enormous amount of RAM , and it starts to execute all the 'scheduled / late' flow.

**Comment by bjorhn** [comment] 2022-10-26 08:30
I believe something similar to this might be the cause of something I've been seeing since first migrating to Prefect 2 back in August. Since then I've had to manually restart agent processes every now and then due to them no longer grabbing flow runs. The processes never properly "crashed" but the last thing they logged was usually some sort of http error, then they got stuck.

**Comment by johnkangw** [comment] 2022-10-26 15:56
I have a similar issue with agents silently failing in the middle of the night (running Prefect agent on a windows VM). I had a separate issue because i thought it was connected to windows: https://github.com/PrefectHQ/prefect/issues/6685#issuecomment-1292260233

**Comment by madkinsz** [comment] 2022-10-26 16:58
Thanks for the report! We believe we have identified the root cause of this (https://github.com/PrefectHQ/prefect/issues/6685#issuecomment-1292223436) and deployed a fix this morning. Let us know if you encounter this again :)

**Closed** 2022-10-26 16:58 UTC
Labels: bug, priority:high, cloud

**Comment by vholmer** [comment] 2022-11-07 18:17
@madkinsz just FYI we haven't had any issues since this fix. Thanks a lot! :smile:

**Comment by johnkangw** [comment] 2022-11-07 20:59
@madkinsz I haven't either! Things are good on my end even on a windows VM!

**Comment by madkinsz** [comment] 2022-11-07 21:00
Thanks ya'll! Great to hear.
