### ISSUE TITLE
RuntimeError: The task runner must be started before submitting work.

### ISSUE THREAD

**Issue by glesperance** [PrefectHQ/prefect#14788] opened 2024-07-29 21:45 UTC
### Bug summary

```python

import asyncio

from prefect import flow, task

from prefect_ray import RayTaskRunner


@task
async def shout(number):
    await asyncio.sleep(5)
    print(f"#{number}")


@task
def count_to(highest_number):
    futures = shout.map([i for i in range(highest_number)])
    return [f.result() for f in futures]


@flow(log_prints=True, task_runner=RayTaskRunner())
async def many_flows(highest_number: int, times: int):
    futures = count_to.map([highest_number] * times)
    return [f.result() for f in futures]


if __name__ == "__main__":
    asyncio.run(many_flows(10, 3))
```

This fails with

```log
/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/bin/python /Users/gabriel/Workspace/trampoline-ai/trampoline-ai.forma/apps/transform/scratch/prefect-tests/broken/ray-bug-submitted-as-issue.py
(trampoline-ai-transform-3gw9QNML-py3.10) gabriel@mt trampoline-ai.forma % /Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/bin/python /Users
/gabriel/Workspace/trampoline-ai/trampoline-ai.forma/apps/transform/scratch/prefect-tests/broken/ray-bug-submitted-as-issue.py
17:43:06.226 | INFO    | prefect.engine - Created flow run 'fluorescent-gerbil' for flow 'many-flows'
17:43:06.229 | INFO    | prefect.engine - View at https://app.prefect.cloud/account/d0cdeecd-4ec8-4dc6-98a8-d6c45e5c049d/workspace/80bf2478-7e65-4b46-988f-e3307068b3b5/runs/flow-run/af127312-741e-483d-a81d-1cd223b4cf3a
17:43:06.463 | INFO    | prefect.task_runner.ray - Creating a local Ray instance
2024-07-29 17:43:08,573 INFO worker.py:1772 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265 
17:43:09.627 | INFO    | prefect.task_runner.ray - Using Ray cluster with 1 nodes.
17:43:09.628 | INFO    | prefect.task_runner.ray - The Ray UI is available at 127.0.0.1:8265
(count_to pid=34664) 17:43:12.390 | INFO    | Task run 'count_to-7cb412a6-570e-4d7c-9e20-264e1b6d2fcc' - Created task run 'count_to-7cb412a6-570e-4d7c-9e20-264e1b6d2fcc' for task 'count_to'
(count_to pid=34664) 17:43:12.672 | ERROR   | Task run 'count_to-7cb412a6-570e-4d7c-9e20-264e1b6d2fcc' - Task run failed with exception: RuntimeError('The task runner must be started before submitting work.') - Retries are exhausted
(count_to pid=34664) Traceback (most recent call last):
(count_to pid=34664)   File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/task_engine.py", line 763, in run_context
(count_to pid=34664)     yield self
(count_to pid=34664)   File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/task_engine.py", line 819, in run_task_sync
(count_to pid=34664)     engine.call_task_fn(txn)
(count_to pid=34664)   File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/task_engine.py", line 792, in call_task_fn
(count_to pid=34664)     result = call_with_parameters(self.task.fn, parameters)
(count_to pid=34664)   File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/utilities/callables.py", line 208, in call_with_parameters
(count_to pid=34664)     return fn(*args, **kwargs)
(count_to pid=34664)   File "/Users/gabriel/Workspace/trampoline-ai/trampoline-ai.forma/apps/transform/scratch/prefect-tests/broken/ray-bug-submitted-as-issue.py", line 16, in count_to
(count_to pid=34664)     futures = shout.map([i for i in range(highest_number)])
(count_to pid=34664)   File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/_internal/compatibility/deprecated.py", line 322, in wrapper
(count_to pid=34664)     result = wrapped(*args, **kwargs)
(count_to pid=34664)   File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/tasks.py", line 1352, in map
(count_to pid=34664)     futures = task_runner.map(self, parameters, wait_for)
(count_to pid=34664)   File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect_ray/task_runners.py", line 311, in map
(count_to pid=34664)     return super().map(task, parameters, wait_for)
(count_to pid=34664)   File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/task_runners.py", line 116, in map
(count_to pid=34664)     raise RuntimeError(
(count_to pid=34664) RuntimeError: The task runner must be started before submitting work.
17:43:12.810 | ERROR   | Flow run 'fluorescent-gerbil' - Encountered exception during execution: RuntimeError('The task runner must be started before submitting work.')
Traceback (most recent call last):
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/flow_engine.py", line 633, in run_context
    yield self
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/flow_engine.py", line 696, in run_flow_async
    await engine.call_flow_fn()
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/flow_engine.py", line 651, in _call_flow_fn
    result = await call_with_parameters(self.flow.fn, self.parameters)
  File "/Users/gabriel/Workspace/trampoline-ai/trampoline-ai.forma/apps/transform/scratch/prefect-tests/broken/ray-bug-submitted-as-issue.py", line 23, in many_flows
    return [f.result() for f in futures]
  File "/Users/gabriel/Workspace/trampoline-ai/trampoline-ai.forma/apps/transform/scratch/prefect-tests/broken/ray-bug-submitted-as-issue.py", line 23, in <listcomp>
    return [f.result() for f in futures]
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect_ray/task_runners.py", line 147, in result
    _result = run_coro_as_sync(_result)
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 249, in run_coro_as_sync
    return call.result()
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 312, in result
    return self.future.result(timeout=timeout)
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 182, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 383, in _run_async
    result = await coro
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 231, in coroutine_wrapper
    return await task
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 388, in ctx_call
    result = await async_fn(*args, **kwargs)
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/states.py", line 127, in _get_state_result
    raise await get_state_exception(state)
RuntimeError: The task runner must be started before submitting work.
(count_to pid=34664) 17:43:12.804 | ERROR   | Task run 'count_to-7cb412a6-570e-4d7c-9e20-264e1b6d2fcc' - Finished in state Failed('Task run encountered an exception RuntimeError: The task runner must be started before submitting work.')
(count_to pid=34674) 17:43:12.408 | INFO    | Task run 'count_to-ba0a6ad7-c2e5-458a-8199-94d4db8479f3' - Created task run 'count_to-ba0a6ad7-c2e5-458a-8199-94d4db8479f3' for task 'count_to' [repeated 2x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)
(count_to pid=34674) 17:43:12.687 | ERROR   | Task run 'count_to-ba0a6ad7-c2e5-458a-8199-94d4db8479f3' - Task run failed with exception: RuntimeError('The task runner must be started before submitting work.') - Retries are exhausted [repeated 2x across cluster]
(count_to pid=34674) Traceback (most recent call last): [repeated 2x across cluster]
(count_to pid=34674)   File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/task_engine.py", line 763, in run_context [repeated 2x across cluster]
(count_to pid=34674)     yield self [repeated 2x across cluster]
(count_to pid=34674)   File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/task_engine.py", line 819, in run_task_sync [repeated 2x across cluster]
(count_to pid=34674)     engine.call_task_fn(txn) [repeated 2x across cluster]
(count_to pid=34674)   File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/task_engine.py", line 792, in call_task_fn [repeated 2x across cluster]
(count_to pid=34674)     result = call_with_parameters(self.task.fn, parameters) [repeated 2x across cluster]
(count_to pid=34674)   File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/utilities/callables.py", line 208, in call_with_parameters [repeated 2x across cluster]
(count_to pid=34674)     return fn(*args, **kwargs) [repeated 2x across cluster]
(count_to pid=34674)   File "/Users/gabriel/Workspace/trampoline-ai/trampoline-ai.forma/apps/transform/scratch/prefect-tests/broken/ray-bug-submitted-as-issue.py", line 16, in count_to [repeated 2x across cluster]
(count_to pid=34674)     futures = shout.map([i for i in range(highest_number)]) [repeated 2x across cluster]
(count_to pid=34674)   File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/_internal/compatibility/deprecated.py", line 322, in wrapper [repeated 2x across cluster]
(count_to pid=34674)     result = wrapped(*args, **kwargs) [repeated 2x across cluster]
(count_to pid=34674)   File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/task_runners.py", line 116, in map [repeated 6x across cluster]
(count_to pid=34674)     futures = task_runner.map(self, parameters, wait_for) [repeated 2x across cluster]
(count_to pid=34674)     return super().map(task, parameters, wait_for) [repeated 2x across cluster]
(count_to pid=34674)     raise RuntimeError( [repeated 2x across cluster]
(count_to pid=34674) RuntimeError: The task runner must be started before submitting work. [repeated 2x across cluster]
(count_to pid=34672) 17:43:12.858 | ERROR   | Task run 'count_to-988a1244-a118-45a6-bba3-6173d5262820' - Finished in state Failed('Task run encountered an exception RuntimeError: The task runner must be started before submitting work.') [repeated 2x across cluster]
17:43:14.499 | ERROR   | Flow run 'fluorescent-gerbil' - Finished in state Failed('Flow run encountered an exception: RuntimeError: The task runner must be started before submitting work.')
Traceback (most recent call last):
  File "/Users/gabriel/Workspace/trampoline-ai/trampoline-ai.forma/apps/transform/scratch/prefect-tests/broken/ray-bug-submitted-as-issue.py", line 27, in <module>
    asyncio.run(many_flows(10, 3))
  File "/usr/local/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/flow_engine.py", line 698, in run_flow_async
    return engine.state if return_type == "state" else engine.result()
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/flow_engine.py", line 245, in result
    raise self._raised
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/flow_engine.py", line 633, in run_context
    yield self
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/flow_engine.py", line 696, in run_flow_async
    await engine.call_flow_fn()
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/flow_engine.py", line 651, in _call_flow_fn
    result = await call_with_parameters(self.flow.fn, self.parameters)
  File "/Users/gabriel/Workspace/trampoline-ai/trampoline-ai.forma/apps/transform/scratch/prefect-tests/broken/ray-bug-submitted-as-issue.py", line 23, in many_flows
    return [f.result() for f in futures]
  File "/Users/gabriel/Workspace/trampoline-ai/trampoline-ai.forma/apps/transform/scratch/prefect-tests/broken/ray-bug-submitted-as-issue.py", line 23, in <listcomp>
    return [f.result() for f in futures]
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect_ray/task_runners.py", line 147, in result
    _result = run_coro_as_sync(_result)
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 249, in run_coro_as_sync
    return call.result()
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 312, in result
    return self.future.result(timeout=timeout)
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 182, in result
    return self.__get_result()
  File "/usr/local/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 383, in _run_async
    result = await coro
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 231, in coroutine_wrapper
    return await task
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 388, in ctx_call
    result = await async_fn(*args, **kwargs)
  File "/Users/gabriel/Library/Caches/pypoetry/virtualenvs/trampoline-ai-transform-3gw9QNML-py3.10/lib/python3.10/site-packages/prefect/states.py", line 127, in _get_state_result
    raise await get_state_exception(state)
RuntimeError: The task runner must be started before submitting work.
```

### Version info (`prefect version` output)

```Text
Version:             3.0.0rc13
API version:         0.8.4
Python version:      3.10.14
Git commit:          530521dd
Built:               Fri, Jul 26, 2024 1:24 PM
OS/Arch:             darwin/x86_64
Profile:             default
Server type:         cloud
Pydantic version:    2.8.2
Integrations:
  prefect-ray:       0.4.0rc2
```

**Comment by desertaxle** [comment] 2024-07-30 17:56
Thanks for the issue @glesperance! I think you're seeing this error because you're mapping inside a task that itself was mapped in a flow via a `RayTaskRunner`, and the tasks mapped via Ray run in a different memory space, so the mapped task doesn't have access to the active task runner.

The active task runner is available on the `FlowRunContext`, which works well if the run is using a shared memory space (like with the `ThreadPoolTaskRunner`), but task runners like the `RayTaskRunner` require the use of the [`serialize_context`](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/context.py#L62-L77) and [`hydrated_context`](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/context.py#L80-L116) utilities which handle transporting context to different memory spaces.

If I had to guess, the issue is that a new task runner is created but not started [here](https://github.com/PrefectHQ/prefect/blob/0335c769ce8afba5dc67cade8b752f0cbd426c57/src/prefect/context.py#L98). If we update `hydrated_context` to start the task runner, I bet it would resolve this issue.

Let me know if you want to submit a PR for this issue! Otherwise, I can work on a fix and add you as a reviewer so you help make sure the issue is fixed.

**Comment by glesperance** [comment] 2024-07-30 19:08
@desertaxle I'm currently bogged down into implementing a PoC so if you could make a PR I'd be happy to try it / review it. 
ty

**Comment by desertaxle** [comment] 2024-08-05 15:34
Hey @glesperance! I have a potential fix for this issue in https://github.com/PrefectHQ/prefect/pull/14829. If you get the chance, would you be able to give the changes a test/review to make sure it solves the issue for you?

**Closed** 2024-08-06 15:39 UTC
Labels: bug, integrations
