### ISSUE TITLE
Increase the number of flows that a Prefect agent can submit

### ISSUE THREAD

**Issue by gabcoyne** [PrefectHQ/prefect#7826] opened 2022-12-08 22:01 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, as seen with k8s jobs and an agent on k8s, there is a limit to the number of concurrent jobs submitted, it looks to be around 20. This severely limits the throughput of job submission and is the main reason that customers are pursuing multiple agents.

### Describe the proposed behavior

The agent can submit thousands of jobs a minute

### Example Use

[Stress Test Repo](https://github.com/PrefectHQ/stress-testing)

**Comment by madkinsz** [comment] 2022-12-08 22:08
For other maintainers: This is caused by the default thread limiter since we run monitoring of each job in a thread. Yeesh!

**Comment by madkinsz** [comment] 2023-01-09 17:00
I can make more improvements here, but the immediate bottleneck is resolved by #7961.

**Closed by madkinsz** 2023-01-09 17:00 UTC
Labels: enhancement, status:accepted, priority:high, from:sales
