### ISSUE TITLE
Anchor dates in ScheduleIntervals do not properly handle time zone conversions

### ISSUE THREAD

**Issue by austinweisgrau** [PrefectHQ/prefect#9763] opened 2023-05-26 23:07 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Anchor dates set on deployment schedule intervals do not properly handle time zone conversions.

Setting, for example, an Interval Schedule at a daily interval with an anchor date at 4:00am in America/New York time zone results in an anchor date of 6:00am in the America/New York time zone in Prefect Cloud.

### Reproduction

```python3
import datetime
from prefect.server.schemas.schedules import IntervalSchedule

interval = datetime.timedelta(days=1)
anchor_date = datetime.datetime.today().replace(hour=4, minute=0, second=0)
schedule = IntervalSchedule(
            interval=interval, anchor_date=anchor_date, timezone="America/New_York"
        )


this results in an anchor date of 6:00am America/New York in Prefect Cloud.
```

### Versions

```Text
Version:             2.8.2
API version:         0.8.4
Python version:      3.10.9
Git commit:          afbed19d
Built:               Fri, Feb 17, 2023 10:02 AM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```

**Comment by austinweisgrau** [comment] 2023-06-03 00:13
My point is that the timezone setting isn't working. If I set an anchor date at 04:00 with timezone America/New_York, I would expect the flow to be scheduled daily at 4am America/New_York. Instead, flow is scheduled daily at 6am America/New_York.

**Comment by braunreyes** [comment] 2023-07-11 14:53
I was able to recreate this as well.  If I apply a deployment via CLI like this:

```
--interval 86400 --timezone America/New_York --anchor-date 2023-06-27T01:00:00Z
```

I end up with a schedule in the UI, that looks like this:

![image](https://github.com/PrefectHQ/prefect/assets/11067272/0bc262ac-76a1-4f94-8f70-2713994b7487)

The subsequent scheduled flows show scheduled for 8pm as well.

Looking at cron as a comparison, this does not seem correct.

Cron:

```
--cron '0 1 * * *' --timezone America/New_York
```

![image](https://github.com/PrefectHQ/prefect/assets/11067272/39c30179-48a9-4755-bb89-b8657c6d581f)

This is how I would expect interval to look

This is on 2.10.20

**Comment by nchammas** [comment] 2023-07-14 21:05
I am seeing something similar. I've created a deployment with the following schedule:

```python
from datetime import timedelta
from pendulum import datetime

IntervalSchedule(
    anchor_date=datetime(2023, 7, 11, 9, 0),
    interval=timedelta(days=1),
    timezone="America/New_York",
)
```

So I would expect the flow for this deployment to run every morning at 9am, since I am located on the US East Coast.

However, when I look at this same deployment in the Prefect Cloud UI, I see the schedule specified as:

> Daily from Jul 11th, 2023 at 05:00:00 AM (America/New_York)

So it looks like it interpreted the anchor date in UTC, which is 4 hours ahead of EDT (i.e. East Coast summer time), and then translated it to EDT. So 9am minus 4 hours gives you 5am.

It's not the same behavior as @austinweisgrau reported, but I presume the root cause is the same.

**Comment by nchammas** [comment] 2023-07-17 21:07
If I specify the timezone as part of the `datetime()`, things work as expected:

```python
from datetime import timedelta
from pendulum import datetime

IntervalSchedule(
    anchor_date=datetime(2023, 7, 11, 9, 0, tz="America/New_York"),
    interval=timedelta(days=1),
    timezone="America/New_York",
)
```

This is in contrast to `RRule`, where I only have to specify the timezone once for it to work as expected:

```python
from dateutil import rrule

RRuleSchedule(
    rrule=str(rrule.rrule(
        freq=rrule.WEEKLY,
        interval=1,
        dtstart=datetime(2023, 7, 11, 9, 0),
    )),
    timezone="America/New_York",
)
```

So for some reason, `IntervalSchedule` needs the `DateTime` object to be specified in the correct timezone, whereas the `rrule()` utility avoids this problem somehow.

**Comment by jakekaplan** [comment] 2023-08-25 13:13
While I can't produce the original problem of 6am being used as the anchor date:
```python
import datetime
from prefect.server.schemas.schedules import IntervalSchedule
import asyncio

async def main():
    interval = datetime.timedelta(days=1)
    anchor_date = datetime.datetime.today().replace(hour=4, minute=0, second=0)
    schedule = IntervalSchedule(
                interval=interval,
                anchor_date=anchor_date,
                timezone="America/New_York"
            )
    dates = await schedule.get_dates(n=3)
    print("Anchor date:", anchor_date)
    print("Next 3 dates:")
    for d in dates:
        print("-", d)

if __name__ == '__main__':
    asyncio.run(main())
    
# Anchor date: 2023-08-25 04:00:00.822977
# Next 3 dates:
# - 2023-08-26T00:00:00.822977-04:00
# - 2023-08-27T00:00:00.822977-04:00
# - 2023-08-28T00:00:00.822977-04:00
```  

There is some maybe unintuitive behavior here in that the `IntervalSchedule` will interpret the anchor date as `UTC` unless specified (separately pendulum always defaults to `UTC` not naive tz unlike `datetime.datetime`). This is observable below:
```python
IntervalSchedule(
    anchor_date=datetime(2023, 7, 11, 9, 0),
    interval=timedelta(days=1),
    timezone="America/New_York",
)
# Anchor date: 2023-07-11T09:00:00+00:00 <-- UTC anchor date
# Next 3 dates:
# - 2023-08-26T05:00:00-04:00 <-- converted to "America/New_York"
# - 2023-08-27T05:00:00-04:00
# - 2023-08-28T05:00:00-04:00
   
IntervalSchedule(
    anchor_date=datetime(2023, 7, 11, 9, 0, tz="America/New_York"),
    interval=timedelta(days=1)
)
# Anchor date: 2023-07-11T09:00:00-04:00
# Next 3 dates:
# - 2023-08-26T09:00:00-04:00
# - 2023-08-27T09:00:00-04:00
# - 2023-08-28T09:00:00-04:00
```

**Comment by jakekaplan** [comment] 2023-08-29 14:48
I'm going to close this issue as I cannot reproduce the original MRE, however I'll likely link another issue here for updating the behavior to be more intuitive.

**Closed by jakekaplan** 2023-08-29 14:48 UTC
Labels: bug, status:accepted, from:sales
