### ISSUE TITLE
Can't scroll through logs in UI

### ISSUE THREAD

**Issue by samgarvis** [PrefectHQ/prefect#6828] opened 2022-09-14 17:08 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

On 2.0

The scroll through the logs in the UI is jammed. Like it will show the logs and then I can't scroll down anymore. This happens very frequently, and is sometimes detrimental when i need to debug something quickly.

### Reproduction

```python
-----
```

### Error

------

### Versions

------

**Comment by zhen0** [comment] 2022-09-14 17:49
Thanks @samgarvis.  I'm afraid I can't replicate so I wonder if there might be something specific about your setup that's causing an issue?  If you can any more detail, I'm happy to try again.  

For info, we now have logs split by task run which might help cut down on the number of logs you need to scroll through?

https://www.loom.com/share/90c71eecff294e01bcc638ef68b52a67

**Comment by samgarvis** [comment] 2022-09-14 19:07
Update. I can scroll when I move my cursor to the side of the screen, but still cant when it's in the middle
https://www.loom.com/share/743c222889c94f2bbbee90358cde3966

**Comment by zhen0** [comment] 2022-09-15 02:35
Oh interesting!  I'll look out for that and see if we can figure out what the issue is.

**Comment by zhen0** [comment] 2022-09-15 20:27
I think we found the issue. We'll aim to get a fix out soon!

**Comment by pleek91** [comment] 2022-09-23 21:36
@zhen0 did the fix for this go out with the last release?

**Comment by zhen0** [comment] 2022-09-29 13:12
Yes it should have done.  @samgarvis  can you confirm this issue is resolved for you?

**Closed** 2022-10-10 17:26 UTC
Labels: bug, ui, v2, priority:medium
