### ISSUE TITLE
Custom ResultHandler Not Working on Cloud

### ISSUE THREAD

**Issue by joeschmid** [PrefectHQ/prefect#1507] opened 2019-09-14 02:39 UTC
## Description
When using a class derived from ResultHandler (essentially a copy of LocalResultHandler that we want to customize) and running on Cloud, the write() method of the result handler is called and runs, but we get an error about failing to set task state in the task logs:

```
2019-9-13 10:25pm | prefect.CloudTaskRunner | DEBUG | Task 'extract': Handling state change from Pending to Running
-- | -- | -- | --
2019-9-13 10:25pm | prefect.CloudTaskRunner | DEBUG | Task 'extract': Calling task.run() method...
2019-9-13 10:25pm | prefect.TestResultHandler | INFO | WRITE -----------------------------------------
2019-9-13 10:25pm | prefect.TestResultHandler | INFO | parameters={'cache_validator_return_value': 'False'}
2019-9-13 10:25pm | prefect.TestResultHandler | INFO | Starting to upload result to /home/jovyan/tmp/prefect-c__ordd8...
2019-9-13 10:25pm | prefect.TestResultHandler | INFO | Finished uploading result to /home/jovyan/tmp/prefect-c__ordd8...
2019-9-13 10:25pm | prefect.CloudTaskRunner | DEBUG | Task 'extract': Handling state change from Running to Success
2019-9-13 10:25pm | prefect.CloudTaskRunner | ERROR | Failed to set task state with error: ClientError([{'message': "{'_result': {'result_handler': {'type': ['Unsupported value: TestResultHandler']}}}", 'locations': [{'line': 2, 'column': 5}], 'path': ['setTaskRunState'], 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'exception': {'errors': [{'message': "{'_result': {'result_handler': {'type': ['Unsupported value: TestResultHandler']}}}", 'locations': [], 'path': ['setTaskRunState']}]}}}]) Traceback (most recent call last):   File "/opt/conda/lib/python3.7/site-packages/prefect/engine/cloud/task_runner.py", line 95, in call_runner_target_handlers     cache_for=self.task.cache_for,   File "/opt/conda/lib/python3.7/site-packages/prefect/client/client.py", line 906, in set_task_run_state     self.graphql(mutation, variables=dict(state=serialized_state))  # type: Any   File "/opt/conda/lib/python3.7/site-packages/prefect/client/client.py", line 212, in graphql     raise ClientError(result["errors"]) prefect.utilities.exceptions.ClientError: [{'message': "{'_result': {'result_handler': {'type': ['Unsupported value: TestResultHandler']}}}", 'locations': [{'line': 2, 'column': 5}], 'path': ['setTaskRunState'], 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'exception': {'errors': [{'message': "{'_result': {'result_handler': {'type': ['Unsupported value: TestResultHandler']}}}", 'locations': [], 'path': ['setTaskRunState']}]}}}]
```
The Task remains in Running state until the ZombieKiller terminates it.

## Expected Behavior
We'd expect the write() method of the result handler to execute without error and the task to execute sucessfully.

## Reproduction
```
from datetime import timedelta
import tempfile
import cloudpickle

import prefect
from prefect import Flow, task, Parameter
from prefect.environments.execution.remote import RemoteEnvironment
from prefect.engine.result_handlers import ResultHandler

CACHE_VALIDATOR_PARAM_NAME = 'cache_validator_return_value'


def test_cache_validator(state, inputs, parameters):
    # For testing purposes, the parameter controls whether we return True or False
    return parameters.get(CACHE_VALIDATOR_PARAM_NAME, 'False') == 'True'


class TestResultHandler(ResultHandler):
    def __init__(self, dir):
        self.dir = dir
        super().__init__()

    def read(self, fpath):
        self.logger.info('READ ------------------------------------------')
        self.logger.info("Starting to read result from {}...".format(fpath))
        with open(fpath, "rb") as f:
            val = cloudpickle.loads(f.read())
        self.logger.info("Finished reading result from {}...".format(fpath))
        return val

    def write(self, result):
        self.logger.info('WRITE -----------------------------------------')
        self.logger.info('parameters={}'.format(prefect.context.parameters))
        fd, loc = tempfile.mkstemp(prefix="prefect-", dir=self.dir)
        self.logger.info("Starting to upload result to {}...".format(loc))
        with open(fd, "wb") as f:
            f.write(cloudpickle.dumps(result))
        self.logger.info("Finished uploading result to {}...".format(loc))
        return loc


@task(result_handler=TestResultHandler(dir='/home/jovyan/tmp'), checkpoint=True)
def extract(p):
    return [1, 2, 36]


@task(result_handler=TestResultHandler(dir='/home/jovyan/tmp'), checkpoint=True,
      cache_validator=test_cache_validator, cache_for=timedelta(minutes=5))
def transform(x):
    return [i * 10 for i in x]


@task()  # cache_validator=test_cache_validator, cache_for=timedelta(minutes=2))
def load(y):
    import prefect
    logger = prefect.context.get("logger")
    logger.info("Received y: {}".format(y))


env = RemoteEnvironment(
    executor="prefect.engine.executors.DaskExecutor",
    executor_kwargs={"address": "tcp://dask-scheduler:8786"}
)

with Flow("SimpleResultHandlerFlow", environment=env) as flow:
    p1 = Parameter(CACHE_VALIDATOR_PARAM_NAME, default='False')
    e = extract(p1)
    t = transform(e)
    l = load(t)
```

## Environment
We're using our own Dask cluster via RemoteEnvironment and the DaskExecutor.

**Comment by jlowin** [comment] 2019-09-14 05:27
@joeschmid Thanks for raising this -- I *believe* that this is an issue we identified and fixed earlier this week ( see: https://github.com/PrefectHQ/prefect/pull/1480). The fix was included in the Core 0.6.4 release, which in turn should be part of the next Cloud release.

In the meantime, I can't swear this will work but if you try naming your result handler class `LocalResultHandler` instead of `TestResultHandler` (or whatever you actually named it), the 0.6.3 deserializer will be able to process it in Cloud. To be clear, Cloud is not actually receiving your custom code, of course, but it is doing a validation step that unfortunately was too strictly tied to class names (if #1480 is the root cause)

**Comment by joeschmid** [comment] 2019-09-14 13:44
Thanks @jlowin, that makes sense -- looks like a simple GraphQL schema validation issue on the result handler name. Just tested renaming our custom result handler to LocalResultHandler and that does indeed work. (Presumably any other existing Prefect-defined result handler name should work, too.)

This workaround is perfectly fine for us for the time being so feel free to close this issue whenever you prefer. (Maybe leave it open for now in case others happen to run into it and then close it when 0.6.4 gets released to Cloud, but totally up to you.) Thanks for the quick help!

**Comment by cicdw** [comment] 2019-09-27 05:33
This issue should be resolved with the latest release of Prefect Cloud!

**Closed by cicdw** 2019-09-27 05:33 UTC
Labels: bug
