### ISSUE TITLE
Retry (only) on selected errors

### ISSUE THREAD

**Issue by tadejsv** [PrefectHQ/prefect#8179] opened 2023-01-16 21:38 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

For tasks, we can specify retry. But this retry will happen for all errors.

### Describe the proposed behavior

Would be great if it was possible to specify on which errors the retry should (not) occur. For example, we could specify that we want errors to occur on network connectivity errors or rate limiting errors, but to not occur on access denied errors.

Ideally, there would be some option `retriable_errors` or `non_retriable_errors` that allows specifying error classes, but also a function for custom logic.

### Additional context

Temporal.io implements this, see [non-retriable errors](https://docs.temporal.io/retry-policies#non-retryable-errors), so I believe there is a use case for this.

**Comment by madkinsz** [comment] 2023-01-16 23:48
Hi, this is a duplicate of https://github.com/PrefectHQ/prefect/issues/7576

**Comment by peytonrunyan** [comment] 2023-01-17 22:10
I'm going to close this issue for house keeping. Thanks for submitting the issue though!

**Closed by peytonrunyan** 2023-01-17 22:10 UTC
Labels: status:duplicate, enhancement
