### ISSUE TITLE
Create a process type work pool if no pool exists when a user runs `prefect worker start -p my-pool`

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#9225] opened 2023-04-14 15:35 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

This doesn’t work if `my-pool` doesn’t exist:
`prefect worker start -p my-pool`

### Describe the proposed behavior

Create a process type work pool by default in such cases. Specify that the the work pool created has a process type.

### Additional context

@desertaxle  said: "seems reasonable to me. I don’t see a downside in defaulting to a process work pool and it’ll reduce friction for users."

**Comment by serinamarie** [comment] 2023-04-14 16:37
Thanks for the issue! To summarize:

Current behavior:
```bash
❯ prefect worker start -p my-pool
Work pool 'my-pool' does not exist. To create a new work pool on worker startup, include a worker type with the --type option.

❯ prefect worker start -p my-pool -t process
Worker 'ProcessWorker 78f2c5ed-25bd-42a5-a755-3d84f5da3588' started!
```

Desired behavior is that it will default to type process if the work pool doesn't exist.
```bash
❯ prefect worker start -p my-pool
Work pool 'my-pool' does not exist. A process type worker will be created.
Worker 'ProcessWorker 78f2c5ed-25bd-42a5-a755-3d84f5da3588' started!
```

Someone would want to handle that here:

https://github.com/PrefectHQ/prefect/blob/b6d0433a15b8172c0f897a6eac2b4d747350fd1f/src/prefect/cli/worker.py#L92-L96

**Comment by desertaxle** [comment] 2023-04-14 16:49
I don't think this is a duplicate of #9224 because this issue relates to the behavior of `prefect worker start` when used with a work pool that doesn't exist while #9224 relates to the behavior of `prefect deploy` when used with a work pool that doesn't exist.

**Comment by serinamarie** [comment] 2023-04-14 17:13
Thought it was just a mistake, got it 👍

**Comment by serinamarie** [comment] 2023-04-14 17:13
Thanks for the issue! To summarize:

Current behavior:
```bash
❯ prefect worker start -p my-pool
Work pool 'my-pool' does not exist. To create a new work pool on worker startup, include a worker type with the --type option.

❯ prefect worker start -p my-pool -t process
Worker 'ProcessWorker 78f2c5ed-25bd-42a5-a755-3d84f5da3588' started!
```

Desired behavior is that it will default to type process if the work pool doesn't exist.
```bash
❯ prefect worker start -p my-pool
Work pool 'my-pool' does not exist. A process type worker will be created.
Worker 'ProcessWorker 78f2c5ed-25bd-42a5-a755-3d84f5da3588' started!
```

Someone would want to handle that here:

https://github.com/PrefectHQ/prefect/blob/b6d0433a15b8172c0f897a6eac2b4d747350fd1f/src/prefect/cli/worker.py#L92-L96

**Comment by Shubhamparashar** [comment] 2023-04-17 13:25
@discdiver Please assign this issue to me, I would like to work on this

**Comment by batuhanfaik** [comment] 2023-04-17 14:33
```bash
prefect_api_url=$PREFECT_API_URL
work_pool_name=$WORK_POOL_NAME
response=$(curl -s -o /dev/null \
  -w "%{http_code}" \
  -X POST \
  "$prefect_api_url/work_pools/" \
  -H "accept: application/json" \
  -H "Content-Type: application/json" \
  -d '{
  "name": "'$work_pool_name'",
  "description": "",
  "type": "prefect-agent",
  "base_job_template": {},
  "is_paused": false,
  "concurrency_limit": 0
}')

# Check if the work pool exists
if [ $response -eq 201 ]; then
    echo "Work pool $WORK_POOL_NAME does not exist... Created!"
elif [ $response -eq 409 ]; then
    echo "Work pool $WORK_POOL_NAME already exists!"
else
    echo "Unexpected response code: $response. Exiting..."
    exit 1
fi

echo "Running Prefect Agent with Pool: $WORK_POOL_NAME and Queue: $WORK_QUEUE_NAME"
prefect agent start --pool $WORK_POOL_NAME --work-queue $WORK_QUEUE_NAME
```

I send a request to API to check if the work-pool already exists and it works like a charm :) Pretty sure you can refactor this to work with `workers` instead of `agents`

**Comment by billpalombi** [comment] 2023-04-21 01:41
@Shubhamparashar I have assigned this issue to you. Thank you for taking this on! Please be sure that the confirmation message specifies that the created work pool has a `process` type.

**Comment by Shubhamparashar** [comment] 2023-04-25 18:49
Hi @billpalombi PR #9326, in which I have explicitly created a process type work pool. However, I believe it would have been possible to reuse the code present in the create() function of worker_pool.py. Let me know the best approach in this scenario.

**Closed** 2023-04-28 20:33 UTC
Labels: enhancement, good first issue, status:accepted, status:in-progress, team:orchestration
