### ISSUE TITLE
Type-check error when using result of mapped task

### ISSUE THREAD

**Issue by tekumara** [PrefectHQ/prefect#6923] opened 2022-09-22 12:09 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Using the result of a mapped task causes a type error in vscode/pyright.

### Reproduction

```python
from typing import List
from prefect import flow, task


@task
def count_rows(batch: str) -> int:
    return 1


@task
def summary(count: List[int]) -> None:
    total = sum(count)


@flow
def map_flow() -> None:
    counts = count_rows.map(["a"])  # type: ignore
    summary(counts)                 # <--- type error here


if __name__ == "__main__":
    map_flow()
```

### Error

vscode/pyright:
```
(variable) counts: List[PrefectFuture[int, Sync]]
Argument of type "List[PrefectFuture[int, Sync]]" cannot be assigned to parameter "count" of type "List[int]" in function "__call__"
  TypeVar "_T@list" is invariant
    "PrefectFuture[int, Sync]" is incompatible with "int"
```

### Versions

prefect 2.4.0

**Comment by madkinsz** [comment] 2022-09-22 13:47
This is basically a duplicate of https://github.com/PrefectHQ/prefect/issues/5985

**Closed** 2022-09-22 22:48 UTC
Labels: bug, status:duplicate, needs:external

**Comment by tekumara** [comment] 2022-09-22 23:13
Ah good catch, I've closed since its a duplicate.
