### ISSUE TITLE
Prefect logger deadlock

### ISSUE THREAD

**Issue by fyrestone** [PrefectHQ/prefect#15181] opened 2024-09-03 13:15 UTC
### Bug summary

When executing code in VSCode, it’s possible to hang after importing Prefect.

The simple repro code:

```python
import asyncio


async def _sim_in_vscode():
    from prefect import task
    import mlflow  # <-------- hangs here.
    print(task)
    print(mlflow)


asyncio.run(_sim_in_vscode())
```

The execution stack is:

```python
  File "/Users/user/prefect/logging_deadlock.py", line 11, in <module>
    asyncio.run(_sim_in_vscode())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/user/prefect/logging_deadlock.py", line 6, in _sim_in_vscode
    import mlflow
  File "/Users/user/prefect/venv/lib/python3.9/site-packages/mlflow/__init__.py", line 90, in <module>
    _configure_mlflow_loggers(root_module_name=__name__)
  File "/Users/user/prefect/venv/lib/python3.9/site-packages/mlflow/utils/logging_utils.py", line 62, in _configure_mlflow_loggers
    logging.config.dictConfig(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/logging/config.py", line 809, in dictConfig
    dictConfigClass(config).configure()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/logging/config.py", line 537, in configure
    _clearExistingHandlers()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/logging/config.py", line 274, in _clearExistingHandlers
    logging.shutdown(logging._handlerList[:])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 2141, in shutdown
    h.flush()
  File "/Users/user/prefect/venv/lib/python3.9/site-packages/prefect/logging/handlers.py", line 112, in flush
    from_sync.call_soon_in_loop_thread(create_call(APILogWorker.drain_all))
  File "/Users/user/prefect/venv/lib/python3.9/site-packages/prefect/_internal/concurrency/api.py", line 101, in call_soon_in_loop_thread
    runner = get_global_loop()
  File "/Users/user/prefect/venv/lib/python3.9/site-packages/prefect/_internal/concurrency/threads.py", line 258, in get_global_loop
    GLOBAL_LOOP.start()
  File "/Users/user/prefect/venv/lib/python3.9/site-packages/prefect/_internal/concurrency/threads.py", line 150, in start
    self._ready_future.result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    self._condition.wait(timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt
```

The root cause is that the `from_sync.call_soon_in_loop_thread` may create the global event loop in `APILogHandler.flush`, however, there is a debug log in loop's `__init__` that requires the logging lock which was already required by the `logging.config.dictConfig`

![image](https://github.com/user-attachments/assets/9e9996cb-98c6-4f3e-803d-41bff2589f1e)
![image](https://github.com/user-attachments/assets/e101a4c3-61fe-46d8-943a-7cc79a16695c)

### Version info (`prefect version` output)

```Text
Version:             3.0.0rc20
API version:         0.8.4
Python version:      3.9.6
Git commit:          6dd34dc6
Built:               Thu, Aug 29, 2024 12:06 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         server
Pydantic version:    2.7.4
Integrations:
  prefect-ray:       0.4.0rc2


Name: mlflow
Version: 2.16.0
```

**Comment by zzstoatzz** [comment] 2024-09-03 16:40
hi @fyrestone - I believe this is a duplicate of https://github.com/PrefectHQ/prefect/issues/15063

please feel free to re-open if you think I'm mistaken

**Closed** 2024-09-03 16:41 UTC
Labels: bug
