### ISSUE TITLE
NoneType can't be used in 'await' expression

### ISSUE THREAD

**Issue by OliverKleinBST** [PrefectHQ/prefect#14858] opened 2024-08-06 08:19 UTC
### Bug summary

when running run_deployment to use a worker deployed on Kubernetes we get an error after migration to 2.20.0:

```
Worker 'KubernetesWorker 7915621e-44b2-47d2-a150-2270f7c184f5' submitting flow run '05e5b154-f691-4566-a813-0818b3b913b8'
09:26:53 AM
prefect.flow_runs.worker
Failed to submit flow run '05e5b154-f691-4566-a813-0818b3b913b8' to infrastructure.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/workers/base.py", line 908, in _submit_run_and_capture_errors
    result = await self.run(
  File "/usr/local/lib/python3.9/site-packages/prefect_kubernetes/worker.py", line 612, in run
    async with self._get_configured_kubernetes_client(configuration) as client:
  File "/usr/local/lib/python3.9/contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "/usr/local/lib/python3.9/site-packages/prefect_kubernetes/worker.py", line 743, in _get_configured_kubernetes_client
    await config.load_incluster_config()
TypeError: object NoneType can't be used in 'await' expression
09:26:54 AM
prefect.flow_runs.worker
Completed submission of flow run '05e5b154-f691-4566-a813-0818b3b913b8'
```

### Version info (`prefect version` output)

```Text
(bst_wfm.venv) C:\Users\llk7rt>prefect version
Version:             2.20.0
API version:         0.8.4
Python version:      3.9.18
Git commit:          15274df8
Built:               Thu, Aug 1, 2024 3:14 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.41.2
```

**Comment by k-wolski** [comment] 2024-08-06 12:56
I had the same issue, needed to rollback to 2.19.8 and then it started to working again.

**Comment by netanelm-upstream** [comment] 2024-08-06 13:09
+1 had the same issue

**Comment by nil-sahin** [comment] 2024-08-06 14:20
+1 here, less than 10% of our flows are able to run due to this.

**Comment by desertaxle** [comment] 2024-08-06 14:37
Thanks for the issue @OliverKleinBST! It looks like this issue was fixed in https://github.com/PrefectHQ/prefect/pull/14801 and was included in the `0.4.1` release of `prefect-kubernetes`. Could you share your `prefect-kubernetes` version and try upgrading your `prefect-kubernetes` version and see if that fixes this issue?

**Comment by matt-mckeithen** [comment] 2024-08-06 14:50
@desertaxle can you point me to the version of prefect-kubernetes that was used in the [2.20-python3.11-kubernetes](https://hub.docker.com/layers/prefecthq/prefect/2.20-python3.11-kubernetes/images/sha256-e709407ed4c7c0129106b5dcec3b6f44b91f458dc556fadbb08a196915d4f43e?context=explore) image?

We are mostly using this image tag [2-python3.11-kubernetes](https://hub.docker.com/layers/prefecthq/prefect/2-python3.11-kubernetes/images/sha256-e709407ed4c7c0129106b5dcec3b6f44b91f458dc556fadbb08a196915d4f43e?context=explore).  Those images were released 3 days ago.  Rolling back to 2.19.8 also fixed our issues.

**Comment by anthuswilliams** [comment] 2024-08-06 15:01
I've pulled the image and confirmed it is not running this release of `prefect-kubernetes`

**Comment by OliverKleinBST** [comment] 2024-08-06 18:39
I just gave it a retry making sure image is re-pulled...and I can confirm it is now working again!

**Comment by desertaxle** [comment] 2024-08-09 16:08
Thanks for confirming @OliverKleinBST! 

I will close this issue now as resolved, but feel free to leave a comment if you're still encountering this after re-pulling the `prefecthq/prefect` Docker image.

**Closed by desertaxle** 2024-08-09 16:08 UTC
Labels: bug, integrations
