### ISSUE TITLE
CronSchedule validation fails when provided with a timezone

### ISSUE THREAD

**Issue by mferryRV** [PrefectHQ/prefect#9535] opened 2023-05-11 17:32 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Version ==2.10.8

Supplying a timezone to CronSchedule causes a validation failure.

### Reproduction

```python3
>>> from prefect.server.schemas.schedules import CronSchedule
>>> schedule = CronSchedule(cron="0 7 * * *", timezone="America/New_York", day_or=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for CronSchedule
timezone
  argument of type 'function' is not iterable (type=type_error)
```

### Error

```python3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for CronSchedule
timezone
  argument of type 'function' is not iterable (type=type_error)
```

### Versions

```Text
2.10.8
```

### Additional context

This appears to originate in the validation function:
```
    @validator("timezone")
    def valid_timezone(cls, v):
        if v and v not in pendulum.tz.timezones:
            raise ValueError(f'Invalid timezone: "{v}"')
        return v
```

This appears to be an error in how pendulum.tz.timezones is referenced without making a function call:
```
>>> import pendulum
>>> pendulum.tz.timezones
<function timezones at 0x10d923370>
>>> pendulum.tz.timezones()
('Africa/Algiers', 'Atlantic/Cape_Verde',
```

**Comment by madkinsz** [comment] 2023-05-11 19:06
@mferryRV want to submit a fix? Looks pretty quick!

**Comment by ajwadjaved** [comment] 2023-05-11 22:15
Hi, this was my first open source contribution. Please let me know if I did anything wrong or if my code didn't fix the error. I wasn't getting the error anymore when I ran the code locally.

**Comment by rkscodes** [comment] 2023-05-25 10:33
Should I work on it, seems stale at this point

**Comment by jawnsy** [comment] 2023-06-21 18:42
I'm not sure if this was a change in pendulum's API, but creating a CronSchedule works for me.

Given that we have not seen many reports about this, I'm closing the issue out. Please feel free to add a comment if you're able to reproduce the original issue.

```
Python 3.10.6 (main, Oct 24 2022, 11:04:07) [Clang 12.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pendulum

>>> pendulum.__version__
'2.1.2'

>>> pendulum.tz.timezones[0:5]
('Africa/Abidjan', 'Africa/Accra', 'Africa/Addis_Ababa', 'Africa/Algiers', 'Africa/Asmara')

>>> from prefect.server.schemas.schedules import CronSchedule

>>> CronSchedule(cron="0 7 * * *", timezone="America/New_York")
CronSchedule(cron='0 7 * * *', timezone='America/New_York', day_or=True)
```

**Closed by jawnsy** 2023-06-21 18:42 UTC
Labels: bug, good first issue, status:accepted, priority:medium
