### ISSUE TITLE
Pydantic SecureString is not supported fully 

### ISSUE THREAD

**Issue by MrChadMWood** [PrefectHQ/prefect#11972] opened 2024-02-13 00:19 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Seems first reported here: https://discourse.prefect.io/t/obscure-secret-in-prefect-ui-with-pydantic/1803

> So, I tried the following:
```
from pydantic import SecretStr
from prefect import flow

@flow(name='example')
def main(username:str, password:SecretStr):
    # do stuff with the "password" variable
    pass
```
> After the deployment, when I access the “Custom Run” option, the password is indeed obscured in the UI (*********** instead of mysecretpass). However, the password is visible when I access the Parameters tab in the Flow Run.

### Reproduction

```python3
from pydantic import SecretStr
from prefect import flow

@flow(name='example')
def main(username:str, password:SecretStr):
    # do stuff with the "password" variable
    pass
```

### Error

```python3
By default, sensitive information is shared with everybody having access to the same network that Prefect is hosted on.
```

### Versions

```Text
Version:             2.14.15
API version:         0.8.4
Python version:      3.11.5
Git commit:          e585e980
Built:               Thu, Jan 11, 2024 6:18 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         server
```

### Additional context

A potential duplicate: https://discourse.prefect.io/t/what-to-do-when-flow-parameters-are-sensitive/3964

**Comment by zhen0** [comment] 2024-02-13 13:34
I think this is a duplicate of https://github.com/PrefectHQ/prefect/issues/11679. As I set out there, our strong recommendation is that any secret values should use a [secret block](https://docs.prefect.io/latest/concepts/blocks/?h=blocks). Although obfuscation may be a convenience, we do not want to give a false sense of security for something that does not offer the same level of security as a secret block does.

**Closed** 2024-02-13 13:34 UTC
Labels: bug, needs:triage

**Comment by MrChadMWood** [comment] 2024-02-13 15:13
@zhen0 Although I appreciate and understand the concern for not misleading users; i.e., security via obfuscation is not security... At the same time, I think there is value in not requiring custom blocks be built and used solely to prevent a value from being captured by Prefect. Can an abstraction be considered where a type annotation of `SecretString` is handled similarly to a Secret Block, or can we simply turn off capture of the parameter values altogether?

**Comment by MrChadMWood** [comment] 2024-02-14 16:15
Moving to use a secret block for now. I can confirm this is working fine.

I would like to leave with a note regarding why I personally think this feature should be considered further. First, creating a secret block requires that the secret value be known ahead of time. If I am wishing to securely handle anything more dynamic in nature, it won't work. Moreover, it adds complexity to any existing CI/CD solution that manages secrets and provides it to the Python code at runtime.
