### ISSUE TITLE
`prefect cloud login` with browser fails on Python 3.12 and uvicorn 0.29

### ISSUE THREAD

**Issue by atkinson** [PrefectHQ/prefect#12371] opened 2024-03-21 04:19 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used GitHub search to find a similar request and didn't find it 😇

### Describe the issue

Following the very fist steps in the tutorial:
> pip install -U prefect
> prefect cloud login
[open browser, click "authorize"] 
Browser window says, "Authorizing...", and then, "Success: You can close this window".

After clicking Authorize, there is an error in the console: https://gist.github.com/atkinson/bf5113032a28311598ebd566c221d87c

### Describe the proposed change

Some troubleshooting tips.

### Additional context

I'm on OSX with python 3.12

PS: I don't need support, I used the API key to login.

**Comment by scharlottej13** [comment] 2024-03-21 18:33
I also ran into the same problem (and ended up using an API key to login). I'm using Prefect 2.16.3.

**Comment by scharlottej13** [comment] 2024-03-21 19:59
Thanks @aaazzam!

**Comment by bunchesofdonald** [comment] 2024-03-25 19:43
The traceback from the original issue (https://gist.github.com/atkinson/bf5113032a28311598ebd566c221d87c) shows that there was a successful authentication attempt, and then it attempted to read the workspaces. To do that it tried to open a TCP connection, but _something_ happened and during this attempt a CancelledError was raised. 

Most _likely_ what occurred here is that there was a TCP connect timeout due to network connectivity issues, given that I'm not sure there's much we can do on our end. We could add handling for `CancelledError` to the command, but we would swallow helpful tracebacks in doing so.

@atkinson I'm going to go ahead and close this out, but feel free to re-open if you feel like I missed something or if you have more information that might lead to us being able to reproduce this issue.

**Comment by bunchesofdonald** [comment] 2024-03-28 15:13
We've been able to reproduce this error now using Python 3.12 and Uvicorn 0.29. Reopening so we can track that.

**Comment by bunchesofdonald** [comment] 2024-04-23 16:03
Since we pinned uvicorn to < 0.29 we haven't seen any more reports of this issue. Closing out for no.

**Closed by bunchesofdonald** 2024-04-23 16:03 UTC
Labels: component:cli
