### ISSUE TITLE
Block Description Page Displays Secrets in Settings Section

### ISSUE THREAD

**Issue by wildex** [PrefectHQ/prefect#7562] opened 2022-11-17 10:35 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When you view Block Page, you can see secret Values displayed there.

For example when you add RemoteFilesystemBlock, you can see AWS SECRET KEY there in the Settings Section

**Settings**

```
{
  "use_ssl": false,
  "key": "KEY_HERE",
  "secret": "SECRET_HERE",
  "client_kwargs": {
    "endpoint_url": "some_endpoint"
  }
}
```

### Reproduction

Create S3, or RemoteFileSystem block with Setting AWS Secrets there

### Error

Secrets should not be displayed on the Block page

### Browers

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

**Comment by zhen0** [comment] 2022-11-18 14:15
The UI hides inputs that are marked as secret but the remote file system settings are currently set as an object. @ahuang11 @desertaxle -I suspect this is by design but checking in - should the remote file system block be a secret rather than an object?

**Comment by desertaxle** [comment] 2022-11-18 14:36
Yes this is currently working as designed. Only block fields that are typed as `SecretStr` in their python declaration are obfuscated in the UI and in logs. Sometimes secrets need to be added to object fields, particularly for general purpose blocks like `RemoteFileSystem`. We are evaluating a new field type that would allow us to obfuscate object fields. That is being tracked in https://github.com/PrefectHQ/prefect/issues/6735.

As a workaround, if the `S3` block in the core library doesn't cover your use case, you can checkout the [`S3Bucket` block](https://prefecthq.github.io/prefect-aws/s3/#prefect_aws.s3.S3Bucket) in `prefect-aws` as an alternative. If it doesn't cover your use case, we can investigate updating it to cover your use case.

**Comment by wildex** [comment] 2022-11-18 15:26
Thank you for fast reply! I ended up extending `S3WithEndpoint(S3)`, because I had to use endpoint_url.
But it seems that `S3Bucket` block would be sufficient, as per your advice.

**Comment by zhen0** [comment] 2022-11-21 17:43
Thanks @wildex - I'm closing this as "as-designed" but do keep the feedback coming!

**Closed by zhen0** 2022-11-21 17:43 UTC
Labels: status:as-designed, ui, component:blocks

**Comment by wildex** [comment] 2022-11-27 20:29
Hi Prefect guys.

Just to let you know, I still had an issue in my case.
 I've created a new block type `S3WithEndpoint ` and stored my flow code in deployment using this block.
Later I am running this deployment in a Docker container and it seems that the Prefect engine does not know how to load information using `S3WithEndpoint` from my new block. 
Since dispatch method of load_block would not work. 

```
Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 247, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/usr/local/lib/python3.9/site-packages/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/prefect/deployments.py", line 153, in load_flow_from_flow_run
    storage_block = Block._from_block_document(storage_document)
  File "/usr/local/lib/python3.9/site-packages/prefect/blocks/core.py", line 540, in _from_block_document
    else cls.get_block_class_from_schema(block_document.block_schema)
  File "/usr/local/lib/python3.9/site-packages/prefect/blocks/core.py", line 571, in get_block_class_from_schema
    return lookup_type(cls, block_schema_to_key(schema))
  File "/usr/local/lib/python3.9/site-packages/prefect/utilities/dispatch.py", line 186, in lookup_type
    raise KeyError(
KeyError: "No class found for dispatch key 's3withendpoint' in registry for type 'Block'."
```

**Comment by zhen0** [comment] 2022-11-30 14:07
Hi @wildex - for your comment above I suggest opening a separate issue.  Thanks!
