### ISSUE TITLE
Wrong exception class being raised on querying for non-existent 

### ISSUE THREAD

**Issue by OptimeeringBigya** [PrefectHQ/prefect#9037] opened 2023-04-03 12:32 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I have encountered a bug while attempting to query for the task concurrency tag by its name. Specifically, when the tag does not exist, an incorrect exception is being raised. The exception that is currently being raised is `prefect.exceptions.PrefectHTTPStatusError` . However, the exception that should be raised in this case is `prefect.exceptions.ObjectNotFound` .

### Reproduction

```python3
from prefect.client.orchestration import get_client

async def get_tag(tag_name: str):
    async with get_client() as client:
        try:
            response = await client.read_concurrency_limit_by_tag(tag_name)
        except Exception as err:
            print(type(err))



if __name__ == "__main__":
    import asyncio
    asyncio.run(get_tag("TAG_DOESNT_EXIST"))
```

### Error

```python3
<class 'prefect.exceptions.PrefectHTTPStatusError'>

Process finished with exit code 0
```

### Versions

```Text
Version:             2.9.0
API version:         0.8.4
Python version:      3.10.8
Git commit:          69f57bd5
Built:               Thu, Mar 30, 2023 1:08 PM
OS/Arch:             linux/x86_64
Profile:             prefcloud
Server type:         cloud
```

**Comment by AmanSal1** [comment] 2023-04-05 13:24
@OptimeeringBigya is this issue fixed?

**Comment by Sam-ScottLogic** [comment] 2023-04-06 08:18
May I work on this please?

**Comment by Sam-ScottLogic** [comment] 2023-04-06 08:21
@OptimeeringBigya

**Comment by madkinsz** [comment] 2023-04-06 22:33
Hi! @AmanSal1 and @Sam-ScottLogic — please try running the minimal example on the latest release if you want to double check if something is done. Otherwise, we generally close the issue when things are fixed. You're always welcome to work on an issue that is marked as accepted :)

**Comment by AmanSal1** [comment] 2023-04-07 05:11
Hi @madkinsz ,
I ran the minimal example and I was getting the expected behavior that's why I asked is the issue fixed
Here is the screenshot::
![254](https://user-images.githubusercontent.com/121633121/230545120-4d1e50f1-6df9-46dc-9d38-4f9030e0b897.PNG)

**Comment by madkinsz** [comment] 2023-04-07 05:42
@AmanSal1 thanks for clarifying! I can indeed produce the same behavior against both a local API and Cloud and it looks like it's been correct since 2.0.0. Sorry for the confusion.

@OptimeeringBigya it sounds like you've reported this mistakenly. Please share the full traceback for the error you got and we can determine the cause of the status error.

**Closed by madkinsz** 2023-04-07 05:42 UTC
Labels: bug, good first issue, status:accepted, priority:low

**Comment by madkinsz** [comment] 2023-04-07 06:18
This looks like it may have been a now resolved Cloud-only issue where a 500 was returned instead of a 404 (internal tracking at https://github.com/PrefectHQ/nebula/issues/4335)

**Comment by madkinsz** [comment] 2023-04-11 14:26
@OptimeeringBigya I cannot reproduce the behavior above — would you share an example with output?
