### ISSUE TITLE
Add functionality to be able to modify prefect variables during flow run

### ISSUE THREAD

**Issue by ma-dentalcorp** [PrefectHQ/prefect#10372] opened 2023-08-04 19:38 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently, with prefect variables, we can use the `variables.get()` to retrieve the value during a flow run but there isn't a way to update it during a flow run e.g. using `variables.set()`.

### Describe the proposed behavior

I would like to be able to update this prefect variable during a flow run using e.g. `variables.set()`

### Example Use

For example, I want to just store one date variable to keep track of when the last run was made for this flow programmatically. And during each flow run, I will retrieve this date and do some logic with it, and afterwards update this date variable after completion of the flow run. I could of course store this variable elsewhere but since it's just one variable related to a flow, it'd be nice to just store it in prefect.

**Comment by serinamarie** [comment] 2023-08-04 21:55
Hi @ma-dentalcorp, thanks for the issue! This is by design, although I can definitely see the use case for it. 
@billpalombi, did you have any thoughts on that?

**Comment by billpalombi** [comment] 2023-08-10 14:07
We should explore this, though we'll have to consider the implications for caching.

@ma-dentalcorp, in the meantime, you can set a variable from code with the [variables PATCH route](https://app.prefect.cloud/api/docs?deviceId=9f049948-40e2-4442-b804-39c52ac51c13&deviceId=9f049948-40e2-4442-b804-39c52ac51c13#tag/Variables/operation/update_variable_by_name_api_accounts__account_id__workspaces__workspace_id__variables_name__name__patch)

**Comment by feliperazeek** [comment] 2023-09-21 13:12
This would be really great, I wanted to use it as a persistent watermark, tracking the date for the last successful run for a task. So in case of failures, I can just re-run and picks up where it left off, much like a Kafka offset.

**Comment by cicdw** [comment] 2024-08-14 20:29
`Variable.set` is implemented; looks like we forgot to close this issue when it was released!

**Closed by cicdw** 2024-08-14 20:29 UTC
Labels: enhancement
