### ISSUE TITLE
Unexpected error when flattened task fails

### ISSUE THREAD

**Issue by andywaugh** [PrefectHQ/prefect#5299] opened 2022-01-04 13:00 UTC
## Description
Something is going wrong when a flattened task fails - this can be caused by a signal FAIL or simply an unhandled exception. Specifically, the `len` call on this line https://github.com/PrefectHQ/prefect/blob/17b885bbae4aa01a9859ff28f9d9cd3623dedc1a/src/prefect/utilities/executors.py#L728 appears to be the issue.

This behaviour only seems to happen when `flatten` is used. If a mapped task fails without the use of flatten the flow works as expected.

Apologies if this is raised in error; this seems like it would be core to a lot of flows so I'm surprised it hasn't already been raised if it's a legitimate bug.

## Expected Behavior
I expect the flow to complete with a status of FAILED.

## Reproduction
PoC code:
```
from prefect import Task, Flow, mapped, flatten
from prefect.engine.signals import FAIL


class SuccessTask(Task):
    def run(self, some_input):
        print(some_input)
        return [False, True, False]


class RaiseErrorTask(Task):
    def run(self, do_raise):
        if do_raise:
            raise TypeError("Example error")

        return True


class RaiseFailTask(Task):
    def run(self, do_raise):
        if do_raise:
            raise FAIL("fail...")

        return True


class TestFlow(Flow):
    def __init__(self, **kwargs) -> None:
        super().__init__(name="test_flow", **kwargs)
        with self:
            res = SuccessTask()(some_input=1)
            # Same behaviour seen when unhandled exception is thrown - swap RaiseFailTask for RaiseErrorTask below
            res2 = RaiseFailTask()(do_raise=mapped(res))
            SuccessTask()(some_input=flatten(res2))


TestFlow().run()
```

Output:
```
[2022-01-04 12:43:41+0000] INFO - prefect.FlowRunner | Beginning Flow run for 'test_flow'
[2022-01-04 12:43:41+0000] INFO - prefect.TaskRunner | Task 'SuccessTask': Starting task run...
1
[2022-01-04 12:43:41+0000] INFO - prefect.TaskRunner | Task 'SuccessTask': Finished task run for task with final state: 'Success'
[2022-01-04 12:43:41+0000] INFO - prefect.TaskRunner | Task 'RaiseFailTask': Starting task run...
[2022-01-04 12:43:41+0000] INFO - prefect.TaskRunner | Task 'RaiseFailTask': Finished task run for task with final state: 'Mapped'
[2022-01-04 12:43:41+0000] INFO - prefect.TaskRunner | Task 'RaiseFailTask[0]': Starting task run...
[2022-01-04 12:43:41+0000] INFO - prefect.TaskRunner | Task 'RaiseFailTask[0]': Finished task run for task with final state: 'Success'
[2022-01-04 12:43:41+0000] INFO - prefect.TaskRunner | Task 'RaiseFailTask[1]': Starting task run...
[2022-01-04 12:43:41+0000] INFO - prefect.TaskRunner | FAIL signal raised: FAIL('fail...')
[2022-01-04 12:43:41+0000] INFO - prefect.TaskRunner | Task 'RaiseFailTask[1]': Finished task run for task with final state: 'Failed'
[2022-01-04 12:43:41+0000] INFO - prefect.TaskRunner | Task 'RaiseFailTask[2]': Starting task run...
[2022-01-04 12:43:41+0000] INFO - prefect.TaskRunner | Task 'RaiseFailTask[2]': Finished task run for task with final state: 'Success'
[2022-01-04 12:43:41+0000] ERROR - prefect.FlowRunner | Unexpected error: TypeError("object of type 'bool' has no len()")
Traceback (most recent call last):
  File "/Users/andy/Code/misc/prefect-bug-explore-8114/.venv/lib/python3.8/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/Users/andy/Code/misc/prefect-bug-explore-8114/.venv/lib/python3.8/site-packages/prefect/engine/flow_runner.py", line 519, in get_flow_run_state
    children = executors.flatten_mapped_children(
  File "/Users/andy/Code/misc/prefect-bug-explore-8114/.venv/lib/python3.8/site-packages/prefect/utilities/executors.py", line 728, in flatten_mapped_children
    [executor.submit(lambda c: len(c._result.value), c) for c in mapped_children]
  File "/Users/andy/Code/misc/prefect-bug-explore-8114/.venv/lib/python3.8/site-packages/prefect/utilities/executors.py", line 728, in <listcomp>
    [executor.submit(lambda c: len(c._result.value), c) for c in mapped_children]
  File "/Users/andy/Code/misc/prefect-bug-explore-8114/.venv/lib/python3.8/site-packages/prefect/executors/local.py", line 28, in submit
    return fn(*args, **kwargs)
  File "/Users/andy/Code/misc/prefect-bug-explore-8114/.venv/lib/python3.8/site-packages/prefect/utilities/executors.py", line 728, in <lambda>
    [executor.submit(lambda c: len(c._result.value), c) for c in mapped_children]
TypeError: object of type 'bool' has no len()
[2022-01-04 12:43:41+0000] ERROR - prefect.test_flow | Unexpected error occured in FlowRunner: TypeError("object of type 'bool' has no len()")
```

## Environment
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "macOS-10.16-x86_64-i386-64bit",
    "prefect_backend": "cloud",
    "prefect_version": "0.15.11",
    "python_version": "3.8.9"
  }
}

**Comment by anna-geller** [comment] 2022-01-10 12:21
The issue you are facing is that a Failed task propagates downstream. To use flatten, you would need to use the FilterTask beforehand. Note that FilterTask can filter exceptions, but not signals so it still won't work if you explicitly raise FAIL. But normal use case where a task fails with an exception works fine. 

Here is an example showing how the FilterTask filters out the failed mapped child task allowing the flatten task to work as intended. 

```python
from prefect import Task, Flow, mapped, flatten, task
from prefect.engine.signals import FAIL
from typing import Any, List
from prefect.triggers import all_finished
from prefect.tasks.control_flow import FilterTask

default_filter = FilterTask()


@task(trigger=all_finished)
def get_list_of_bool(some_input: Any) -> List[bool]:
    print("printing input:")
    print(some_input)
    return [False, True, False]


@task
def fail(do_raise: bool) -> bool:
    if do_raise:
        raise FAIL("fail...")
    return True


@task
def throw_exception(do_raise: bool) -> bool:
    if do_raise:
        raise ValueError("failing...")
    return True


with Flow("ex") as flow:
    res = get_list_of_bool(some_input=1)
    res2 = throw_exception.map(res)
    filtered_result = default_filter(res2)
    get_list_of_bool(res2)
    get_list_of_bool(filtered_result)
    res3 = get_list_of_bool(some_input=flatten(filtered_result))


if __name__ == "__main__":
    flow.run()
```
![image](https://user-images.githubusercontent.com/86264395/148765121-f9a2ed87-effa-474e-9325-4a06241be443.png)

The output:
```shell
[2022-01-10 13:16:26+0100] INFO - prefect.FlowRunner | Beginning Flow run for 'ex'
[2022-01-10 13:16:26+0100] INFO - prefect.TaskRunner | Task 'get_list_of_bool': Starting task run...
printing input:
1
[2022-01-10 13:16:26+0100] INFO - prefect.TaskRunner | Task 'get_list_of_bool': Finished task run for task with final state: 'Success'
[2022-01-10 13:16:26+0100] INFO - prefect.TaskRunner | Task 'throw_exception': Starting task run...
[2022-01-10 13:16:26+0100] INFO - prefect.TaskRunner | Task 'throw_exception': Finished task run for task with final state: 'Mapped'
[2022-01-10 13:16:26+0100] INFO - prefect.TaskRunner | Task 'throw_exception[0]': Starting task run...
[2022-01-10 13:16:26+0100] INFO - prefect.TaskRunner | Task 'throw_exception[0]': Finished task run for task with final state: 'Success'
[2022-01-10 13:16:26+0100] INFO - prefect.TaskRunner | Task 'throw_exception[1]': Starting task run...
[2022-01-10 13:16:26+0100] ERROR - prefect.TaskRunner | Task 'throw_exception[1]': Exception encountered during task execution!
Traceback (most recent call last):
  File "/Users/anna/.conda/envs/prefectCloudFlows/lib/python3.8/site-packages/prefect/engine/task_runner.py", line 876, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/Users/anna/.conda/envs/prefectCloudFlows/lib/python3.8/site-packages/prefect/utilities/executors.py", line 454, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "<input>", line 27, in throw_exception
ValueError: failing...
[2022-01-10 13:16:26+0100] INFO - prefect.TaskRunner | Task 'throw_exception[1]': Finished task run for task with final state: 'Failed'
[2022-01-10 13:16:26+0100] INFO - prefect.TaskRunner | Task 'throw_exception[2]': Starting task run...
[2022-01-10 13:16:26+0100] INFO - prefect.TaskRunner | Task 'throw_exception[2]': Finished task run for task with final state: 'Success'
[2022-01-10 13:16:26+0100] INFO - prefect.TaskRunner | Task 'FilterTask': Starting task run...
[2022-01-10 13:16:26+0100] INFO - prefect.TaskRunner | Task 'FilterTask': Finished task run for task with final state: 'Success'
[2022-01-10 13:16:26+0100] INFO - prefect.TaskRunner | Task 'get_list_of_bool': Starting task run...
printing input:
[True, ValueError('failing...'), True]
[2022-01-10 13:16:26+0100] INFO - prefect.TaskRunner | Task 'get_list_of_bool': Finished task run for task with final state: 'Success'
[2022-01-10 13:16:26+0100] INFO - prefect.TaskRunner | Task 'get_list_of_bool': Starting task run...
printing input:
[True, True]
[2022-01-10 13:16:26+0100] INFO - prefect.TaskRunner | Task 'get_list_of_bool': Finished task run for task with final state: 'Success'
[2022-01-10 13:16:26+0100] INFO - prefect.TaskRunner | Task 'get_list_of_bool': Starting task run...
printing input:
[True, True]
[2022-01-10 13:16:26+0100] INFO - prefect.TaskRunner | Task 'get_list_of_bool': Finished task run for task with final state: 'Success'
[2022-01-10 13:16:26+0100] INFO - prefect.FlowRunner | Flow run SUCCESS: all reference tasks succeeded

```

**Comment by andywaugh** [comment] 2022-01-10 13:51
Thanks for the response and solution, Anna. This still feels like a bug to me then, do you agree?

I would expect in the example you give above for the flow to complete but with a status of FAILED (as opposed to mine which crashed mid-flow) because something did go wrong since one of the tasks failed. However I think your flow is reporting a SUCCESS because the failed task is being filtered out?

It also doesn't feel quite right that a signal can't be raised in a flattened task.

**Comment by kvnkho** [comment] 2022-01-10 15:03
Relevant issue: https://github.com/PrefectHQ/prefect/issues/3631

**Comment by anna-geller** [comment] 2022-01-10 17:23
I understand the problem, but I can't say whether this should be considered a bug or whether it should be considered an expected behavior. Since you raise a FAIL signal, you intend the flow run (or at least the task run) to fail. Given there is an open issue Kevin mentioned, is it OK to close this one @andywaugh?

**Closed** 2022-01-11 06:27 UTC
