### ISSUE TITLE
Unable to filter for blocks if more than 200 blocks are configured for a workspace

### ISSUE THREAD

**Issue by kaliserichmond** [PrefectHQ/prefect#8634] opened 2023-02-23 17:51 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

A workspace with over 200 blocks will return the first 200 in block type alphabetical order and the search bar will only search within that 200 list. 

### Reproduction

Reproduce: 
1. create 200 json blocks and 1 block that is a local file system 

Expected:
the local file system block should be searchable by name and type

Actual:
the search is only returning on blocks in the initial loaded 200 list, no network calls are occurring.

Example account and workspace: 
https://app.prefect.cloud/account/541ad1cc-f622-4472-8cc7-b9caeefacc99/workspace/0c36a012-a834-4598-b05b-b8911581b7e1/blocks

### Error

Here's a video recording: https://www.loom.com/share/1bc7761a125d408aac464a3c6a4bde91

### Browers

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge

### Prefect version

```Text
2.8.2
```

**Comment by zhen0** [comment] 2023-02-28 21:45
Closing as a duplicate of https://github.com/PrefectHQ/prefect/issues/6915

**Closed by zhen0** 2023-02-28 21:45 UTC
Labels: bug, status:duplicate, ui
