### ISSUE TITLE
ORION: cannot insert into a non-existing table

### ISSUE THREAD

**Issue by eli-osherovich** [PrefectHQ/prefect#5211] opened 2021-12-08 12:19 UTC
Hello.
For some reason `orion` fails while trying to `insert` into a non-existing table. 
Below please find the error that happens when running an example from the tutorial. A similar error happens when I try to run `perfect start orion`, but the table name is different of course.

```
Traceback (most recent call last):
  File "/home/eli/src/prefect/tt.py", line 17, in <module>
    flow_state = main_flow()
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/prefect/flows.py", line 227, in __call__
    return enter_flow_run_engine_from_flow_call(self, parameters)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/prefect/engine.py", line 113, in enter_flow_run_engine_from_flow_call
    return anyio.run(begin_run)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/anyio/_core/_eventloop.py", line 56, in run
    return asynclib.run(func, *args, **backend_options)  # type: ignore
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 233, in run
    return native_run(wrapper(), debug=debug)
  File "/home/eli/virtenvs/mkl/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/eli/virtenvs/mkl/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 228, in wrapper
    return await func(*args)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/prefect/client.py", line 59, in wrapper
    return await fn(*args, **kwargs)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/prefect/engine.py", line 147, in create_then_begin_flow_run
    flow_run = await client.create_flow_run(
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/prefect/client.py", line 352, in create_flow_run
    flow_id = await self.create_flow(flow)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/prefect/client.py", line 190, in create_flow
    response = await self.post("/flows/", json=flow_data.dict(json_compatible=True))
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/prefect/client.py", line 118, in post
    response = await self._client.post(route, **kwargs)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/httpx/_client.py", line 1827, in post
    return await self.request(
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/httpx/_client.py", line 1513, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/httpx/_client.py", line 1600, in send
    response = await self._send_handling_auth(
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/httpx/_client.py", line 1628, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/httpx/_client.py", line 1665, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/httpx/_client.py", line 1702, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/httpx/_transports/asgi.py", line 152, in handle_async_request
    await self.app(scope, receive, send)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/prefect/orion/api/flows.py", line 34, in create_flow
    model = await models.flows.create_flow(session=session, flow=flow)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/prefect/orion/models/flows.py", line 40, in create_flow
    await session.execute(insert_stmt)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/session.py", line 212, in execute
    return await greenlet_spawn(
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 134, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute
    cursor.execute(statement, parameters)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 100, in execute
    self._adapt_connection._handle_exception(error)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 229, in _handle_exception
    raise error
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 82, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
    return current.driver.switch(awaitable)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
    value = await result
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/aiosqlite/cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/eli/virtenvs/mkl/lib/python3.9/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: flow
[SQL: INSERT INTO flow (id, created, updated, name, tags) VALUES (?, ?, ?, ?, ?) ON CONFLICT (name) DO NOTHING]
[parameters: ('3927fd0b-6486-445a-b076-d2df40bf674f', '2021-12-08 12:15:53.070135', '2021-12-08 12:15:53.070159', 'main-flow', '[]')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

```

**Comment by madkinsz** [comment] 2021-12-08 16:30
Hi @eli-osherovich -- running `prefect orion reset-db` should resolve this. 

Was this a fresh installation? What version do you have?

**Comment by TimoVink** [comment] 2021-12-08 20:32
I'm not the reporter of this issue, but I was having the same issue. My particular set of steps:

1. Ran `pip install -U "prefect>=2.0.0a"` as per the [the instructions](https://orion-docs.prefect.io/getting-started/installation/)
2. Confirmed with `prefect version` that I had `2.0a5`
3. Saw the note about `sqlite` at the bottom of that page, so ran an `apt install sqlite` (which _did_ install new packages).
4. Tried running the first example on the [First steps](https://github.com/PrefectHQ/prefect/issues/5211) page, but got the error described in this issue.

I can confirm that running `prefect orion reset-db` fixed it for me. Thanks!

**Comment by madkinsz** [comment] 2021-12-08 23:05
Thanks for the additional report! We've attempted to fix database creation a couple of times now but there appear to be some edge-case environments in which the tables are not created at startup. I think it will always work if you run `prefect orion start` first but there may be issues with ephemeral runs before the database has been created.

**Comment by madkinsz** [comment] 2021-12-08 23:32
Another fix for this should be in the new alpha :)

Internal tracking at https://github.com/PrefectHQ/orion/pull/684

**Comment by eli-osherovich** [comment] 2021-12-09 07:39
> Thanks for the additional report! We've attempted to fix database creation a couple of times now but there appear to be some edge-case environments in which the tables are not created at startup. I think it will always work if you run `prefect orion start` first but there may be issues with ephemeral runs before the database has been created.

Actually no. Running `prefect orion start` fails with a similar error: cannot insert into a non-existent db.

**Closed** 2021-12-12 07:50 UTC

**Comment by RaimundoNeto7** [comment] 2022-02-21 16:07
Can someone help me?

I'm using `prefect = "2.0a12"` and when I run `prefect orion start` or run `prefect orion database reset`, I get the error `sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table flow already exists`, because the prefect tries create_table `flow`, trace below:

```
Traceback (most recent call last):
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute
    cursor.execute(statement, parameters)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 100, in execute
    self._adapt_connection._handle_exception(error)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 229, in _handle_exception
    raise error
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 82, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
    return current.driver.switch(awaitable)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
    value = await result
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/aiosqlite/cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: table flow already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/bin/prefect", line 8, in <module>
    sys.exit(app())
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/prefect/cli/base.py", line 111, in with_profile_from_option
    return fn(*args, **kwargs)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/prefect/utilities/asyncio.py", line 119, in wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/prefect/utilities/asyncio.py", line 66, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/anyio/_core/_eventloop.py", line 56, in run
    return asynclib.run(func, *args, **backend_options)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 233, in run
    return native_run(wrapper(), debug=debug)
  File "/home/raimundo/.pyenv/versions/3.9.0/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/raimundo/.pyenv/versions/3.9.0/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 228, in wrapper
    return await func(*args)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/prefect/cli/orion.py", line 142, in start
    await db.create_db()
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/prefect/orion/database/interface.py", line 51, in create_db
    await self.run_migrations_upgrade()
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/prefect/orion/database/interface.py", line 59, in run_migrations_upgrade
    await run_sync_in_worker_thread(alembic_upgrade)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/prefect/utilities/asyncio.py", line 51, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(context.run, call, cancellable=True)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/prefect/orion/database/alembic_commands.py", line 29, in alembic_upgrade
    alembic.command.upgrade(alembic_config(), revision, sql=dry_run)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/alembic/command.py", line 320, in upgrade
    script.run_env()
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/alembic/script/base.py", line 563, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/prefect/orion/database/migrations/env.py", line 70, in <module>
    apply_migrations()
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/prefect/utilities/asyncio.py", line 115, in wrapper
    return run_async_from_worker_thread(async_fn, *args, **kwargs)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/prefect/utilities/asyncio.py", line 62, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/anyio/from_thread.py", line 35, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 847, in run_async_from_thread
    return f.result()
  File "/home/raimundo/.pyenv/versions/3.9.0/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/home/raimundo/.pyenv/versions/3.9.0/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/prefect/orion/database/migrations/env.py", line 64, in apply_migrations
    await connection.run_sync(do_run_migrations)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/engine.py", line 536, in run_sync
    return await greenlet_spawn(fn, conn, *arg, **kw)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 136, in greenlet_spawn
    result = context.switch(value)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/prefect/orion/database/migrations/env.py", line 52, in do_run_migrations
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/alembic/runtime/environment.py", line 851, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/alembic/runtime/migration.py", line 620, in run_migrations
    step.migration_fn(**kw)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/prefect/orion/database/migrations/versions/sqlite/9725c1cbee35_initial_migration.py", line 25, in upgrade
    op.create_table(
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/alembic/operations/ops.py", line 1254, in create_table
    return operations.invoke(op)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/alembic/operations/base.py", line 392, in invoke
    return fn(self, operation)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/alembic/operations/toimpl.py", line 114, in create_table
    operations.impl.create_table(table)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/alembic/ddl/impl.py", line 356, in create_table
    self._exec(schema.CreateTable(table))
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/alembic/ddl/impl.py", line 197, in _exec
    return conn.execute(construct, multiparams)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 280, in execute
    return self._execute_20(
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 77, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1381, in _execute_ddl
    ret = self._execute_context(
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 719, in do_execute
    cursor.execute(statement, parameters)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 100, in execute
    self._adapt_connection._handle_exception(error)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 229, in _handle_exception
    raise error
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 82, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
    return current.driver.switch(awaitable)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
    value = await result
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/aiosqlite/cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/raimundo/pagarme/onboarding-wkr/.venv/lib/python3.9/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table flow already exists
[SQL: 
CREATE TABLE flow (
	id CHAR(36) DEFAULT (
    (
        lower(hex(randomblob(4))) 
        || '-' 
        || lower(hex(randomblob(2))) 
        || '-4' 
        || substr(lower(hex(randomblob(2))),2) 
        || '-' 
        || substr('89ab',abs(random()) % 4 + 1, 1) 
        || substr(lower(hex(randomblob(2))),2) 
        || '-' 
        || lower(hex(randomblob(6)))
    )
    ) NOT NULL, 
	created DATETIME DEFAULT (strftime('%Y-%m-%d %H:%M:%f000', 'now')) NOT NULL, 
	updated DATETIME DEFAULT (strftime('%Y-%m-%d %H:%M:%f000', 'now')) NOT NULL, 
	name VARCHAR NOT NULL, 
	tags JSON DEFAULT '[]' NOT NULL, 
	CONSTRAINT pk_flow PRIMARY KEY (id), 
	CONSTRAINT uq_flow__name UNIQUE (name)
)

]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

```
