### ISSUE TITLE
Can't create a work pool using local Prefect server instance because work pool logos are hosted online

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#11025] opened 2023-10-25 15:42 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When using a local Prefect server instance offline a work pool cannot be created because the logos are served by sanity.io.

Connecting to the internet, it works fine.

### Reproduction

While offline, start a Prefect server instance. 

Navigate to http://127.0.0.1:4200/work-pools/create

### Error

No work pool creation options load.

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.13.8
API version:         0.8.4
Python version:      3.10.12
Git commit:          1331bb3b
Built:               Thu, Oct 19,
2023 2:29 PM
OS/Arch:             darwin/arm64
Profile:             local
Server type:         server
```

### Additional context

Naive potential solution is to skip the logos if the attempt to load the logos fails.

**Comment by desertaxle** [comment] 2023-10-25 15:46
The UI is unable to display work pool types when offline because the metadata for work pool types is hosted on GitHub. This is a duplicate of https://github.com/PrefectHQ/prefect/issues/9377. I think we may need to update our build process to package the work pool type metadata with the published version of `prefect` for users hosting their server in an environment that cannot reach GitHub.

**Comment by desertaxle** [comment] 2023-10-25 15:48
Closing because this looks like a duplicate of #9377. Feel free to reopen if this is a separate issue. You can follow #9377 for updates!

**Closed by desertaxle** 2023-10-25 15:48 UTC
Labels: bug, ui

**Comment by discdiver** [comment] 2023-10-25 16:06
Ah, thanks, @desertaxle. Didn't see that one while looking for issues. Maybe I'll rename that issue as the problem seems to be larger than GitHub not being reachable.

**Comment by discdiver** [comment] 2023-10-25 16:09
Updated that issue to be more descriptive, easier for other people to find.
