### ISSUE TITLE
running prefect 2.11.4 with pydantic 1.10.2 leads to TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by OliverKleinBST** [PrefectHQ/prefect#10506] opened 2023-08-25 10:07 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

- I have installed prefect 2.11.4 in python 3.8 under windows.
- I used to have a need for pydantic 2.10.2 which is in the range of supported versions in your requirements.txt
- When I run prefect server start I get an error: TypeError: issubclass() arg 1 must be a class
- The same happens when I run a flow from within an Azure Function with Linux plan
- upgrading to pydantic 2.10.12 seems to solve the problem, so eventually you want to update requirement dependencies of prefect to be more strict

### Reproduction

```python3
prefect server start
```

### Error

```python3
Traceback (most recent call last):
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\site-packages\uvicorn\__main__.py", line 4, in <module>
    uvicorn.main()
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\site-packages\uvicorn\main.py", line 416, in main
    run(
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\site-packages\uvicorn\server.py", line 68, in serve
    config.load()
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\site-packages\uvicorn\config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\site-packages\prefect\server\__init__.py", line 1, in <module>
    from . import models, orchestration, schemas, services
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\site-packages\prefect\server\models\__init__.py", line 1, in <module>
    from . import (
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\site-packages\prefect\server\models\deployments.py", line 15, in <module>
    from prefect.server.api.workers import WorkerLookups
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\site-packages\prefect\server\api\__init__.py", line 1, in <module>
    from . import (
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\site-packages\prefect\server\api\concurrency_limits_v2.py", line 133, in <module>
    async def bulk_increment_active_slots(
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\site-packages\fastapi\routing.py", line 704, in decorator
    self.add_api_route(
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\site-packages\prefect\server\utilities\server.py", line 138, in add_api_route
    return super().add_api_route(path, endpoint, **kwargs)
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\site-packages\fastapi\routing.py", line 643, in add_api_route
    route = route_class(
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\site-packages\fastapi\routing.py", line 489, in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\site-packages\fastapi\dependencies\utils.py", line 261, in get_dependant
    type_annotation, depends, param_field = analyze_param(
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\site-packages\fastapi\dependencies\utils.py", line 429, in analyze_param
    field = create_response_field(
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\site-packages\fastapi\utils.py", line 99, in create_response_field
    return ModelField(**kwargs)  # type: ignore[arg-type]
  File "pydantic\fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "C:\Users\LLK7RT\.conda\envs\prefectazf\lib\typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
Server stopped!
```

### Versions

```Text
2.11.4
```

**Comment by zzstoatzz** [comment] 2023-08-25 21:05
hi @OliverKleinBST 
> I used to have a need for pydantic 2.10.2 which is in the range of supported versions in your requirements.txt

do you mean pydantic 1.10.2? [pydantic 2.3.0 is the latest version released](https://pypi.org/project/pydantic/) and [our `requirements.txt` enforces pydantic 1 at this time](https://github.com/PrefectHQ/prefect/blob/main/requirements.txt#L28).

do you mind verifying the version of pydantic do you have installed when you encounter this error?

**Comment by OliverKleinBST** [comment] 2023-08-26 15:02
Hi @zzstoatzz 

sorry for the confusion. Indeed I wanted to refer to pydantic 1. I.e. with pydantic 1.10.2 I do have the problem and with pydantic 1.10.12 its working.

**Comment by egeres** [comment] 2023-10-23 10:14
I got this error with prefect `2.13.8` but because I mistakenly switched to an env with pydantic `1.10.4`, now prefect is working perfectly with pydantic `2.4.2`

**Comment by quassy** [comment] 2023-11-03 16:13
I get the same error when trying to **deploy** a flow specifically with Prefect `2.14.3` and Pydantic `2.4.2`. There is no issue with Prefect `2.14.2` so it seems like a regression:
```
Traceback (most recent call last):
  File "./.venv/lib/python3.10/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "./.venv/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 255, in coroutine_wrapper
    return call()
  File "./.venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 382, in __call__
    return self.result()
  File "./.venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 282, in result
    return self.future.result(timeout=timeout)
  File "./.venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 168, in result
    return self.__get_result()
  File "/opt/homebrew/Cellar/python@3.10/3.10.13_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "./.venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 345, in _run_async
    result = await coro
  File "./.venv/lib/python3.10/site-packages/prefect/cli/deployment.py", line 1174, in build
    deployment = await Deployment.build_from_flow(
  File "./.venv/lib/python3.10/site-packages/prefect/deployments/deployments.py", line 863, in build_from_flow
    deployment.parameter_openapi_schema = parameter_schema(flow)
  File "./.venv/lib/python3.10/site-packages/prefect/utilities/callables.py", line 322, in parameter_schema
    if HAS_PYDANTIC_V2 and has_v2_model_as_param(signature):
  File "./.venv/lib/python3.10/site-packages/prefect/_internal/pydantic/v2_schema.py", line 22, in has_v2_model_as_param
    return any(
  File "./.venv/lib/python3.10/site-packages/prefect/_internal/pydantic/v2_schema.py", line 24, in <genexpr>
    or (inspect.isclass(p.annotation) and issubclass(p.annotation, V2BaseModel))
  File "/opt/homebrew/Cellar/python@3.10/3.10.13_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
An exception occurred.

```

**Comment by Andrew-S-Rosen** [comment] 2023-11-04 06:24
I can also confirm that this is a regression.

**Comment by Andrew-S-Rosen** [comment] 2023-11-09 22:42
FWIW, my issue was exactly better described by #7502.

**Comment by urimandujano** [comment] 2023-11-10 00:09
Hi @OliverKleinBST 

It looks like your specific traceback is coming from an error in fastapi and in prefect `2.11.4` we were not pinning our fastapi dependency. It's possible that this issue is related to and older version of `prefect` pulling in a newer version of `pydantic`. Can you share the version of python you're using and the output of `pip list`? That'll help me understand what your project's state is. 

@quassy, I think your comment is in line with what was reported on in https://github.com/PrefectHQ/prefect/issues/11149. My latest comment there should apply in your case.

**Comment by OliverKleinBST** [comment] 2023-11-10 08:14
Hi @urimandujano 

meanwhile we bumped our versions to prefect 2.14.3 and pydantic 2.x where we have not see a similar problem

**Comment by urimandujano** [comment] 2023-11-10 17:31
I'm glad the later versions are working for you now! I'm unable to reproduce this issue in a fresh virtualenv with `prefect 2.11.4` and `pydantic 1.10.2` so I'm going to close this. Please open a new issue if the problem returns.

**Closed by urimandujano** 2023-11-10 17:31 UTC
Labels: bug, needs:details, status:waiting for user
