### ISSUE TITLE
Invalid JSON payload should raise in `/filter` endpoints

### ISSUE THREAD

**Issue by MattDelac** [PrefectHQ/prefect#10601] opened 2023-09-01 16:49 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

One thing that is very misleading is that is the json payload is wrong in the /bots/filter endpoint (or any xxx/filter) it should fail and not return everything silently

Example with `/bots/filter`
<img width="1301" alt="image" src="https://github.com/PrefectHQ/prefect/assets/18557047/b2b1b9cc-bf59-473b-b346-a66a01886e7c">

Another example where the documentation says that I should be able to filter by name by it does not work
And plus filtering by names does not work at all even if it's part of the API docs
https://app.prefect.cloud/api/docs#tag/Workspace-Roles/operation/read_workspace_roles_api_accounts__account_id__workspace_roles_filter_post
<img width="1042" alt="image" src="https://github.com/PrefectHQ/prefect/assets/18557047/63c41ec8-061d-4e41-91cc-c87a9e44e50b">

<img width="924" alt="image" src="https://github.com/PrefectHQ/prefect/assets/18557047/4fadbf8b-85eb-4959-8aac-d2ad25ac91e4">

### Reproduction

```python3
see the description which details how to reproduce the bug
```

### Versions

```Text
Postman
```

**Comment by serinamarie** [comment] 2023-09-01 17:47
Hi @MattDelac, thanks for this issue! I was able to reproduce it and this seems a reasonable request to me. We'll add this to our backlog!

**Comment by pleek91** [comment] 2023-09-12 16:02
I believe in your roles example the api expects `any_` but you've passed `_any`. The underscore is in the wrong place. So I think both issues here are the same in that the api accepts any json payload and just ignores invalid properties.

**Comment by jawnsy** [comment] 2023-09-13 17:57
Hey @MattDelac, thanks for raising this issue! I really empathize with your situation, as I've been there many times myself, as I'm sure is true for many developers.

I explored this a bit with some help from a colleague (thank you @chrisguidry!) and, while we would welcome a pull request to add some more sophisticated validation capabilities, we could not find a straightforward way to implement this feature given our constraints around compatibility.

Here is some relevant context:

* We always try to maintain backward compatibility, meaning that an older version of Prefect should be compatible with newer versions of Prefect server or Prefect Cloud.
* When practical, we also aim to maintain forward compatibility, meaning that a new version of Prefect should be compatible with older versions of Prefect server. This is much less practical, so it is not something we can achieve consistently, but it is important to note.
* Several of our models are used both for serialization (for a client sending a request, such as a flow or worker) and deserialization (in Prefect Cloud or Prefect server). There are two compatibility aspects to consider (a V2 client communicating with a V1 server, and a V1 client communicating with a V2 server).
* If we add a new field between V1 and V2 schemas, this is a backward-compatible change, but it is not a forward-compatible one: a V1 client would not send the new field, while a V2 client would send a new field to a server that may not recognize it. In the latter case, the current behavior is that the server would ignore the new field, but would still return results for other matching filters, which seems more desirable than throwing an error.

We explored whether we could return warnings instead of errors, allowing us to retain our existing compatibility behavior while also giving an indication of the case you described (unknown fields that are due to typos or due to a filter that does not exist yet):

* [Kubernetes returns a special `Warning` header](https://kubernetes.io/blog/2020/09/03/warnings/) that includes deprecation notices, and this is part of a [proposed upcoming HTTP standard, RFC 7234](https://datatracker.ietf.org/doc/html/rfc7234#section-5.5); this behavior seems like it may be ideal for this case as well
* [Pydantic supports three modes of operation](https://codingshower.com/pydantic-ignore-allow-or-deny-extra-fields-not-defined-in-model-schema/) when encountering fields that are not in the schema:
   * Raise a validation error (`forbid`)
   * Capture the extra fields and expose it with a special method (`allow`)
   * Ignore extra fields (`ignore`) - this is our current behavior
* If we use `forbid`, we would need to capture the validation error (which likely requires a way to hook into FastAPI's lifecycle, since the fields we specify as parameters are deserialized before invoking our route functions). As far as we know, there is no straightforward way to accomplish this. Additionally, to get the non-fatal warning behavior, we'd have to perform a deserialization twice in the pessimistic case: once, to raise an error for extra fields, and then again, to remove the extra fields and propagate to our application logic.
* If we use `allow`, we would be able to [inspect extra fields](https://docs.pydantic.dev/latest/api/base_model/#pydantic.main.BaseModel.model_extra) that were passed to our class to avoid the double deserialization problem (a non-empty `model_extra` field would include unknown fields), but we still have the problem that we'd need to hook into FastAPI's deserialization lifecycle and return warnings as headers. This might be possible with a middleware or similar.
* An alternative to a middleware approach may be to use a utility function or similar, but I think this would result a large amount of duplicated code, which would increase the probability that our APIs are inconsistent.
* The extra configuration is set on the model, rather than during serialization/deserialization, so at a first glance, this would mean that the validation logic would necessarily apply on both directions (when sending a request as well as receiving a response). We would want to allow extra fields when receiving a request from a client or response from a server, but we would not want to allow sending extra fields.

While I do not have experience with the feature, I see that [Postman has support for importing an OpenAPI Schema](https://learning.postman.com/docs/integrations/available-integrations/working-with-openAPI/), which might be helpful to prevent errors.

Additionally, as far as I know, our current behavior (ignore unknown fields) is very common in APIs. I'm not familiar with any that validate requests more strictly.

On balance, while I think this is a valid issue and we would like to solve it, the lack of a straightforward path to resolving it makes it difficult for us to proceed, though we'd welcome discussion of any ideas you have. I hope this helps explain our thought process here.

**Comment by MattDelac** [comment] 2023-09-14 14:55
Hi @jawnsy 

Thanks for the detailed response and all the context. It's really appreciated.

A couple of comments on my side
1. **Validation Warnings**: This might be the best approach in this situation. This would allow us to maintain compatibility while giving the client immediate feedback about potentially unintended behavior. Warnings could alert the client that some fields are ignored without breaking the application.

2. **Forward Compatibility**: The idea of forward compatibility is compelling in theory, but practical implementation often tells a different story. When we introduce new fields or parameters, older versions of the API won't know how to handle them. It often introduces more challenges than solutions like in this situation.

3. **Best practice**: It's worth noting that just because the current behavior of "ignoring unknown fields" is very common doesn't necessarily make it the best practice IMO. Ignoring fields is a simple solution but can lead to overlooked errors. It also gives no feedback to the client, leading to potential issues down the line. And it's well known that human makes mistakes and typos 🙂 

4. **Versioning + Strict Validation**: Have you considered versioning? Having a versioning strategy alongside strict validation can offer the best of both worlds. It would maintain backward compatibility because older API versions would still be available and functioning as they always have. At the same time, it gives feedback to the users about what they might be doing wrong, thanks to strict validation in newer versions.

I know that some of those would take time to implement but I believe that there would be a ton of silent bugs discovered by changing the current behavior (ignoring unknown fields). Having at least warnings would be a huge help to the community.
And maybe some changes can be done incrementally.

**Comment by jawnsy** [comment] 2023-09-17 00:10
Thanks for taking the time to share this excellent feedback, @MattDelac! I think your comment summarizes the situation well and it seems that we generally agree on the constraints and potential approaches we could take.

We'll continue to investigate adding warnings and API versioning, however, because neither of those are straightforward/short-term fixes, we do not have a timeline to completing that work at this time.

**Comment by jawnsy** [comment] 2023-09-21 16:03
Hey @MattDelac, just wanted to give you a brief update on this.

My colleague @zangell44 looked into this and realized that we can bring some data to this work. We’ve instrumented our server-side code in Prefect Cloud to determine the potential impact, and we will provide updates once learn more.

Thanks so much once again for the feedback and discussion!

**Comment by zangell44** [comment] 2024-01-30 14:51
Since Oct 27th, 2023, Prefect Cloud should be raising errors on invalid JSON payloads. Thanks for flagging!

**Closed by zangell44** 2024-01-30 14:51 UTC
Labels: bug, api, from:sales
