### ISSUE TITLE
Overcome 200-Deployment limit in search of Flow Runs

### ISSUE THREAD

**Issue by kevin868** [PrefectHQ/prefect#7581] opened 2022-11-18 01:00 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Flow Runs page:
Having more than 200 Deployments means some of them don't appear in the Filter / Dropdown list. 
Searching by an expected deployment name or prefix fails.

The workaround right now is to leave Flow Runs, and go to Deployments -> (choose deployment) -> Runs

Potential solution is:
- when text is entered in the Deployment dropdown AND no results are found in the client-side Deployments list. --> call the Deployment API (ex. `deployments?deployment-name=`) to search for more/missing possibilities

### Reproduction

1) Have more than 200 Deployments
2) Open Flow Runs, and try to search in the Deployments dropdown

This is confusing, to not be able to search for the Deployment by name. Yet, if you hover over the History graph OR scroll down through Flow Runs, you WILL see runs tied to these missing Deployments.

### Error

Several deployments with `dp9` in the name DO exist. They can be found by going to Deployments page, or scrolling through Flow Runs.

<img width="945" alt="Screenshot 2022-11-17 at 7 27 03 PM" src="https://user-images.githubusercontent.com/15519577/202591794-521efdc4-e610-4f77-ad72-17b2f3a3b65e.png">

### Browers

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Prefect version

```Text
2.6.7
```

**Comment by pleek91** [comment] 2022-11-21 20:19
We'll need to update that component to hit the api for search rather than filtering client side. Using the `deployment.name.like_`. We should also update it to let you scroll through more than 200 results at a time.

**Comment by EmilRex** [comment] 2023-03-31 14:29
Related to #7481

**Comment by Bada-S** [comment] 2023-09-14 16:53
Rather than create a new issue, I will post here. A user reported not being able to select some of their flows in the dropdown for automations since they have >200 flows. I was able to reproduce this using this script
```
from prefect import flow

if __name__ == "__main__":
    # generate 500 flows and run them
    for i in range(500):
        exec(f"@flow()\ndef f_{i}(): print({i})")
    for i in range(500):
        exec(f"f_{i}()")
```
to generate flows.
![image](https://github.com/PrefectHQ/prefect/assets/69161193/79d3f7f0-2603-4174-8ea7-361c36323dd6)
![image](https://github.com/PrefectHQ/prefect/assets/69161193/5509fe66-05e0-4fea-afed-50a9cc9990fe)

**Comment by pleek91** [comment] 2023-09-20 13:18
This issue is closed by https://github.com/PrefectHQ/prefect-ui-library/pull/1747

Flows issue is https://github.com/PrefectHQ/prefect/issues/9805 which was closed by https://github.com/PrefectHQ/prefect-ui-library/pull/1759

**Closed by pleek91** 2023-09-20 13:18 UTC
Labels: bug, status:accepted, ui, from:sales, orchestration
