### ISSUE TITLE
Prefect UI not displaying double-backslashes in markdown artifact

### ISSUE THREAD

**Issue by PPPSDavid** [PrefectHQ/prefect#10021] opened 2023-06-21 22:15 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

same issue as observed in https://github.com/PrefectHQ/prefect/issues/9816 seems to be persisting

### Reproduction

See linked issue: https://github.com/PrefectHQ/prefect/issues/9816

### Error

see linked issue: https://github.com/PrefectHQ/prefect/issues/9816

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Additional context

part of our "raw data" markdown looks like this (directly copie from the Prefect UI):

`\n\n ABC Cat:\n \\\\123\\45`

and what we saw is:

ABC Cat:
123\45

Note that the two backslashes before "45" is escaped and recognized, but the first 4 backslashes are not resolved into "\\"

**Comment by znicholasbrown** [comment] 2023-06-21 22:34
Closing as duplicate of #9816 - will reopen that initial ticket if needed.

**Closed by znicholasbrown** 2023-06-21 22:34 UTC
Labels: bug, status:duplicate, ui
