### ISSUE TITLE
Cannot use CLI to build deployment with interval schedule

### ISSUE THREAD

**Issue by hozn** [PrefectHQ/prefect#10740] opened 2023-09-15 17:43 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I am unable to use `prefect deployment build` to create a deployment with an interval timer.

I have also tried using a `prefect.yaml` file with same result.

### Reproduction

```python3
prefect deployment build --name "My Flow" --interval=60 --timezone=UTC --skip-upload --apply myflow.py:myflow
```

(Initially tried without `timezone` specified, but error is the same.)

I have also tried a prefect.yaml file:

# Snip
deployments:
- name: My Flow
  version: 1.0
  tags: []
  description: null
  schedule:
    interval: 60
    timezone: UTC
  entrypoint: myflow.py:myflow
  parameters: {}
  work_pool:
    name: default-agent-pool
    work_queue_name: default
    job_variables: {}

```
```

### Error

```python3
Traceback (most recent call last):
  File "/Users/hans/Library/Caches/pypoetry/virtualenvs/proj-cvPU66vz-py3.11/lib/python3.11/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/hans/Library/Caches/pypoetry/virtualenvs/proj-cvPU66vz-py3.11/lib/python3.11/site-packages/prefect/utilities/asyncutils.py", line 255, in coroutine_wrapper
    return call()
           ^^^^^^
  File "/Users/hans/Library/Caches/pypoetry/virtualenvs/proj-cvPU66vz-py3.11/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 382, in __call__
    return self.result()
           ^^^^^^^^^^^^^
  File "/Users/hans/Library/Caches/pypoetry/virtualenvs/proj-cvPU66vz-py3.11/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 282, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hans/Library/Caches/pypoetry/virtualenvs/proj-cvPU66vz-py3.11/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 168, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/hans/Library/Caches/pypoetry/virtualenvs/proj-cvPU66vz-py3.11/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 345, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "/Users/hans/Library/Caches/pypoetry/virtualenvs/proj-cvPU66vz-py3.11/lib/python3.11/site-packages/prefect/cli/deployment.py", line 1074, in build
    schedule = IntervalSchedule(
               ^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for IntervalSchedule
timezone
  argument of type 'function' is not iterable (type=type_error)
```

Error is same when using prefect.yaml but does not show full stack trace (by default, anyway).
```


### Versions

```Text
2.13.1
```

**Comment by serinamarie** [comment] 2023-09-15 18:32
Duplicate of #10741

**Closed by serinamarie** 2023-09-15 18:32 UTC
Labels: bug, needs:triage
