### ISSUE TITLE
GCS returns 400 error code when attempting to store flow as script on Google Cloud Storage

### ISSUE THREAD

**Issue by fpun** [PrefectHQ/prefect#5050] opened 2021-10-12 01:23 UTC
## Description
I'm registering flows to Prefect Cloud as part of a build pipeline running on Google Cloud Build.
Flows are stored on Google Cloud Storage using prefect.storage.GCS with stored_as_script set to True.

When processing the flow, GCS doesn't receive the call it expects and returns a 400 code. Full trace below:

```
Step #2: Collecting flows...
Step #2: Processing './***.py':
Step #2:   Building `GCS` storage...
Step #2: [2021-10-12 00:14:04+0000] INFO - prefect.GCS | Uploading script ***.py to *** in ***
Step #2:     Error building storage:
Step #2:       Traceback (most recent call last):
Step #2:         File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2594, in upload_from_file
Step #2:     retry=retry,
Step #2:         File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2412, in _do_upload
Step #2:     retry=retry,
Step #2:         File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2242, in _do_resumable_upload
Step #2:     response = upload.transmit_next_chunk(transport, timeout=timeout)
Step #2:         File "/usr/local/lib/python3.7/site-packages/google/resumable_media/requests/upload.py", line 505, in transmit_next_chunk
Step #2:     self._process_response(response, len(payload))
Step #2:         File "/usr/local/lib/python3.7/site-packages/google/resumable_media/_upload.py", line 678, in _process_response
Step #2:     callback=self._make_invalid,
Step #2:         File "/usr/local/lib/python3.7/site-packages/google/resumable_media/_helpers.py", line 104, in require_status_code
Step #2:     *status_codes
Step #2:       google.resumable_media.common.InvalidResponse: ('Request failed with status code', 400, 'Expected one of', <HTTPStatus.OK: 200>, 308)
Step #2:
Step #2: During handling of the above exception, another exception occurred:
Step #2:
Step #2:       Traceback (most recent call last):
Step #2:         File "/usr/local/lib/python3.7/site-packages/prefect/cli/build_register.py", line 463, in build_and_register
Step #2:     storage.build()
Step #2:         File "/usr/local/lib/python3.7/site-packages/prefect/storage/gcs.py", line 156, in build
Step #2:     blob.upload_from_file(file_obj)
Step #2:         File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2598, in upload_from_file
Step #2:     _raise_from_invalid_response(exc)
Step #2:         File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 4437, in _raise_from_invalid_response
Step #2:     raise exceptions.from_http_status(response.status_code, message, response=response)
Step #2:       google.api_core.exceptions.BadRequest: 400 PUT https://storage.googleapis.com/upload/storage/v1/b/***/o?uploadType=resumable&upload_id=***: Invalid request.  There were 1966 byte(s) in the request body.  There should have been 2039 byte(s) (starting at offset 0 and ending at offset 2038) according to the Content-Range header.: ('Request failed with status code', 400, 'Expected one of', <HTTPStatus.OK: 200>, 308)
```

I'm wondering if it might be related to GCS Blob.upload_from_file function needing a byte input, as discussed on [this SO thread](https://stackoverflow.com/questions/54637468/gcp-storage-cant-upload-string-with-invisible-ascii-caracters)

## Expected Behavior
Expecting no error

## Reproduction
Example that exhibits the behavior :

```python
from prefect import Flow
from prefect.run_configs import LocalRun
from prefect.executors import LocalDaskExecutor
from prefect.storage import GCS


run_config = LocalRun()
storage = GCS(
    stored_as_script=True,
    bucket='bucket_name'
)

flow = Flow(
    'Flow name',
    storage=storage,
    run_config=run_config,
    executor=LocalDaskExecutor()
)
```

## Environment
The build step executes the following commands using the prefecthq/prefect:0.15.6 image

```
prefect auth login -k $$PREFECT_API_KEY && prefect register --project $BRANCH_NAME --path "./***.py" --label $BRANCH_NAME'
```

prefect diagnostics:

```json
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.4.0-1052-gcp-x86_64-with-debian-11.1",
    "prefect_backend": "cloud",
    "prefect_version": "0.15.6",
    "python_version": "3.7.12"
  }
}
```

**Comment by anna-geller** [comment] 2022-05-11 11:40
Closing the issue since I couldn't reproduce and this issue occurs because `local_script_path` + `key` were not provided and those are required to use script storage.

Here is a working example allowing to use GCS script storage: https://github.com/anna-geller/packaging-prefect-flows/blob/master/flows/gcs_local_run.py

**Closed by anna-geller** 2022-05-11 11:40 UTC
