### ISSUE TITLE
Would you like to schedule when this flow runs? is asked for each flow every time prefect deploy is run even when schedule is explicitly null

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#10057] opened 2023-06-23 21:42 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When I run `prefect deploy --all` I need to type n for each deployment when the `Would you like to schedule when this flow runs?` prompt pops up. Its a little annoying and its strange because it is the only prompt that pops up so it feels out of place. It ruins the magic of prefect deploy --all.

At PACC I had a lot of users ask me if we were working on removing this prompt for an already defined deployment.

### Reproduction

```python3
# Welcome to your prefect.yaml file! You can you this file for storing and managing
# configuration for deploying your flows. We recommend committing this file to source
# control along with your flow code.

# Generic metadata about this project
name: prefect-patterns
prefect-version: 2.10.17

# build section allows you to manage and build docker images
build:

# push section allows you to manage if and how this project is uploaded to remote locations
push:

# pull section allows you to provide instructions for cloning this project in remote locations
pull:
- prefect.deployments.steps.git_clone:
    repository: https://github.com/taylor-curran/prefect-patterns.git
    branch: main

# the deployments section allows you to provide configuration for deploying flows
deployments:
- name: dep-task-wrapped
  version:
  tags: []
  description:
  entrypoint: flows/subflow-patterns/task_wrapped_deployments.py:task_wrapped_deployments
  parameters: {}
  work_pool:
    name: my-process-flow
    work_queue_name:
    job_variables: {}
  schedule: null
- name: dep-sync-subflows
  version:
  tags: []
  description:
  entrypoint: flows/subflow-patterns/sync_subflows.py:sync_subflows
  parameters: {}
  work_pool:
    name: my-process-flow
    work_queue_name:
    job_variables: {}
  schedule: null


prefect deploy --all
```

### Versions

```Text
Version:             2.10.17
API version:         0.8.4
Python version:      3.9.16
Git commit:          6d53d9b4
Built:               Thu, Jun 22, 2023 5:28 PM
OS/Arch:             darwin/arm64
Profile:             tay-sandbox
Server type:         cloud
```

### Additional context

![image](https://github.com/PrefectHQ/prefect/assets/68969861/dd03ceb6-675b-4893-a9ad-38f3cc44f63e)

**Comment by serinamarie** [comment] 2023-06-23 21:44
Closing as duplicate of https://github.com/PrefectHQ/prefect/issues/9907

**Closed by serinamarie** 2023-06-23 21:44 UTC
Labels: bug, status:triage
