### ISSUE TITLE
Prefect Agent dies with "Agent stopped!" message

### ISSUE THREAD

**Issue by tibuch** [PrefectHQ/prefect#8571] opened 2023-02-17 10:33 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

My prefect agent keeps dying in shorter and shorter intervals. First it was after 24h and the last death was <3h after starting it.

I am running the agent in a tmux session.

### Reproduction

```python3
prefect agent start --pool default-agent-pool --work-queue default
```

### Error

```python3
Failed the last 3 attempts.  Please check your environment and configuration.
Examples of recent errors:

Traceback (most recent call last):
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/h2/connection.py", line 224, in process_input
    func, target_state = self._transitions[(self.state, input_)]
KeyError: (<ConnectionState.CLOSED: 3>, <ConnectionInputs.SEND_HEADERS: 0>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpcore/_async/http2.py", line 108, in handle_async_request
    await self._send_request_headers(request=request, stream_id=stream_id)
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpcore/_async/http2.py", line 205, in _send_request_headers
    self._h2_state.send_headers(stream_id, headers, end_stream=end_stream)
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/h2/connection.py", line 766, in send_headers
    self.state_machine.process_input(ConnectionInputs.SEND_HEADERS)
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/h2/connection.py", line 228, in process_input
    raise ProtocolError(
h2.exceptions.ProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpcore/_async/http_proxy.py", line 313, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpcore/_async/http2.py", line 144, in handle_async_request
    raise LocalProtocolError(exc)  # pragma: nocover
httpcore.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/prefect/utilities/services.py", line 46, in critical_service_loop
    await workload()
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/prefect/agent.py", line 262, in check_for_cancelled_flow_runs
    async for work_queue in self.get_work_queues():
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/prefect/agent.py", line 144, in get_work_queues
    work_queue = await self.client.read_work_queue_by_name(
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/prefect/client/orchestration.py", line 838, in read_work_queue_by_name
    response = await self._client.get(
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpx/_client.py", line 1751, in get
    return await self.request(
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/prefect/client/base.py", line 229, in send
    response = await self._send_with_retry(
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/prefect/client/base.py", line 187, in _send_with_retry
    response = await request()
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpx/_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpx/_client.py", line 1716, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED



Failed the last 3 attempts.  Please check your environment and configuration.
Examples of recent errors:

Traceback (most recent call last):
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/h2/connection.py", line 224, in process_input
    func, target_state = self._transitions[(self.state, input_)]
KeyError: (<ConnectionState.CLOSED: 3>, <ConnectionInputs.SEND_HEADERS: 0>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpcore/_async/http2.py", line 108, in handle_async_request
    await self._send_request_headers(request=request, stream_id=stream_id)
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpcore/_async/http2.py", line 205, in _send_request_headers
    self._h2_state.send_headers(stream_id, headers, end_stream=end_stream)
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/h2/connection.py", line 766, in send_headers
    self.state_machine.process_input(ConnectionInputs.SEND_HEADERS)
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/h2/connection.py", line 228, in process_input
    raise ProtocolError(
h2.exceptions.ProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpcore/_async/http_proxy.py", line 313, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpcore/_async/http2.py", line 144, in handle_async_request
    raise LocalProtocolError(exc)  # pragma: nocover
httpcore.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/prefect/utilities/services.py", line 46, in critical_service_loop
    await workload()
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/prefect/agent.py", line 194, in get_and_submit_flow_runs
    responses = await self.client.get_scheduled_flow_runs_for_work_pool(
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/prefect/client/orchestration.py", line 2259, in get_scheduled_flow_runs_for_work_pool
    response = await self._client.post(
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpx/_client.py", line 1842, in post
    return await self.request(
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/prefect/client/base.py", line 229, in send
    response = await self._send_with_retry(
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/prefect/client/base.py", line 187, in _send_with_retry
    response = await request()
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpx/_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpx/_client.py", line 1716, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/_prefect/miniconda3/envs/prefect2/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.LocalProtocolError: Invalid input ConnectionInputs.SEND_HEADERS in state ConnectionState.CLOSED


Agent stopped!
```

### Versions

```Text
Version:             2.8.1
API version:         0.8.4
Python version:      3.9.13
Git commit:          920d07a0
Built:               Thu, Feb 16, 2023 12:27 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```

**Comment by tibuch** [comment] 2023-02-17 10:34
The first line in the error says `Please check your environment and configuration.` Unfortunately, I don't know which points I should look into. Happy to try things out.

**Comment by madkinsz** [comment] 2023-02-17 20:36
Hi! This is a duplicate of https://github.com/PrefectHQ/prefect/issues/7442 – I'd recommend disabling HTTP/2 as we are still working on resolving the bug in the upstream HTTP library.

**Closed by madkinsz** 2023-02-17 20:36 UTC
Labels: bug, status:triage
