### ISSUE TITLE
custom flow run names not respected by timeline view

### ISSUE THREAD

**Issue by zzstoatzz** [PrefectHQ/prefect#8601] opened 2023-02-21 00:29 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

The timeline view does not respect custom flow run names

### Reproduction

use something like `run_deployment` to create a flow run with a custom name and navigate to timeline view

### Error

![image](https://user-images.githubusercontent.com/31014960/220217429-146b6bd4-35cb-44ff-abad-dbe8f1cadceb.png)

### Browers

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

**Comment by rpeden** [comment] 2023-02-22 15:39
This looks like a duplicate of #8180 in that it is caused by the same underlying issue.

What's happening is that subflows get run by a task, and the generated task name is what's showing up in the timeline instead of the flow run name.

**Closed** 2023-02-22 15:40 UTC
Labels: bug, ui, status:triage
