### ISSUE TITLE
Prefect 2.7.1 breaking change when deploying to 2.7.0 server

### ISSUE THREAD

**Issue by TheBeege** [PrefectHQ/prefect#7988] opened 2022-12-26 09:17 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Prefect version 2.7.1 introduces a new field to the deploy request's body: `worker_pool_queue_id`. A Prefect server of version 2.7.0 returns a `422 Unprocessable Entity` error when attempting this:
```
An error occurred while deploying: HTTPStatusError("Client error '422 Unprocessable Entity' for url 'https://myprefect/api/deployments/'\nFor more information check: https://httpstatuses.com/422")
```

Prefect server version 2.7.0 does not accept this request body field and rejects the request stating it does not recognize the parameter. Unfortunately, I don't have the validation rejection error handy right now.

Also, please note that I had to use Wireshark to pull out the request, as the deploy command does not provide any debug flag for outputting troubleshooting info.

### Reproduction

```python3
# Deploy a Prefect 2.7.0 server
# With Prefect 2.7.1, run the below for some flow named `my_flow_module` and other appropriate parameter values
python -m my_flow_module deploy \
      	--deployment-name "my_deployment" \
      	--flow-name "my_flow" \
      	--image "my_image" \
      	--deployment-file-path "some_deployment_file.yml"
```

### Error

```python3
An error occurred while deploying: HTTPStatusError("Client error '422 Unprocessable Entity' for url 'https://myprefectserver/api/deployments/'\nFor more information check: https://httpstatuses.com/422")
```

### Versions

```Text
Server version: 2.7.0
Local client version: 2.7.1
```

### Additional context

If a more complete reproduction is required, please let me know. I'm a little overworked right now, but if it's required, I can make the time.

**Comment by jawnsy** [comment] 2022-12-27 15:41
Hello there,

Thanks for the detailed bug report and steps to reproduce!

Orion supports backward compatibility (old client versions can be used with new server versions), but not forward compatibility (new client versions are not guaranteed to work with old server versions), as [documented in our version compatibility guidelines](https://github.com/PrefectHQ/prefect/blob/main/docs/contributing/versioning.md#client-compatibility-with-orion):

>When running a Prefect Orion server, you are in charge of ensuring the version is compatible with those of the clients that are using the server. Prefect aims to maintain backwards compatibility with old clients for each server release. In contrast, sometimes new clients cannot be used with an old server. The new client may expect the server to support functionality that it does not yet include. For this reason, we recommend that all clients are the same version as the server or older.
>
>For example, a client on 2.1.0 can be used with a server on 2.5.0. A client on 2.5.0 cannot be used with a server on 2.1.0.

We may consider detecting this and providing a warning, but I don't think this is a class of issues that we can fix in general.

Is it a showstopper for you to either upgrade the server or downgrade clients?

**Comment by peytonrunyan** [comment] 2022-12-28 13:53
Hey @TheBeege - thanks for taking the time make such a thorough issue post! It looks like @jawnsy covered the way change compatibility is setup at Prefect, and I don't think I have anything substantive to add. 

I'm going to go ahead and close this issue just for the sake of keeping things organized, but if you have any questions or concerns around updating your server version, please feel free to ask them on our Slack. It's quite active, and we should be able to help get you squared away :). 

https://www.prefect.io/community/

**Closed by peytonrunyan** 2022-12-28 13:53 UTC
Labels: bug, status:triage

**Comment by TheBeege** [comment] 2023-01-02 06:03
> Hello there,
> 
> Thanks for the detailed bug report and steps to reproduce!
> 
> Orion supports backward compatibility (old client versions can be used with new server versions), but not forward compatibility (new client versions are not guaranteed to work with old server versions), as [documented in our version compatibility guidelines](https://github.com/PrefectHQ/prefect/blob/main/docs/contributing/versioning.md#client-compatibility-with-orion):
> 
> > When running a Prefect Orion server, you are in charge of ensuring the version is compatible with those of the clients that are using the server. Prefect aims to maintain backwards compatibility with old clients for each server release. In contrast, sometimes new clients cannot be used with an old server. The new client may expect the server to support functionality that it does not yet include. For this reason, we recommend that all clients are the same version as the server or older.
> > For example, a client on 2.1.0 can be used with a server on 2.5.0. A client on 2.5.0 cannot be used with a server on 2.1.0.
> 
> We may consider detecting this and providing a warning, but I don't think this is a class of issues that we can fix in general.
> 
> Is it a showstopper for you to either upgrade the server or downgrade clients?

@jawnsy Got it. Thank you! We ended up upgrading our server instance.

@peytonrunyan Understood. Thanks!

Folks in my department are becoming heavy users of Prefect, so I'm sure I'll be in touch now and then :)
