### ISSUE TITLE
Enable configurable delay for task state updates for waiting tasks 

### ISSUE THREAD

**Issue by ctilling** [PrefectHQ/prefect#10643] opened 2023-09-06 20:10 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently the server wait time is hard coded to 30 seconds [here](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/engine.py#L2139-L2150) so that tasks that are submitted to a task runner that are waiting to be run, are only started every 30 seconds. For example if 30 tasks are submitted to the `ConcurrentTaskRunner` with a task concurrency limit of 10. It will take at least 90 seconds for the tasks to complete even if the tasks run very quickly. 

### Describe the proposed behavior

The desired behavior would be to surface this constant as a configurable parameter so users can set custom wait times based on their requirements.

**Comment by desertaxle** [comment] 2023-09-06 20:18
Thanks for the issue @ctilling! I'm going to close this issue since it is a duplicate of https://github.com/PrefectHQ/prefect/issues/9500, but please feel free to post details regarding your use case on the linked issue!

**Closed by desertaxle** 2023-09-06 20:18 UTC
Labels: status:duplicate
