### ISSUE TITLE
No flow found in file since 0.14.4 due to using magic variables

### ISSUE THREAD

**Issue by alexkoay** [PrefectHQ/prefect#4018] opened 2021-01-27 04:34 UTC
Prefect is unable to find the correct flow to execute because I was relying on a factory function to derive the name automatically from the filename via `inspect.stack()` and using `stored_as_script=True`.
I believe this is due to the utility function using `exec()` to instantiate the file to locate the flow in its `globals()`.
0.14.4 started checking for flow names from #3969 as a result of my earlier issue #3961.
The flow name was not set correctly in the past (it was set as `<string>`), but it was silently missed since the previous versions just used the first flow it finds.

**Suggestion**: Using `runpy.run_path()` seems to fix this issue for my use-case, and correctly populates the filename and other magic variables.

**Comment by jcrist** [comment] 2021-01-28 15:33
I'm sorry, I'm having a hard time understanding the issue here. Can you provide a reproducible example of a flow that fails to load so we can investigate further?

**Comment by alexkoay** [comment] 2021-01-28 16:31
Okay, I have generate_flow() in a separate file, but this works just as well.
The function looks at the stack to retrieve its caller's location and uses that as the flow name.

As such, when you put the following in a file, the flow will use the file's name when registering, but when executing, `flow.name == '<string>'` instead.

```py
import os
import inspect
import prefect

def generate_flow(**kwargs):
    fpath = inspect.stack()[1].filename
    fname = os.path.basename(fpath)
    name = fname.rsplit('.', 1)[0]
    return prefect.Flow(name=name, stored_as_script=True, **kwargs)

@prefect.task
def log(s):
    print(s)

with generate_flow() as flow:
    out = log('test')
```

**Comment by jcrist** [comment] 2021-01-29 19:50
Ah, yeah, that's a pattern we can't commit to supporting (and is rather fragile anyway since it depends on the call frame). Since flow storage is abstract, not all flow storage mechanisms have an obvious thing we can use for a file path (what's the filepath for S3 storage? The key? The bucket + key? What about webhook storage?). Further, the method you're using above requires that your local path used when registering the flow matches the path the flow is stored at at runtime. This may not be true (and frequently isn't).

Closing this as something we can't really commit to fixing, I suggest you move to specifying the filename manually.

**Closed by jcrist** 2021-01-29 19:50 UTC

**Comment by alexkoay** [comment] 2021-02-01 09:51
Perhaps in another line of questioning, is there anyway to use `extract_flow_from_module()` from other storage apart from Local?

**Comment by jcrist** [comment] 2021-02-01 15:42
Module-based flow storage currently only works with the `Local` storage class (we're thinking about ways to make this more flexible). That said, you can use `Local` storage with a docker agent, provided you build the docker images yourself.

```python
from prefect.storage import Local
from prefect.run_configs import DockerRun

flow.storage = Local("mypackage.module:my_flow", add_default_labels=False)
flow.run_config = DockerRun(image="your-prebuilt-image")
```
