### ISSUE TITLE
ECS worker erroring out with `network_configuration` in 2.11.4

### ISSUE THREAD

**Issue by vishaalkk** [PrefectHQ/prefect#10458] opened 2023-08-21 15:00 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When running Prefect deploy with the latest version -- 2.11.4, it errors out:

<img width="645" alt="image" src="https://github.com/PrefectHQ/prefect/assets/13641827/d4b09fd8-7807-4a5d-adf1-2046d35cb515">

### Reproduction

```python3
This is what an example `prefect.yaml` looks like:


name: dbt-runner-flow
deployments:
- name: dbt-project-ci
  entrypoint: flow.py:entrypoint_flow
  work_pool:
    name: default-worker-pool
    job_variables:
      task_definition_arn: "TASKDEF"  
  push:
  - prefect_aws.deployments.steps.push_to_s3:
      id: push-code
      requires: prefect-aws>=0.3.0
      bucket: prefect-storage-local
      folder: prefect-main/dbt-runner-flow/dbt-project-ci
  pull:
  - prefect_aws.deployments.steps.pull_from_s3:
      id: pull-code
      requires: prefect-aws>=0.3.0
      bucket: '{{ push-code.bucket }}'
      folder: '{{ push-code.folder }}'
  schedule: null
  tags:
  - team:data-engineering
  description: dbt Project CI
  parameters:
    debug: false
    seed_build: false
    skip_tests: false
    full_refresh: false
    install_deps: true
    take_snapshot: false
    yaml_selector: selector
    dbt_project_name: project
    data_team_name: data-engineering
    source_freshness: false
prefect-version: 2.11.4
```

### Error

```python3
| 1 validation error for ParsingModel[WorkPool]
| __root__ -> base_job_template
|   The variables specified in the job configuration template must be present as
| properties in the variables schema. Your job configuration uses the following
| undeclared variable(s): network_configuration. (type=value_error)
```

### Versions

```Text
Version:             2.11.4
API version:         0.8.4
Python version:      3.10.12
Git commit:          7d2a9103
Built:               Thu, Aug 17, 2023 3:41 PM
OS/Arch:             darwin/x86_64
Profile:             default
Server type:         cloud
```

**Comment by EmilRex** [comment] 2023-08-21 15:36
Possibly related to prefect-aws#304 being introduced.

**Comment by desertaxle** [comment] 2023-08-21 15:53
This is likely caused by validation that is only meant to be run on the creation and update of work pools is also being run on read. 

@vishaalkk we'll get a fix for this out in the next release, but in the meantime you should be able to mitigate this error by downgrading to 2.11.4.

**Closed** 2023-08-24 15:08 UTC
Labels: bug
