### ISSUE TITLE
Enhancement: ensure boolean parameter configurations are handled by UI

### ISSUE THREAD

**Issue by j-tr** [PrefectHQ/prefect#7118] opened 2022-09-19 14:52 UTC
**Bug Description**

switches for custom boolean parameters for flow runs are set to "False" in the flow run creation form irrespective of the actual default value. when these switches are not changed during the flow run creation, the flow run will be submitted without these parameters, and consequently using the default settings that could be "True". This results in a mismatch between what the user sees on flow submission and what's actually executed. However, if the switches are toggled back and forth, effectively resulting in the same state of the form, the flows are submitted with the parameters from the form, overwriting the default parameters. This means that toggling the switches back and forth results in a different outcome than not touching the switches at all, even though the form looks exactly the same. this could lead to some very hard to reproduce issues.

**Steps To Reproduce**
Experiment 1

1. Deploy flow with at least one "True" default parameter. e.g.:
```
from prefect import flow, get_run_logger


@flow(name="param_example")
def main(
    *,
    bool_true: bool = True,    # <-- Default TRUE
    bool_false: bool = False,
) -> None:
    logger = get_run_logger()
    logger.info(bool_true)
    logger.info(bool_false)
```
2. Create Flow run with custom parameters and see all switches in state "False". Do not click on any switch. Run flow.
![image (13)](https://user-images.githubusercontent.com/11021147/191044958-36c83181-feea-421b-9c00-ef434c0e245e.png)

3. Go to flow run -> Parameters, see that no parameters were submitted, consequently default parameters were used. See output for the provided example flow to verify.
![image (14)](https://user-images.githubusercontent.com/11021147/191045301-34ac349b-9bdf-4ede-8d9d-29fbc63831fa.png)

This shows a missmatch between the submission form and the actual flow run

Experiment 2:

1. Go to the same deployment, Run with custom parameters
2. Toggle bool_true switch back and forth. The form now looks exactly like in the first experiment.
3. Run flow, go to flow run -> Parameters, see that a parameter was used, overwriting the default parameter.

This shows that toggling switches back and forth can result in a flow run with different parameters.

Same applies for string parameters with default values. When typing text in the input field and deleting it, the default values will be displaced again but the flow is submitted with an empty string as parameter, resulting in a mismatch between the submission form and the actual run configuration.

**Browsers Tested:**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge
* [ ] IE

-

---------
**Notes**

**Comment by zhen0** [comment] 2022-10-10 12:45
Transferring to the Prefect issue which is where we track 2.0 issues.

**Comment by zhen0** [comment] 2022-10-10 12:46
I think there's a UX issue to be investigated here around whether you need to click the save button for parameters on custom runs but whoever takes this on should investigate more fully.

**Comment by EmilRex** [comment] 2022-10-14 20:21
@zhen0 Do you think this is related to #6950?

**Comment by zhen0** [comment] 2022-10-14 20:30
Hmmm not exactly. I haven't replicated this one but I think the issue here is a UX one. The ui correctly doesn't show flow default parameters here but not entering a value means the flow default parameters are used. Entering a value here overrides the flow default parameters and uses the deployment parameters. It's a little confusing for booleans. The parameters table was designed to help with making that clearer but we maybe need to think more about the design here.

**Comment by zhen0** [comment] 2022-10-14 20:33
For #6950 again I haven't replicated it but from the ticket I think there's also a UX issue - it's really hard for the ui to know if it should take what it sees as an empty string vs a properly null value.

**Comment by madkinsz** [comment] 2022-10-14 20:38
Possible UX solution: Can you change the display of the textbox contents so (with a string as an example) that when you leave the box it shows the quotes around your text? This way empty text would show `""`. Then you could include a "X" to clear the contents (for fields that are nullable) which would change it from `""` to `null`.

**Comment by zhen0** [comment] 2022-10-14 20:45
Actually - see my comment on #6950 - I can't replicate either. 🤨

**Comment by WillRaphaelson** [comment] 2023-08-31 15:55
Thanks for the issue, going to retool this a little. Toggles are unfortunately not great for booleans especially when the parameter is optional (which position should the toggle be if the parameter is not set?) Ideally we cover the following scenarios in the following ways.

- boolean parameter is required, no default: form gets radio buttons true and false, none selected, need to select to submit form.
- boolean parameter required, default is provided: form gets toggle, set to the default that's provided
- boolean parameter not required, no default is provided : form gets radio buttons true and false, none selected, do not need to select to submit form.
- boolean parameter not required, no default is provided: form gets radio buttons with default selected. can unselect and still submit form.

**Comment by znicholasbrown** [comment] 2023-09-14 15:46
Added a needs eng feedback label to this as the issue is fairly stale and might no longer apply; we'll investigate this as we tackle schemas more broadly

**Comment by pleek91** [comment] 2024-02-28 17:12
@j-tr this is working correctly now in our new enhanced deployment parameters ui which is available in cloud and will soon be available in open source. 

## Experiment 1
Parameters appear with correct values when form is rendered
![Image](https://github.com/PrefectHQ/prefect/assets/6200442/88b18ff9-256a-486a-8a80-8bab48bd27ba)

Submitting the form without touching the toggles submits run with correct default values
![Image](https://github.com/PrefectHQ/prefect/assets/6200442/2dbda9fa-36e7-43dd-baf6-eff12d4476e9)

## Experiment 2
Same result, the value shown to the user by the toggle is the same value that is submitted for the run. 

@WillRaphaelson we've also accounted for optional values that are not required by allowing users to select "Omit value" for any optional value. So if a boolean is optional it can be omitted completely

![Image](https://github.com/PrefectHQ/prefect/assets/6200442/326e04b4-00bc-4206-bbc4-089452d49e16)

**Comment by discdiver** [comment] 2024-03-05 19:33
Iin Cloud today in a deployment run with a required boolean param with no default value. The toggle appears to be toggled to False, but it fails validation (because it’s None presumably). That would likely surprise users.

Goes with @WillRaphaelson's suggested solution for point one above: - boolean parameter is required, no default: form gets radio buttons true and false, none selected, need to select to submit form.

**Comment by martin-schulze-e2m** [comment] 2024-03-15 12:42
Is this really closed for the case `bool | None = None`?

We are seeing problems with the new UI where there is a toggle for this and it now has the default value `False`. This worked with the old UI.

**Comment by pleek91** [comment] 2024-03-15 15:20
@discdiver thanks for bringing that up. We had a few related reports about that as well. Fixed by
https://github.com/PrefectHQ/prefect-ui-library/pull/2202 and https://github.com/PrefectHQ/prefect-ui-library/pull/2180

@martin-schulze-e2m thanks for commenting on this issue. Can you confirm for me if you're using pydantic v1 or v2? There is a long [standing issue in v1](https://github.com/pydantic/pydantic/issues/1270) where `None` basically gets removed from the generated schemas. We've tried to do some patching on our end but there are still some cases we haven't been able to account for. 

Pydantic v2 produces a correct schema for this and when I test your snippet I get this for the form. Let's me pick a boolean or `None` and correctly defaults to `None`
<img width="363" alt="image" src="https://github.com/PrefectHQ/prefect/assets/6200442/83bdc70f-ad48-41b7-9e7c-534283ca06e3">

> Furthermore, a simple parameter: bool just defaults to a toggle with value false even if nothing has been set.

That is the expected behavior for `value: bool` where no default value is set. The toggle defaults to `false` and if you submit `false` will be submitted for the parameter's value. 

A couple things that might help are the "Use JSON Input" and "Omit Value" options on the fields menu on the right. If you want to use `None` for a value you can select use json input and enter `null` for the json value. And if the parameter is optional you can select omit value and it won't submit a value for that parameter at all which will allow the run time default to be used instead. 

<img width="928" alt="image" src="https://github.com/PrefectHQ/prefect/assets/6200442/ce3d471c-b306-487a-b7c1-20f731af7700">

**Comment by pleek91** [comment] 2024-03-19 16:15
@martin-schulze-e2m thanks for the feedback. If you want users running flows from the ui to specifically make a choice between two values I'd recommend using an enum with true and false as the values rather than a plain `bool`. That way users will be presented with a dropdown that has no default value and if they do not select a value they'll receive a validation error.

**Closed** 2024-03-21 16:22 UTC
Labels: bug, status:accepted, ui
