### ISSUE TITLE
Automation error related to state change triggered from cloud UI

### ISSUE THREAD

**Issue by jbnitorum** [PrefectHQ/prefect#6023] opened 2022-07-18 18:55 UTC
## Description
We have an automation set to run for various flow state changes where the default json payload is posted to an outside API.  This works flawlessly when states change through the normal course of running a flow.  However, when we manually change the state of a flow using the UI.  (i.e. take a flow in a failed state and set its state to 'Cancelled') we get an error in the notification center 

![image](https://user-images.githubusercontent.com/9852181/179582543-f696f151-4865-4d73-8c78-9ba01d7cd3e6.png)

When we check our API we see that no request was made.  This error is occurring somewhere in cloud from the time the state is changed via the 'Set State' button in the UI and when the automation posts to our API.

**Comment by jbnitorum** [comment] 2022-07-25 19:48
This is set up as an automation and not a legacy webhook.  The action was set up with the GraphQL API so that we could include a header with the webhook request.

**Comment by jbnitorum** [comment] 2022-08-12 12:41
We experienced another error here as well.  In this instance we had some flow runs that we unable to start the flow at all due to an import error.  So the flow code never even loads.  It's instances such as this that we found the cloud notifications most useful.  Any error handling in the flow would never catch this because it never actually loads.  However, given that cloud notifications continue to have issues we got no notification of the errors.  Can you please address this:

![image](https://user-images.githubusercontent.com/9852181/184355939-028d01b7-9052-460f-a6b5-84d91468575d.png)

**Comment by madkinsz** [comment] 2022-08-12 16:59
@zangell44 would you have any time to retrieve some more information about the exception that's being raised? I can probably fix the webhook action.

**Comment by zangell44** [comment] 2022-08-12 17:04
Yeah - based on the notification message, this looks like the first error is occurring because the payload or headers contain an "invalid control character". https://stackoverflow.com/questions/22394235/invalid-control-character-with-python-json-loads. I don't think it's coming from the action config itself though, maybe the event payload?

I'll keep digging on this. It seems likely the second message is a similar issue.

**Comment by jbnitorum** [comment] 2022-08-12 17:47
Since the headers are the same for all instances of the action I don’t think that would be the case.  We are only seeing this error when it comes as a result of a flow being cancelled using the UI or when a flow fails before it is able to load the flow code at all.  Normal state changes also trigger this action and cause no issues.  As for the payload that certainly could be the case but are just sending the default payload, we haven’t configured anything custom.  Since the error occurs before invoking the webhook there isn’t a way (that I know of) for use to view/validate the payload.

**Comment by madkinsz** [comment] 2022-08-12 21:37
We've determined the cause and a fix has been merged. We'll close the issue when it is deployed.

**Comment by jbnitorum** [comment] 2022-08-16 18:23
Ok great, when can I expect it to be deployed?

**Comment by madkinsz** [comment] 2022-12-05 22:23
I believe this addressed, if not please reach out to our support team and we will investigate further.

**Closed** 2022-12-05 22:22 UTC
Labels: component:cloud, v1, priority:high, status:in-progress

**Comment by jbnitorum** [comment] 2022-12-07 19:39
This has not been fixed.
