### ISSUE TITLE
All workers hang if using prefect-ray 0.4.0 with Python 3.12 on Mac, exclude or surface error

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#15587] opened 2024-10-04 14:04 UTC
### Bug summary

All workers, of any type, hang when trying to connect to Cloud or server if using `prefect-ray` 0.4.0 with Python 3.12 on Mac. Tested with several Prefect 3.0 versions.

This issue goes away if you upgrade to `prefect-ray` to 0.4.2 (latest version as of this report).

In the docs, we warn people that Ray's Python 3.12 support is an issue, but breaking all worker processes silently is rough.

Maybe we could handle an incompatible integration with a more helpful error.

### Version info (`prefect version` output)

```Text
Version:             3.0.4
API version:         0.8.4
Python version:      3.12.2
Git commit:          c068d7e2
Built:               Tue, Oct 1, 2024 11:54
AM
OS/Arch:             darwin/arm64
Profile:             sandbox-jeff
Server type:         cloud
Pydantic version:    2.8.2
Integrations:
  prefect-dbt:       0.6.1
  prefect-bitbucket: 0.3.0
  prefect-kubernetes: 0.5.0
  prefect-snowflake: 0.28.0
  prefect-slack:     0.3.0
  prefect-email:     0.4.0
  prefect-ray:       0.4.0  # fails, works if upgrade to 0.4.2
  prefect-aws:       0.5.0
  prefect-databricks: 0.3.0
  prefect-gcp:       0.6.1
  prefect-azure:     0.4.0
  prefect-sqlalchemy: 0.5.0
  prefect-shell:     0.3.0
  prefect-gitlab:    0.3.0
  prefect-dask:      0.3.1
  prefect-github:    0.3.0
```

### Additional context

This issue was tricky to resolve. The debug logs don't move beyond the following.

```bash
prefect worker start -p pp --with-healthcheck 
09:29:22.333 | DEBUG   | prefect.profiles - Using profile 'sandbox-jeff'
09:29:22.458 | DEBUG   | prefect.client - Connecting to API at https://api.prefect.cloud/api/accounts/9b649228-0419-40e1-9e0d-44954b5c0ab6/workspaces/d137367a-5055-44ff-b91c-6f7366c9e4c4/
09:29:23.519 | DEBUG   | prefect.client - Connecting to API at https://api.prefect.cloud/api/accounts/9b649228-0419-40e1-9e0d-44954b5c0ab6/workspaces/d137367a-5055-44ff-b91c-6f7366c9e4c4/
09:29:23.833 | DEBUG   | prefect.client - Connecting to API at https://api.prefect.cloud/api/accounts/9b649228-0419-40e1-9e0d-44954b5c0ab6/workspaces/d137367a-5055-44ff-b91c-6f7366c9e4c4/
Discovered type 'process' for work pool 'pp'.
```

**Comment by desertaxle** [comment] 2024-10-04 21:20
I suspect this has the same root cause as https://github.com/PrefectHQ/prefect/issues/14955. I'm going to close since it has already been fixed by https://github.com/PrefectHQ/prefect/pull/15392. For future readers, the resolution for this issue is to upgrade to `prefect-ray>=0.4.1`.

**Closed by desertaxle** 2024-10-04 21:20 UTC
Labels: bug
