### ISSUE TITLE
Prefect Tasks do not seem to cache when invoked in a map

### ISSUE THREAD

**Issue by jlewis91** [PrefectHQ/prefect#1067] opened 2019-05-23 13:33 UTC
Hi,

Trying to get the Prefect cache to work for a mapped task. It seems like the tasks are correctly cached, but something about the function signature prevents the cache from correctly being recalled. New to prefect, so definitely may just be operator error...

```
from prefect import Flow, task
from prefect.schedules import IntervalSchedule
import pendulum
from prefect.engine.cache_validators import all_inputs
import time

# Define flow run frequency
refresh_schedule = IntervalSchedule(
    start_date=pendulum.parse("2019-01-01"),
    interval=pendulum.duration(minutes=1)
)



@task
def a():
    return [1,2]

@task(
    cache_for=pendulum.duration(hours=1),
    cache_validator=all_inputs)
def b(a):
    time.sleep(2.5)
    
    

with Flow("test_flow", schedule=refresh_schedule) as test_flow:
    z = a()
    b.map(a=z)


test_flow.run()
```

**Comment by joshmeek** [comment] 2019-05-23 14:02
Hey @jlewis91! What is the output / behavior you are expecting to happen? I just edited the example from https://docs.prefect.io/guide/examples/cached_task.html to use mapping and an `all_inputs` cache validator. I believe that the desired behavior of this type of caching is to cache the outputs of tasks https://github.com/PrefectHQ/prefect/blob/master/src/prefect/engine/cache_validators.py#L2 which may mean that you want to move your `@task` cache specifications to the `a()` task since the `b()` task has no output.

Cache attached to the printing function (similar to your provided snippet):
```python
import datetime
import random

from prefect import task, Flow
from prefect.schedules import IntervalSchedule
from prefect.engine.cache_validators import all_inputs


@task
def return_random_number():
    return [random.random(), random.random()]


@task(cache_for=datetime.timedelta(minutes=1, seconds=30), cache_validator=all_inputs)
def print_number(num):
    print("=" * 50)
    print("Value: {}".format(num))
    print("=" * 50)


schedule = IntervalSchedule(
    start_date=datetime.datetime.utcnow(), interval=datetime.timedelta(minutes=1)
)


with Flow("cached-task", schedule=schedule) as flow:
    print_number.map(num=return_random_number)


flow.run()

# Output
==================================================
Value: 0.5936466140541883
==================================================
==================================================
Value: 0.1186081317628308
==================================================
==================================================
Value: 0.018668753898761437
==================================================
==================================================
Value: 0.6501630260095527
==================================================
==================================================
Value: 0.002431539493655821
==================================================
==================================================
Value: 0.8617373816025835
==================================================
```


Cache attached to the first task which actually outputs something:
```python
import datetime
import random

from prefect import task, Flow
from prefect.schedules import IntervalSchedule
from prefect.engine.cache_validators import all_inputs


@task(cache_for=datetime.timedelta(minutes=1, seconds=30), cache_validator=all_inputs)
def return_random_number():
    return [random.random(), random.random()]


@task
def print_number(num):
    print("=" * 50)
    print("Value: {}".format(num))
    print("=" * 50)


schedule = IntervalSchedule(
    start_date=datetime.datetime.utcnow(), interval=datetime.timedelta(minutes=1)
)


with Flow("cached-task", schedule=schedule) as flow:
    print_number.map(num=return_random_number)


flow.run()

# Output
==================================================
Value: 0.10814516419129827
==================================================
==================================================
Value: 0.35544069451439086
==================================================
==================================================
Value: 0.35544069451439086
==================================================
==================================================
Value: 0.10814516419129827
==================================================
==================================================
Value: 0.8859987369594939
==================================================
==================================================
Value: 0.4163279518380276
==================================================
```

On https://docs.prefect.io/guide/core_concepts/execution.html#caching it notes that input caching happens when Prefect determines that the task will need to be run in the future and in this example it is a flow running on a schedule which finishes successfully so there are no retries or `manual_only` triggers set.

**Comment by cicdw** [comment] 2019-05-23 14:55
@jlewis91 thanks for the bug report!  I am able to reproduce locally.

@joshmeek caching stores the outputs, but it also ensures that the task won't run again if the cache is still valid.  So in the example that @jlewis91 provided, if you add some print statements to the `b` task you'll see that it still runs the second time, when in fact it should not.

**Comment by jlewis91** [comment] 2019-05-23 15:12
Great! Looking forward to a fix, love the lib. And thanks for the quick response!! 😄

**Comment by cicdw** [comment] 2019-05-24 00:16
@jlewis91 great bug find and thanks for the reproducible example!  I've got a fix in at #1071, so once it's merged you can work off the master branch to avoid this bug, or wait until next week when we cut a new release which will include the fix.

**Comment by jlewis91** [comment] 2019-05-24 08:21
Awesome. Thanks!

**Comment by jlewis91** [comment] 2019-05-24 09:43
Just read your PR, was curious to see what changes you needed to make. As part of going through the code, I saw a couple of changes that might improve readability / take advantage of the `any` short-circuiting in python. Please let me know what you think. 😃  https://github.com/PrefectHQ/prefect/pull/1072

**Closed** 2019-05-24 17:44 UTC
Labels: bug
