### ISSUE TITLE
Support for composite tasks

### ISSUE THREAD

**Issue by eric-czech** [PrefectHQ/prefect#2694] opened 2020-06-01 21:22 UTC
## Current behavior

Currently, it appears there is no way to compose tasks.

## Proposed behavior

I think this is a good example of where composite tasks would be useful:

```python
@task
def read_table(path):
  ... # Load some tabular data structure

@task 
def get_merged_tables(path1, path2):
  t1 = read_table(path1)
  t2 = read_table(path2)
  return t1.join(t2)
```

Both `read_csv` and `get_merged_tables` are useful tasks on their own in this case, likely called individually from several different places in a pipeline.  Is there a better workaround than the following or anything on the roadmap to this end?

```python
def _read_table(path):
  ...

@task 
def read_table(path):
  return _read_table(path)

@task 
def get_merged_tables(path1, path2):
  t1 = _read_table(path1)
  t2 = _read_table(path2)
  return t1.join(t2)
```

**Comment by cicdw** [comment] 2020-06-01 21:40
Hi @eric-czech you can merge tasks by calling their `run` method directly:

```python
@task 
def get_merged_tables(path1, path2):
  t1 = read_table.run(path1)
  t2 = read_table.run(path2)
  return t1.join(t2)
```

**Comment by eric-czech** [comment] 2020-06-05 15:47
Makes sense, thanks @cicdw.  Is there any way for Prefect to maintain knowledge of task nesting?  I'm assuming it's lost in that case.  More specifically, I liked that it was possible to capture/monitor that kind of organization in [Dagster Composite Solids](https://docs.dagster.io/docs/tutorial/advanced#composite-solids).  Has this feature been requested before?

**Comment by cicdw** [comment] 2020-06-05 19:34
Being a Prefect Task is a binary thing - either Prefect manages the execution (retries, etc.) or it doesn't.  I don't see any _engineering_ benefit to a nested task construct.  Introducing a new data model that lives in between a Flow and Task has a lot of complexity risk (as [Airflow learned the hard way](https://www.mail-archive.com/dev@airflow.apache.org/msg00818.html)).  We'd need to answer questions like can the parent task be retried and will it refresh all the subtask states? etc.

That being said, we did some user research and from our user group we _do_ understand that people want the ability to organize / group tasks in the UI so we are prioritizing work that will allow users to expand / collapse pieces of their DAG based on task tags. 

I'm curious if you have a use case in mind other than what I've described here though!

**Comment by jcrist** [comment] 2020-06-09 19:29
Using your top example:

```python
@task
def read_table(path):
  ... # Load some tabular data structure

@task 
def get_merged_tables(path1, path2):
  t1 = read_table(path1)
  t2 = read_table(path2)
  return t1.join(t2)
```

If this were to be equivalent to the existing strategy of:

```python
@task
def read_table(path):
  ... # Load some tabular data structure

@task 
def get_merged_tables(path1, path2):
  t1 = read_table.run(path1)
  t2 = read_table.run(path2)
  return t1.join(t2)
```

would that solve your problem? I'm not saying we'd do this for sure (this is doable though), I'm more curious if the issue is that you want to be able to call decorated tasks from inside other tasks, or that you want a nested dag structure (so the nested `read_table` calls would also show up in prefect's ui as some kind of sub-task). Does that make sense?

**Comment by jcrist** [comment] 2020-07-16 20:24
Got it. We're tracking "subflows" (what we're calling this kind of feature) in #1745, you can follow along there to see the conversation. Closing.

**Closed by jcrist** 2020-07-16 20:24 UTC
Labels: enhancement
