### ISSUE TITLE
Logs don't propagate from worker

### ISSUE THREAD

**Issue by taranlu-houzz** [PrefectHQ/prefect#14657] opened 2024-07-18 00:34 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When using a logger, the log messages do not show up in the worker logs or the web ui if the deployment is run via a work pool. When run directly via the cli, the logs show up as expected.

### Reproduction
Just slightly modified the flow from the quickstart tutorial.
```python3
import httpx  # an HTTP client library and dependency of Prefect

from prefect import (
    flow,
    task,
)
from prefect.logging import get_run_logger


@task(retries=2)
def get_repo_info(repo_owner: str, repo_name: str):
    """Get info about a repo - will retry twice after failing"""
    logger = get_run_logger()
    logger.error("get_repo_info task started")
    url = f"https://api.github.com/repos/{repo_owner}/{repo_name}"
    api_response = httpx.get(url)
    api_response.raise_for_status()
    repo_info = api_response.json()
    logger.error("get_repo_info task completed")
    return repo_info


@task
def get_contributors(repo_info: dict):
    """Get contributors for a repo"""
    logger = get_run_logger()
    logger.info("get_contributors task started")
    contributors_url = repo_info["contributors_url"]
    response = httpx.get(contributors_url)
    response.raise_for_status()
    contributors = response.json()
    logger.info("get_contributors task completed")
    return contributors


@flow(log_prints=True)
def repo_info(repo_owner: str = "PrefectHQ", repo_name: str = "prefect"):
    """
    Given a GitHub repository, logs the number of stargazers
    and contributors for that repo.
    """
    logger = get_run_logger()
    logger.error("repo_info flow started")
    repo_info = get_repo_info(repo_owner, repo_name)
    print(f"Stars 🌠 : {repo_info['stargazers_count']}")

    contributors = get_contributors(repo_info)
    print(f"Number of contributors 👷: {len(contributors)}")


if __name__ == "__main__":
    repo_info()
```

### Versions (`prefect version` output)

```Text
Version:             3.0.0rc10
API version:         0.8.4
Python version:      3.12.3
Git commit:          200cf212
Built:               Wed, Jul 3, 2024 1:39 PM
OS/Arch:             darwin/arm64
Profile:             tl_test
Server type:         server
Pydantic version:    2.8.2
```

**Comment by zhen0** [comment] 2024-07-18 13:35
Thanks for the issue @taranlu-houzz

**Comment by zhen0** [comment] 2024-07-18 15:57
With a more basic flow I'm unable to reproduce.  Let me try with your example. 

![Image](https://github.com/user-attachments/assets/4bb30176-430b-44cd-832f-560b78e87e08)

**Comment by taranlu-houzz** [comment] 2024-07-18 17:57
@zhen0 Hey, thanks for helping to look into this. Could you post the basic flow that you used so that I can sanity check to see if it has the same issue when I try to run it?

**Comment by zhen0** [comment] 2024-07-18 20:09
Actually I tried with your flow on 3.0.0rc11 @taranlu-houzz and I can't reproduce there either 🤔 

Here's what I see in the UI:

![Image](https://github.com/user-attachments/assets/d677dc17-2072-4e92-b027-422505ee9aa1)


And the worker logs:

![Image](https://github.com/user-attachments/assets/84b9dab2-e209-4ca5-9147-7416b132323b)

Could you see if you have the same issues on 3.0.0rc11?  And also any other info you can provide would be helpful - what type of work pool are you using?  (I tried with a process worker) and are you running the OSS server or is this in Cloud?

**Comment by taranlu-houzz** [comment] 2024-07-18 22:01
I just tested using `3.0.0rc11` and unfortunately am still not getting the logs. Here is some more info about my setup:
- Tested running the OSS server locally and in a Docker container (x86-64 container).
  - In both cases, `prefect` is installed into a `venv`
- The worker is a process worker
- I tried messing with the logging level env vars, but setting them to `DEBUG` did not cause the missing logs to show up.

**Comment by taranlu-houzz** [comment] 2024-07-18 22:16
Here is an example of what I am seeing when I run things locally:

<details>
  <summary>Server Command and Output</summary>
  
```
❯ pdm run prefect server start

 ___ ___ ___ ___ ___ ___ _____
| _ \ _ \ __| __| __/ __|_   _|
|  _/   / _|| _|| _| (__  | |
|_| |_|_\___|_| |___\___| |_|

Configure Prefect to communicate with the server with:

    prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api

View the API reference documentation at http://127.0.0.1:4200/docs

Check out the dashboard at http://127.0.0.1:4200
```
  
</details>

<details>
  <summary>Worker Command and Output</summary>

```
❯ pdm run prefect worker start --pool my-work-pool
Discovered type 'process' for work pool 'my-work-pool'.
Worker 'ProcessWorker 75cb2a30-08b5-44fe-b340-9fe98fc06596' started!
15:13:59.576 | INFO    | prefect.flow_runs.worker - Worker 'ProcessWorker 75cb2a30-08b5-44fe-b340-9fe98fc06596' submitting flow run '1c45010a-6c8d-4e50-a2a3-34bb3500585
e'
15:13:59.648 | INFO    | prefect.flow_runs.worker - Opening process...
15:13:59.664 | INFO    | prefect.flow_runs.worker - Completed submission of flow run '1c45010a-6c8d-4e50-a2a3-34bb3500585e'
15:14:01.519 | INFO    | prefect.deployment - Cloned repository 'https://github.com/prefecthq/demos.git' into 'demos'
15:14:01.652 | INFO    | Task run 'get_repo_info-0' - Created task run 'get_repo_info-0' for task 'get_repo_info'
15:14:02.182 | INFO    | Task run 'get_repo_info-0' - Finished in state Completed()
15:14:02.183 | INFO    | Flow run 'loyal-hyrax' - Stars 🌠 : 15437
15:14:02.214 | INFO    | Task run 'get_contributors-0' - Created task run 'get_contributors-0' for task 'get_contributors'
15:14:02.866 | INFO    | Task run 'get_contributors-0' - Finished in state Completed()
15:14:02.867 | INFO    | Flow run 'loyal-hyrax' - Number of contributors 👷: 30
15:14:02.883 | INFO    | Flow run 'loyal-hyrax' - Finished in state Completed()
 > Running git_clone step...
15:14:03.073 | INFO    | prefect.flow_runs.worker - Process 24496 exited cleanly.
```

</details>

<details>
  <summary>Run the flow directly</summary>

```
❯ pdm run python my_gh_workflow.py
15:08:35.949 | INFO    | prefect.engine - Created flow run 'tireless-sambar' for flow 'repo-info'
15:08:35.950 | INFO    | prefect.engine - View at http://127.0.0.1:4200/runs/flow-run/db839ca2-6c7a-43d0-b1c0-e4b2aa526f15
15:08:35.974 | ERROR   | Flow run 'tireless-sambar' - repo_info flow started
15:08:36.011 | INFO    | Task run 'get_repo_info-0' - Created task run 'get_repo_info-0' for task 'get_repo_info'
15:08:36.037 | ERROR   | Task run 'get_repo_info-0' - get_repo_info task started
15:08:36.323 | ERROR   | Task run 'get_repo_info-0' - get_repo_info task completed
15:08:36.351 | INFO    | Task run 'get_repo_info-0' - Finished in state Completed()
15:08:36.352 | INFO    | Flow run 'tireless-sambar' - Stars 🌠 : 15437
15:08:36.383 | INFO    | Task run 'get_contributors-0' - Created task run 'get_contributors-0' for task 'get_contributors'
15:08:36.411 | INFO    | Task run 'get_contributors-0' - get_contributors task started
15:08:36.814 | INFO    | Task run 'get_contributors-0' - get_contributors task completed
15:08:36.846 | INFO    | Task run 'get_contributors-0' - Finished in state Completed()
15:08:36.847 | INFO    | Flow run 'tireless-sambar' - Number of contributors 👷: 30
15:08:36.869 | INFO    | Flow run 'tireless-sambar' - Finished in state Completed()
```

</details>

**Comment by zhen0** [comment] 2024-07-19 14:21
That is odd.  I don't see anything immediately from your set-up that would cause that to happen.

**Comment by zhen0** [comment] 2024-07-19 14:22
I'm going to leave this issue open to see if others come across the same thing or if we can get any more ideas about what might cause this. Thanks.

**Comment by taranlu-houzz** [comment] 2024-07-23 20:56
@zhen0 Turns out this was my mistake. The script that I was using to create the deployment was the unaltered one from the quickstart tutorial:
```python
from prefect import flow

# Source for the code to deploy (here, a GitHub repo)
SOURCE_REPO="https://github.com/prefecthq/demos.git"

if __name__ == "__main__":
    flow.from_source(
        source=SOURCE_REPO,
        entrypoint="my_gh_workflow.py:repo_info", # Specific flow to run
    ).deploy(
        name="my-first-deployment",
        work_pool_name="my-work-pool", # Work pool target
        cron="0 1 * * *", # Cron schedule (1am every day)
    )
```
So it was running the unmodified version from the source repo when I would run that script to register the deployment, but when running the flow locally, I was running the updated version.

I do have a quick followup question: I changed the `create_depolyment.py` script to just use my flow directly, but it seems that it does not allow using the `.deploy()` method without using docker related params (e.g. `build`). Is it possible to create a deployment for a local flow, and have that deployment set to run using a worker pool (`process` worker) to do things like manage concurrency? Or is that not a supported use case?

Regardless, thank you for the help!

**Comment by zhen0** [comment] 2024-07-23 22:05
Oh I'm glad you got it figured out! You should be able to use deploy with a process work pool. I'm afraid I don't see it well documented but the relevant PR is here: https://github.com/PrefectHQ/prefect/pull/12017

I'm also a fan of using the `prefect deploy` cli command.

**Comment by zhen0** [comment] 2024-07-23 22:05
I'm going to close this issue but do feel free to pen a new one if you run into other issues.

**Closed** 2024-07-23 22:05 UTC
Labels: bug, 3.x
