### ISSUE TITLE
Parameters erroneously considered optional

### ISSUE THREAD

**Issue by 3XJuli** [PrefectHQ/prefect#9055] opened 2023-04-04 13:56 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

Pydantic class with only optional parameters is considered optional, even though it is not optional.

When deploying a flow that takes a pydantic-class with only optional/default parameters, the UI erroneously passes no parameters at all. This causes an error when the flow is run.

This is problematic especially with flags: I can not use a flow that only has a flag with default-value. 

Might be related to https://github.com/PrefectHQ/prefect/issues/9018 - There however, the entire flow-parameter was optional, so I am not sure if it's related (sorry, if it is a duplicate!)

### Reproduction

```python from prefect import flow, get_run_logger
from pydantic import Field, BaseModel


class SingleParameter(BaseModel):
    flag: bool = Field(
        default=False,
    )
    test: int = 1


@flow(name="Flow")
def some_flow(params: SingleParameter):
    get_run_logger().info(params)


if __name__ == "__main__":
    params = SingleParameter()
    some_flow(params=params)
    params = SingleParameter(flag=True)
    some_flow(params=params)
```

Deployed using:
```
prefect deployment build file.py:some_flow -n some_flow 
prefect deployment apply some_flow-deployment.yaml 
```

Screenshot of the Run-Configuration using Run -> Quick run:
![image](https://user-images.githubusercontent.com/45656848/229812779-4ddfd06c-64ff-4b3c-b579-829344f28b36.png)

Screenshot of Params of Flow Run: 
![image](https://user-images.githubusercontent.com/45656848/229813830-21ddcced-250d-49d0-8bcb-f9a209059b60.png)

### Error

![image](https://user-images.githubusercontent.com/45656848/229813662-14d8ead4-77b1-4991-b3ac-2a57a26fcc0d.png)

### Browers

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.8.6
API version:         0.8.4
Python version:      3.10.6
Git commit:          061d877b
Built:               Thu, Mar 16, 2023 2:58 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```

**Comment by znicholasbrown** [comment] 2023-04-07 16:48
Thanks for the report @3XJuli - I can confirm this is an issue; I'm seeing the `params` field populated in the required list of the schema here so we'll need to investigate why it's being marked as optional. I'm not sure if those subfields should also be optional or not, since one has a default and the other does not but neither show up required in the schema... it may be that we need to tackle that separately. 

Will use this as the tracking ticket so updates will get posted here.

**Closed** 2023-04-10 16:42 UTC
Labels: bug, ui, priority:high, team:orchestration

**Comment by pleek91** [comment] 2023-04-10 16:43
Fix for this was merged to the prefect-ui-library. Will go out with the next release
