### ISSUE TITLE
Codecov reports have unexpectedly stopped

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#1132] opened 2019-06-11 05:13 UTC
It appears that ~7 days ago, our codecov reports just ...stopped working.  Even when I ssh into a CircleCI job and manually run pytest + use the bash uploader, the report says it has issues (but doesn't identify what those issues might be).

Our codecov badge now says "unknown", so I'd like to get this resolved.

PRs in which I unsuccessfully attempted some changes:
- https://github.com/PrefectHQ/prefect/pull/1130
- https://github.com/PrefectHQ/prefect/pull/1131

**Comment by jlowin** [comment] 2019-06-11 11:53
@zangell44 this might have confounded your efforts in #1104

**Comment by zangell44** [comment] 2019-06-11 17:19
@jlowin I have a bad feeling I may have caused this by messing with the `codecov.yml` file.

The last PR where codecov was working correctly was [#1114](https://github.com/PrefectHQ/prefect/pull/1114), Jun 6 at 10:19 am. 

I made a [commit](https://github.com/PrefectHQ/prefect/pull/1104/commits/72b773c2fef62c159172f4f2043c42f658dd3320) that specified several flags in the codecov file. Jun 6 at 11:08 am. 

It seems like all PRs after that starting with [#1116](https://github.com/PrefectHQ/prefect/pull/1116), Jun 6 at 6:14 pm started to have issues.

I was having trouble getting codecov to comment at all starting about this time, but I thought it was the changes on my branch.

I went ahead and emailed codecov support to see if this could have broken something/if they have any recommendations to resolve the issue.

**Comment by cicdw** [comment] 2019-06-11 17:37
Thanks for contacting support @zangell44 ! Let us know if they respond. 

While I agree the timing is suspicious, I'd be really surprised if your temporary codecov edits permanently affected the bot somehow.  I can actually see what codecov thinks our current yaml settings are in our team settings, and this is what it shows:
```
{
    "codecov": {
        "require_ci_to_pass": true
    }, 
    "comment": {
        "behavior": "default", 
        "branches": null, 
        "layout": "header", 
        "require_base": false, 
        "require_changes": false, 
        "require_head": true
    }, 
    "coverage": {
        "precision": 2, 
        "range": [
            70.0, 
            100.0
        ], 
        "round": "down", 
        "status": {
            "changes": false, 
            "patch": false, 
            "project": {
                "default": {
                    "target": 92.0, 
                    "threshold": 1.0
                }
            }
        }
    }, 
    "parsers": {
        "gcov": {
            "branch_detection": {
                "conditional": true, 
                "loop": true, 
                "macro": false, 
                "method": false
            }
        }, 
        "javascript": {
            "enable_partials": false
        }
    }
}
```

**Comment by zangell44** [comment] 2019-06-11 18:45
That is certainly a relief to see 😅 , I'll let you know if they reply to my email

**Comment by jlowin** [comment] 2019-06-11 18:56
@zangell44 yeah, I expect this is coincidental, I just wanted to point it out in case your work had actually been productive but this issue shadowed it.

**Comment by cicdw** [comment] 2019-06-12 04:29
Reason to believe this isn't just us:
- https://github.com/codecov/codecov-bash/issues/176

**Comment by zangell44** [comment] 2019-06-12 17:46
Codecov got back to me with a generic email about "best-effort" support, probably won't get much from them unless Prefect is a paying customer.

Saw [this post](https://community.codecov.io/t/coverage-reports-uploaded-successfully-by-travis-but-not-showing-in-codecov/259) on their community forums, looks like there was a bug in codecov that might be fixed now.

**Comment by jlowin** [comment] 2019-06-12 18:14
Customer service: /shrug

I have been debugging these reports by hand and I think the issue is that Codecov isn't parsing the full filepaths anymore - for example `.../.../python/site-packages/prefect/engine/task_runner.py` vs `prefect/engine/task_runner.py`. THe former is generated by CircleCI (off the installed package), and the latter is what I get locally (off an editable package). I can upload the latter by hand; the former fails. So I think maybe the filepath parsing failed; Codecov says they do work to map the filepaths to the git paths.

**Closed** 2019-06-13 23:52 UTC
Labels: bug, help wanted
