### ISSUE TITLE
After Deleting Notifications in the UI the page auto-refresh to show the correct notification was deleted

### ISSUE THREAD

**Issue by teherin** [PrefectHQ/prefect#7487] opened 2022-11-10 15:54 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When deleting a notification from the notifications page the LAST notification row is aways shown as deleted in the UI. If the page is _manually_ refreshed the correct notification is shown to be removed

### Reproduction

1. Have 3 different notifications configured - helpful if they are all different methodologies so its easy to keep track of based on the icon
2. Right click the 3 dots menu to delete the FIRST notification
3. On automatic page refresh observe the LAST row is the one that is removed in the UI
4. Manually refresh the page to see the correct (first) notification removed from the list.

### Error

n/a

### Browers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

**Comment by zhen0** [comment] 2022-11-11 19:15
Duplicate of https://github.com/PrefectHQ/prefect/issues/7488

**Closed** 2022-11-15 23:03 UTC
Labels: bug, status:duplicate, ui
