### ISSUE TITLE
docker-compose config/environment variables not present. 

### ISSUE THREAD

**Issue by Jesperrekuh** [PrefectHQ/prefect#3557] opened 2020-10-21 01:01 UTC
## Description
Not able to fire up local prefect server backend / prefect server start
environment variables are not loaded when server.py runs `docker-compose up`

> WARNING: The POSTGRES_DB variable is not set. Defaulting to a blank string.
> WARNING: The POSTGRES_PASSWORD variable is not set. Defaulting to a blank string.
> WARNING: The POSTGRES_USER variable is not set. Defaulting to a blank string.

## Reproduction
No exports in .profile or .bash_rc
clean install on linux Ubuntu 18
pip install prefect
prefect backend server (copied and adjusted backend.toml with git config.toml) 
prefect server start, not able to start postgres , warning 

env vars from config are present in server.py
however subprocess.Popen(... , env=env) not working fires:
docker-compose up

creating a .env file where tmp/docker-compose.yml is placed worked, postgres starts 
however running into new issues graphql not able to connect.

## Environment
Python 3.6.9 (default, Oct  8 2020, 12:12:24)
[GCC 8.4.0] on linux

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

docker-compose version 1.27.4, build 4052419
docker-py version: 4.3.1
CPython version: 3.7.7

Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40

**Comment by madkinsz** [comment] 2020-10-23 15:50
Hi! Just a heads up that I have spent some time trying to reproduce this but it looks like I'd have to get an ubuntu image with docker-in-docker going to do this locally which is quite a bit of effort. I'd suggest trying python 3.7+ in the meantime. Perhaps someone else in the community running ubuntu can investigate this.

**Comment by Jesperrekuh** [comment] 2020-10-24 23:55
Thats odd, are you running on a Mac/Win? 
The environment is passed into the new subprocess, that works, checked it.

Actually, while reading docker docs a .env file need to be used when vars are not passed as compose arguments .
In the cli/server.py added some code to dump the env-vars in a .env file in working dir. Et voila, all good.

[https://docs.docker.com/compose/environment-variables/](url)

**Comment by tx00g** [comment] 2020-10-25 19:39
@Jesperrekuh did you start container successfully?

 I've debugged every part step-by-step including this issue with .env file and error you pulled it this thread. And finally made it almost working - it starts with OK in all logs, UI is working and GraphQL connection link in browser showed successful connection on default 4200 port (http://localhost:4200/graphql), but that's it. Dashboard isn't responding like prefect server wasn't configured yet, creating Agent returns GraphQL error on wrong query... while outside of container it works perfectly.

If you issued same thing - what did you do to make it work in container? Or if you have one working, can you share the image or Dockerfile?

**Comment by Jesperrekuh** [comment] 2020-10-25 20:35
@tx00g , Im still working on it, Im at the part of registering flows. For what Ive understand of `prefect register ... `  the server works only on localhost, but you probably already know. I connect via ssh and tunnel / port forward localhost:8080 and 4200. In my webbrowser I type localhost:8080. (prefect is running on VMWare Ubuntu). 
the `prefect server start` generates a docker-compose.yml file in workdir/tmp, Ive added it below.
 
You could check in your browser(F12) and for errors in console,  so far I've no errors when I tunnel to the ui.

What I would recommend, when all of your config is ok, remove all prefect related docker images, `docker container prune`  next `docker rmi <id> `  , maybe that helps, I believe this is recommended for docker-compose when you adjust yml files some of your changes wont work...  

networks:
  prefect-server:
    name: prefect-server
services:
  apollo:
    command: bash -c "./post-start.sh && npm run serve"
    depends_on:
    - graphql
    environment:
      GRAPHQL_SERVICE_HOST: http://graphql
      GRAPHQL_SERVICE_PORT: ${GRAPHQL_HOST_PORT:-4201}
      HASURA_API_URL: ${HASURA_API_URL:-http://hasura:3000/v1alpha1/graphql}
      PREFECT_API_HEALTH_URL: ${PREFECT_API_HEALTH_URL:-http://graphql:4201/health}
      PREFECT_API_URL: ${PREFECT_API_URL:-http://graphql:4201/graphql/}
      PREFECT_SERVER__TELEMETRY__ENABLED: ${PREFECT_SERVER__TELEMETRY__ENABLED:-true}
    image: prefecthq/apollo:${PREFECT_SERVER_TAG:-latest}
    networks:
    - prefect-server
    ports:
    - ${APOLLO_HOST_PORT:-4200}:4200
    restart: always
  graphql:
    command: bash -c "${PREFECT_SERVER_DB_CMD} && python src/prefect_server/services/graphql/server.py"
    depends_on:
    - hasura
    environment:
      PREFECT_SERVER_DB_CMD: ${PREFECT_SERVER_DB_CMD:-"echo 'DATABASE MIGRATIONS SKIPPED'"}
      PREFECT_SERVER__DATABASE__CONNECTION_URL: ${DB_CONNECTION_URL}
      PREFECT_SERVER__HASURA__ADMIN_SECRET: ${PREFECT_SERVER__HASURA__ADMIN_SECRET:-hasura-secret-admin-secret}
      PREFECT_SERVER__HASURA__HOST: hasura
    image: prefecthq/server:${PREFECT_SERVER_TAG:-latest}
    networks:
    - prefect-server
    ports:
    - ${GRAPHQL_HOST_PORT:-4201}:4201
    restart: always
  hasura:
    command: graphql-engine serve
    depends_on:
    - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${DB_CONNECTION_URL}
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_LOG_LEVEL: warn
      HASURA_GRAPHQL_QUERY_PLAN_CACHE_SIZE: 100
      HASURA_GRAPHQL_SERVER_PORT: '3000'
    image: hasura/graphql-engine:v1.3.0
    networks:
    - prefect-server
    ports:
    - ${HASURA_HOST_PORT:-3000}:3000
    restart: always
  postgres:
    command:
    - postgres
    - -c
    - max_connections=150
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - /tmp/pg_data:/var/lib/postgresql/data
    image: postgres:11
    networks:
    - prefect-server
    ports:
    - ${POSTGRES_HOST_PORT:-5432}:5432
    restart: always
  towel:
    command: python src/prefect_server/services/towel/__main__.py
    depends_on:
    - graphql
    environment:
      PREFECT_SERVER__HASURA__ADMIN_SECRET: ${PREFECT_SERVER__HASURA__ADMIN_SECRET:-hasura-secret-admin-secret}
      PREFECT_SERVER__HASURA__HOST: hasura
    image: prefecthq/server:${PREFECT_SERVER_TAG:-latest}
    networks:
    - prefect-server
    restart: always
  ui:
    command: /intercept.sh
    depends_on:
    - apollo
    environment:
      PREFECT_SERVER__APOLLO_URL: ${APOLLO_URL:-http://localhost:4200/graphql}
    image: prefecthq/ui:${PREFECT_UI_TAG:-latest}
    networks:
    - prefect-server
    ports:
    - ${UI_HOST_PORT:-8080}:8080
    restart: always
version: '3.7'

**Comment by joshmeek** [comment] 2020-10-26 18:00
> Thats odd, are you running on a Mac/Win?
> The environment is passed into the new subprocess, that works, checked it.
> 
> Actually, while reading docker docs a .env file need to be used when vars are not passed as compose arguments .
> In the cli/server.py added some code to dump the env-vars in a .env file in working dir. Et voila, all good.
> 
> [https://docs.docker.com/compose/environment-variables/](url)

@Jesperrekuh will you be able to make a PR for this patch? If not could you outline the steps you took and we can get it fixed for the next release! 🙂

**Comment by madkinsz** [comment] 2020-10-26 23:38
> Thats odd, are you running on a Mac/Win?

I'm running OSX generally but have a second machine running Ubuntu 20

> Actually, while reading docker docs a .env file need to be used when vars are not passed as compose arguments .
> In the cli/server.py added some code to dump the env-vars in a .env file in working dir. Et voila, all good.
> 
> [https://docs.docker.com/compose/environment-variables/](url)

This should not be the only supported case. From the top of the docs you link
> It’s possible to use environment variables in your shell to populate values inside a Compose file:

I can confirm this is working fine with Python 3.6/3.8, docker engine 19.3, and docker-compose 1.25/1.27 on Ubuntu 20.04.1 so perhaps this is an Ubuntu 18 issue. The next step from my end is to spin that Ubuntu environment up and try to reproduce yet again.

**Comment by madkinsz** [comment] 2020-10-27 19:45
After launching Ubuntu 18.04 on GCP I still have no issues starting the server

```
michaeladkins@mz-testing-docker-compose:~/prefect$ docker --version
Docker version 19.03.13, build 4484c46d9d
michaeladkins@mz-testing-docker-compose:~/prefect$ docker-compose --version
docker-compose version 1.27.4, build unknown
michaeladkins@mz-testing-docker-compose:~/prefect$ prefect diagnostics
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.4.0-1028-gcp-x86_64-with-Ubuntu-18.04-bionic",
    "prefect_backend": "server",
    "prefect_version": "0.13.12",
    "python_version": "3.6.9"
  }
}
```

```bash

# Install docker

sudo apt-get update
sudo apt-get install     apt-transport-https     ca-certificates     curl     gnupg-agent     software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
sudo add-apt-repository    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io

# Confirm docker is working
sudo docker run hello-world

# Ensure docker is working without sudo
sudo groupadd docker
sudo usermod -aG docker $USER
groups
docker run hello-world

# Install pip
sudo apt install python3-pip

# Install docker-compose
pip3 install docker-compose

# Clone prefect from git and install
# could just run `pip3 install prefect`
sudo apt-get install git
git clone https://github.com/PrefectHQ/prefect.git
cd prefect/
pip3 install -e .

# Run the server
prefect server start
```

**Comment by Jesperrekuh** [comment] 2020-10-28 00:02
Thanks for sharing this, seems like problems are resolved...  all docker stuff was up to date / newest.

What I've missed:
**-- pip3 install docker-compose**

Could reproduce my errors by uninstalling `pip3 uninstall docker-compose`
And all issues returned.

**-- pip3 install docker-compose**
I think I missed it in the documenation, however it isnt mentioned here [https://docs.prefect.io/core/getting_started/installation.html](url) ?

Again thank you

**Comment by madkinsz** [comment] 2020-10-28 02:37
I'm glad it's working now! 

For reference, I cannot reproduce this on Ubuntu 20 installing docker-compose with apt and only switched to pip to reach the same version as you. On Ubuntu 18 apt installs a docker-compose version that is too old to work with our compose file (and says so when you try). When I install docker-compose following the documentation on the docker website (e.g. via curl `1.27.4, build 40524192`) I also cannot reproduce your issue. My best bet is that you missed installing some of the docker-compose prerequisites and pip took care of those for you? However then it's weird that uninstalling the pip version makes things break again.

The documentation says that docker-compose is required but does not give details on how to install it, instead we link to the [docker installation page](https://docs.docker.com/compose/install/) which lists using `pip` under alternative methods. I believe we do not include it in our python requirements because it tightens the bounds on our other required packages.

**Comment by tx00g** [comment] 2020-10-28 11:04
Installing docker-compose from pip finally made `prefect server start` work in container. But with creating .env file with missing variables and adding it into docker-compose.yml, but that's it.

**Comment by madkinsz** [comment] 2020-10-28 14:41
> Installing docker-compose from pip finally made `prefect server start` work in container. But with creating .env file with missing variables and adding it into docker-compose.yml, but that's it.

Sorry, could you explain that second part again? For Jesperrekuh, pip has solved all their issues and I have not run into a case where a .env file was needed yet.

**Comment by tx00g** [comment] 2020-10-30 15:16
> > Installing docker-compose from pip finally made `prefect server start` work in container. But with creating .env file with missing variables and adding it into docker-compose.yml, but that's it.
> 
> Sorry, could you explain that second part again? For Jesperrekuh, pip has solved all their issues and I have not run into a case where a .env file was needed yet.

For me to make it work (after installing docker-compose via pip3) I added to `docker-compose.yml` for GraphQL and Postgres services `env_file: .env`

.env:
```
PREFECT_SERVER_DB_CMD=echo ""
POSTGRES_DB=prefect_server
POSTGRES_PASSWORD=prefect
POSTGRES_USER=prefect
PGUSER=prefect
PGPASSWORD=prefect
PGDATABASE=prefect_server
DB_CONNECTION_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
```
 
With this setup it worked and from RHEL and from docker container.

**Comment by madkinsz** [comment] 2020-10-30 16:06
> For me to make it work (after installing docker-compose via pip3) I added to `docker-compose.yml` for GraphQL and Postgres services `env_file: .env`
> 
> .env:
> 
> ```
> PREFECT_SERVER_DB_CMD=echo ""
> POSTGRES_DB=prefect_server
> POSTGRES_PASSWORD=prefect
> POSTGRES_USER=prefect
> PGUSER=prefect
> PGPASSWORD=prefect
> PGDATABASE=prefect_server
> DB_CONNECTION_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
> ```
> 
> With this setup it worked and from RHEL and from docker container.

I'm glad you got it working! Since I cannot replicate a situation where a `.env` file is required and we've solved the original issue here I'm going to close this for now. Thanks for your help everyone!

**Closed by madkinsz** 2020-10-30 16:06 UTC
