### ISSUE TITLE
Boolean parameter overriden via deployment can't be overriden from UI

### ISSUE THREAD

**Issue by hateyouinfinity** [PrefectHQ/prefect#7927] opened 2022-12-16 18:56 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Boolean parameter overriden via deployment can't be overriden from UI.

If you
1. Create a flow that has a boolean parameter with a default value set
2. Override that parameter when creating a deployment from that flow
3. Override that parameter (again) when creating a flow run from UI

the override made from UI will be ignored.

**Example:**

See _Reproduction_ for the deployment source code. <br>
Parameters set via deployment override:
![](https://i.imgur.com/0FXabBB.png) <br>
Creating a flow run with custom parameters:
![](https://i.imgur.com/hhfD5V9.png) <br>
Overrides to some of the parameters are ignored:
![](https://i.imgur.com/TrFeUGa.png) ![](https://i.imgur.com/AARgMya.png) <br>

#### Scope

Affected (AFAIU):
- UI overrides to boolean parameters which have a flow-level default value overriden via deployment

Not affected:
- Non-boolean parameters (at least ints and strings, see `descr` above)
- Boolean parameters w/o a flow-level default value (see `bool_no_default` above)
- Overrides done via API

### Reproduction

```python3
import asyncio

from prefect import flow, get_client, get_run_logger
from prefect.deployments import Deployment


@flow(name="overrides")
def flowfunc(
    bool_no_default: bool,
    bool_first: bool = False,
    bool_second: bool = True,
    descr: str = "no overrides (Flow)",
):
    logger = get_run_logger()
    logger.info(
        f"bool_no_default={bool_no_default}\nbool_first={bool_first}\nbool_second={bool_second}\ndescr={descr}"
    )


async def deploy_overrides():
    depl = await Deployment.build_from_flow(
        flow=flowfunc,
        name="overrides",
        parameters={
            "bool_no_default": True,
            "bool_first": True,
            "bool_second": False,
            "descr": "set bool_no_default=True, bool_first=True, bool_second=False (Deployment)",
        },
        apply=True,
    )


async def create_run_with_double_overrides():
    client = get_client()
    depl = await client.read_deployment_by_name(name="overrides/overrides")
    await client.create_flow_run_from_deployment(
        deployment_id=depl.id,
        parameters={
            "bool_no_default": False,
            "bool_first": False,
            "bool_second": True,
            "descr": "set bool_no_default=False, bool_first=False, bool_second=True (API)",
        },
    )


if __name__ == "__main__":
    asyncio.run(deploy_overrides())
```

### Versions

```Text
Version:             2.7.1
API version:         0.8.3
Python version:      3.10.8
Git commit:          33f7de50
Built:               Thu, Dec 8, 2022 4:09 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.34.1
```

**Comment by pleek91** [comment] 2022-12-19 20:26
@hateyouinfinity thanks for the detailed issue. We are looking it a fix for this.

**Comment by paulinjo** [comment] 2023-03-24 20:36
Just noticed the same behaviour in some of my flows, although based on the age of this issue it's been going on for a lot longer than I would have thought.

For my team I'd consider this to be a pretty critical issue. We have a standard parameter in all of our flows that is used for testing to disable writing when set (`dry_run=True`), and it's not possible to have it work as intended with the current behaviour.

**Comment by pleek91** [comment] 2024-03-05 17:42
@hateyouinfinity and @paulinjo this has been address in our new enhanced deployment parameters ui which is available in cloud and will soon be available in oss. Please let me know if you're still having an issue with this using the new ui.

**Closed** 2024-03-12 14:31 UTC
Labels: bug, status:accepted, ui
