### ISSUE TITLE
 Deployment.build_from_flow not working with prefect 2.16.1 getting : "'extra fields not permitted" if apply=True

### ISSUE THREAD

**Issue by fletanoux** [PrefectHQ/prefect#12149] opened 2024-03-04 13:32 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Since upgrading to prefect 2.16.1 (I've skipped 2.16.0) i can no longer deploy my flow with Deployment.build_from_flow.

A parameter was probably removed from the /api/deployment/ route, but is still passed by `create_deployment`

### Reproduction

```python3
from prefect.deployments.deployments import Deployment

Deployment.build_from_flow(
    flow=fn,
    name="flowname",
    apply=True,
)
```

### Error

```python3
Error while deploying fact_bridge_stats: Client error '422 Unprocessable Entity' for url 'http://127.0.0.1:4200/api/deployments/'
Response: {'exception_message': 'Invalid request received.', 'exception_detail': [{'loc': ['body', 'schedules'], 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}], 'request_body': {'name': 'local:fact_bridge_stats', 'flow_id': '45094af8-5c4c-4582-ae4f-e65ef70f31e6', 'schedules': [], 'parameter_openapi_schema': {'title': 'Parameters', 'type': 'object', 'properties': {'start_at': {'title': 'start_at', 'position': 0, 'type': 'string', 'format': 'date-time'}, 'end_at': {'title': 'end_at', 'position': 1, 'type': 'string', 'format': 'date-time'}}}, 'parameters': {}, 'tags': [], 'manifest_path': None, 'work_queue_name': 'default', 'storage_document_id': None, 'infrastructure_document_id': '22ac069b-ad26-43a8-99d7-141273170aa8', 'schedule': None, 'description': None, 'path': '/Users/florianl/Documents/Dev/bi/orion', 'version': 'ac448c7078c1ce66763cf4130da3bba2', 'entrypoint': 'orion/flows/bi/fact/bridge_stats.py:fact_bridge_stats', 'infra_overrides': {}}}
```

### Versions

```Text
prefect --version
14:26:51.555 | DEBUG   | prefect.profiles - Using profile 'preprod'
2.16.1
```

### Additional context

As a result i've reverted to 2.15.0 and everything is fine on that version. 

I also dumped the JSON that is sent to the api, it if may help you :

`{'name': 'local:fact_bridge_stats', 'flow_id': '45094af8-5c4c-4582-ae4f-e65ef70f31e6', 'schedules': [], 'parameter_openapi_schema': {'title': 'Parameters', 'type': 'object', 'properties': {'start_at': {'title': 'start_at', 'position': 0, 'type': 'string', 'format': 'date-time'}, 'end_at': {'title': 'end_at', 'position': 1, 'type': 'string', 'format': 'date-time'}}}, 'parameters': {}, 'tags': [], 'manifest_path': None, 'work_queue_name': 'default', 'storage_document_id': None, 'infrastructure_document_id': '22ac069b-ad26-43a8-99d7-141273170aa8', 'schedule': None, 'description': None, 'path': '/Users/florianl/Documents/Dev/bi/orion', 'version': 'ac448c7078c1ce66763cf4130da3bba2', 'entrypoint': 'orion/flows/bi/fact/bridge_stats.py:fact_bridge_stats', 'infra_overrides': {}}`

My random guess would be the `schedule: None` since that's the main focus of the version.

**Comment by jakekaplan** [comment] 2024-03-05 13:46
Hi @fletanoux thanks for filing this issue!

I believe that this is due to a mismatch between your client and server versions. Can you try updating your prefect server version to `2.16.1` and try again?

**Comment by shawnlong636** [comment] 2024-03-06 03:16
Hey @jakekaplan and @fletanoux, I can definitely concur that the that issue is due to mismatched client and server versions, as I had the same issue.

Also though, I'm running it into a pedantic issue when deploying using a CronSchedule with build_from_flow:

```python
deployment = Deployment.build_from_flow(
    flow=flow,
    infra_overrides=self.options.infra_overrides,
    schedule=[CronSchedule(cron=self.options.cron_schedule, timezone="America/Los_Angeles")] if self.options.cron_schedule else None,
    name=self.options.name,
    tags=self.options.tags,
    work_pool_name=self.options.work_pool_name,
    work_queue_name=self.options.work_queue_name,
    storage=self.storage_block,
    ignore_file=self.options.ignore_file
)
```

Output
```
schedules -> 0 -> schedule
  field required (type=value_error.missing)
```

**Comment by jakekaplan** [comment] 2024-03-06 14:11
Hi @shawnlong636 I am able to reproduce your issue however I do think it is separate from the original version mismatch issue filed here. I am going to close this issue as it is a known conflicting change between client/server versions.

You can track the issue you're having [here](https://github.com/PrefectHQ/prefect/issues/12177) as that should work.

**Closed by jakekaplan** 2024-03-06 14:11 UTC
Labels: bug, status:waiting for user
