### ISSUE TITLE
Prefect UI fallsback to JSON input when enum has only one value

### ISSUE THREAD

**Issue by IAL32** [PrefectHQ/prefect#11658] opened 2024-01-17 08:58 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

If a flow parameter is an enum, and there is only one member of the enum, the UI asks for a JSON input instead of the classic dropdown.

### Reproduction

```py
from enum import Enum
class LoadType(Enum):
    LATEST_BATCH = "Latest Batch"
```

Create a flow using such parameter, like:

```py
@flow
def my_flow(load_type: LoadType = LoadType.LATEST_BATCH):
    ....
```

Then a textfield input (JSON) will be shown instead of a dropdown.

### Error

<img width="317" alt="image" src="https://github.com/PrefectHQ/prefect/assets/562969/a203d89c-a6df-466f-8d7b-1808d6527737">

### Browsers

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

### Prefect version

```Text
2.14.5
```

### Additional context

I am able to temporarily patch the issue by having a dummy entry, but this is not ideal:

```py
from enum import Enum
class LoadType(Enum):
    LATEST_BATCH = "Latest Batch"
    DONT_USE = "Don't Use"
```

<img width="338" alt="image" src="https://github.com/PrefectHQ/prefect/assets/562969/81ca4854-7d4d-4c35-aa04-27cdc215ee57">

**Comment by desertaxle** [comment] 2024-01-17 15:57
Thanks for the issue @IAL32! 

Based on the example it looks like the parameter schema is generated as expected:
```json
{
  "title": "Parameters",
  "type": "object",
  "properties": {
    "load_type": {
      "title": "load_type",
      "default": "Latest Batch",
      "position": 0,
      "allOf": [
        {
          "$ref": "#/definitions/LoadType"
        }
      ]
    }
  },
  "definitions": {
    "LoadType": {
      "title": "LoadType",
      "description": "An enumeration.",
      "enum": [
        "Latest Batch"
      ]
    }
  }
}
```
Looks like we'll need to update the UI to handle this case.

**Comment by pleek91** [comment] 2024-02-28 19:15
@IAL32 testing this using our new enhanced deployment parameters ui which is available in cloud and will soon be available in open source I can no longer reproduce. So I believe this is fixed in the latest version. Thank you for reporting!

![Image](https://github.com/PrefectHQ/prefect/assets/6200442/c0ad3032-1972-44bf-8676-af7cc0a4e839)

**Comment by pleek91** [comment] 2024-03-21 16:18
Closing this issue now that enhanced deployment parameters are available in oss and cloud. But please let us know if you're still having issues with this!

**Closed by pleek91** 2024-03-21 16:18 UTC
Labels: bug, ui
