### ISSUE TITLE
Pip install fail

### ISSUE THREAD

**Issue by robmarkcole** [PrefectHQ/prefect#834] opened 2019-03-25 08:49 UTC
Mac OSx with Anaconda distro

```
Robins-MacBook:data robincole$ pip install prefect
Collecting prefect
  Downloading https://files.pythonhosted.org/packages/c3/86/6599cd54083875df820e3f980a22788a3e23756d8878f3b0e31a61b74dfe/prefect-0.5.0-py3-none-any.whl (208kB)
    100% |████████████████████████████████| 215kB 1.3MB/s
Requirement already satisfied: toml<1.0,>=0.9.4 in /Users/robincole/anaconda3/lib/python3.6/site-packages (from prefect) (0.9.6)
Requirement already satisfied: cryptography<3.0,>=2.2.2 in /Users/robincole/anaconda3/lib/python3.6/site-packages (from prefect) (2.2.2)
Requirement already satisfied: click<8.0,>=7.0 in /Users/robincole/anaconda3/lib/python3.6/site-packages (from prefect) (7.0)
Collecting cloudpickle<0.7,>=0.6.0 (from prefect)
  Downloading https://files.pythonhosted.org/packages/fc/87/7b7ef3038b4783911e3fdecb5c566e3a817ce3e890e164fc174c088edb1e/cloudpickle-0.6.1-py2.py3-none-any.whl
Collecting mypy<0.700,>=0.600 (from prefect)
  Downloading https://files.pythonhosted.org/packages/88/11/8092fdd9cf4c507e6c799bf663e713a5418beb9fda422df810f72641224c/mypy-0.670-py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 4.3MB/s
Collecting pendulum<3.0,>=2.0.4 (from prefect)
  Downloading https://files.pythonhosted.org/packages/5b/57/71fc910edcd937b72aa0ef51c8f5734fbd8c011fa1480fce881433847ec8/pendulum-2.0.4.tar.gz (75kB)
    100% |████████████████████████████████| 81kB 6.0MB/s
  Installing build dependencies ... error
  Complete output from command /Users/robincole/anaconda3/bin/python /Users/robincole/anaconda3/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/4_/093rm79d22bb6kb4xpvprxp40000gp/T/pip-build-env-jqpwlpgv/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- poetry>=0.12:
  Traceback (most recent call last):
    File "/Users/robincole/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/Users/robincole/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/Users/robincole/anaconda3/lib/python3.6/site-packages/pip/__main__.py", line 16, in <module>
      from pip._internal import main as _main  # isort:skip # noqa
    File "/Users/robincole/anaconda3/lib/python3.6/site-packages/pip/_internal/__init__.py", line 40, in <module>
      from pip._internal.cli.autocompletion import autocomplete
    File "/Users/robincole/anaconda3/lib/python3.6/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
      from pip._internal.cli.main_parser import create_main_parser
    File "/Users/robincole/anaconda3/lib/python3.6/site-packages/pip/_internal/cli/main_parser.py", line 12, in <module>
      from pip._internal.commands import (
    File "/Users/robincole/anaconda3/lib/python3.6/site-packages/pip/_internal/commands/__init__.py", line 6, in <module>
      from pip._internal.commands.completion import CompletionCommand
    File "/Users/robincole/anaconda3/lib/python3.6/site-packages/pip/_internal/commands/completion.py", line 6, in <module>
      from pip._internal.cli.base_command import Command
    File "/Users/robincole/anaconda3/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 25, in <module>
      from pip._internal.index import PackageFinder
    File "/Users/robincole/anaconda3/lib/python3.6/site-packages/pip/_internal/index.py", line 41, in <module>
      from pip._internal.wheel import Wheel
    File "/Users/robincole/anaconda3/lib/python3.6/site-packages/pip/_internal/wheel.py", line 7, in <module>
      import compileall
    File "/Users/robincole/anaconda3/lib/python3.6/compileall.py", line 20, in <module>
      from concurrent.futures import ProcessPoolExecutor
    File "/Users/robincole/anaconda3/lib/python3.6/site-packages/concurrent/futures/__init__.py", line 8, in <module>
      from concurrent.futures._base import (FIRST_COMPLETED,
    File "/Users/robincole/anaconda3/lib/python3.6/site-packages/concurrent/futures/_base.py", line 381
      raise exception_type, self._exception, self._traceback
                          ^
  SyntaxError: invalid syntax

  ----------------------------------------
Command "/Users/robincole/anaconda3/bin/python /Users/robincole/anaconda3/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/4_/093rm79d22bb6kb4xpvprxp40000gp/T/pip-build-env-jqpwlpgv/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- poetry>=0.12" failed with error code 1 in None
Robins-MacBook:data robincole$
```

**Comment by jlowin** [comment] 2019-03-25 11:08
Hi @robmarkcole, that's a very odd error -- it looks like you have a package with Python 2 syntax installed under Python 3. More unusual, it looks like it's claiming to be `concurrent.futures` which to the best of my knowledge is part of the Py3 standard library. 

It sounds like your environment might have gotten messed up at some point, and maybe even installed the Python 2 backport of `concurrent.futures`.

In a fresh Python interpreter, could you try:
```python
from concurrent import futures
```

If you get an error, then I believe the problem is in fact a backported package. I'm not sure how that would have gotten there. Perhaps `pip uninstall concurrent.futures` will take care of it? In any case, a fresh conda environment will definitely let you kick the tires on Prefect.

**Comment by robmarkcole** [comment] 2019-03-25 11:37
Hi @jlowin `from concurrent import futures` does not raise any errors, and I cannot recall a similar error on any other installs. I have now successfully installed prefect in a fresh conda env

**Comment by jlowin** [comment] 2019-03-25 11:56
So strange, according to the traceback `concurrent.futures` is where the syntax error lies! I'm sorry I couldn't be more helpful but I'm glad you've gotten it running. I'll close the issue but if you find any other clues that suggest it might be something in Prefect, please reopen and ping myself or @cicdw.

**Closed** 2019-03-25 11:56 UTC
