### ISSUE TITLE
Task run durations on y axis are often inappropriate

### ISSUE THREAD

**Issue by cpinflux** [PrefectHQ/prefect#15195] opened 2024-09-03 18:40 UTC
### Bug summary

The times shown on the y-axis are often shown with inappropriate values:
![image](https://github.com/user-attachments/assets/7dfdd30a-22b1-4342-b5d2-e251df44fcea)
Generally I'd suggest the intervals shown are rounder times, e.g. 30s, 1m, 1m 30s and 2m here. But principally here, rounding *down* to the whole minute and printing the same value twice is not good.

### Version info (`prefect version` output)

```Text
Version:             3.0.0rc19
API version:         0.8.4
Python version:      3.12.5
Git commit:          eac7892e
Built:               Thu, Aug 22, 2024 10:02 AM
OS/Arch:             linux/x86_64
Profile:             ephemeral
Server type:         server
Pydantic version:    2.8.2
```

**Comment by zzstoatzz** [comment] 2024-09-03 18:42
hi @cpinflux - thank you for the issue! I believe this is a dupe of https://github.com/PrefectHQ/prefect/issues/7806

feel free to re-open if you feel there's additional nuance to this one

**Closed by zzstoatzz** 2024-09-03 18:42 UTC
Labels: bug

**Comment by cpinflux** [comment] 2024-09-03 19:11
Yep, sorry, didn't imagine I'd need to go that far back, what with the v3 release and all.
