### ISSUE TITLE
How can I resolve the "Crash detected! Execution was cancelled by the runtime environment" error in my code?

### ISSUE THREAD

**Issue by wfg314** [PrefectHQ/prefect#14984] opened 2024-08-17 02:08 UTC
### my code:
```python
from prefect import flow, task
import time
import asyncio


@task
async def my_task(a):
    time.sleep(10)
    return a


@flow
async def my_flow():
    res = await my_task("abc")
    return res


async def main():
    tasks = [asyncio.create_task(my_flow()) for i in range(3)]
    tasks_results = await asyncio.gather(*tasks, return_exceptions=True)
    return tasks_results


if __name__ == '__main__':
    tasks_result = asyncio.run(main())
    print(tasks_result)

``` 
### error messages:
```shell
10:00:23.412 | INFO    | prefect.engine - Created flow run 'tireless-raptor' for flow 'my-flow'
10:00:23.467 | INFO    | prefect.engine - Created flow run 'beautiful-poodle' for flow 'my-flow'
10:00:23.503 | INFO    | prefect.engine - Created flow run 'big-anteater' for flow 'my-flow'
10:00:23.529 | INFO    | Flow run 'tireless-raptor' - Created task run 'my_task-0' for task 'my_task'
10:00:23.530 | INFO    | Flow run 'tireless-raptor' - Executing 'my_task-0' immediately...
10:00:23.629 | INFO    | Flow run 'big-anteater' - Created task run 'my_task-0' for task 'my_task'
10:00:23.630 | INFO    | Flow run 'big-anteater' - Executing 'my_task-0' immediately...
10:00:23.654 | INFO    | Flow run 'beautiful-poodle' - Created task run 'my_task-0' for task 'my_task'
10:00:23.655 | INFO    | Flow run 'beautiful-poodle' - Executing 'my_task-0' immediately...
10:00:33.675 | INFO    | Task run 'my_task-0' - Finished in state Completed()
10:00:33.706 | INFO    | Flow run 'tireless-raptor' - Finished in state Completed()
10:00:33.728 | ERROR   | Task run 'my_task-0' - Crash detected! Execution was cancelled by the runtime environment.
10:00:33.738 | ERROR   | Task run 'my_task-0' - Crash detected! Execution was cancelled by the runtime environment.
10:00:33.770 | ERROR   | Flow run 'beautiful-poodle' - Crash detected! Execution was cancelled by the runtime environment.
10:00:33.883 | ERROR   | Flow run 'big-anteater' - Crash detected! Execution was cancelled by the runtime environment.
``` 
### expect:
output should be ["abc", "abc", "abc"]

### Version info (`prefect version` output)

```Text
$ prefect version
Version:             2.19.8
API version:         0.8.4
Python version:      3.11.0
Git commit:          478e89d6
Built:               Thu, Jul 11, 2024 2:25 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.38.4
```

**Comment by desertaxle** [comment] 2024-08-19 21:33
Hey @wfg314! I wasn't able to recreate the error with the code you provided, but I noticed that you're calling `time.sleep` in your task, which will block the event loop. Could you try using `asyncio.sleep` to see if it resolves your issue?

**Comment by wfg314** [comment] 2024-08-20 02:38
> Hey @wfg314! I wasn't able to recreate the error with the code you provided, but I noticed that you're calling `time.sleep` in your task, which will block the event loop. Could you try using `asyncio.sleep` to see if it resolves your issue?

 @desertaxle Use ‘asyncio.sleep' to run multiple times, with different error messages each time.:

```python
from prefect import flow, task
import asyncio


@task
async def my_task(a):
    await asyncio.sleep(10)
    return a


@flow
async def my_flow():
    res = await my_task("abc")
    return res


async def main():
    tasks = [asyncio.create_task(my_flow()) for i in range(3)]
    tasks_results = await asyncio.gather(*tasks, return_exceptions=True)
    return tasks_results


if __name__ == '__main__':
    tasks_result = asyncio.run(main())
    print(tasks_result)
``` 

```shell
10:22:03.777 | INFO    | prefect.engine - Created flow run 'brave-chinchilla' for flow 'my-flow'
10:22:03.798 | INFO    | prefect.engine - Created flow run 'amphibian-gorilla' for flow 'my-flow'
10:22:03.874 | INFO    | prefect.engine - Created flow run 'zircon-avocet' for flow 'my-flow'
10:22:03.914 | INFO    | Flow run 'brave-chinchilla' - Created task run 'my_task-0' for task 'my_task'
10:22:03.915 | INFO    | Flow run 'brave-chinchilla' - Executing 'my_task-0' immediately...
10:22:03.997 | INFO    | Flow run 'amphibian-gorilla' - Created task run 'my_task-0' for task 'my_task'
10:22:03.999 | INFO    | Flow run 'amphibian-gorilla' - Executing 'my_task-0' immediately...
10:22:04.050 | INFO    | Flow run 'zircon-avocet' - Created task run 'my_task-0' for task 'my_task'
10:22:04.050 | INFO    | Flow run 'zircon-avocet' - Executing 'my_task-0' immediately...
10:22:14.107 | INFO    | Task run 'my_task-0' - Finished in state Completed()
10:22:14.139 | INFO    | Flow run 'brave-chinchilla' - Finished in state Completed()
10:22:14.171 | INFO    | Task run 'my_task-0' - Finished in state Completed()
10:22:14.200 | INFO    | Task run 'my_task-0' - Finished in state Completed()
10:22:14.226 | INFO    | Flow run 'zircon-avocet' - Finished in state Completed()
10:22:14.234 | ERROR   | Flow run 'amphibian-gorilla' - Crash detected! Execution was cancelled by the runtime environment.
10:22:14.367 | ERROR   | concurrent.futures - exception calling callback for <Future at 0x21f98c2d510 state=finished returned bool>
Traceback (most recent call last):
  File "C:\Python311\Lib\concurrent\futures\_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "C:\Python311\Lib\asyncio\futures.py", line 401, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "C:\Python311\Lib\asyncio\base_events.py", line 803, in call_soon_threadsafe
    self._check_closed()
  File "C:\Python311\Lib\asyncio\base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
``` 

```shell
10:27:47.931 | INFO    | prefect.engine - Created flow run 'pygmy-teal' for flow 'my-flow'
10:27:47.953 | INFO    | prefect.engine - Created flow run 'congenial-dachshund' for flow 'my-flow'
10:27:47.975 | INFO    | prefect.engine - Created flow run 'light-coati' for flow 'my-flow'
10:27:48.108 | INFO    | Flow run 'pygmy-teal' - Created task run 'my_task-0' for task 'my_task'
10:27:48.109 | INFO    | Flow run 'pygmy-teal' - Executing 'my_task-0' immediately...
10:27:48.126 | INFO    | Flow run 'light-coati' - Created task run 'my_task-0' for task 'my_task'
10:27:48.127 | INFO    | Flow run 'light-coati' - Executing 'my_task-0' immediately...
10:27:48.148 | INFO    | Flow run 'congenial-dachshund' - Created task run 'my_task-0' for task 'my_task'
10:27:48.149 | INFO    | Flow run 'congenial-dachshund' - Executing 'my_task-0' immediately...
10:27:58.252 | INFO    | Task run 'my_task-0' - Finished in state Completed()
10:27:58.293 | INFO    | Flow run 'pygmy-teal' - Finished in state Completed()
10:27:58.311 | INFO    | Task run 'my_task-0' - Finished in state Completed()
10:27:58.332 | INFO    | Task run 'my_task-0' - Finished in state Completed()
10:27:58.361 | INFO    | Flow run 'congenial-dachshund' - Finished in state Completed()
10:27:58.384 | INFO    | Flow run 'light-coati' - Finished in state Completed()
10:27:58.526 | ERROR   | concurrent.futures - exception calling callback for <Future at 0x26c5aa46e50 state=finished returned bool>
Traceback (most recent call last):
  File "C:\Python311\Lib\concurrent\futures\_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "C:\Python311\Lib\asyncio\futures.py", line 401, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "C:\Python311\Lib\asyncio\base_events.py", line 803, in call_soon_threadsafe
    self._check_closed()
  File "C:\Python311\Lib\asyncio\base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
10:27:58.530 | ERROR   | concurrent.futures - exception calling callback for <Future at 0x26c5c26a810 state=finished returned bool>
Traceback (most recent call last):
  File "C:\Python311\Lib\concurrent\futures\_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "C:\Python311\Lib\asyncio\futures.py", line 401, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "C:\Python311\Lib\asyncio\base_events.py", line 803, in call_soon_threadsafe
    self._check_closed()
  File "C:\Python311\Lib\asyncio\base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
[CancelledError(''), CancelledError(''), 'abc']
``` 

```shell
10:30:22.554 | INFO    | prefect.engine - Created flow run 'super-beetle' for flow 'my-flow'
10:30:22.580 | INFO    | prefect.engine - Created flow run 'berserk-firefly' for flow 'my-flow'
10:30:22.603 | INFO    | prefect.engine - Created flow run 'wise-skink' for flow 'my-flow'
10:30:22.733 | INFO    | Flow run 'berserk-firefly' - Created task run 'my_task-0' for task 'my_task'
10:30:22.733 | INFO    | Flow run 'berserk-firefly' - Executing 'my_task-0' immediately...
10:30:22.752 | INFO    | Flow run 'wise-skink' - Created task run 'my_task-0' for task 'my_task'
10:30:22.752 | INFO    | Flow run 'wise-skink' - Executing 'my_task-0' immediately...
10:30:22.770 | INFO    | Flow run 'super-beetle' - Created task run 'my_task-0' for task 'my_task'
10:30:22.771 | INFO    | Flow run 'super-beetle' - Executing 'my_task-0' immediately...
10:30:32.868 | INFO    | Task run 'my_task-0' - Finished in state Completed()
10:30:32.898 | INFO    | Task run 'my_task-0' - Finished in state Completed()
10:30:32.920 | INFO    | Flow run 'wise-skink' - Finished in state Completed()
10:30:32.970 | INFO    | Flow run 'berserk-firefly' - Finished in state Completed()
10:30:32.989 | INFO    | Task run 'my_task-0' - Finished in state Completed()
10:30:33.036 | INFO    | Flow run 'super-beetle' - Finished in state Completed()
10:30:33.189 | ERROR   | concurrent.futures - exception calling callback for <Future at 0x25ef99de090 state=finished returned bool>
Traceback (most recent call last):
  File "C:\Python311\Lib\concurrent\futures\_base.py", line 340, in _invoke_callbacks
    callback(self)
  File "C:\Python311\Lib\asyncio\futures.py", line 401, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "C:\Python311\Lib\asyncio\base_events.py", line 803, in call_soon_threadsafe
    self._check_closed()
  File "C:\Python311\Lib\asyncio\base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
['abc', 'abc', CancelledError('')]
``` 

```shell
10:33:06.193 | INFO    | prefect.engine - Created flow run 'courageous-quail' for flow 'my-flow'
10:33:06.220 | INFO    | prefect.engine - Created flow run 'precise-lion' for flow 'my-flow'
10:33:06.332 | INFO    | prefect.engine - Created flow run 'cerulean-anaconda' for flow 'my-flow'
10:33:06.359 | INFO    | Flow run 'precise-lion' - Created task run 'my_task-0' for task 'my_task'
10:33:06.360 | INFO    | Flow run 'precise-lion' - Executing 'my_task-0' immediately...
10:33:06.376 | INFO    | Flow run 'courageous-quail' - Created task run 'my_task-0' for task 'my_task'
10:33:06.378 | INFO    | Flow run 'courageous-quail' - Executing 'my_task-0' immediately...
10:33:06.533 | INFO    | Flow run 'cerulean-anaconda' - Created task run 'my_task-0' for task 'my_task'
10:33:06.534 | INFO    | Flow run 'cerulean-anaconda' - Executing 'my_task-0' immediately...
10:33:16.474 | INFO    | Task run 'my_task-0' - Finished in state Completed()
10:33:16.508 | INFO    | Task run 'my_task-0' - Finished in state Completed()
10:33:16.528 | INFO    | Flow run 'precise-lion' - Finished in state Completed()
10:33:16.550 | INFO    | Flow run 'courageous-quail' - Finished in state Completed()
10:33:16.585 | ERROR   | Task run 'my_task-0' - Crash detected! Execution was cancelled by the runtime environment.
10:33:16.730 | ERROR   | Flow run 'cerulean-anaconda' - Crash detected! Execution was cancelled by the runtime environment.
```

**Comment by desertaxle** [comment] 2024-08-20 17:43
Thanks for trying that @wfg314!

I can reproduce this now that I have a Windows setup, which makes me think this is a Windows-specific issue (or happens more often on Windows). 

This is the traceback that I see:
```

  File "C:\Users\alexander\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\alexander\dev\prefect\with a space\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 389, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "C:\Users\alexander\dev\prefect\with a space\Lib\site-packages\prefect\client\utilities.py", line 98, in with_injected_client
    async with context as new_client:
  File "C:\Users\alexander\dev\prefect\with a space\Lib\site-packages\prefect\client\orchestration.py", line 3374, in __aexit__
    return await self._exit_stack.__aexit__(*exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexander\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 754, in __aexit__
    raise exc_details[1]
  File "C:\Users\alexander\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 737, in __aexit__
    cb_suppress = await cb(*exc_details)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexander\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 217, in __aexit__
    await anext(self.gen)
  File "C:\Users\alexander\dev\prefect\with a space\Lib\site-packages\prefect\client\base.py", line 151, in app_lifespan_context
    await context.__aexit__(*exc_info)
  File "C:\Users\alexander\dev\prefect\with a space\Lib\site-packages\asgi_lifespan\_manager.py", line 113, in __aexit__
    return await self._exit_stack.__aexit__(exc_type, exc_value, traceback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexander\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 754, in __aexit__
    raise exc_details[1]
  File "C:\Users\alexander\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 737, in __aexit__
    cb_suppress = await cb(*exc_details)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexander\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 642, in _exit_wrapper
    await callback(*args, **kwds)
  File "C:\Users\alexander\dev\prefect\with a space\Lib\site-packages\asgi_lifespan\_manager.py", line 49, in shutdown
    await self._concurrency_backend.run_and_fail_after(
  File "C:\Users\alexander\dev\prefect\with a space\Lib\site-packages\asgi_lifespan\_concurrency\asyncio.py", line 44, in run_and_fail_after
    await asyncio.wait_for(coroutine(), timeout=seconds)
  File "C:\Users\alexander\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\alexander\dev\prefect\with a space\Lib\site-packages\asgi_lifespan\_concurrency\asyncio.py", line 17, in wait
    await self._event.wait()
  File "C:\Users\alexander\AppData\Local\Programs\Python\Python312\Lib\asyncio\locks.py", line 212, in wait
    await fut
asyncio.exceptions.CancelledError
```

My hunch is that this is related to the upgrade of `anyio` to version 4, but I'll keep digging.

**Comment by desertaxle** [comment] 2024-08-20 17:49
Also, this issue appears to be limited to the `2.x` version line. I don't see it on the most recent `3.0` release candidate.

**Comment by desertaxle** [comment] 2024-11-21 21:04
@wfg314 since this issue is fixed in the 3.x versions of Prefect which are now the actively supported versions, I recommend upgrading to the newest version of `prefect`. If there's anything blocking your upgrade, please let us know by opening an issue!

**Closed** 2024-11-21 21:04 UTC
Labels: bug, 2.x
