### ISSUE TITLE
RemoteDisconnected after Lazarus

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [PrefectHQ/prefect#3277] opened 2020-09-08 10:20 UTC
## Description
Got the following error when running job on k8 agent using cloud. This was before flow itself started 

`
Rescheduled by a Lazarus process. This is attempt 1.
`
`
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
`

## Expected Behavior
No error as the flow can run.

## Reproduction
```python
@task(**base_task_settings())
def numbers_task():
    return [1, 2, 3]


@task(**base_task_settings())
def map_task(x):
    sleep(2)
    return x + 1


@task(**base_task_settings())
def reduce_task(x):
    return sum(x)


schedule = CronSchedule(cron="2/30 * * * *", start_date=now)

with Flow("Map-Reduce", schedule=schedule) as mr_flow:
    numbers = numbers_task()
    first_map = map_task.map(numbers)
    second_map = map_task.map(first_map)
    reduction = reduce_task(second_map)

if __name__ == "__main__":
    mr_flow.run(run_on_schedule=False)
```

## Environment
prefect 0.13.5 with k8 agent and cloud

**Comment by jcrist** [comment] 2020-09-08 16:15
This shouldn't be an issue, it indicates that the flow run took longer to start than the default flow run timeout (10 min I believe). Prefect agents (currently) don't track the status of a job, once the agent has kicked it off we don't know if it's broken/failed or just hasn't started yet. After a timeout, the job is marked as possibly dead, and a new job is scheduled. So if your k8s cluster is backed up a bit and the job doesn't start in a soon-ish manner, it will be resubmitted and the original job won't run.

We might change this design in the future, but for now that log message should be innocuous. Does that make sense?

**Comment by jcrist** [comment] 2020-09-08 16:15
That said, the ` ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))` should probably not show up on the user-side. Where did you see that log message?

**Comment by thomasfrederikhoeck** [comment] 2020-09-08 21:10
I saw the message in the cloud log where it was the log related to the error that failed the flow. @jcrist

**Comment by jcrist** [comment] 2020-09-08 21:26
Can you post the logs where that occurred (a few log lines above and below it)? No worries if not.

**Comment by thomasfrederikhoeck** [comment] 2020-09-09 07:24
![image](https://user-images.githubusercontent.com/44194839/92567579-2f349e00-f27e-11ea-94d9-a18c192fd602.png)

**Comment by thomasfrederikhoeck** [comment] 2020-09-11 07:12
@jcrist So the cloud logs just shows that it failed.

**Comment by cicdw** [comment] 2020-09-12 22:44
@thomasfrederikhoeck the reason this appears to be Lazarus related is most likely because there is some issue within your k8s cluster - Lazarus "resurrects" distressed Flows that never enter a Running state after being Submitted, and is 99% of the time caused by an infra issue on the user's side (we are working on making these issues more prominent in the logs, too).

**Comment by thomasfrederikhoeck** [comment] 2020-09-14 09:03
@cicdw ah, so agent submits the job without any errors, but the pod is never started and therefor never contacts the Cloud API?

**Comment by cicdw** [comment] 2020-09-15 16:28
Yup, that's correct

**Closed** 2020-09-24 13:03 UTC
