### ISSUE TITLE
Service 'EventsWorker' failed with N pending items.

### ISSUE THREAD

**Issue by carlosjourdan** [PrefectHQ/prefect#11811] opened 2024-02-02 14:03 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When running "prefect worker start --pool mypool" I get several error messages with the text "Service 'EventsWorker' failed with N pending items." This keeps popping up at random times, and seems to have no effect on my flows.

### Reproduction

```python3
Create a local process workpool

Run prefect worker start --pool mypool
```

### Error

```python3
Discovered type 'process' for work pool 'mypool'.
Worker 'ProcessWorker dc4e0f75-8b7a-48a0-a623-784470e28c82' started!
10:53:42.457 | ERROR   | GlobalEventLoopThread | prefect._internal.concurrency - Service 'EventsWorker' failed with 2 pending items.
```

### Versions

```Text
(flow_runner) C:\Users\carlos_jourdan>prefect version
Version:             2.14.20
API version:         0.8.4
Python version:      3.9.12
Git commit:          8ceb0962
Built:               Thu, Feb 1, 2024 6:30 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         cloud
```

**Comment by serinamarie** [comment] 2024-02-03 02:40
Hi @carlosjourdan, thanks for the issue! I am unable to replicate your issue on macOS. Do you happen to know if you see this issue using other operating systems or just on Windows?

**Comment by carlosjourdan** [comment] 2024-02-04 17:44
Hi @serinamarie. Indeed I'm only able to reproduce this issue on a windows box with a "process" typed worker. Also, setting PREFECT_LOGGING_LEVEL to DEBUG does not reveal anything other than the expected polling from the worker to the cloud.

**Comment by serinamarie** [comment] 2024-02-06 22:02
Sounds good. We can add to this to our backlog to look into! I am glad to hear there's **no** breaking functionality and it doesn't seem to affect your flows. One thing that might help whoever looks into this is determining if this bug was introduced in `2.14.20` and if not, when it was. @carlosjourdan if you were able to provide that info, that might help us get a jumpstart on where to look.

**Comment by nikhiljain12** [comment] 2024-02-10 00:15
This is happening for me on macOS after I upgraded from `python3.9` to `python3.11.8`. Getting lots of errors like this:

```
16:08:40.791 | ERROR   | GlobalEventLoopThread | prefect._internal.concurrency - Service 'EventsWorker' failed with 1 pending items.
```

The flow works fine though.

**Comment by EmilRex** [comment] 2024-04-25 20:37
One suggestion for further debugging: try installing `prefect>=2.18.1` and run the following command: `prefect events stream`. This command listens for events and more importantly, raises a different error than this general warning. Events communicate over web sockets rather than HTTP, which could be relevant to the underlying cause.

**Comment by Andrew-S-Rosen** [comment] 2024-04-26 20:34
Just writing in to confirm that I also get this issue on a Linux machine with Python 3.11 and Prefect 2.18.1. Same as @nikhiljain12: flow works fine despite the ERROR log. I don't have time to dig into this more at the moment but will report back if/when I do.

**Comment by kid7st** [comment] 2024-08-07 12:17
Check in. Same issue happened to me in Mac with the sample code in official doc: https://docs-3.prefect.io/3.0rc/get-started/quickstart#convert-your-script-to-a-prefect-workflow

> 20:07:51.462 | ERROR   | GlobalEventLoopThread | prefect._internal.concurrency - Service 'EventsWorker' failed with 1 pending items.
20:07:51.517 | INFO    | Task run 'get_repo_info-0' - Created task run 'get_repo_info-0' for task 'get_repo_info'
20:07:52.255 | ERROR   | GlobalEventLoopThread | prefect._internal.concurrency - Service 'EventsWorker' failed with 1 pending items.
20:07:53.557 | INFO    | Task run 'get_repo_info-0' - Finished in state Completed()
20:07:53.558 | INFO    | Flow run 'cuddly-kagu' - Stars 🌠 : 15569
20:07:53.938 | ERROR   | GlobalEventLoopThread | prefect._internal.concurrency - Service 'EventsWorker' failed with 1 pending items.
20:07:54.582 | INFO    | Task run 'get_contributors-0' - Created task run 'get_contributors-0' for task 'get_contributors'
20:07:54.789 | ERROR   | GlobalEventLoopThread | prefect._internal.concurrency - Service 'EventsWorker' failed with 1 pending items.
20:07:55.317 | ERROR   | GlobalEventLoopThread | prefect._internal.concurrency - Service 'EventsWorker' failed with 1 pending items.
20:07:56.502 | INFO    | Task run 'get_contributors-0' - Finished in state Completed()
20:07:56.503 | INFO    | Flow run 'cuddly-kagu' - Number of contributors 👷: 30
20:07:56.872 | INFO    | Flow run 'cuddly-kagu' - Finished in state Completed()

prefect version:

```
prefect version
Version:             3.0.0rc7
API version:         0.8.4
Python version:      3.11.9
Git commit:          ed41da9d
Built:               Thu, Jun 20, 2024 4:59 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         cloud
Pydantic version:    2.7.4
```

**Comment by onefinedayLAST** [comment] 2024-09-08 05:41
Hi guys, can one help here ? I also have the same issue... 

I upgraded from v2.2 to v3.0 and then all my flows broke. In order to identify the RCA I am using this simple flow below... 

The flow actually executes and sends the message via telegram but I don't get to see any tasks that were run in the flow dashboard thus I am unable to visualize. 

**Simple code like this :**

```
from prefect import flow, task
import logging
import boto3
import json
import requests
import asyncio

logging.basicConfig(level=logging.INFO)

@task
async def get_ssm_parameter(parameter_name, region_name='xxxx'):
    session = boto3.session.Session()
    ssm_client = session.client('ssm', region_name=region_name)
    try:
        response = ssm_client.get_parameter(Name=parameter_name, WithDecryption=True)
        return json.loads(response['Parameter']['Value'])
    except Exception as e:
        logging.error(f"Error retrieving parameter {parameter_name}: {e}")
        raise

@task
async def send_telegram_message(message):
    telegram_creds = await get_ssm_parameter('xxxx')
    chat_id = telegram_creds['chat_id']
    bot_token = telegram_creds['chat_pin']
    
    url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
    payload = {
        "chat_id": chat_id,
        "text": message
    }
    
    try:
        response = requests.post(url, json=payload)
        response.raise_for_status()
        logging.info("Telegram message sent successfully")
    except Exception as e:
        logging.error(f"Error sending Telegram message: {e}")

@task(log_prints=True)
async def say_hello(name: str):
    await send_telegram_message(f"Hello, {name}!")
    print(f"Hello, {name}!")

@flow
async def hello_universe(names: list[str]):
    tasks = [say_hello(name) for name in names]
    await asyncio.gather(*tasks)

if __name__ == "__main__":
    # create your first deployment to automate your flow
    asyncio.run(hello_universe.serve(name="your-first-deployment"))
```

**These GlobalEvenLoopThread errors possibly are not letting the tasks get recorded:**

```
11:02:39.132 | INFO    | prefect.flow_runs.runner - Runner 'your-first-deployment' submitting flow run '79e76a64-78e6-4f3c-9604-01ceff61cd96'
11:02:39.199 | INFO    | prefect.flow_runs.runner - Opening process...
11:02:39.207 | INFO    | prefect.flow_runs.runner - Completed submission of flow run '79e76a64-78e6-4f3c-9604-01ceff61cd96'
11:02:41.159 | INFO    | Flow run 'nonchalant-kiwi' - Downloading flow code from storage at '.'
11:02:41.670 | INFO    | Task run 'say_hello-40b' - Created task run 'say_hello-40b' for task 'say_hello'
11:02:41.689 | INFO    | Task run 'send_telegram_message-a5d' - Created task run 'send_telegram_message-a5d' for task 'send_telegram_message'
11:02:41.707 | INFO    | Task run 'get_ssm_parameter-d15' - Created task run 'get_ssm_parameter-d15' for task 'get_ssm_parameter'
11:02:41.771 | ERROR   | GlobalEventLoopThread | prefect._internal.concurrency - Service 'EventsWorker' failed with 6 pending items.
11:02:42.080 | INFO    | Task run 'get_ssm_parameter-d15' - Finished in state Completed()
11:02:42.170 | ERROR   | GlobalEventLoopThread | prefect._internal.concurrency - Service 'EventsWorker' failed with 1 pending items.
11:02:42.743 | INFO    | Task run 'send_telegram_message-a5d' - Finished in state Completed()
11:02:42.744 | INFO    | Task run 'say_hello-40b' - Hello, finallyPlsWork!
11:02:42.779 | INFO    | Task run 'say_hello-40b' - Finished in state Completed()
11:02:42.835 | ERROR   | GlobalEventLoopThread | prefect._internal.concurrency - Service 'EventsWorker' failed with 2 pending items.
11:02:42.862 | INFO    | Flow run 'nonchalant-kiwi' - Finished in state Completed()
11:02:43.268 | INFO    | prefect.flow_runs.runner - Process for flow run 'nonchalant-kiwi' exited cleanly.
```

**My Flow Dashboard:**

![image](https://github.com/user-attachments/assets/ed0ee707-ccf1-46fd-91a1-aafd84ae385e)

**Comment by cicdw** [comment] 2024-09-09 16:06
Closing as duplicate of the more recently opened issue https://github.com/PrefectHQ/prefect/issues/15274

**Closed by cicdw** 2024-09-09 16:06 UTC
Labels: bug, needs:details, arch:windows
