### ISSUE TITLE
slowly when cache for large DataFrame use DaskExecutor

### ISSUE THREAD

**Issue by sylvoslee** [PrefectHQ/prefect#2399] opened 2020-04-24 12:13 UTC
## and give a Warning as below,what is the correct way do it?

```
@task(cache_for=timedelta(days=1))
def generate_large_dataframe(month:int)->pd.DataFrame:
        pass
site-packages\distributed\worker.py:3349: UserWarning: Large object of size 101.12 MB detected in task graph:
  {'task': <Parameter: month>, 'state': None, 'upstr ...  DaskExecutor>}
Consider scattering large objects ahead of time
with client.scatter to reduce scheduler burden and
keep data on workers

    future = client.submit(func, big_data)    # bad

    big_future = client.scatter(big_data)     # good
    future = client.submit(func, big_future)  # good
  % (format_bytes(len(b)), s)
```

**Comment by joshmeek** [comment] 2020-04-27 16:59
@sylvoslee Could you give more clarification on this issue and a reproducible example?

**Comment by lauralorenz** [comment] 2020-05-19 20:39
Hi @sylvoslee, I'm closing this issue in favor of this other issue, since your error looks like this is a symptom we are planning to investigate here: https://github.com/PrefectHQ/prefect/issues/2042. That issue is currently blocked by some changes we are making to the pipeline, but please watch out there for improvements. TL;DR you don't need to make any changes to your flow as a result of this warning, and we will be improving the size constraints in future versions of prefect so you don't see this warning anymore!

**Closed by lauralorenz** 2020-05-19 20:39 UTC
Labels: needs clarification

**Comment by jmrichardson** [comment] 2020-10-10 20:57
Hi, I am getting the same error:

```
/home/jmrichardson/anaconda3/envs/tipjar/lib/python3.7/site-packages/distributed/worker.py:3385: UserWarning: Large object of size 37.41 MB detected in task graph:
  (<function TA.STOCHD at 0x7f03856f5320>,           ... 11', [237, 11])
Consider scattering large objects ahead of time
with client.scatter to reduce scheduler burden and
keep data on workers

    future = client.submit(func, big_data)    # bad

    big_future = client.scatter(big_data)     # good
    future = client.submit(func, big_future)  # good
  % (format_bytes(len(b)), s)
```
