### ISSUE TITLE
prefect-dbt: trigger_dbt_cli_command does not fail flow when dbt command fails

### ISSUE THREAD

**Issue by e1337us3r** [PrefectHQ/prefect#15455] opened 2024-09-20 19:54 UTC
### Bug summary

# Summary
Hi everyone and thanks for your good work. The problem we are facing is that prefect task and flow is completed successfully for the dbt cli command that exits with non 0 status code.

The dbt command in question is `dbt source freshness` which runs data freshness check. In our case, 1 of the 5 test fail as can be seen in the prefect logs.

```py
from prefect import flow
from prefect_dbt.cli.commands import trigger_dbt_cli_command

@flow
def trigger_dbt_flow() -> str:
    trigger_dbt_cli_command(
        command="dbt source freshness"
    )

if __name__ == "__main__":
    trigger_dbt_flow()

```

Prefect execution logs:
```
Created task run 'trigger_dbt_cli_command-0' for task 'trigger_dbt_cli_command'
Executing 'trigger_dbt_cli_command-0' immediately...
Running dbt command: ['source', 'freshness', '--profiles-dir', '/opt/prefect/dbt', '--project-dir', PosixPath('/opt/prefect/dbt'), '--target', 'prod']
Registered adapter: snowflake=1.8.3
Unable to do partial parsing because saved manifest not found. Starting full parse.
Found 7 models, 25 data tests, 5 sources, 566 macros
Pulling freshness from warehouse metadata tables for 5 sources
Concurrency: 1 threads (target='prod')
1 of 5 START freshness of raw.source1........................... [RUN]
1 of 5 PASS freshness of raw.source1 ............................ [PASS in 0.01s]
2 of 5 START freshness of raw.source2 ............................... [RUN]
2 of 5 PASS freshness of raw.source2 ................................ [PASS in 0.00s]
3 of 5 START freshness of raw.source3 ................................... [RUN]
3 of 5 ERROR STALE freshness of raw.source3 ............................. [ERROR STALE in 0.00s]
4 of 5 START freshness of raw.source4 .......................................... [RUN]
CANCEL query source.raw.source4.................................. [CANCEL]
4 of 5 PASS freshness of raw.source4........................................... [PASS in 0.07s]
Finished running 5 sources in 0 hours 0 minutes and 2.55 seconds (2.55s).
Done.
Finished in state Completed()
Finished in state Completed('All states completed.')
```

`trigger_dbt_cli_command` underneath calls `dbt_runner_client.invoke(cli_args)`([can be found here](https://github.com/PrefectHQ/prefect/blob/main/src/integrations/prefect-dbt/prefect_dbt/cli/commands.py#L188)). Here is the object it returned:

```py
dbtRunnerResult(success=False, exception=None, result=FreshnessResult(results=[SourceFreshnessResult(status='pass', timing=[TimingInfo(name='compile', started_at=datetime.datetime(2024, 9, 18, 12, 39, 43, 39417), completed_at=datetime.datetime(2024, 9, 18, 12, 39, 43, 39423)), TimingInfo(name='execute', started_at=datetime.datetime(2024, 9, 18, 12, 39, 43, 39870), completed_at=datetime.datetime(2024, 9, 18, 12, 39, 43, 40314))], thread_id='Thread-1 (worker)', execution_time=0.0023610591888427734, adapter_response={}, message=None, failures=None, node=SourceDefinition( config=SourceConfig(_extra={}, enabled=True), patch_path=None, unrendered_config={}, created_at=1726662725.7182531, _event_status={}), max_loaded_at=datetime.datetime(2024, 9, 18, 12, 31, 29, 821000, tzinfo=<UTC>), snapshotted_at=datetime.datetime(2024, 9, 18, 12, 39, 41, 925000, tzinfo=<UTC>), age=492.104), SourceFreshnessResult(status='pass', timing=[TimingInfo(name='compile', started_at=datetime.datetime(2024, 9, 18, 12, 39, 43, 49439), completed_at=datetime.datetime(2024, 9, 18, 12, 39, 43, 49443)), TimingInfo(name='execute', started_at=datetime.datetime(2024, 9, 18, 12, 39, 43, 49908), completed_at=datetime.datetime(2024, 9, 18, 12, 39, 43, 50306))], thread_id='Thread-1 (worker)', execution_time=0.0020928382873535156, adapter_response={}, message=None, failures=None, node=SourceDefinition( freshness=FreshnessThreshold(warn_after=Time(count=1, period='hour'), error_after=Time(count=2, period='hour'), filter=None), external=None), max_loaded_at=datetime.datetime(2024, 9, 18, 12, 39, 32, 639000, tzinfo=<UTC>), snapshotted_at=datetime.datetime(2024, 9, 18, 12, 39, 41, 925000, tzinfo=<UTC>), age=9.286), SourceFreshnessResult(status='error', timing=[TimingInfo(name='compile', started_at=datetime.datetime(2024, 9, 18, 12, 39, 43, 54718), completed_at=datetime.datetime(2024, 9, 18, 12, 39, 43, 54721)), TimingInfo(name='execute', started_at=datetime.datetime(2024, 9, 18, 12, 39, 43, 55041), completed_at=datetime.datetime(2024, 9, 18, 12, 39, 43, 55309))], thread_id='Thread-1 (worker)', execution_time=0.00150299072265625, adapter_response={}, message=None, failures=None, node=SourceDefinition(freshness=FreshnessThreshold(warn_after=Time(count=12, period='hour'), error_after=Time(count=24, period='hour'), filter=None), external=None,created_at=1726662725.718337, _event_status={}), max_loaded_at=datetime.datetime(2024, 9, 10, 6, 59, 34, 197000, tzinfo=<UTC>), snapshotted_at=datetime.datetime(2024, 9, 18, 12, 39, 41, 925000, tzinfo=<UTC>), age=711607.728), RunResult(status='skipped', timing=[], thread_id='WorkerThread-0', execution_time=0, adapter_response={}, message='Skipping due to fail_fast', failures=None,freshness=FreshnessThreshold(warn_after=Time(count=12, period='hour'), error_after=Time(count=24, period='hour'), filter=None), external=None, config=SourceConfig(_extra={}, enabled=True), patch_path=None, unrendered_config={}, created_at=1726662725.7175329, _event_status={}), agate_table=None), RunResult(status='skipped', timing=[], thread_id='WorkerThread-0', execution_time=0, adapter_response={}, message='Skipping due to fail_fast', failures=None, node=SourceDefinition( loaded_at_field=None, freshness=FreshnessThreshold(warn_after=Time(count=12, period='hour'), error_after=Time(count=24, period='hour'), filter=None), external=None, config=SourceConfig(_extra={}, enabled=True), patch_path=None, unrendered_config={},  created_at=1726662725.718098, _event_status={}), agate_table=None)], elapsed_time=2.5737338066101074, metadata=FreshnessMetadata(dbt_schema_version='https://schemas.getdbt.com/dbt/sources/v3.json', dbt_version='1.8.6', generated_at=datetime.datetime(2024, 9, 18, 12, 39, 43, 474534), invocation_id='ac660055-7b2e-43dd-96db-656dc8f14d46', env={})))
```

As can be seen, the operation returned `success=False` and `exception=None`. This should result in Prefect failing the flow, but it does not.

 [On line 190](https://github.com/PrefectHQ/prefect/blob/main/src/integrations/prefect-dbt/prefect_dbt/cli/commands.py#L190), `result.exception` is checked for truthful value but since the value is None program continues. 

[On line 216](https://github.com/PrefectHQ/prefect/blob/main/src/integrations/prefect-dbt/prefect_dbt/cli/commands.py#L216), `result.success` is checked for truthful value, which would catch the issue. However, there is an additional check `isinstance(result.result, RunExecutionResult)` which returns false because `FreshnessResult` is not instance of `RunExecutionResult`.

I think the easy fix is the change the instance check to compare against `ExecutionResult` class instead since both `RunExecutionResult` and `FreshnessResult`  are child classes of `ExecutionResult`.

### Version info (`prefect version` output)

```Text
Version:             2.20.6
API version:         0.8.4
Python version:      3.11.8
Git commit:          905bef9f
Built:               Thu, Sep 5, 2024 10:08 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.43.2
```

### Additional context

Dependencies:

```toml

[tool.poetry.dependencies]
python = "^3.11"
prefect = {extras = ["aws", "dbt"], version = "^2.20.3"}
prefect-dbt = {extras = ["snowflake"], version = "<0.6.2"}
```

**Comment by desertaxle** [comment] 2024-09-23 19:17
Thanks for the awesome write-up @e1337us3r! Since you've already found the root cause and a solution, would you want to submit a PR? If not, no worries; I think we'll be able to get a fix for this in the next release of `prefect-dbt`!

**Comment by e1337us3r** [comment] 2024-09-23 22:32
Sure, I'd be happy to do the PR

**Closed** 2024-09-27 22:20 UTC
Labels: bug
