### ISSUE TITLE
Copy button doesn't work - in a EC2 instance - possibly VPN related

### ISSUE THREAD

**Issue by bastien-k** [PrefectHQ/prefect#12070] opened 2024-02-23 12:51 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

On a Flow Runs, tab Parameters, there is a convenient Copy button on the right to copy the parameters JSON.
But this button do not work.  
The browser console shows this error when we click:
`TypeError: Cannot read properties of undefined (reading 'writeText')`

### Reproduction

Run a flow, go to the flow run, go to parameter tab, click on Copy button, try to past.

### Error

The browser console shows this error when we click:
`TypeError: Cannot read properties of undefined (reading 'writeText')`

### Browsers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Prefect version

```Text
Version:             2.15.0
API version:         0.8.4
Python version:      3.11.8
Git commit:          e90804b8
Built:               Thu, Feb 15, 2024 2:54 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          postgresql
```

**Comment by discdiver** [comment] 2024-02-23 16:05
Thank you for the report.

I'm not able to recreate on a self-hosted server instance with sqlite with Prefect 2.15.0 with chrome with un-nested parameters. 
{
  "issue_number": "22",
  "issue_text": "22",
  "user_login_name": "33"
}.

What data types are your parameters?

Does upgrading to 2.16.0 fix the issue?

**Comment by bastien-k** [comment] 2024-02-23 16:16
I upgraded to 2.16 and did a minimal test, the issue remain.

```python
@flow
def test_flow(str_input: str = "test"):
    return flow


if __name__ == "__main__":
    test_flow()
```

![image](https://github.com/PrefectHQ/prefect/assets/141129860/46d98032-e8a2-4800-8ded-22c6f770afc9)

**Comment by zhen0** [comment] 2024-02-26 21:16
Thanks for flagging @bastien-k I also cannot reproduce in a locally hosted version of the UI or Cloud.  I suspect there is something specific to your setup/the EC2 instance.  I'll add to our backlog to investigate further.

**Comment by pleek91** [comment] 2024-07-02 19:36
Most likely this is because the clipboard api of the browser is only available on localhost or in a secure context (https). So if you'd deployed prefect to an ec2 instance and are accessing it in an "unsecure" (nothing to do with actual vpn security but the url used to access it in the browser) then the browser is going to reject any attempts to manage the clipboard. This feature works on a local install and in cloud. So closing this issue.

**Closed by pleek91** 2024-07-02 19:36 UTC
Labels: bug, ui
