### ISSUE TITLE
Document `LOG_TO_CLOUD`

### ISSUE THREAD

**Issue by arlobryer** [PrefectHQ/prefect#2261] opened 2020-04-03 15:15 UTC
## Current behaviour
When attaching a logger to Prefects log handler, the logs don't appear in Prefect Cloud. This is because `PREFECT__LOGGING__LOG_TO_CLOUD` defaults to `False` in the code. Additionally, this parameter is undocumented in the logging docs for Prefect.

## Proposed behaviour
1. Document this parameter somewhere in https://docs.prefect.io/core/concepts/logging.html
2. Consider defaulting to `True`.

## Example
Logging configuration is critical for best use of the Cloud UI. Defaulting to `True` would make this more discoverable and explicit.

**Comment by joshmeek** [comment] 2020-04-03 15:30
Thanks for opening @arlobryer! I'm leaning more towards the documentation side because we want to avoid attempting to send logs to the API endpoint if not running in the context of a server or cloud run. That could also lead to unexpected errors with new users.

**Comment by cicdw** [comment] 2020-04-03 15:44
I don't think I fully understand the issue -- logging to cloud _does_ default to True anytime you run a Flow through an agent (which is the only way to run a Flow w/ Cloud).  We could definitely document how to turn it _off_ but it's always on by default in Cloud contexts.

**Comment by arlobryer** [comment] 2020-04-03 16:08
@cicdw - it seems that without the config set, the logs never make it to the Cloud UI. We found that we had to explicitly set that environment variable to see the logs appearing.

Does that makes sense? Otherwise we can definitely put together more details of what we were struggling with.

Thanks.

**Comment by joshmeek** [comment] 2020-04-03 16:55
@arlobryer Any chance you could provide a reproducible example? I'm looking through the code and it seems like the config should be automatically set when running in the context of a cloud/server run? 🤔

**Comment by lauralorenz** [comment] 2020-04-21 20:37
@arlobryer closing this issue for now since from our investigations it should be defaulted to True in this case, if you can get a reproducible example for us feel free to reopen. Thanks! :)

**Closed by lauralorenz** 2020-04-21 20:37 UTC
Labels: docs, enhancement
