### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by jmrichardson** [PrefectHQ/prefect#10956] opened 2023-10-15 15:27 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Using map function causes database to lock but everything seems to work correctly

### Reproduction

```python3
    features_add = [task.result() for task in features_create.map(feature_list, unmapped(data))]
```

### Error

```python3
Traceback (most recent call last):
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\engine\base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\engine\default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 113, in execute
    self._adapt_connection._handle_exception(error)
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 263, in _handle_exception
    raise error
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 95, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 125, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 185, in greenlet_spawn
    value = await result
  File "D:\Anaconda3\envs\mld\lib\site-packages\aiosqlite\cursor.py", line 48, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "D:\Anaconda3\envs\mld\lib\site-packages\aiosqlite\cursor.py", line 40, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "D:\Anaconda3\envs\mld\lib\site-packages\aiosqlite\core.py", line 133, in _execute
    return await future
  File "D:\Anaconda3\envs\mld\lib\site-packages\aiosqlite\core.py", line 106, in run
    result = function()
sqlite3.OperationalError: database is locked
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\mld\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\Anaconda3\envs\mld\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "D:\Anaconda3\envs\mld\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "D:\Anaconda3\envs\mld\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\Anaconda3\envs\mld\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\Anaconda3\envs\mld\lib\site-packages\prefect\_vendor\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "D:\Anaconda3\envs\mld\lib\site-packages\prefect\_vendor\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "D:\Anaconda3\envs\mld\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\Anaconda3\envs\mld\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\Anaconda3\envs\mld\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\Anaconda3\envs\mld\lib\site-packages\prefect\server\utilities\server.py", line 101, in handle_response_scoped_depends
    response = await default_handler(request)
  File "D:\Anaconda3\envs\mld\lib\site-packages\prefect\_vendor\fastapi\routing.py", line 251, in app
    raw_response = await run_endpoint_function(
  File "D:\Anaconda3\envs\mld\lib\site-packages\prefect\_vendor\fastapi\routing.py", line 177, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\Anaconda3\envs\mld\lib\site-packages\prefect\server\api\block_documents.py", line 41, in create_block_document
    return await models.block_documents.create_block_document(
  File "D:\Anaconda3\envs\mld\lib\site-packages\prefect\server\database\dependencies.py", line 119, in async_wrapper
    return await fn(*args, **kwargs)
  File "D:\Anaconda3\envs\mld\lib\site-packages\prefect\server\models\block_documents.py", line 54, in create_block_document
    await session.flush()
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 768, in flush
    await greenlet_spawn(self.sync_session.flush, objects=objects)
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 192, in greenlet_spawn
    result = context.switch(value)
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\orm\session.py", line 4179, in flush
    self._flush(objects)
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\orm\session.py", line 4314, in _flush
    with util.safe_reraise():
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\orm\session.py", line 4275, in _flush
    flush_context.execute()
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\orm\persistence.py", line 1226, in _emit_insert_statements
    result = connection.execute(
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\engine\base.py", line 1412, in execute
    return meth(
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\sql\elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\engine\base.py", line 1635, in _execute_clauseelement
    ret = self._execute_context(
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\engine\base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\engine\base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\engine\base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\engine\base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\engine\default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 113, in execute
    self._adapt_connection._handle_exception(error)
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 263, in _handle_exception
    raise error
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 95, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 125, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "D:\Anaconda3\envs\mld\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 185, in greenlet_spawn
    value = await result
  File "D:\Anaconda3\envs\mld\lib\site-packages\aiosqlite\cursor.py", line 48, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "D:\Anaconda3\envs\mld\lib\site-packages\aiosqlite\cursor.py", line 40, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "D:\Anaconda3\envs\mld\lib\site-packages\aiosqlite\core.py", line 133, in _execute
    return await future
  File "D:\Anaconda3\envs\mld\lib\site-packages\aiosqlite\core.py", line 106, in run
    result = function()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO block_document (name, data, is_anonymous, block_type_id, block_schema_id, id, created, updated) VALUES (:name, :data, :is_anonymous, :block_type_id, :block_schema_id, :id, :created, :updated)]
[parameters: {'name': 'anonymous-e11d75bf-756f-4997-b179-697c0efbe576', 'data': '"gAAAAABlLAPXHnwpJPl6yZyD5U9Ya9_NjytNITpVkJbaCT95wu43vfw4jevprNJd1RSABPfw2hWHEXTD9zA9lez7hWeM-hKkQQPluhvTtLo72m0Sjz73Bz4Tp4gH7XNf6jDJcbpsGOefrOLOPAeZAwowL7V1bib6pw=="', 'is_anonymous': 1, 'block_type_id': '965ac9c0-28cf-4b3c-aa45-3f02a567fabe', 'block_schema_id': 'a9bfbf71-aa21-4e4d-af83-196d6cd84491', 'id': '9dc76ace-8b10-44c5-87a3-ee8c9e365698', 'created': '2023-10-15 15:23:03.973249', 'updated': '2023-10-15 15:23:03.973249'}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

### Versions

```Text
Version:             2.13.5
API version:         0.8.4                   
Python version:      3.10.12                 
Git commit:          0fe4277b                
Built:               Thu, Oct 5, 2023 3:58 PM
OS/Arch:             win32/AMD64             
Profile:             default                 
Server type:         ephemeral               
Server:                                      
  Database:          sqlite
  SQLite version:    3.43.0
```

**Comment by jakekaplan** [comment] 2023-10-16 14:35
Hi @jmrichardson thanks for filing this issue! This is a duplicate of https://github.com/PrefectHQ/prefect/issues/10188. While this is a scary warning, it is not an error. The SQLite database will occasionally lock to ensure proper concurrent requests. Any request that fails due to this will retry.

**Closed by jakekaplan** 2023-10-16 14:35 UTC
Labels: bug
