### ISSUE TITLE
`from __future__ import annotations` causes flow initialization to fail with `issubclass arg must be a class`

### ISSUE THREAD

**Issue by NodeJSmith** [PrefectHQ/prefect#7502] opened 2022-11-10 21:04 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When using `from __future__ import annotations` flow initialization fails on `pydantic.create_model` with message `issubclass() arg must be a class`.

### Reproduction

```python3
from __future__ import annotations

from datetime import date

from prefect import flow


@flow
def main(dt: date):
    print("test")


if __name__ == "__main__":
    main(date(2021, 6, 30))
```

### Error

```python3
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/my_name/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/my_name/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/my_name/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/my_name/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/my_name/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/my_name/.vscode-server/extensions/ms-python.python-2022.18.2/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/my_name/source/my_project/src/generate_report.py", line 11, in <module>
    def main(dt: date):
  File "/home/my_name/source/my_project/venv/lib/python3.8/site-packages/prefect/flows.py", line 619, in flow
    Flow(
  File "/home/my_name/source/my_project/venv/lib/python3.8/site-packages/prefect/context.py", line 163, in __register_init__
    __init__(__self__, *args, **kwargs)
  File "/home/my_name/source/my_project/venv/lib/python3.8/site-packages/prefect/flows.py", line 171, in __init__
    self.parameters = parameter_schema(self.fn)
  File "/home/my_name/source/my_project/venv/lib/python3.8/site-packages/prefect/utilities/callables.py", line 159, in parameter_schema
    pydantic.create_model(
  File "pydantic/main.py", line 664, in pydantic.main.BaseModel.schema
  File "pydantic/schema.py", line 186, in pydantic.schema.model_schema
  File "pydantic/schema.py", line 580, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 621, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 254, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 526, in pydantic.schema.field_type_schema
  File "pydantic/schema.py", line 921, in pydantic.schema.field_singleton_schema
  File "/usr/lib/python3.8/abc.py", line 102, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
```

### Versions

```Text
Version:             2.6.6
API version:         0.8.3
Python version:      3.8.10
Git commit:          87767cda
Built:               Thu, Nov 3, 2022 1:15 PM
OS/Arch:             linux/x86_64
Profile:             data
Server type:         cloud
```

### Additional context

This is caused by [PEP 563](https://peps.python.org/pep-0563/), specifically:

```This PEP proposes changing function annotations and variable annotations so that they are no longer evaluated at function definition time. Instead, they are preserved in __annotations__ in string form.```

When using this import statement the value of `type_` in the below statement in `parameter_schema.py` is a string with the value `'date'`.
```python
pydantic.create_model("CheckParameter", __config__=ModelConfig, **{name:(type_, field)}).schema(by_alias=True)
```
If I manually change the value of `type_` to `date` (the class), then no error is raised. I don't have enough familiarity with `typing.get_type_hints` to provide suggestions, but I did confirm that if I use `typing.get_type_hints(fn)` I do get the `date` class, which we could then pass to `pydantic.create_model`.

**Comment by madkinsz** [comment] 2022-11-10 21:11
Thanks for the issue! I originally thought this was an upstream issue (see https://github.com/pydantic/pydantic/issues/2678) but with another look this does look to be caused by the way we are reading type hints to generate a model. We'll probably need to look into how Pydantic solves this problem, which is perhaps discussed in the linked issue.

**Comment by filpano** [comment] 2023-05-12 12:52
I ran into this exact same issue yesterday which causes me a lot of debugging head-scratching :).

This also seems to happen with other types, e.g. `pendulum.Date`. Removing the `from __future__ import annotations` import does indeed make the issue go away.

Interestingly, this bug caused my flow orchestration to go haywire, as my flow runs were crashing with an infrastructure failure and all I could see was:

Prefect `2.8.5` scheduled flow run (flow run logs):

```
Encountered exception during execution:
Traceback (most recent call last):
  File "/home/prefect/.local/lib/python3.10/site-packages/prefect/engine.py", line 665, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "/home/prefect/.local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 154, in run_sync_in_interruptible_worker_thread
    async with anyio.create_task_group() as tg:
  File "/home/prefect/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/home/prefect/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/prefect/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/prefect/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/prefect/.local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 135, in capture_worker_thread_and_result
    result = __fn(*args, **kwargs)
  File "/tmp/tmp8qibmy3oprefect/flow_definitions/product_classification_preprocessing.py", line 115, in update_tables
    update_athena_tables(date=date, process_full_month=process_full_month)
  File "/home/prefect/.local/lib/python3.10/site-packages/prefect/flows.py", line 468, in __call__
    return enter_flow_run_engine_from_flow_call(
  File "/home/prefect/.local/lib/python3.10/site-packages/prefect/engine.py", line 179, in enter_flow_run_engine_from_flow_call
    return run_async_from_worker_thread(begin_run)
  File "/home/prefect/.local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 177, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/home/prefect/.local/lib/python3.10/site-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/home/prefect/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/prefect/.local/lib/python3.10/site-packages/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "/home/prefect/.local/lib/python3.10/site-packages/prefect/engine.py", line 504, in create_and_begin_subflow_run
    result_factory = await ResultFactory.from_flow(
  File "/home/prefect/.local/lib/python3.10/site-packages/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "/home/prefect/.local/lib/python3.10/site-packages/prefect/results.py", line 139, in from_flow
    result_storage=flow.result_storage or ctx.result_factory.storage_block,
AttributeError: 'Flow' object has no attribute 'result_storage'
```

Prefect `2.10.8` scheduled flow run (agent logs):

```
/usr/lib/python3.10/runpy.py:126: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Engine execution of flow run 'd2ae38bc-51b7-4d78-a1f0-2d4f30c10fdf' exited with unexpected exception
Traceback (most recent call last):
  File "/home/prefect/.local/lib/python3.10/site-packages/prefect/engine.py", line 2233, in <module>
    enter_flow_run_engine_from_subprocess(flow_run_id)
  File "/home/prefect/.local/lib/python3.10/site-packages/prefect/engine.py", line 202, in enter_flow_run_engine_from_subprocess
    return from_sync.wait_for_call_in_loop_thread(
  File "/home/prefect/.local/lib/python3.10/site-packages/prefect/_internal/concurrency/api.py", line 215, in wait_for_call_in_loop_thread
    return call.result()
  File "/home/prefect/.local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 173, in result
    return self.future.result(timeout=timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/prefect/.local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 218, in _run_async
    result = await coro
  File "/home/prefect/.local/lib/python3.10/site-packages/prefect/client/utilities.py", line 40, in with_injected_client
    return await fn(*args, **kwargs)
  File "/home/prefect/.local/lib/python3.10/site-packages/prefect/engine.py", line 301, in retrieve_flow_then_begin_flow_run
    if flow.should_validate_parameters:
AttributeError: 'Flow' object has no attribute 'should_validate_parameters'
Process 'bright-dodo' exited with status code: 1
```

which doesn't seem to have anything to do with the issue at all (and was quite hard to debug)! I'm not a Python guru, but this smells like it might have something to do with dynamic imports...

**Comment by madkinsz** [comment] 2023-05-12 15:25
Hm I thought perhaps you were encountering https://github.com/PrefectHQ/prefect/issues/8688 but a fix is out in 2.10.7

**Comment by Andrew-S-Rosen** [comment] 2023-11-09 14:50
@zanieb: I have some more details. This is still a significant issue.

In Prefect 2.14.3, Pydantic 2.4.2, Python 3.10.13 run the following:

```python
from __future__ import annotations
from prefect import flow

class Test:
    pass

@flow
def foo(x: Test):
   print(x)
```

This yields the same error as originally reported. Removing the `from __future__ import annotations` line gets rid of the bug. Concerningly, setting `validate_parameters=False` does _not_ get rid of the bug, which is a major usability concern.

**Comment by zanieb** [comment] 2023-11-09 14:55
Thanks for the details Andrew — I'm not working on this project anymore perhaps @desertaxle can help instead.

**Comment by Andrew-S-Rosen** [comment] 2023-11-09 14:58
Sorry about that! Hope you're enjoying the new adventures :)

**Comment by jamesdow21** [comment] 2023-11-22 19:10
When the `from __future__ import annotations` switch is used, the insoect.Parameter.annotation attribute becomes a string instead of a type

The two ways of parsing the parameters (for v1 or v2 of pydantic) are [here](https://github.com/PrefectHQ/prefect/blob/d1894e8089d432cd62c7b63558fa75a8bf7049a7/src/prefect/utilities/callables.py#L275-L289) and [here](https://github.com/PrefectHQ/prefect/blob/d1894e8089d432cd62c7b63558fa75a8bf7049a7/src/prefect/_internal/pydantic/v2_schema.py#L59-L82)

Instead of returning `type_` directly after assigning it with `type_ = Any if param.annotation is inspect._empty else param.annotation`, you could check if it is a string and then [manually un-stringize](https://docs.python.org/3.10/howto/annotations.html#manually-un-stringizing-stringized-annotations) it (`inspect.get_annotations` is only available in Python 3.10+)

**Comment by Andrew-S-Rosen** [comment] 2023-11-22 21:31
@jamesdow21: Thanks, that is a great observation!! Are you interested in opening a PR for this? If not, I'll try to give it a go when I have some time since this is an important one for me (I'm not quite sure why more Prefect users aren't running into this...).

**Comment by jamesdow21** [comment] 2023-11-27 20:37
> @jamesdow21: Thanks, that is a great observation!! Are you interested in opening a PR for this? If not, I'll try to give it a go when I have some time since this is an important one for me (I'm not quite sure why more Prefect users aren't running into this...).

I can give it a shot in a couple days when I'll have some free time.  
I'm hoping that it can be a pretty easy implementation by essentially copy-pasting the source for `inspect.get_annotations` into src/prefect/utilities/compat.py  
The only trip up I'm worried about is if it is difficult to get the original globals and locals for the annotations after the handful of layers of passing around the decorated flow function


I'm also surprised that this isn't occurring more commonly, I always default to using the [PEP563](https://peps.python.org/pep-0563/) annotations (at least until my minimum version will be 3.13 with [PEP649](https://peps.python.org/pep-0649/) style annotations)

**Comment by Andrew-S-Rosen** [comment] 2023-12-17 20:55
If we don't want to copy source code, I suppose we could also just do a check if Python 3.10 is used and then call the `inspect.get_annotations` function directly.

**Comment by Andrew-S-Rosen** [comment] 2024-01-07 19:01
@jamesdow21 -- -FYI, I opened a PR in #11578.

**Closed** 2024-01-10 20:23 UTC
Labels: bug, status:accepted, needs:research, great writeup, orchestration
