### ISSUE TITLE
Flow hooks `on_crashed` / `on_cancellation` not executing correctly with KubernetesWorker

### ISSUE THREAD

**Issue by prefectcboyd** [PrefectHQ/prefect#10826] opened 2023-09-26 18:47 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Testing three separate scenarios for behavior:

1. ✅ Local (no deployment) via `python flow.py`
2. ✅ Local (process based worker deployment) via `prefect deployment run 'generic-testing-flow/hook_testing_local`
3. ❌ Remote (Kubernetes based worker deployment) via `prefect deployment run 'generic-testing-flow/hook_testing`

Testing local without a deployment, I can only confirm that `on_crashed` works through `Ctrl+C` as I cannot `CANCEL` a flow run without a backed deployment.

Testing local with a deployment (scenario 2), works with `on_cancelled` as expected.

Testing remote with a Kubernetes worker, neither the `on_cancelled` or `on_crashed` hooks execute.

### Reproduction

```python3
from prefect import task, flow, get_run_logger
import time

def handle_cancelled(flow, flow_run, state) -> None:
    print("cancelled!!!!!!!")


def handle_crashed(flow, flow_run, state) -> None:
    print("crashed!!!!!!!")

@task
def do_the_sleep():
    time.sleep(120)


@flow(name="generic-testing-flow", on_cancellation=[handle_cancelled], on_crashed=[handle_crashed])
def hello():
    logger = get_run_logger()
    logger.info("Testing Hello")
    print("Testing Hello Print")
    logger.info("Sleeping for 120 seconds")
    print("Sleeping for 120 seconds - Print")
    do_the_sleep()

if __name__ == "__main__":
    hello()
```

### Error

```python3
17:46:16.514 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - Running call get(timeout=1.9999816939234734) in thread 'APILogWorkerThread'
17:46:16.514 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - <WatcherThreadCancelScope, name='get' RUNNING, runtime=0.00> entered
17:46:18.515 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - <WatcherThreadCancelScope, name='get' COMPLETED, runtime=2.00> exited
17:46:18.515 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - Encountered exception in call get(timeout=1.9999816939234734)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 315, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/queue.py", line 179, in get
    raise Empty
_queue.Empty
17:46:18.515 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - Running call get(timeout=1.9999819993972778) in thread 'APILogWorkerThread'
17:46:18.516 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - <WatcherThreadCancelScope, name='get' RUNNING, runtime=0.00> entered
17:46:20.516 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - <WatcherThreadCancelScope, name='get' COMPLETED, runtime=2.00> exited
17:46:20.516 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - Encountered exception in call get(timeout=1.9999819993972778)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 315, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/queue.py", line 179, in get
    raise Empty
_queue.Empty
17:46:20.517 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - Running call get(timeout=1.99998389929533) in thread 'APILogWorkerThread'
17:46:20.517 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - <WatcherThreadCancelScope, name='get' RUNNING, runtime=0.00> entered
17:46:22.156 | DEBUG   | MainThread   | prefect._internal.concurrency - <WatcherThreadCancelScope, name='hello' COMPLETED, runtime=101.37> exited
17:46:22.156 | DEBUG   | MainThread   | prefect._internal.concurrency - Encountered exception in call hello()
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 315, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "flow.py", line 23, in hello
    do_the_sleep()
  File "/usr/local/lib/python3.9/site-packages/prefect/tasks.py", line 550, in __call__
    return enter_task_run_engine(
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1144, in enter_task_run_engine
    return from_sync.wait_for_call_in_loop_thread(begin_run)
  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/api.py", line 242, in wait_for_call_in_loop_thread
    waiter.wait()
  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/waiters.py", line 170, in wait
    self._handle_waiting_callbacks()
  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/waiters.py", line 137, in _handle_waiting_callbacks
    callback: Call = self._queue.get()
  File "/usr/local/lib/python3.9/queue.py", line 171, in get
    self.not_empty.wait()
  File "/usr/local/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1876, in cancel_flow_run
    raise TerminationSignal(signal=signal.SIGTERM)
prefect.exceptions.TerminationSignal
17:46:22.158 | DEBUG   | prefect.task_runner.concurrent - Shutting down task runner...
17:46:22.159 | INFO    | GlobalEventLoopThread | prefect._internal.concurrency - <WatcherThreadCancelScope, name='do_the_sleep' CANCELLED, runtime=101.00> cancelling
17:46:22.159 | DEBUG   | GlobalEventLoopThread | prefect._internal.concurrency - <WatcherThreadCancelScope, name='do_the_sleep' CANCELLED, runtime=101.00> sending exception to supervised thread <Thread(WorkerThread-2, started 140317789517504)>
17:46:22.161 | DEBUG   | GlobalEventLoopThread | prefect._internal.concurrency - Service <prefect.logging.handlers.APILogWorker object at 0x7f9e5d0e8250> enqueing item {'name': 'prefect.task_runs', 'level': 40, 'message': 'Crash detected! Execution was cancelled by the runtime environment.', 'timestamp': '2023-09-26T17:46:22.160626+00:00', 'flow_run_id': '88a5ed6b-a2bb-48e9-a265-af6266f649ea', 'task_run_id': 'ff97fa58-ebb5-4b12-a40f-38326b4184d3', '__payload_size__': 283}
17:46:22.160 | ERROR   | Task run 'do_the_sleep-0' - Crash detected! Execution was cancelled by the runtime environment.
17:46:22.164 | DEBUG   | GlobalEventLoopThread | prefect._internal.concurrency - Service <prefect.logging.handlers.APILogWorker object at 0x7f9e5d0e8250> enqueing item {'name': 'prefect.task_runs', 'level': 10, 'message': 'Crash details:\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 291, in aresult\n    return await asyncio.wrap_future(self.future)\nasyncio.exceptions.CancelledError\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1950, in report_task_run_crashes\n    yield\n  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1542, in begin_task_run\n    state = await orchestrate_task_run(\n  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1729, in orchestrate_task_run\n    result = await call.aresult()\n  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 293, in aresult\n    raise CancelledError() from exc\nprefect._internal.concurrency.cancellation.CancelledError', 'timestamp': '2023-09-26T17:46:22.164084+00:00', 'flow_run_id': '88a5ed6b-a2bb-48e9-a265-af6266f649ea', 'task_run_id': 'ff97fa58-ebb5-4b12-a40f-38326b4184d3', '__payload_size__': 1181}
17:46:22.164 | DEBUG   | Task run 'do_the_sleep-0' - Crash details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 291, in aresult
    return await asyncio.wrap_future(self.future)
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1950, in report_task_run_crashes
    yield
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1542, in begin_task_run
    state = await orchestrate_task_run(
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1729, in orchestrate_task_run
    result = await call.aresult()
  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 293, in aresult
    raise CancelledError() from exc
prefect._internal.concurrency.cancellation.CancelledError
17:46:22.178 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - <WatcherThreadCancelScope, name='get' COMPLETED, runtime=1.66> exited
17:46:22.179 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - Finished call get(timeout=1.99998389929533)
17:46:22.179 | DEBUG   | GlobalEventLoopThread | prefect._internal.concurrency - Service <prefect.logging.handlers.APILogWorker object at 0x7f9e5d0e8250> added item {'name': 'prefect.task_runs', 'level': 40, 'message': 'Crash detected! Execution was cancelled by the runtime environment.', 'timestamp': '2023-09-26T17:46:22.160626+00:00', 'flow_run_id': '88a5ed6b-a2bb-48e9-a265-af6266f649ea', 'task_run_id': 'ff97fa58-ebb5-4b12-a40f-38326b4184d3'} to batch (size 283/3000000)
17:46:22.183 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - Running call get(timeout=0.33781109750270844) in thread 'APILogWorkerThread'
17:46:22.185 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - <WatcherThreadCancelScope, name='get' RUNNING, runtime=0.00> entered
17:46:22.187 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - <WatcherThreadCancelScope, name='get' COMPLETED, runtime=0.00> exited
17:46:22.193 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - Finished call get(timeout=0.33781109750270844)
17:46:22.193 | DEBUG   | GlobalEventLoopThread | prefect._internal.concurrency - Service <prefect.logging.handlers.APILogWorker object at 0x7f9e5d0e8250> added item {'name': 'prefect.task_runs', 'level': 10, 'message': 'Crash details:\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 291, in aresult\n    return await asyncio.wrap_future(self.future)\nasyncio.exceptions.CancelledError\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1950, in report_task_run_crashes\n    yield\n  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1542, in begin_task_run\n    state = await orchestrate_task_run(\n  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1729, in orchestrate_task_run\n    result = await call.aresult()\n  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 293, in aresult\n    raise CancelledError() from exc\nprefect._internal.concurrency.cancellation.CancelledError', 'timestamp': '2023-09-26T17:46:22.164084+00:00', 'flow_run_id': '88a5ed6b-a2bb-48e9-a265-af6266f649ea', 'task_run_id': 'ff97fa58-ebb5-4b12-a40f-38326b4184d3'} to batch (size 1464/3000000)
17:46:22.196 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - Running call get(timeout=0.32156049460172653) in thread 'APILogWorkerThread'
17:46:22.197 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - <WatcherThreadCancelScope, name='get' RUNNING, runtime=0.00> entered
17:46:22.295 | DEBUG   | prefect.engine - Reported crashed task run 'do_the_sleep-0' successfully!
17:46:22.298 | DEBUG   | GlobalEventLoopThread | prefect._internal.concurrency - Service <prefect.logging.handlers.APILogWorker object at 0x7f9e5d0e8250> enqueing item {'name': 'prefect.flow_runs', 'level': 40, 'message': 'Crash detected! Execution was aborted by a termination signal.', 'timestamp': '2023-09-26T17:46:22.297888+00:00', 'flow_run_id': '88a5ed6b-a2bb-48e9-a265-af6266f649ea', 'task_run_id': None, '__payload_size__': 244}
17:46:22.297 | ERROR   | Flow run 'crafty-dolphin' - Crash detected! Execution was aborted by a termination signal.
17:46:22.299 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - <WatcherThreadCancelScope, name='get' COMPLETED, runtime=0.10> exited
17:46:22.302 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - Finished call get(timeout=0.32156049460172653)
17:46:22.303 | DEBUG   | GlobalEventLoopThread | prefect._internal.concurrency - Service <prefect.logging.handlers.APILogWorker object at 0x7f9e5d0e8250> enqueing item {'name': 'prefect.flow_runs', 'level': 10, 'message': 'Crash details:\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1913, in report_flow_run_crashes\n    yield\n  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 519, in begin_flow_run\n    terminal_or_paused_state = await orchestrate_flow_run(\n  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 829, in orchestrate_flow_run\n    result = await flow_call.aresult()\n  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 291, in aresult\n    return await asyncio.wrap_future(self.future)\n  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 315, in _run_sync\n    result = self.fn(*self.args, **self.kwargs)\n  File "flow.py", line 23, in hello\n    do_the_sleep()\n  File "/usr/local/lib/python3.9/site-packages/prefect/tasks.py", line 550, in __call__\n    return enter_task_run_engine(\n  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1144, in enter_task_run_engine\n    return from_sync.wait_for_call_in_loop_thread(begin_run)\n  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/api.py", line 242, in wait_for_call_in_loop_thread\n    waiter.wait()\n  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/waiters.py", line 170, in wait\n    self._handle_waiting_callbacks()\n  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/waiters.py", line 137, in _handle_waiting_callbacks\n    callback: Call = self._queue.get()\n  File "/usr/local/lib/python3.9/queue.py", line 171, in get\n    self.not_empty.wait()\n  File "/usr/local/lib/python3.9/threading.py", line 312, in wait\n    waiter.acquire()\n  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1876, in cancel_flow_run\n    raise TerminationSignal(signal=signal.SIGTERM)\nprefect.exceptions.TerminationSignal', 'timestamp': '2023-09-26T17:46:22.301821+00:00', 'flow_run_id': '88a5ed6b-a2bb-48e9-a265-af6266f649ea', 'task_run_id': None, '__payload_size__': 2175}
17:46:22.301 | DEBUG   | Flow run 'crafty-dolphin' - Crash details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1913, in report_flow_run_crashes
    yield
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 519, in begin_flow_run
    terminal_or_paused_state = await orchestrate_flow_run(
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 829, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 291, in aresult
    return await asyncio.wrap_future(self.future)
  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 315, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "flow.py", line 23, in hello
    do_the_sleep()
  File "/usr/local/lib/python3.9/site-packages/prefect/tasks.py", line 550, in __call__
    return enter_task_run_engine(
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1144, in enter_task_run_engine
    return from_sync.wait_for_call_in_loop_thread(begin_run)
  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/api.py", line 242, in wait_for_call_in_loop_thread
    waiter.wait()
  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/waiters.py", line 170, in wait
    self._handle_waiting_callbacks()
  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/waiters.py", line 137, in _handle_waiting_callbacks
    callback: Call = self._queue.get()
  File "/usr/local/lib/python3.9/queue.py", line 171, in get
    self.not_empty.wait()
  File "/usr/local/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1876, in cancel_flow_run
    raise TerminationSignal(signal=signal.SIGTERM)
prefect.exceptions.TerminationSignal
17:46:22.308 | DEBUG   | GlobalEventLoopThread | prefect._internal.concurrency - <function _get_state_result at 0x7f9e5dd01040> --> return coroutine for internal await
17:46:22.308 | DEBUG   | GlobalEventLoopThread | prefect._internal.concurrency - <function get_state_exception at 0x7f9e5dd01dc0> --> return coroutine for internal await
17:46:22.309 | DEBUG   | GlobalEventLoopThread | prefect._internal.concurrency - <AsyncCancelScope, name='get_task_call_return_value' COMPLETED, runtime=101.52> exited
17:46:22.311 | DEBUG   | GlobalEventLoopThread | prefect._internal.concurrency - Service <prefect.logging.handlers.APILogWorker object at 0x7f9e5d0e8250> added item {'name': 'prefect.flow_runs', 'level': 40, 'message': 'Crash detected! Execution was aborted by a termination signal.', 'timestamp': '2023-09-26T17:46:22.297888+00:00', 'flow_run_id': '88a5ed6b-a2bb-48e9-a265-af6266f649ea', 'task_run_id': None} to batch (size 1708/3000000)
17:46:22.312 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - Running call get(timeout=0.20580953359603882) in thread 'APILogWorkerThread'
17:46:22.314 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - <WatcherThreadCancelScope, name='get' RUNNING, runtime=0.00> entered
17:46:22.314 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - <WatcherThreadCancelScope, name='get' COMPLETED, runtime=0.00> exited
17:46:22.314 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - Finished call get(timeout=0.20580953359603882)
17:46:22.316 | DEBUG   | GlobalEventLoopThread | prefect._internal.concurrency - Service <prefect.logging.handlers.APILogWorker object at 0x7f9e5d0e8250> added item {'name': 'prefect.flow_runs', 'level': 10, 'message': 'Crash details:\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1913, in report_flow_run_crashes\n    yield\n  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 519, in begin_flow_run\n    terminal_or_paused_state = await orchestrate_flow_run(\n  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 829, in orchestrate_flow_run\n    result = await flow_call.aresult()\n  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 291, in aresult\n    return await asyncio.wrap_future(self.future)\n  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 315, in _run_sync\n    result = self.fn(*self.args, **self.kwargs)\n  File "flow.py", line 23, in hello\n    do_the_sleep()\n  File "/usr/local/lib/python3.9/site-packages/prefect/tasks.py", line 550, in __call__\n    return enter_task_run_engine(\n  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1144, in enter_task_run_engine\n    return from_sync.wait_for_call_in_loop_thread(begin_run)\n  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/api.py", line 242, in wait_for_call_in_loop_thread\n    waiter.wait()\n  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/waiters.py", line 170, in wait\n    self._handle_waiting_callbacks()\n  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/waiters.py", line 137, in _handle_waiting_callbacks\n    callback: Call = self._queue.get()\n  File "/usr/local/lib/python3.9/queue.py", line 171, in get\n    self.not_empty.wait()\n  File "/usr/local/lib/python3.9/threading.py", line 312, in wait\n    waiter.acquire()\n  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1876, in cancel_flow_run\n    raise TerminationSignal(signal=signal.SIGTERM)\nprefect.exceptions.TerminationSignal', 'timestamp': '2023-09-26T17:46:22.301821+00:00', 'flow_run_id': '88a5ed6b-a2bb-48e9-a265-af6266f649ea', 'task_run_id': None} to batch (size 3883/3000000)
17:46:22.317 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - Running call get(timeout=0.20068690925836563) in thread 'APILogWorkerThread'
17:46:22.317 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - <WatcherThreadCancelScope, name='get' RUNNING, runtime=0.00> entered
17:46:22.389 | DEBUG   | GlobalEventLoopThread | prefect._internal.concurrency - <AsyncCancelScope, name='retrieve_flow_then_begin_flow_run' COMPLETED, runtime=103.25> exited
17:46:22.389 | DEBUG   | GlobalEventLoopThread | prefect._internal.concurrency - Encountered exception in async call retrieve_flow_then_begin_flow_run(UUID('88a5ed6b-a2bb-48e9-a265-af6266f649ea'), user_thread=<_MainThread(MainThread, started 140318213...)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1913, in report_flow_run_crashes
    yield
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 519, in begin_flow_run
    terminal_or_paused_state = await orchestrate_flow_run(
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 829, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 291, in aresult
    return await asyncio.wrap_future(self.future)
  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 315, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "flow.py", line 23, in hello
    do_the_sleep()
  File "/usr/local/lib/python3.9/site-packages/prefect/tasks.py", line 550, in __call__
    return enter_task_run_engine(
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1144, in enter_task_run_engine
    return from_sync.wait_for_call_in_loop_thread(begin_run)
  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/api.py", line 242, in wait_for_call_in_loop_thread
    waiter.wait()
  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/waiters.py", line 170, in wait
    self._handle_waiting_callbacks()
  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/waiters.py", line 137, in _handle_waiting_callbacks
    callback: Call = self._queue.get()
  File "/usr/local/lib/python3.9/queue.py", line 171, in get
    self.not_empty.wait()
  File "/usr/local/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1876, in cancel_flow_run
    raise TerminationSignal(signal=signal.SIGTERM)
prefect.exceptions.TerminationSignal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 345, in _run_async
    result = await coro
  File "/usr/local/lib/python3.9/site-packages/prefect/client/utilities.py", line 51, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 441, in retrieve_flow_then_begin_flow_run
    return await begin_flow_run(
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 519, in begin_flow_run
    terminal_or_paused_state = await orchestrate_flow_run(
  File "/usr/local/lib/python3.9/contextlib.py", line 670, in __aexit__
    raise exc_details[1]
  File "/usr/local/lib/python3.9/contextlib.py", line 653, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/usr/local/lib/python3.9/contextlib.py", line 199, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1923, in report_flow_run_crashes
    flow_run_state = await propose_state(client, state, flow_run_id=flow_run.id)
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 2175, in propose_state
    raise prefect.exceptions.Abort(response.details.reason)
prefect.exceptions.Abort: Run is already in terminal state CANCELLED.
17:46:22.390 | INFO    | prefect.engine - Engine execution of flow run '88a5ed6b-a2bb-48e9-a265-af6266f649ea' aborted by orchestrator: Run is already in terminal state CANCELLED.
17:46:22.394 | DEBUG   | EventsWorkerThread | prefect._internal.concurrency - <WatcherThreadCancelScope, name='get' COMPLETED, runtime=101.12> exited
17:46:22.395 | DEBUG   | EventsWorkerThread | prefect._internal.concurrency - Finished call get()
17:46:22.395 | DEBUG   | GlobalEventLoopThread | prefect._internal.concurrency - Exiting service <prefect.events.worker.EventsWorker object at 0x7f9e54660700>
17:46:22.396 | INFO    | EventsWorkerThread | prefect._internal.concurrency - Exiting worker thread 'EventsWorkerThread'
17:46:22.397 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - <WatcherThreadCancelScope, name='get' COMPLETED, runtime=0.08> exited
17:46:22.397 | DEBUG   | APILogWorkerThread | prefect._internal.concurrency - Finished call get(timeout=0.20068690925836563)
17:46:22.398 | DEBUG   | GlobalEventLoopThread | prefect._internal.concurrency - Service <prefect.logging.handlers.APILogWorker object at 0x7f9e5d0e8250> processing batch of size 3883
17:46:22.520 | INFO    | APILogWorkerThread | prefect._internal.concurrency - Exiting worker thread 'APILogWorkerThread'
```

### Versions

```Text
# prefect version
Version:             2.13.2
API version:         0.8.4
Python version:      3.9.18
Git commit:          dcd8a58f
Built:               Thu, Sep 21, 2023 2:33 PM
OS/Arch:             linux/x86_64
Profile:             default
```

### Additional context

It also strikes me as interesting that the results for scenario 1 (local, no deployment) show the hook runs:
![image](https://github.com/PrefectHQ/prefect/assets/105737359/cdffbbd0-5c4a-48dd-aee8-9ec7bc19e757)

scenario 2 (local, with deployment) does not show the hook run in the UI, but I can get it from the worker logs. There's really no indication it ran from the UI at all.
![image](https://github.com/PrefectHQ/prefect/assets/105737359/95ae9ad9-3bc1-4c18-a92a-2bcf83313a3b)

scenario 3 (k8s, with deployment) obviously does not execute the hooks, so nothing gets reported, but also it's quite difficult to capture the logs, because the job is removed, tearing down the pod. This means, I have to start the flow-run, then go tail logs through CLI and dump the output, then cancel. 
![image](https://github.com/PrefectHQ/prefect/assets/105737359/38a7f162-f411-4134-90e3-7ba025b85928)

**Comment by serinamarie** [comment] 2023-09-26 19:28
All in all, this appears to be about differences in cancellation behavior:

```bash
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 345, in _run_async
    result = await coro
  File "/usr/local/lib/python3.9/site-packages/prefect/client/utilities.py", line 51, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 441, in retrieve_flow_then_begin_flow_run
    return await begin_flow_run(
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 519, in begin_flow_run
    terminal_or_paused_state = await orchestrate_flow_run(
  File "/usr/local/lib/python3.9/contextlib.py", line 670, in __aexit__
    raise exc_details[1]
  File "/usr/local/lib/python3.9/contextlib.py", line 653, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/usr/local/lib/python3.9/contextlib.py", line 199, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 1923, in report_flow_run_crashes
    flow_run_state = await propose_state(client, state, flow_run_id=flow_run.id)
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 2175, in propose_state
    raise prefect.exceptions.Abort(response.details.reason)
prefect.exceptions.Abort: Run is already in terminal state CANCELLED.
```

As far as this, we never make it to the point where we would run the `on_cancellation` and `on_crashed` flow run hooks, because we fail to propose a `CANCELLING` state when it's already in state `CANCELLED`. Even if we moved the logic up for running the flow run hooks, we only run on flows in a `CANCELLING` state, not in a `CANCELLED` state. 

Perhaps an `on_cancelled` hook is something we should consider implementing, since issues around differences in cancellation continue to arise, and we do not always appear to put our flows into a `CANCELLING` state before they are cancelled. 

https://github.com/PrefectHQ/prefect/blob/main/src/prefect/engine.py#L1923

**Comment by serinamarie** [comment] 2023-09-27 19:00
Hi @prefectcboyd, more consistency in our crash/cancellation callbacks is on our roadmap and we will be actively working on improving this behavior over the next couple of months!

**Comment by desertaxle** [comment] 2023-10-20 14:20
This issue should be resolved with the current experimental enhanced cancellation feature. I've tested the flow in the reproduction with the most recent `prefect` version (2.13.8), the most recent `prefect-kubernetes` version (0.4.1), and the `PREFECT_EXPERMENTAL_ENABLE_ENHANCED_CANCELLATION` setting enabled on my Kubernetes worker and I see the `on_cancellation` hooks firing on every canceled flow run. I expect this to be resolved for all users once we make enhanced cancellation the default.

**Comment by desertaxle** [comment] 2023-11-29 14:44
As of 2.14.6, enhanced cancellation is the default. Any workers upgraded to 2.14.6 should see consistent and reliable execution of the `on_cancellation` hook. The `on_crashed` hook will also be more reliable but will not run in scenarios where a Kubernetes job fails to start or dies before the `on_crashed` hook can run.

I'm closing this issue because the primary concern of the `on_cancellation` hook not firing has been resolved, but further work might be needed related to the `on_crashed` hook.

**Closed by desertaxle** 2023-11-29 14:44 UTC
Labels: bug, from:sales
