### ISSUE TITLE
Prefect CLI `work-pool create` fails for type `prefect-agent`

### ISSUE THREAD

**Issue by batuhanfaik** [PrefectHQ/prefect#9588] opened 2023-05-16 08:15 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When trying to create a work pool of type `prefect-agent` using the CLI, the error given below is raised. Creating a work pool of type `process` using the CLI does not raise any errors and creating a work pool of type `prefect-agent` using the REST API (or the UI) does not raise any errors.

### Reproduction

```python3
prefect work-pool create "test-pool"
```

### Error

```python3
Unknown work pool type 'prefect-agent'. Please choose from process.
```

### Versions

```Text
Version:             2.10.9
API version:         0.8.4
Python version:      3.9.13
Git commit:          1655c1fa
Built:               Thu, May 11, 2023 2:29 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
```

### Additional context

The Prefect server is located within the same Docker network as the container I am running the CLI command from.

I tried to see the root cause of this problem. Apparently `collections/views/aggregate-worker-metadata` endpoint returns an HTTP 500 status code.

### Digging Deeper

Adding print statements to [here](https://github.com/PrefectHQ/prefect/blob/c0d4e7777f5c3051f2fed8413a605290e381c2f3/src/prefect/cli/work_pool.py#L434-L436)
```text
Using base URL: http://<$PREFECT_API_URL>:4200/api
Using client: <prefect.client.orchestration.PrefectClient object at 0xMEMORYADDR>
Error getting worker metadata: Server error '500 Internal Server Error' for url 'http://<$PREFECT_API_URL>:4200/api/collections/views/aggregate-worker-metadata'
Response: {'exception_message': 'Internal Server Error'}
```

**Comment by desertaxle** [comment] 2023-05-23 17:31
@batuhanfaik does your Prefect server have access to GithHub? If not then this issue has the same root cause as https://github.com/PrefectHQ/prefect/issues/9377.

**Comment by batuhanfaik** [comment] 2023-05-23 17:53
If we're talking about an HTTP/S request to GitHub or something similar, I can simulate it within my network and share the results. Nonetheless, like yourself said, default configuration should be bundled imo

**Comment by serinamarie** [comment] 2024-03-12 21:45
Closing this as completed. Please feel free to open a new issue if it persists.

**Closed by serinamarie** 2024-03-12 21:45 UTC
Labels: bug, status:accepted, orchestration
