### ISSUE TITLE
Error about missing memory parameter when calling RegisterTaskDefinition in ECS Run

### ISSUE THREAD

**Issue by aroder** [PrefectHQ/prefect#5498] opened 2022-03-01 14:08 UTC
## Description

After upgrading to v1, my ECS Agent complains about a missing memory parameter. But the flow run's configuration shows that memory is indeed configured.

![image](https://user-images.githubusercontent.com/23650/156181136-b45a4a72-13ef-44b6-aa79-245323768861.png)

```
[2022-03-01 13:15:52,973] ERROR - agent | Exception encountered while deploying flow run 9f57aa12-452d-41e7-b27b-952981adc6f0	arn:aws:ecs:us-east-1:703668590763:task/datateer-prt/d0f9f91d90724e17b69c5ea7f296f883	prefect-fargate-agent-prt
3/1/2022, 6:15:52 AM	Traceback (most recent call last):	arn:aws:ecs:us-east-1:703668590763:task/datateer-prt/d0f9f91d90724e17b69c5ea7f296f883	prefect-fargate-agent-prt
3/1/2022, 6:15:52 AM	File "/usr/local/lib/python3.7/site-packages/prefect/agent/agent.py", line 388, in _deploy_flow_run	arn:aws:ecs:us-east-1:703668590763:task/datateer-prt/d0f9f91d90724e17b69c5ea7f296f883	prefect-fargate-agent-prt
3/1/2022, 6:15:52 AM	deployment_info = self.deploy_flow(flow_run)	arn:aws:ecs:us-east-1:703668590763:task/datateer-prt/d0f9f91d90724e17b69c5ea7f296f883	prefect-fargate-agent-prt
3/1/2022, 6:15:52 AM	File "/usr/local/lib/python3.7/site-packages/prefect/agent/ecs/agent.py", line 295, in deploy_flow	arn:aws:ecs:us-east-1:703668590763:task/datateer-prt/d0f9f91d90724e17b69c5ea7f296f883	prefect-fargate-agent-prt
3/1/2022, 6:15:52 AM	resp = self.ecs_client.register_task_definition(**taskdef)	arn:aws:ecs:us-east-1:703668590763:task/datateer-prt/d0f9f91d90724e17b69c5ea7f296f883	prefect-fargate-agent-prt
3/1/2022, 6:15:52 AM	File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 391, in _api_call	arn:aws:ecs:us-east-1:703668590763:task/datateer-prt/d0f9f91d90724e17b69c5ea7f296f883	prefect-fargate-agent-prt
3/1/2022, 6:15:52 AM	return self._make_api_call(operation_name, kwargs)	arn:aws:ecs:us-east-1:703668590763:task/datateer-prt/d0f9f91d90724e17b69c5ea7f296f883	prefect-fargate-agent-prt
3/1/2022, 6:15:52 AM	File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 719, in _make_api_call	arn:aws:ecs:us-east-1:703668590763:task/datateer-prt/d0f9f91d90724e17b69c5ea7f296f883	prefect-fargate-agent-prt
3/1/2022, 6:15:52 AM	raise error_class(parsed_response, operation_name)	arn:aws:ecs:us-east-1:703668590763:task/datateer-prt/d0f9f91d90724e17b69c5ea7f296f883	prefect-fargate-agent-prt
3/1/2022, 6:15:52 AM	botocore.errorfactory.ClientException: An error occurred (ClientException) when calling the RegisterTaskDefinition operation: Invalid setting for container 'flow'. At least one of 'memory' or 'memoryReservation' must be specified.	arn:aws:ecs:us-east-1:703668590763:task/datateer-prt/d0f9f91d90724e17b69c5ea7f296f883	prefect-fargate-agent-prt
3/1/2022, 6:15:52 AM	[2022-03-01 13:15:52,763] INFO - agent | Deploying flow run 9f57aa12-452d-41e7-b27b-952981adc6f0 to execution environment...	arn:aws:ecs:us-east-1:703668590763:task/datateer-prt/d0f9f91d90724e17b69c5ea7f296f883	prefect-fargate-agent-prt
3/1/2022, 6:07:40 AM	[2022-03-01 13:07:40,259] ERROR - agent | Deployment of 57a7b8dd-afc1-471c-bbac-216a8ec9f85b aborted!
```

## Expected Behavior

I expected the memory parameter from the flow's `run_config`  to be passed to AWS

## Reproduction

I have not been able to reproduce this outside of our operational environment

## Environment

We just upgraded to v1
```
{
  "config_overrides": {},
  "env_vars": [
    "PREFECT__USER_CONFIG_PATH"
  ],
  "system_information": {
    "platform": "Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.2.5",
    "prefect_backend": "cloud",
    "prefect_version": "1.0.0",
    "python_version": "3.8.7"
  }
}
```
We are setting the memory and we have a task definition--do those conflict?
```
   flow.run_config = ECSRun(
        cpu="1 vcpu",  
        memory="8 GB",
        task_definition=task_definition,
```

**Comment by anna-geller** [comment] 2022-03-08 19:03
Closing since the issue is apparently resolved by setting memory on a task definition
![image](https://user-images.githubusercontent.com/86264395/157307153-5f1ee1f8-69c8-4729-98d0-cebe86df249c.png)

**Closed by anna-geller** 2022-03-08 19:03 UTC
