### ISSUE TITLE
Error with prefect - missing 1 required positional argument

### ISSUE THREAD

**Issue by tommycarpi** [PrefectHQ/prefect#12583] opened 2024-04-03 22:17 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Since yesterday when I type "prefect" in console I get this error, and I cannot run any other job

Traceback (most recent call last):
  File "/opt/homebrew/bin/prefect", line 5, in <module>
    from prefect.cli import app
  File "/opt/homebrew/lib/python3.11/site-packages/prefect/cli/__init__.py", line 13, in <module>
    import prefect.cli.shell
  File "/opt/homebrew/lib/python3.11/site-packages/prefect/cli/shell.py", line 137, in <module>
    Optional[List[str]], typer.Option(help="Optional tags for the flow run.")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Option() missing 1 required positional argument: 'default'

Have you experienced this?
I've updated to the latest v2.16.8 but still same error.

### Reproduction

```python3
type "prefect" in console
```

### Error

```python3
Traceback (most recent call last):
  File "/opt/homebrew/bin/prefect", line 5, in <module>
    from prefect.cli import app
  File "/opt/homebrew/lib/python3.11/site-packages/prefect/cli/__init__.py", line 13, in <module>
    import prefect.cli.shell
  File "/opt/homebrew/lib/python3.11/site-packages/prefect/cli/shell.py", line 137, in <module>
    Optional[List[str]], typer.Option(help="Optional tags for the flow run.")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Option() missing 1 required positional argument: 'default'
```

### Versions

```Text
2.16.8
```

**Comment by zzstoatzz** [comment] 2024-04-03 22:34
hi @tommycarpi - this is due to a breaking change in `typer`, which should be fixed in `main` and will be released tomorrow

to verify the problem is fixed in `main` you could install it and check
```python
 pip install git+https://github.com/prefecthq/prefect.git
 ```
 
but in the meantime, you can downgrade `typer` to `0.11.0` I believe

I'll close this issue but please let me know if there's something else going on and I can re-open it

**Closed by zzstoatzz** 2024-04-03 22:34 UTC
Labels: bug, needs:triage
