### ISSUE TITLE
Pausing flow run from the UI exits the flow entirely

### ISSUE THREAD

**Issue by jspbach** [PrefectHQ/prefect#9269] opened 2023-04-20 05:47 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Pausing a flow run from the Prefect Server UI will exit the flow entirely instead of pausing it. This does not happen when the pause_flow_run() function is directly invoked inside the code, but it breaks live monitoring from the Prefect UI.

Attached is the graph for a perfect run using the minimal reproducible code below.
<img width="626" alt="image" src="https://user-images.githubusercontent.com/91104936/233268262-33f99eae-e6c3-4748-b1dc-3b2a61d7c58b.png">

### Reproduction
First, a minimal reproducible example.

```python3
from prefect import flow, task, get_run_logger
import time
@task
def append_1(num: str):
    time.sleep(6)
    return num + "1"

@task
def append_2(num: str):
    time.sleep(6)
    return num + "2"

@task
def append_num(num: str, append_with: str):
    time.sleep(6)
    return num + append_with

@task
def convert_str_to_int(num: str):
    time.sleep(6)
    return int(num)

from prefect.engine import pause_flow_run
@flow()
def minimal_reproducible_example(num: str):
    x = append_1.submit(num)
    y = append_2.submit(x.result())
    z = append_num.submit(y.result(), "12")
    logger = get_run_logger()
    logger.info(f"First result: {convert_str_to_int(x.result())}")
    # pause_flow_run(timeout=30)
    logger.info(f"Second result: {convert_str_to_int(y.result())}")
    logger.info(f"Third result: {convert_str_to_int(z.result())}")
```

The line pause_flow_run(timeout=30) is commented out, but we'll come back to this later. This is a minimal flow that, when run perfectly, will generate the DAG attached in the bug summary section.

### Error

```python3
When this flow is running and the user pauses that flow from the UI, it does not rerun when the user selects "Resume". This behavior is independent of the task runner (I tried with both SequentialTaskRunner and ConcurrentTaskRunner).

Looking into the logs generated with `prefect agent start -q 'default'`, I find that the process associated with the flow run is immediately terminated after the user hits Pause. Here's an example:


INFO    | Flow run 'pistachio-hyrax' - Executing 'convert_str_to_int-0' immediately...
INFO    | Task run 'convert_str_to_int-0' - Task run encountered a pause signal during orchestration.
INFO    | Flow run 'pistachio-hyrax' - Currently paused and suspending execution. Resume before (time) to finish execution.
INFO    | prefect.infrastructure.process - Process 'pistachio-hyrax' exited cleanly. #this is the line in question
INFO    | prefect.agent - Found 1 flow runs awaiting cancellation. # I cancelled the flow after realizing that it won't run again.
INFO    | prefect.agent - Killing process (hash):(pid) for flow run '(flow run ID)'...
WARNING | prefect.agent - Unable to kill process (pid): The process was not found. Marking flow run as cancelled.
```

This behavior is consistent across many versions and machines and Docker environments that I tested. However, if we specify the flow to run at a specific point in the code using pause_flow_run, then the function will run normally.
```


### Versions

```Text
Version:             2.10.4
API version:         0.8.4
Python version:      3.10.6
Git commit:          b6d0433a
Built:               Thu, Apr 13, 2023 5:34 PM
OS/Arch:             linux/aarch64
Profile:             default
Server type:         server
```

**Comment by billpalombi** [comment] 2023-04-20 13:40
Thanks for bringing to to our attention @jspbach, we'll look into it asap.

**Comment by madkinsz** [comment] 2023-04-24 19:02
I believe this was fixed by #9175 — can you confirm?

**Comment by madkinsz** [comment] 2023-05-25 18:03
@jspbach when you resume the flow run it should be rescheduled and run again — I do not think this is a bug I think this is how it's intended to work?

**Comment by jspbach** [comment] 2023-05-29 04:35
Thank you for alerting me. I haven't touched the retry function in weeks since I created this issue - will try to recreate it one more time. The bug I encountered was that when I paused a flow mid-run then the entire process associated with the flow seemed to be destroyed as well and so when I resumed the flow from paused state it would fail.

Is that how it's supposed to work? I am under the impression that "resume" will do what it does and pick up the flow from where it left, not restarting the flow from scratch; that would be "retry" instead. If I'm wrong please correct me.

**Comment by EmilRex** [comment] 2023-07-19 22:20
Just wanted to confirm that this is still happening as of 2.10.21

## Reproduction

1. Put the following in a file and execute it

```python
import time

from prefect import task, flow
from prefect.deployments import Deployment


@task
def wait():
    time.sleep(10)


@flow
def waiter():
    while True:
        wait()

if __name__ == '__main__':
    deployment = Deployment.build_from_flow(
        flow=waiter,
        name="default",
        work_queue_name="default",
        work_pool_name="default-agent-pool",
    )
    deployment.apply()
```

2. Run the deployment from the UI and wait for the flow run to start
3. Pause the flow run

## Logs

```
Agent started! Looking for work from queue(s): default...
18:14:59.143 | INFO    | prefect.agent - Submitting flow run 'cfe60903-7586-4156-bf52-7d1a2ff3d552'
18:15:00.192 | INFO    | prefect.infrastructure.process - Opening process 'mysterious-catfish'...
18:15:00.931 | INFO    | prefect.agent - Completed submission of flow run 'cfe60903-7586-4156-bf52-7d1a2ff3d552'
/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
18:15:02.173 | INFO    | Flow run 'mysterious-catfish' - Downloading flow code from storage at '/Users/emilchristensen/github/examples/pause'
18:15:03.062 | INFO    | Flow run 'mysterious-catfish' - Created task run 'wait-0' for task 'wait'
18:15:03.064 | INFO    | Flow run 'mysterious-catfish' - Executing 'wait-0' immediately...
18:15:13.825 | INFO    | Task run 'wait-0' - Finished in state Completed()
18:15:13.960 | INFO    | Flow run 'mysterious-catfish' - Created task run 'wait-1' for task 'wait'
18:15:13.961 | INFO    | Flow run 'mysterious-catfish' - Executing 'wait-1' immediately...
18:15:24.486 | INFO    | Task run 'wait-1' - Finished in state Completed()
18:15:24.573 | INFO    | Flow run 'mysterious-catfish' - Created task run 'wait-2' for task 'wait'
18:15:24.573 | INFO    | Flow run 'mysterious-catfish' - Executing 'wait-2' immediately...
18:15:24.808 | INFO    | Task run 'wait-2' - Task run encountered a pause signal during orchestration.
18:15:24.874 | INFO    | Flow run 'mysterious-catfish' - Currently paused and suspending execution. Resume before 2023-07-19T22:20:21.280000+00:00 to finish execution.
18:15:27.885 | INFO    | prefect.infrastructure.process - Process 'mysterious-catfish' exited cleanly.
```

## Version Info
```
Version:             2.10.21
API version:         0.8.4
Python version:      3.9.16
Git commit:          da816542
Built:               Thu, Jul 13, 2023 2:05 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         cloud
```

**Comment by EmilRex** [comment] 2023-07-19 22:31
Notably, pausing the flow run only stops the execution of new tasks. For example, with the following modification, the flow keeps running after being paused, and new tasks are created in the `NotReady` state,

```python
@flow
def waiter():
    while True:
        wait.submit()
        time.sleep(5)
```

**Closed** 2023-07-20 17:07 UTC
Labels: bug, needs:details, status:accepted, priority:medium, status:in-progress, orchestration
