### ISSUE TITLE
Default values of pydantic model flow parameters not shown in UI

### ISSUE THREAD

**Issue by j-tr** [PrefectHQ/prefect#9018] opened 2023-03-31 16:04 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

This seems to be a UI bug.

When deploying a flow with pydantic model parameters, the default parameters of the model are displayed in the UI instead of the default value for the flow parameter. However, on execution, the default values of the flow parameter are used, resulting in a mismatch between displayed parameters in the UI and actually used parameters during flow execution.

When deploying the code from the reproduction example, this results in a submission form with the value a=1.
![image](https://user-images.githubusercontent.com/11021147/229170044-a0d4d1a1-e155-457f-a6fe-9dfd66b45748.png)
When running the flow via the "Run" button, it gets executed with parameter a=2.
![image](https://user-images.githubusercontent.com/11021147/229170525-0a5f0301-f401-4e2c-9eb4-ce9e966ace19.png)

This causes two issues:
- Confusion about what parameter is actually used at flow submission
- **It makes it impossible to submit a flow with a=1!**

Note that this is relevant because the model definition could be external and could not be manipulated by the flow programmer, meaning that flow default parameters are the only way for the flow programmer to set default values.

### Reproduction

```python3
from prefect import flow
from pydantic import BaseModel


class Param(BaseModel):
    a: int = 1


@flow(
    name="PydanticModelUITest",
)
def main(
    *,
    param: Param = Param(a=2)
) -> None:
    print(param)


if __name__ == "__main__":
    main()
```

### Versions

```Text
Version:             2.9.0
API version:         0.8.4
Python version:      3.8.15
Git commit:          69f57bd5
Built:               Thu, Mar 30, 2023 1:08 PM
OS/Arch:             linux/x86_64
Server type:         cloud
```

**Comment by znicholasbrown** [comment] 2023-03-31 16:38
Hi @j-tr - thanks for the thorough issue; this does indeed look like a bug, though I think the UI is handling this appropriately. 

This looks to be an issue because the UI strips parameter values that match the defaults in the _parameter open api schema_ (the blob generated from your Pydantic models). However, that implicitly assumes that there are no runtime defaults, which is what's being used in this case. Unfortunately the UI can't assume that you want the schema default and send it anyway because then you could never use your runtime defaults either 🤔 

@madkinsz any thoughts how we might approach this? It feels like the UI is doing the appropriate value mapping and the issue is actually with differences between schema and runtime defaults but i'm not confident

**Comment by j-tr** [comment] 2023-04-03 07:54
hi @znicholasbrown, thanks for looking into this. 
I feel like simply displaying the runtime defaults (as available in the parameters tab) instead of the model defaults as default values in the UI fields and never stripping any values but submitting the flow explicitly with these defaults would solve the problem.
This would:
- prevent any confusion because the flow would always run with exactly the parameters that are visible in the UI on submission.
- enable the flow programmer to set the default values in the submission form even if they have no control over the model.
- cause no problems when submitting flows that match the runtime default values.
- if no runtime defaults are provided, model defaults could still be used as fallback.

What do you think?

**Comment by john-jam** [comment] 2023-04-11 08:25
We are also hitting this. The UI shows the default values of the pydantic models but not the overridden ones in the default values of the flow arguments.
[This related issue](https://github.com/PrefectHQ/prefect/issues/9055) was solved few hours ago. Any chance this also solves this issue?

**Comment by john-jam** [comment] 2023-04-11 09:02
To add more context to that bug, here's a reproducible example with a local prefect server and agent.

## Environment

```
Version:             2.10.2
API version:         0.8.4
Python version:      3.8.16
Git commit:          16747be2
Built:               Fri, Apr 7, 2023 10:19 AM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.31.1
```

## Flow code & deployment

```python
from prefect import flow, get_run_logger
from pydantic import BaseModel


class DummyParam(BaseModel):
    sub_param1: int = 1
    sub_param2: int = 1


flow_name = "dummy_flow"


@flow(name=flow_name)
def dummy_flow(
    dummy_param: DummyParam = DummyParam(sub_param1=2)
) -> None:
    get_run_logger().info(dummy_param)


if __name__ == "__main__":
    from prefect import get_client
    from prefect.deployments import Deployment
    import anyio
    import json

    deployment_name = "dummy_deployment"
    Deployment.build_from_flow(
        flow=dummy_flow,
        name=deployment_name,
        apply=True
    )

    async def check_deployment(name: str):
        async with get_client() as client:
            fetched_deployment = await client.read_deployment_by_name(name=name)
            print(json.dumps(fetched_deployment.parameter_openapi_schema, indent=4))

    anyio.run(check_deployment, f"{flow_name}/{deployment_name}")
```

**Output**:
```json
{
    "title": "Parameters",
    "type": "object",
    "properties": {
        "dummy_param": {
            "title": "dummy_param",
            "default": {
                "sub_param1": 2,
                "sub_param2": 1
            },
            "position": 0,
            "allOf": [
                {
                    "$ref": "#/definitions/DummyParam"
                }
            ]
        }
    },
    "definitions": {
        "DummyParam": {
            "title": "DummyParam",
            "type": "object",
            "properties": {
                "sub_param1": {
                    "title": "Sub Param1",
                    "default": 1,
                    "type": "integer"
                },
                "sub_param2": {
                    "title": "Sub Param2",
                    "default": 1,
                    "type": "integer"
                }
            }
        }
    }
}
```

## Results

Same behavior as described in this issue description: A default value of `1` showed in the UI but the value `2` used in the flow.

But we can see that the value `2` is properly defined in the `parameter_openapi_schema.properties` field but not in the `parameter_openapi_schema.definitions`. Maybe the UI could use the `parameter_openapi_schema.properties` to set the defaults?

**Comment by pleek91** [comment] 2024-03-05 14:58
In the new enhanced deployment parameters UI this now works as expected. When creating a new run from the ui the correct default value is rendered and that value is used when creating the run. This is available in cloud and will be available soon in OSS. 

![Image](https://github.com/PrefectHQ/prefect/assets/6200442/ded301fa-c04a-48d4-af67-d556ffc3ce0a)

**Comment by pleek91** [comment] 2024-03-21 18:50
Closing this issue since this has been fixed by enhanced deployment parameters. If anyone is still experiencing issues related to default values. Please open a new issue. Thank you everyone for your feedback!

**Closed by pleek91** 2024-03-21 18:50 UTC
Labels: bug, status:accepted, ui, great writeup, orchestration
