### ISSUE TITLE
Prefect CLI error

### ISSUE THREAD

**Issue by xiaodiannao** [PrefectHQ/prefect#1641] opened 2019-10-18 13:30 UTC
## Description
Hi everyone, I've just started playing with this very nice project. One thing I have some problems with though is the prefect CLI. I'm using the latest official Docker image and I added a hello_world workflow which executes fine if I run it with `python3 hello_world.py`. When I try to list the flows on using `prefect get flows` I'm getting the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/prefect", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/prefect/cli/get.py", line 103, in flows
    result = Client().graphql(query)
  File "/usr/local/lib/python3.6/site-packages/prefect/client/client.py", line 221, in graphql
    raise ClientError(result["errors"])
prefect.utilities.exceptions.ClientError: [{'message': 'Response not successful: Received status code 400', 'locations': [], 'path': ['flow'], 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'exception': {'response': {'size': 0, 'timeout': 0}, 'statusCode': 400, 'result': {'errors': [{'extensions': {'path': '$', 'code': 'invalid-headers'}, 'message': 'Missing Authorization header in JWT authentication mode'}]}}}}]
```

other commands such as `prefect get flow-runs` aren't working either and yield similar error messages.

## Expected Behavior
See a list of my flows

## Reproduction
1. Pull the Prefect Docker image (latest)
2. Add a hello_world.py flow inside Docker container (/usr/local/prefect/flows in my case) 
3. Run `prefect get flows` inside Docker container

## Environment
Official Prefect Docker image

**Comment by joshmeek** [comment] 2019-10-18 13:41
Hey @xiaodiannao the Prefect CLI is currently intended to be a communication method in conjunction with Prefect Cloud. This is due to the fact that managing these runs requires a persistence layer upon which Cloud provides for users!

For more information go [here](https://www.prefect.io/products/cloud-scheduler)

On another note I'm really glad you opened this issue because I am curious to hear your _expected behavior_ when using the Prefect CLI completely locally. We have some mechanisms built into Prefect which would allow for extendability of the CLI into the local space and this is great motivation for it!

**Comment by lauralorenz** [comment] 2020-04-06 17:37
Hi! This should now be supported with Prefect Core's server; check out version 0.10.0 if you are interested in maintaining state on your flows locally. Closing this now :)

**Closed by lauralorenz** 2020-04-06 17:37 UTC
Labels: discussion
