### ISSUE TITLE
Prefect does not "recognize" the exceptions of type "requests.exceptions.HTTPError". 

### ISSUE THREAD

**Issue by nmilushev** [PrefectHQ/prefect#4389] opened 2021-04-11 19:16 UTC
## Description
Prefect flow runs infinitely if a task throws "requests.exceptions.HTTPError". The task which throws the error is stuck on "Starting task run...".

## Expected Behavior
Prefect should "recognize" the exceptions of type "requests.exceptions.HTTPError" and the task run should fail.

## Reproduction
There is the following schematic.
![Screenshot from 2021-04-11 21-52-54](https://user-images.githubusercontent.com/32278538/114317347-530bdb00-9b10-11eb-96da-91224c344624.png)

The parameter _tickers_ is a string array. For each item the task _extract_ invokes a method from a python module which makes http requests. The task has retry_delay, max_retries and timeout assigned. However none of those is triggered upon exception of the mentioned type. To reproduce the bug, set the python module to raise a "requests.exceptions.HTTPError".

## Environment
prefect diagnostics:
```
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-4.15.0-140-generic-x86_64-with-Ubuntu-18.04-bionic",
    "prefect_backend": "cloud",
    "prefect_version": "0.13.19",
    "python_version": "3.6.9"
  }
}
```

**Comment by madkinsz** [comment] 2021-04-12 14:29
@nmilushev Thanks for the bug report! I'll take a look at this one as soon as possible as we definitely don't want to be hiding errors in your tasks.

**Comment by madkinsz** [comment] 2021-04-12 16:58
Hey @nmilushev -- I can't reproduce this with the following


```python
from prefect import Flow, task
from requests.exceptions import HTTPError
from datetime import timedelta


@task(max_retries=3, retry_delay=timedelta(seconds=1))
def err():
    raise HTTPError("Testing")


with Flow("test") as flow:
    err()

flow.run()
```

Or when registered and running with Cloud instead.

**Comment by nmilushev** [comment] 2021-04-12 17:48
Hi @madkinsz we'll do some scenarios on our end, will get back to you!

**Comment by nmilushev** [comment] 2021-04-12 19:25
Hi @madkinsz, please try the following task implementation:
```
@task(max_retries=3, retry_delay=timedelta(seconds=10), timeout=60)
def extract():
    session = requests.Session()
    response = session.get('https://www.linkedin.com/sasa/?_l=en_US')
    response.raise_for_status()
    return None
```

**Comment by zangell44** [comment] 2021-04-12 22:36
Hi @nmilushev 

I'm also struggling to reproduce the bug. The following flow fails correctly for me when calling `flow.run()` or with registering and running from Prefect Cloud. (using Python 3.6.9 and Prefect Core 0.13.19)

```python
from prefect import Flow, task
import requests
from datetime import timedelta

@task
def foo():
    return ['foo']

@task(max_retries=3, retry_delay=timedelta(seconds=10), timeout=60)
def extract(param):
    session = requests.Session()
    response = session.get('https://www.linkedin.com/sasa/?_l=en_US')
    response.raise_for_status()
    return None

with Flow('test-http-timeout') as flow:
    foos = foo()
    # add mapping in case this is mapping related
    extract.map(foos)

#flow.run()
#flow.register('Test')
```
Can you reproduce on your end with the minimal example above?

**Comment by nmilushev** [comment] 2021-04-13 19:47
Hi @zangell44,
using your setup works as expected on my side too.

There are three things in addition that can cause the issue.
1. Our flow has in addition `flow.environment`:
```
def prepare_flow():
    with Flow('test-http-timeout') as flow:
        foos = foo()
        # add mapping in case this is mapping related
        extract.map(foos)
        flow.environment = LocalEnvironment(
            labels=[], executor=LocalDaskExecutor(scheduler='threads', num_workers=1),
        )
        return flow


flow = prepare_flow()
# flow.register(project_name='Test')
# flow.run()
```
2. It stucks only when registering and running from the Cloud. Running it via `flow.run()` works as expected - no issue here.
3. The following lines should be located in another python module in a method and the method should be invoked in scope of the task. If they are directly placed in the task, as on your example, the flow behaves as expected - no issue in that case.
```
session = requests.Session()
response = session.get('https://www.linkedin.com/sasa/?_l=en_US')
response.raise_for_status()
```

**Comment by madkinsz** [comment] 2021-04-13 20:18
Hey @nmilushev -- can you try using your session in a `with` block? e.g. `with requests.Session() as s:`. It seems possible that you're encountering an issue with the session failing to close correctly.

It'd also be helpful if you could provide us with a simple, single file reproducible example.

**Comment by nmilushev** [comment] 2021-04-14 17:49
Hi @madkinsz, I tried wrapping it in a with block - same story.
One thing to clarify - we are running Prefect on a server of ours, not on Prefect Cloud.
Perhaps I should have begun with the modules structure - my bad.

File 1 (in my case another_module.py):
```
import prefect
import requests


def requester():
    logger = prefect.context.get("logger")
    logger.warning('entered requester')
    with requests.Session() as session:
        logger.warning('entered requester with')
        response = session.get('https://www.linkedin.com/sasa/?_l=en_US')
        response.raise_for_status()

```
File 2 (in my case simple_flow.py):
```
from datetime import timedelta
import prefect
from prefect import task, Flow
from prefect.engine.executors import LocalDaskExecutor
from prefect.environments import LocalEnvironment

# the import to another_module


@task
def foo():
    return ['foo']


@task(max_retries=3, retry_delay=timedelta(seconds=10), timeout=60)
def extract(param):
    logger = prefect.context.get("logger")
    logger.warning('invoked extract')
    another_module.requester()
    return None


def prepare_flow():
    with Flow('test-http-timeout') as f:
        foos = foo()
        extract.map(foos)
        # once I comment the below initialization, the flow doesn't stuck and the issue is gone
        f.environment = LocalEnvironment(
            labels=[], executor=LocalDaskExecutor(scheduler='threads', num_workers=1),
        )
        return f


flow = prepare_flow()
flow.register(project_name='test')
```
And here're the logs:
![Screenshot from 2021-04-14 20-39-56](https://user-images.githubusercontent.com/32278538/114755887-d1f85200-9d62-11eb-8211-092511761b59.png)

**Comment by madkinsz** [comment] 2021-04-14 18:09
Can you try using a `LocalRun` instead of a `LocalEnvironment` since that's deprecated functionality? It seems likely that the executor is the issue here. When you don't specify one, we'll use a non-Dask executor. While using a Dask executor you're more liable to encounter a hang like this. Also, does this occur when you remove the timeout? That adds a bit more complexity to the number of threads/processes.

Can you give us the output of `prefect diagnostics` as well?

**Comment by nmilushev** [comment] 2021-04-14 19:50
Yes, having removed the timeout the flow no more stucks. Even keeping `LocalEnvironment`.
Yes, having changed only the following:
```
f.environment = LocalEnvironment(
            labels=[], executor=LocalDaskExecutor(scheduler='threads', num_workers=1),
        )
``` 
with
```
f.run_config = LocalRun()
```
also seems to resolve the issue.
Are the two snippets from above interchangeable?

In the very beginning I've provided the prefect diagnostics for the server, but ever since I've been following your tips on my local machine, so here is the prefect diagnostics of my local machine:
```
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.8.0-49-generic-x86_64-with-glibc2.29",
    "prefect_backend": "server",
    "prefect_version": "0.13.16",
    "python_version": "3.8.5"
  }
}
```

**Comment by madkinsz** [comment] 2021-04-14 20:02
Thanks for providing the diagnostics again! It looks like you're on a pretty old version of Prefect. I just added some improvements to failed timeouts with https://github.com/PrefectHQ/prefect/pull/4384 -- would you mind trying the latest version or the `master` branch to see if we get some more details about what's going wrong with the timeout? I presume this is a pickling issue but I'm not sure. Does changing your executor to use `processes` instead of `threads` fix it while the timeout is being used?

Also yes those two snippets are roughly equivalent but you may want to set a `flow.executor = LocalDaskExecutor(...)` and `LocalRun(labels=[])` still. It seems likely the issue here is not in the `Environment` but in the timeout handler for a threaded scheduler.

**Comment by snenkov** [comment] 2021-04-14 20:06
Hi @madkinsz you mentioned that 

```
f.environment = LocalEnvironment(
            labels=[], executor=LocalDaskExecutor(scheduler='threads', num_workers=1),
        )
```
is depreciated. In this case how can a user use the Dask executor?
The reason I like it is because:
- it can run multiple jobs at the same time (i.e. on more than 1 cpu)
- it does a depth first execution vs the breadth first for the local

**Comment by madkinsz** [comment] 2021-04-14 21:36
@snenkov you just set `flow.executor = DaskExecutor()` instead

**Comment by zangell44** [comment] 2021-05-24 20:01
Assuming this is resolved now, closing

**Closed by zangell44** 2021-05-24 20:01 UTC
