### ISSUE TITLE
Multiprocessing deadlock

### ISSUE THREAD

**Issue by goaaron** [PrefectHQ/prefect#10794] opened 2023-09-21 21:03 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Running native python `multiprocessing` with more than 1 worker leads to a deadlock at the `.join()` step.  I am running this in a docker container.

### Reproduction

```python3
Inside a docker container:


import multiprocessing as mp

def mp_task(args):
    return 1

@flow 
def mp_flow():
    n_cpu = mp.cpu_count()
    pool = multiprocessing.Pool(processes=n_cpu)
    args = iter([1,2,3])

    res = pool.starmap(mp_task, args)
    pool.close()
    pool.join()
    return res
```

### Error

None, just 0 progress.

I will get full core utility across all cpus and then they just drop to 0. and no progress is made.

### Versions

```Text
prefect 2.13
```

**Comment by urimandujano** [comment] 2023-09-21 21:22
Thanks for submitting this issue! Can you provide information on the docker container you're running this code on?

Additionally, I'm getting a `TypeError` trying to run your reproduction code -- can you update your reproduction example with a working example?

**Comment by ori-scala** [comment] 2023-10-03 07:38
A bunch of us reported something similar here: https://discourse.prefect.io/t/prefect-flow-hangs-when-using-pool-join/3157/16
Would be great to have this fixed!

**Comment by ori-scala** [comment] 2023-10-11 16:17
@serinamarie Can we please get an estimation when this will be taken care of or at least looked at?

**Comment by urimandujano** [comment] 2023-10-12 22:48
It would be helpful to get details + an MRE for this issue. I still haven't been able to reproduce using my own example:

```python
# Python 3.8.17
import multiprocessing as mp

from prefect import flow


def mp_task(*args):
    print("hi", args)
    return 1


@flow
def mp_flow():
    n_cpu = mp.cpu_count()
    print(n_cpu)
    pool = mp.Pool(processes=n_cpu)

    res = pool.starmap(mp_task, [[1, 2], [2, 2]])
    pool.close()
    pool.join()
    return res


if __name__ == "__main__":
    mp_flow()
``

**Comment by ori-scala** [comment] 2023-10-15 14:53
@urimandujano Did you run in in a docker container as a subflow?

**Comment by coolbreeze2** [comment] 2023-10-27 04:26
> 获取此问题的详细信息和 MRE 会很有帮助。我仍然无法使用我自己的示例进行重现：
> 
> ```python
> # Python 3.8.17
> import multiprocessing as mp
> 
> from prefect import flow
> 
> 
> def mp_task(*args):
>     print("hi", args)
>     return 1
> 
> 
> @flow
> def mp_flow():
>     n_cpu = mp.cpu_count()
>     print(n_cpu)
>     pool = mp.Pool(processes=n_cpu)
> 
>     res = pool.starmap(mp_task, [[1, 2], [2, 2]])
>     pool.close()
>     pool.join()
>     return res
> 
> 
> if __name__ == "__main__":
>     mp_flow()
> ```

```
# Python 3.8.17
import multiprocessing as mp

from prefect import flow, get_run_logger


def mp_task(*args):
    print("hi", args)
    return 1


@flow
def mp_flow():
    # logger will block
    logger = get_run_logger()
    n_cpu = mp.cpu_count()
    logger.info(n_cpu)
    pool = mp.Pool(processes=n_cpu)

    res = pool.starmap(mp_task, [[1, 2], [2, 2]])
    pool.close()
    pool.join()
    return res


if __name__ == '__main__':
    mp_flow()

```

**Comment by ccueto36** [comment] 2023-11-07 16:50
I also am encountering this issue with one of my flows. My flow uses a third-party module that uses `mp.Pool()` and it causes the flow to hang at the `pool.join()` step. No errors are thrown, it just never performs the join and flow runs forever.

**Comment by GeorgeBark** [comment] 2023-11-20 15:11
Same here, the process hangs at the point of `pool.join()` any news or workaround? Thanks!

**Comment by urimandujano** [comment] 2023-11-29 19:56
Hey @goaaron @ori-scala @GeorgeBark! 

I was able to dig into this a bit more and I was able to replicate the issue under these conditions:

- python>=3.9 
- the flow and multiprocessing subflow run inside of docker containers

It looks like the issue is that in a container, `multiprocessing` will create new processes using `fork` and according to the python docs 
> Note that safely forking a multithreaded process is problematic.

The reason this isn't an issue when running directly on a laptop is because `multiprocessing` will create new processes using `spawn`. The fix here should be to force the `multiprocessing.Pool` to `spawn` new processes:

```python
    ...
    pool = mp.get_context("spawn").Pool(processes=n_cpu)
    res = pool.starmap(mp_task, [[1, 2], [2, 2]])
    ...
```

I was able to get past the hangs after updating my `Pool` creation code. Can you try this work around and let me know how it goes?

**Comment by urimandujano** [comment] 2023-11-29 20:02
@ccueto36 I'm not sure how to best handle your situation. This behavior is coming from the stdlib so I would expect the fix to be implemented in whatever code is creating the `Pool`. Since `prefect` isn't creating the pool, I don't think this is something we should set on our end -- in my opinion it should be set in the 3rd party code. 

As a quick work around, it looks like [you can configure the multiprocessing context](https://docs.python.org/3.9/library/multiprocessing.html#multiprocessing.set_start_method) to use `spawn` but keep in mind you'd probably need to configure the context before the 3rd party code ever creates its pool.

**Comment by urimandujano** [comment] 2023-12-12 16:02
I'm going to close this but I can re-open this issue if the clarification above isn't sufficient and the issues persist.

**Closed by urimandujano** 2023-12-12 16:02 UTC
Labels: bug

**Comment by ori-scala** [comment] 2024-02-19 18:24
@urimandujano Sorry for the late response. I've just got back to testing this one but now I'm getting the exact same issue described here: https://github.com/PrefectHQ/prefect/issues/9329

Tried with and without your suggestion, getting the same pickle error.

**Comment by ori-scala** [comment] 2024-02-19 18:57
Actually, I get this error:
```

Traceback (most recent call last):
--
  | 2024-02-19T20:39:27.671+02:00 | File "/root/micromamba/envs/scala/lib/python3.10/site-packages/prefect/engine.py", line 870, in orchestrate_flow_run
  | 2024-02-19T20:39:27.671+02:00 | result = await flow_call.aresult()
  | 2024-02-19T20:39:27.671+02:00 | File "/root/micromamba/envs/scala/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 294, in aresult
  | 2024-02-19T20:39:27.671+02:00 | return await asyncio.wrap_future(self.future)
  | 2024-02-19T20:39:27.671+02:00 | File "/root/micromamba/envs/scala/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 319, in _run_sync
  | 2024-02-19T20:39:27.671+02:00 | result = self.fn(*self.args, **self.kwargs)
  | 2024-02-19T20:39:27.671+02:00 | File "/tmp/tmpe810_183prefect/scala/prefect/run_commands.py", line 43, in flow_run_commands
  | 2024-02-19T20:39:27.671+02:00 | pool.starmap(run_command, zip(commands, [local_path] * len(commands)))
  | 2024-02-19T20:39:27.671+02:00 | File "/root/micromamba/envs/scala/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
  | 2024-02-19T20:39:27.671+02:00 | return self._map_async(func, iterable, starmapstar, chunksize).get()
  | 2024-02-19T20:39:27.671+02:00 | File "/root/micromamba/envs/scala/lib/python3.10/multiprocessing/pool.py", line 774, in get
  | 2024-02-19T20:39:27.671+02:00 | raise self._value
  | 2024-02-19T20:39:27.671+02:00 | File "/root/micromamba/envs/scala/lib/python3.10/multiprocessing/pool.py", line 540, in _handle_tasks
  | 2024-02-19T20:39:27.671+02:00 | put(task)
  | 2024-02-19T20:39:27.671+02:00 | File "/root/micromamba/envs/scala/lib/python3.10/multiprocessing/connection.py", line 206, in send
  | 2024-02-19T20:39:27.671+02:00 | self._send_bytes(_ForkingPickler.dumps(obj))
  | 2024-02-19T20:39:27.671+02:00 | File "/root/micromamba/envs/scala/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
  | 2024-02-19T20:39:27.671+02:00 | cls(buf, protocol).dump(obj)
  | 2024-02-19T20:39:27.671+02:00 | _pickle.PicklingError: Can't pickle <function run_command at 0x7f7beb44d630>: import of module '__prefect_loader__' failed
  | 2024-02-19T20:39:27.830+02:00 | 18:39:27.828 \| ERROR \| Flow run 'sandy-alligator' - Finished in state Failed("Flow run encountered an exception. PicklingError: Can't pickle <function run_command at 0x7f7beb44d630>: import of module '__prefect_loader__' failed")


```

After commenting out line 166 in `importtools.py`, I get:
```

2024-02-19T20:48:54.446+02:00 | /root/micromamba/envs/scala/lib/python3.10/runpy.py:126: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
-- | --
  | 2024-02-19T20:48:54.446+02:00 | warn(RuntimeWarning(msg))
  | 2024-02-19T20:48:54.452+02:00 | Process SpawnPoolWorker-3:
  | 2024-02-19T20:48:54.453+02:00 | Traceback (most recent call last):
  | 2024-02-19T20:48:54.454+02:00 | File "/root/micromamba/envs/scala/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
  | 2024-02-19T20:48:54.454+02:00 | self.run()
  | 2024-02-19T20:48:54.455+02:00 | File "/root/micromamba/envs/scala/lib/python3.10/multiprocessing/process.py", line 108, in run
  | 2024-02-19T20:48:54.455+02:00 | self._target(*self._args, **self._kwargs)
  | 2024-02-19T20:48:54.455+02:00 | File "/root/micromamba/envs/scala/lib/python3.10/multiprocessing/pool.py", line 114, in worker
  | 2024-02-19T20:48:54.455+02:00 | task = get()
  | 2024-02-19T20:48:54.456+02:00 | File "/root/micromamba/envs/scala/lib/python3.10/multiprocessing/queues.py", line 367, in get
  | 2024-02-19T20:48:54.456+02:00 | return _ForkingPickler.loads(res)
  | 2024-02-19T20:48:54.457+02:00 | ModuleNotFoundError: No module named '__prefect_loader__'

```

Using prefect 2.15.0

Please advise

**Comment by ori-scala** [comment] 2024-02-19 20:15
1 more note - Was able to get the hanging again by using
```
n_cpu = mp.cpu_count()
pool = mp.Pool(processes=n_cpu)
for args in [[1, 2], [2, 2]]:
    partial = functools.partial(mp_task, args)
    pool.apply_async(partial)
pool.close()
pool.join()
```
when replacing `pool = mp.Pool(processes=n_cpu)` with `pool = mp.get_context("spawn").Pool(processes=n_cpu)` it did stop hanging *BUT* it just went through it without actually running the tasks. I guess using the "spawn" thing isn't the right solution for us.

**Comment by amelie-liveeo** [comment] 2024-02-20 10:26
We're also having similar issues with hanging tasks when used in combination with multiprocessing. Here is the issue we are running into. This code hangs forever on `process.join()`. However, it does not hang when the function `run_processes` is not decorated as a function. 

```
from multiprocessing import Process
from prefect import flow, task

@task
def run_processes():
    def processing_task():
        pass

    process = Process(target=processing_task)
    process.start()
    process.join()


@flow()
def main() -> None:
    run_processes()

main()
```

**Comment by j-tr** [comment] 2024-02-21 10:24
@urimandujano configuring multiprocessing to use "spawn" as start method is only a partial workaround as there are many situations where this might not work (spawn generally requires that objects required by the subprocess are picklable, which is not always possible).

From my experience with Prefect so far, multiprocessing within tasks was often a bit tricky. Are there any best practices regarding multiprocessing in Prefect and known limitations that developers should keep in mind?

**Comment by ori-scala** [comment] 2024-02-21 16:25
@amelie-liveeo Trying to run your snippet, the code fail for me with a pickling issue: `AttributeError: Can't pickle local object 'run_processes.<locals>.processing_task'`
AFAIK, `pickle` can't pickle functions. Are you using `dill` or some other package instead of `pickle`?

**Comment by urimandujano** [comment] 2024-02-21 16:37
@amelie-liveeo - you might have more success creating your `multiprocessing.Process` object in the way below:

```python
import multiprocessing as mp

mp.set_start_method("spawn")
process = mp.Process(target=processing_function)
process.start()
process.join()
```

but I think that the moment `processing_function` becomes a task-decorated function we'll see the pickling errors that are being reported in this thread.

I'll ask internally for more information on what types of limitations we have when using `prefect` and `multiprocessing`, but I do know that the `multiprocessing` use case hasn't been one that we've actively worked to support. What are some of your use cases are for running a task through multiprocessing? We have something similar with our `task.submit` / `task.map` interfaces that would support non-blocking execution and it feels like there's a chance to build on that to handle some of the cases here.

**Comment by ori-scala** [comment] 2024-02-21 17:55
Our use case for using multiprocessing and not using Prefect's tasks are for tiny processes that would crush the Prefect's API. Let's say I'd like to run 8 subprocesses on an 8 core machine. Running them through Prefect would be 1flow + 8 tasks while using multiprocessing means just 1 flow. Using Prefect tasks caused the API to throttle and crush the whole flow.

**Comment by amelie-liveeo** [comment] 2024-02-22 08:26
> I'll ask internally for more information on what types of limitations we have when using prefect and multiprocessing, but I do know that the multiprocessing use case hasn't been one that we've actively worked to support.

@urimandujano I see, yes that would be interesting to get some more information about the limitations.

 > What are some of your use cases are for running a task through multiprocessing? 

The example is a simplified version of the problem we are running into. We have an internal library of which one class uses multiprocessing. We would like to use this class within a prefect task. We have multiple levels of parallel processing meaning we already make use of  `task.submit`. We are allocating a couple of CPUs for each of these tasks and to be able to use them optimally we would like to use multiprocessing for this. However, if multiprocessing within a task isn't really a supported use case in prefect, we might resort to a single process for now.   

> Are you using dill or some other package instead of pickle?

@ori-scala No, nothing outside of `pickle` as far as I know.

**Comment by gcasella** [comment] 2024-02-22 22:23
Couple things regarding the way i'm trying to use this..

sample code: 

```
def execute_compute():
    custom_logger.info("test concurrent futures")
    with concurrent.futures.ProcessPoolExecutor(max_workers=20) as executor:
        custom_logger.info("inside concurrent new_function (mp_context change)")
        results = list(executor.map(compute, [1,2,3,4,5,6,7,8,9]))
        custom_logger.info("after futures")
        custom_logger.info(results)
        # executor.shutdown()


def compute(n):
    custom_logger.info(f"Compute square of {n}")
    return n * n       
 

@flow()
def main_flow():
    execute_compute()


if __name__ == "__main__":
    wnce_flow()

```


For this to work i had to actually comment out line 166
https://github.com/PrefectHQ/prefect/blob/main/src/prefect/utilities/importtools.py#L166


after doing that I can actually see my concurrent futures getting executed and completed this time. however it will never close off the `ProcessPoolExecutor` (at the time of writing this, it's been running for 6 minutes.)

<img width="2907" alt="image" src="https://github.com/PrefectHQ/prefect/assets/7719536/3f832c49-0add-4656-b867-e8dcdbffcfc3">
<img width="494" alt="image" src="https://github.com/PrefectHQ/prefect/assets/7719536/88121f69-78ad-48c4-b322-8096be0c322e">

**Comment by j-tr** [comment] 2024-02-26 13:47
thank you @urimandujano for the input. unfortunately, i couldn't get it running with any of the above mentioned approaches. as suggested by you, i opened another issue #12083 with a more specific MRE for my use case.
