### ISSUE TITLE
Flow run UI fails to render when task returns state with custom name

### ISSUE THREAD

**Issue by Cassy343** [PrefectHQ/prefect#9945] opened 2023-06-14 20:34 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I was following the example [here](https://github.com/PrefectHQ/prefect/issues/9347#issuecomment-1532186528) when I ran into this issue. When specifying `name="Skipped"` to the `Completed` function, everything runs normally except the flow run diagram fails to render in the UI. If that keyword argument is removed, then everything runs normally and renders normally.

I pasted the problematic code from the linked example below and did my best to transfer the errors that appear in console when loading the flow run page.

### Reproduction

```python3
def my_task_wrapper(fn):
    @functools.wraps(fn)
    def wrapper(*args, **kwargs):
        skip_tasks = kwargs.pop("skip_tasks", _SKIP_TASKS.get())
        if fn.__name__ in skip_tasks:
            # Below is what causes the issue
            return Completed(name="Skipped")
        return fn(*args, **kwargs)

    return wrapper
```

### Error

```python3
Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
index-b49daa9a.js:89 jX
execute @ index-b49daa9a.js:89
index-b49daa9a.js:1 TypeError: this.isNewValue is not a function
    at Object.add (index-b49daa9a.js:95:349491)
    at index-b49daa9a.js:95:350735
    at rh (index-b49daa9a.js:1:14273)
    at Uu (index-b49daa9a.js:1:14352)
    at W (index-b49daa9a.js:1:24076)
    at SU (index-b49daa9a.js:1:15480)
    at Ct (index-b49daa9a.js:1:48753)
    at e3.ce [as fn] (index-b49daa9a.js:1:47668)
    at e3.run (index-b49daa9a.js:1:5719)
    at it.update (index-b49daa9a.js:1:48588)
zP @ index-b49daa9a.js:1
127.0.0.1:4200/api/flow_runs/filter:1     Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
index-b49daa9a.js:89 jX
execute @ index-b49daa9a.js:89
127.0.0.1:4200/api/flow_runs/filter:1     Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
index-b49daa9a.js:89 jX
execute @ index-b49daa9a.js:89
index-b49daa9a.js:1198 Uncaught TypeError: Cannot read properties of undefined (reading 'default')
    at BP.node [as _value] (index-b49daa9a.js:1198:43939)
    at jKt.drawBox (index-b49daa9a.js:1198:5459)
    at jKt.initBox (index-b49daa9a.js:1198:5142)
    at new jKt (index-b49daa9a.js:1198:2634)
    at PO.createNode (index-b49daa9a.js:1198:25446)
    at index-b49daa9a.js:1198:25129
    at Array.forEach (<anonymous>)
    at PO.renderLayout (index-b49daa9a.js:1198:25021)
    at layoutWorker.onmessage (index-b49daa9a.js:1198:24540)
```

### Versions

```Text
Version:             2.10.10
API version:         0.8.4
Python version:      3.10.10
Git commit:          8159450b
Built:               Thu, May 18, 2023 3:43 PM
OS/Arch:             darwin/x86_64
Profile:             default
Server type:         server
```

**Comment by znicholasbrown** [comment] 2023-06-14 20:41
Hi @Cassy343 - this looks to be a duplicate of [this issue](https://github.com/PrefectHQ/prefect/issues/9689), which was addressed in [this PR](https://github.com/PrefectHQ/prefect-ui-library/pull/1448) and released in [2.10.11](https://github.com/PrefectHQ/prefect/blob/main/RELEASE-NOTES.md#release-21011) (one patch version above yours)

Let me know that doesn't fix your issue and we can reopen!

**Closed by znicholasbrown** 2023-06-14 20:41 UTC
Labels: bug, status:duplicate
