### ISSUE TITLE
Block types in 3.0 need to use 3.0 documentation links consistently

### ISSUE THREAD

**Issue by abrookins** [PrefectHQ/prefect#15222] opened 2024-09-04 18:42 UTC
### Bug summary

Some Block types link to 2.0 documentation that gets redirected to the 3.0 Getting Started Guide. For example, see the Local File System block: https://github.com/PrefectHQ/prefect/blob/main/src/prefect/filesystems.py#L87

### Version info (`prefect version` output)

```Text
This problem exists on the main branch, so all 3.0 releases are affected.
```

**Comment by discdiver** [comment] 2024-09-04 18:47
Closing as duplicate of #14267. Working on the updates. :)

**Closed by discdiver** 2024-09-04 18:47 UTC
Labels: bug
