### ISSUE TITLE
Request for a component/deployment diagram

### ISSUE THREAD

**Issue by reece** [PrefectHQ/prefect#4320] opened 2021-03-30 23:41 UTC
Hello!

I've found an issue here:`API`
Page reference: https://docs.prefect.io/orchestration/concepts/api.html

Overall, the docs are fabulous. Thank you.

Before diving into the API, I would find it very helpful to have a deployment and/or component diagram that showed a full Prefect system: a backend (i.e., server or cloud), prefect daemon, and the various flavors of agents. The best I've found is the Server Architecture diagram, but I want details above the dotted line in that figure.

The terminology of core, backend, server, cloud, client, agent and all the flavors, flow, runner is confusing. The docs are also a bit confusing when it comes to running prefect using docker, running within docker, or running a docker image. Finding a way to diagram all of this complexity would be helpful.

Closely related to this, it would be helpful to have real-world deployment architectures and recommendations. A tutorial on getting prefect up with k8s would be fabulous.

**Comment by madkinsz** [comment] 2021-03-31 00:03
I'm probably going to close this as a duplicate of https://github.com/PrefectHQ/prefect/issues/4187 but I appreciate the additional context you've provided, thanks @reece !

The flow deployment patterns discussed at https://github.com/PrefectHQ/prefect/discussions/4042 may be helpful.

To get started on K8s, all you really need to do is install an agent if you're using Cloud (our CLI will generate a manifest for you). If you're using Server, you may want take a look at [this livestream](https://www.youtube.com/watch?v=EwsMecjSYEU) and the [Helm chart readme](https://github.com/PrefectHQ/server/tree/master/helm/prefect-server). Your flows will run without additional configuration but there are many configuration options available if you want to customize your K8s jobs. Which steps would you want to be included in a tutorial? (fishing for a more fleshed out idea of what we could do here)

**Comment by reece** [comment] 2021-03-31 00:14
The two cited issues are exactly what I'm looking for. Thanks.

Yes, okay to close this issue.

**Closed** 2021-03-31 00:16 UTC
