### ISSUE TITLE
Flow Run fails when base_image="python:3.7" and prefect_version="0.7.0" are set

### ISSUE THREAD

**Issue by nanseay** [PrefectHQ/prefect#1700] opened 2019-11-04 22:38 UTC
## Description
'RemoteEnvironment' object has no attribute 'on_start'
Traceback (most recent call last):
  File "/usr/local/bin/prefect", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/prefect/cli/execute.py", line 79, in cloud_flow
    raise exc
  File "/usr/local/lib/python3.7/site-packages/prefect/cli/execute.py", line 71, in cloud_flow
    storage=storage, flow_location=storage.flows[flow_data.name]
  File "/usr/local/lib/python3.7/site-packages/prefect/environments/execution/remote.py", line 68, in execute
    if self.on_start:
AttributeError: 'RemoteEnvironment' object has no attribute 'on_start'

## Expected Behavior
My flow to run and complete successfully
(Note: flow ran successfully when run locally)

## Reproduction
base_image="python:3.7", prefect_version="0.7.0"

## Environment
Core 0.7.0
Python 3.7.3

**Comment by joshmeek** [comment] 2019-11-04 22:53
Interesting error because `0.7.0` should have the proper environment callback options. cc @wagoodman wonder if this is _somehow_ related to #1698. Will try to reproduce

**Comment by cicdw** [comment] 2019-11-08 02:19
Going to close this as it appears to have been a fluke.

**Closed by cicdw** 2019-11-08 02:19 UTC
Labels: bug
