### ISSUE TITLE
Deployment doesn't apply settings from KubernetesJob only infra_overrides

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [PrefectHQ/prefect#10864] opened 2023-10-02 13:32 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When I deploy deploy with `KubernetesJob `with an custom image it creates an anonymous infra block where the image is in. However when I then run the deployment the image is not used (the standard prefect image is used instead). However if I use `infra_overrides `the image is respected.

The steps to reproduce:

1. Create work pool (called "Thomas Laptop")
2. Build Docker image with `docker build -t bugimage:1 .`
3. Start Kubernetes Agent (using local k8 cluster with Docker Desktop)
4. Run `deploy.py`
5. See that that have an anonynomus block allocated to them (note image is correct)
6. Run the deployment `onlyjob` and see it fail
7. Run the deployment `withoverwrite` and see it succed
8. Use `kubectl pod describe` to see that the image are diffrent eventhough they should be the same.

### Reproduction

```python3
## flow_file.py
from prefect import flow

@flow(name="Hello Flow")
def hello_world(name="world"):
    print(f"Hi {name}!")

## Dockerfile
FROM python:3.8-slim
COPY requirements.txt .
RUN pip install -r requirements.txt --trusted-host pypi.python.org --no-cache-dir
COPY flow_file.py /opt/prefect/flow_file.py
WORKDIR /opt/prefect

## deploy.py
from prefect.deployments import Deployment
from prefect.infrastructure import KubernetesJob
from flow_file import hello_world

path = "."
entrypoint = f'/opt/prefect/flow_file.py:{hello_world.fn.__name__}'
work_pool_name = "Thomas Laptop"

job = KubernetesJob(image="bugimage:1")

deploy1 = Deployment.build_from_flow(hello_world,
                                    "onlyjob",
                                    work_pool_name=work_pool_name,
                                    entrypoint= entrypoint,
                                    path = path, 
                                    skip_upload=True,
                                    infrastructure = job,
                                    load_existing=False)

deploy2 = Deployment.build_from_flow(hello_world,
                                    "withoverwrite",
                                    work_pool_name=work_pool_name,
                                    entrypoint= entrypoint,
                                    path = path, 
                                    skip_upload=True,
                                    infra_overrides={"image":"bugimage:1"},
                                    infrastructure = job,
                                    load_existing=False)

if __name__ == "__main__": 
    deploy1.apply()
    deploy2.apply()
```

### Error

```python3
/usr/local/lib/python3.8/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
13:25:10.880 | INFO    | Flow run 'olive-dachshund' - Downloading flow code from storage at '.'
13:25:10.958 | ERROR   | Flow run 'olive-dachshund' - Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 975, in get_code
  File "<frozen importlib._bootstrap_external>", line 1032, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/prefect/flow_file.py'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/engine.py", line 394, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/usr/local/lib/python3.8/site-packages/prefect/client/utilities.py", line 51, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/prefect/deployments/deployments.py", line 232, in load_flow_from_flow_run  
    flow = await run_sync_in_worker_thread(load_flow_from_entrypoint, str(import_path))
  File "/usr/local/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 91, in run_sync_in_worker_thread    
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread       
    return await future
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.8/site-packages/prefect/flows.py", line 1172, in load_flow_from_entrypoint
    flow = import_object(entrypoint)
  File "/usr/local/lib/python3.8/site-packages/prefect/utilities/importtools.py", line 201, in import_object
    module = load_script_as_module(script_path)
  File "/usr/local/lib/python3.8/site-packages/prefect/utilities/importtools.py", line 164, in load_script_as_module      
    raise ScriptError(user_exc=exc, path=path) from exc
prefect.exceptions.ScriptError: Script at '/opt/prefect/flow_file.py' encountered an exception: FileNotFoundError(2, 'No such file or directory')
```

### Versions

```Text
Version:             2.13.4
API version:         0.8.4
Python version:      3.8.17
Git commit:          48d9d9a2
Built:               Fri, Sep 29, 2023 11:26 AM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         cloud
```

**Comment by thomasfrederikhoeck** [comment] 2023-10-02 13:46
It also applies to other settings such as `service_account_name`. It appears it is related to all settings on `KubernetesJob``.

**Comment by zzstoatzz** [comment] 2023-10-02 14:56
hi @thomasfrederikhoeck

I cannot yet seem to reproduce this, I've got:
- prefect 2.13.4
- agent on k8s
- the following setup
```
from prefect import flow
from prefect.deployments import Deployment
from prefect.infrastructure import KubernetesJob

@flow(name="Hello Flow")
def hello_world(name="world"):
    print(f"Hi {name}!")


job = KubernetesJob(image="bugimage:1")

deploy1 = Deployment.build_from_flow(
    flow=hello_world,
    name="onlyjob",
    work_pool_name="k8s",
    skip_upload=True,
    infrastructure = job,
    load_existing=False
)

deploy2 = Deployment.build_from_flow(
    hello_world,
    "withoverwrite",
    work_pool_name="k8s",
    skip_upload=True,
    infra_overrides={"image":"bugimage:1"},
    infrastructure = job,
    load_existing=False
)

if __name__ == "__main__":
    deploy1.apply()
    deploy2.apply()
```
and when I run `deploy1`, `k describe pod resulting-flow-run-pod-xyz123`:
```
Containers:
  prefect-job:
    Container ID:
    Image:         bugimage:1
```
which gets stuck in `ImagePullBackOff` as expected.

---
can I ask why you showed this traceback?
```
FileNotFoundError: [Errno 2] No such file or directory: '/opt/prefect/flow_file.py'
```
I wonder if there is a problem with your flow file's path in the destination image, in particular, it looks like you're setting the `WORKDIR` in the dockerfile and then telling the agent that the `entrypoint` is some path `/opt/prefect/flow_file.py` with respect to the working directory at runtime, which seems it would already be `/opt/prefect` because of your dockerfile

if I'm incorrect or missing something, please let me know!

**Comment by thomasfrederikhoeck** [comment] 2023-10-02 15:06
I'm running a local k8 cluster (with Docker Desktop) so 'ImagePullBackOff' is not expected. If you have a remote k8 then tag the image accordingly,push it to a register and change the name of the image in the script. As stated above, the deployment "withoverwrites" runs successfully with the flow. So the only difference is how I specified the image - you may have read it a little to quick 😉

**Comment by zzstoatzz** [comment] 2023-10-02 15:34
i noticed this, `ImagePullBackOff` is expected for me, as I don't expect docker to find whatever `bugimage:1` is

i thought the important part was that the described pod has the `image` I specified in `job`, which is it what it seems you were suggesting was not happening

**Comment by thomasfrederikhoeck** [comment] 2023-10-02 17:41
Have you tried going through the steps to reproduce? If you go through the steps that I wrote you should defenitly have the image (step 2)? But I guess that is not that important since the problem happens earliet. Below I have the two deployments and when I inspect the pods that are created only the one stemming from the flow with overides has the correct image:

```
 C:\projects\prefect_me>prefect deployment inspect "Hello Flow/onlyjob" 
{
    'id': '7b4d987d-d1ab-4e3f-a210-b6de29ce6acf',
    'created': '2023-10-02T17:27:39.365529+00:00',
    'updated': '2023-10-02T17:27:39.361842+00:00',
    'name': 'onlyjob',
    'version': '6816e75f8589f9d5751bffaec567d1d2',
    'description': None,
    'flow_id': 'a7891fdd-14fe-4a73-8192-db55e2954e44',
    'schedule': None,
    'is_schedule_active': True,
    'infra_overrides': {},
    'parameters': {},
    'tags': [],
    'work_queue_name': 'default',
    'parameter_openapi_schema': {
        'type': 'object',
        'title': 'Parameters',
        'properties': {'name': {'title': 'name', 'default': 'world', 'position': 0}}
    },
    'path': '/opt/prefect/flows',
    'pull_steps': [],
    'entrypoint': 'tester.py:hello_world',
    'manifest_path': None,
    'storage_document_id': None,
    'infrastructure_document_id': '3f8343b2-5d2a-4fa5-abcb-6a579f3968f6',
    'created_by': {'id': 'a8d32a3b-9745-4646-9669-08f1c9cd7c04', 'type': 'USER', 'display_value': ''},        
    'updated_by': {'id': 'a8d32a3b-9745-4646-9669-08f1c9cd7c04', 'type': 'USER', 'display_value': ''},        
    'work_pool_name': 'Thomas Laptop',
    'enforce_parameter_schema': False,
    'infrastructure': {
        'type': 'kubernetes-job',
        'env': {},
        'labels': {},
        'name': None,
        'command': None,
        'image': 'bugimage:1',
        'namespace': 'default',
        'service_account_name': None,
        'image_pull_policy': None,
        'cluster_config': None,
        'job': {
            'kind': 'Job',
            'spec': {
                'template': {
                    'spec': {
                        'containers': [{'env': [], 'name': 'prefect-job'}],
                        'completions': 1,
                        'parallelism': 1,
                        'restartPolicy': 'Never'
                    }
                }
            },
            'metadata': {'labels': {}},
            'apiVersion': 'batch/v1'
        },
        'customizations': [],
        'job_watch_timeout_seconds': None,
        'pod_watch_timeout_seconds': 60,
        'stream_output': True,
        'finished_job_ttl': None,
        'block_type_slug': 'kubernetes-job'
    },
    'automations': []
}

(norden_prefect_me) C:\projects\prefect_me>prefect deployment inspect "Hello Flow/withoverwrite" 
{
    'id': 'c22e8acf-9002-45c5-ac30-acec28593fc7',
    'created': '2023-10-02T17:27:42.575103+00:00',
    'updated': '2023-10-02T17:27:42.570312+00:00',
    'name': 'withoverwrite',
    'version': '6816e75f8589f9d5751bffaec567d1d2',
    'description': None,
    'flow_id': 'a7891fdd-14fe-4a73-8192-db55e2954e44',
    'schedule': None,
    'is_schedule_active': True,
    'infra_overrides': {'image': 'bugimage:1'},
    'parameters': {},
    'tags': [],
    'work_queue_name': 'default',
    'parameter_openapi_schema': {
        'type': 'object',
        'title': 'Parameters',
        'properties': {'name': {'title': 'name', 'default': 'world', 'position': 0}}
    },
    'path': '/opt/prefect/flows',
    'pull_steps': [],
    'entrypoint': 'tester.py:hello_world',
    'manifest_path': None,
    'storage_document_id': None,
    'infrastructure_document_id': '276500c4-5d74-41b3-b9f7-2fd83a7ef5c8',
    'created_by': {'id': 'a8d32a3b-9745-4646-9669-08f1c9cd7c04', 'type': 'USER', 'display_value': ''},        
    'updated_by': {'id': 'a8d32a3b-9745-4646-9669-08f1c9cd7c04', 'type': 'USER', 'display_value': ''},        
    'work_pool_name': 'Thomas Laptop',
    'enforce_parameter_schema': False,
    'infrastructure': {
        'type': 'kubernetes-job',
        'env': {},
        'labels': {},
        'name': None,
        'command': None,
        'image': 'bugimage:1',
        'namespace': 'default',
        'service_account_name': None,
        'image_pull_policy': None,
        'cluster_config': None,
        'job': {
            'kind': 'Job',
            'spec': {
                'template': {
                    'spec': {
                        'containers': [{'env': [], 'name': 'prefect-job'}],
                        'completions': 1,
                        'parallelism': 1,
                        'restartPolicy': 'Never'
                    }
                }
            },
            'metadata': {'labels': {}},
            'apiVersion': 'batch/v1'
        },
        'customizations': [],
        'job_watch_timeout_seconds': None,
        'pod_watch_timeout_seconds': 60,
        'stream_output': True,
        'finished_job_ttl': None,
        'block_type_slug': 'kubernetes-job'
    },
    'automations': []
}
```

```
C:\Users\tfh>kubectl describe pods expert-chital-2mwmb-krf62
Name:             expert-chital-2mwmb-krf62
Namespace:        default
Priority:         0
Service Account:  default
Node:             docker-desktop/192.168.65.4
Start Time:       Mon, 02 Oct 2023 19:28:32 +0200
Labels:           batch.kubernetes.io/controller-uid=cbc898a6-3b4e-4556-ace7-9d04de3a6606
                  batch.kubernetes.io/job-name=expert-chital-2mwmb
                  controller-uid=cbc898a6-3b4e-4556-ace7-9d04de3a6606
                  job-name=expert-chital-2mwmb
Annotations:      <none>
Status:           Succeeded
IP:               10.1.0.31
IPs:
  IP:           10.1.0.31
Controlled By:  Job/expert-chital-2mwmb
Containers:
  prefect-job:
    Container ID:  docker://75c05e1f6444f82f5fe4a9ea7976e5d66cb87f11a911433245e5f383079d8871
    Image:         prefecthq/prefect:2.13.4-python3.8
    Image ID:      docker-pullable://prefecthq/prefect@sha256:c9329462b09212b8f73a9635ad183555182e8ed5e7e8be424507e4d82e398b88
    Port:          <none>
    Host Port:     <none>
    Args:
      python
      -m
      prefect.engine
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 02 Oct 2023 19:28:33 +0200
      Finished:     Mon, 02 Oct 2023 19:28:37 +0200
    Ready:          False
    Restart Count:  0
    Environment:
      PREFECT_API_URL:       
      PREFECT_API_KEY:       
      PREFECT__FLOW_RUN_ID:  d829d18553e045ad9883551e52a9bb37
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-592qm (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-592qm:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  5m6s  default-scheduler  Successfully assigned default/expert-chital-2mwmb-krf62 to docker-desktop
  Normal  Pulled     5m6s  kubelet            Container image "prefecthq/prefect:2.13.4-python3.8" already present on machine
  Normal  Created    5m6s  kubelet            Created container prefect-job
  Normal  Started    5m6s  kubelet            Started container prefect-job

C:\Users\tfh>kubectl describe pods icy-anteater-zwrkt-5stw5
Name:             icy-anteater-zwrkt-5stw5
Namespace:        default
Priority:         0
Service Account:  default
Node:             docker-desktop/192.168.65.4
Start Time:       Mon, 02 Oct 2023 19:28:32 +0200
Labels:           batch.kubernetes.io/controller-uid=32885526-4bc7-4afa-affd-f826aa6ebd19
                  batch.kubernetes.io/job-name=icy-anteater-zwrkt
                  controller-uid=32885526-4bc7-4afa-affd-f826aa6ebd19
                  job-name=icy-anteater-zwrkt
Annotations:      <none>
Status:           Succeeded
IP:               10.1.0.32
IPs:
  IP:           10.1.0.32
Controlled By:  Job/icy-anteater-zwrkt
Containers:
  prefect-job:
    Container ID:  docker://e912528ee52ef8bf47b4caf56dd70a15519c90920a6db1bea64d9fae682ea9d3
    Image:         bugimage:1
    Image ID:      docker://sha256:5a483a70218cbea7859f1b7c324aeaf9254273a176ecafcfe4971a6e7964bcf8
    Port:          <none>
    Host Port:     <none>
    Args:
      python
      -m
      prefect.engine
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 02 Oct 2023 19:28:33 +0200
      Finished:     Mon, 02 Oct 2023 19:28:37 +0200
    Ready:          False
    Restart Count:  0
    Environment:
      PREFECT_API_URL:       
      PREFECT_API_KEY:       
      PREFECT__FLOW_RUN_ID:  19aa9de5d33646c0a3edc54b83848b2d
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-czpsf (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-czpsf:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  4m57s  default-scheduler  Successfully assigned default/icy-anteater-zwrkt-5stw5 to docker-desktop
  Normal  Pulled     4m57s  kubelet            Container image "bugimage:1" already present on machine
  Normal  Created    4m57s  kubelet            Created container prefect-job
  Normal  Started    4m57s  kubelet            Started container prefect-job

```

**Comment by thomasfrederikhoeck** [comment] 2023-10-02 17:44
> > So the only difference is how I specified the image
> 
> i noticed this, `ImagePullBackOff` is expected for me, as I don't expect docker (also running k8s on docker-desktop) to find whatever `bugimage:1` is
> 
> i thought the important part was that the described pod has the `image` I specified in `job`, which is what it seems you were suggesting was not happening without `infra_overrides`
> 
> can you share the output of `prefect deployment inspect your-deployment` and if possible, clarify why you shared the `FileNotFound` traceback?

Are you seeing the ImagePullBackOff  for both deployments?

**Comment by thomasfrederikhoeck** [comment] 2023-10-02 18:35
No I started the worker with `prefect worker start` locally.

**Comment by zzstoatzz** [comment] 2023-10-02 18:56
aha - you can't use workers with infra blocks. if you're stuck with infra blocks for now, you should use `prefect agent start ...`

**Comment by thomasfrederikhoeck** [comment] 2023-10-02 19:33
Ah then it all makes sense :-) I guess an error there would make sense since comming from prefect 1.x I would expect that I need some kind of KubernetesJob to get it up an running. 

I will use workers, ditch KubernetesJob  and stick to overwrites.

**Comment by zzstoatzz** [comment] 2023-10-02 19:43
great! feel free to reach out in community if you have any trouble getting going with workers - closing this issue

**Closed by zzstoatzz** 2023-10-02 19:43 UTC
Labels: bug, needs:triage

**Comment by thomasfrederikhoeck** [comment] 2023-10-02 19:55
@zzstoatzz If I wanted to define my k8 job template inside my code instead of in UI I would need to stick with intra?

**Comment by zzstoatzz** [comment] 2023-10-02 21:41
@thomasfrederikhoeck - not necessarily

you can define reusable work pool overrides in your `prefect.yaml` that you can apply to one or many deployments (to override the default job template for that worker type, e.g. "kubernetes")

alternatively there's [this](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/client/orchestration.py#L2293) client method if you really need to programmatically update the work pool directly
