### ISSUE TITLE
flatten should handle SKIP signals

### ISSUE THREAD

**Issue by dylanbhughes** [PrefectHQ/prefect#4566] opened 2021-05-21 14:45 UTC
```python
from prefect import task, Flow, flatten
from prefect.engine.signals import SKIP


@task
def return_a_list():
    return [2, 4, 6, 8]


@task
def make_list_of_lists_or_skip(input_item):
    if input_item % 2 == 0:
        raise SKIP("even thing")

    return [(input_item, input_item * 2), (input_item, input_item * 2)]


@task
def do_additional_thing(input_item):
    return input_item[0] + input_item[1]


with Flow("my flow") as flow:
    my_list = return_a_list()
    transformed_list = make_list_of_lists_or_skip.map(my_list)
    result = do_additional_thing.map(flatten(transformed_list))
```

## Current behavior

The flow above fails with:
```
Python 3.8.10 (default, May 19 2021, 11:01:55)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.23.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: flow.run()
[2021-05-21 10:43:13-0400] INFO - prefect.FlowRunner | Beginning Flow run for 'my flow'
[2021-05-21 10:43:13-0400] INFO - prefect.TaskRunner | Task 'return_a_list': Starting task run...
[2021-05-21 10:43:13-0400] INFO - prefect.TaskRunner | Task 'return_a_list': Finished task run for task with final state: 'Success'
[2021-05-21 10:43:13-0400] INFO - prefect.TaskRunner | Task 'make_list_of_lists_or_skip': Starting task run...
[2021-05-21 10:43:13-0400] INFO - prefect.TaskRunner | Task 'make_list_of_lists_or_skip': Finished task run for task with final state: 'Mapped'
[2021-05-21 10:43:13-0400] INFO - prefect.TaskRunner | Task 'make_list_of_lists_or_skip[0]': Starting task run...
[2021-05-21 10:43:13-0400] INFO - prefect.TaskRunner | SKIP signal raised: SKIP('even thing')
[2021-05-21 10:43:13-0400] INFO - prefect.TaskRunner | Task 'make_list_of_lists_or_skip[0]': Finished task run for task with final state: 'Skipped'
[2021-05-21 10:43:13-0400] INFO - prefect.TaskRunner | Task 'make_list_of_lists_or_skip[1]': Starting task run...
[2021-05-21 10:43:13-0400] INFO - prefect.TaskRunner | SKIP signal raised: SKIP('even thing')
[2021-05-21 10:43:13-0400] INFO - prefect.TaskRunner | Task 'make_list_of_lists_or_skip[1]': Finished task run for task with final state: 'Skipped'
[2021-05-21 10:43:14-0400] INFO - prefect.TaskRunner | Task 'make_list_of_lists_or_skip[2]': Starting task run...
[2021-05-21 10:43:14-0400] INFO - prefect.TaskRunner | SKIP signal raised: SKIP('even thing')
[2021-05-21 10:43:14-0400] INFO - prefect.TaskRunner | Task 'make_list_of_lists_or_skip[2]': Finished task run for task with final state: 'Skipped'
[2021-05-21 10:43:14-0400] INFO - prefect.TaskRunner | Task 'make_list_of_lists_or_skip[3]': Starting task run...
[2021-05-21 10:43:14-0400] INFO - prefect.TaskRunner | SKIP signal raised: SKIP('even thing')
[2021-05-21 10:43:14-0400] INFO - prefect.TaskRunner | Task 'make_list_of_lists_or_skip[3]': Finished task run for task with final state: 'Skipped'
[2021-05-21 10:43:14-0400] INFO - prefect.TaskRunner | Task 'do_additional_thing': Starting task run...
[2021-05-21 10:43:14-0400] INFO - prefect.TaskRunner | Task 'do_additional_thing': Finished task run for task with final state: 'Mapped'
[2021-05-21 10:43:14-0400] ERROR - prefect.FlowRunner | Unexpected error: TypeError("object of type 'SKIP' has no len()")
Traceback (most recent call last):
  File "/Users/dylanhughes/miniconda3/envs/arrowstreet_flow/lib/python3.8/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/Users/dylanhughes/miniconda3/envs/arrowstreet_flow/lib/python3.8/site-packages/prefect/engine/flow_runner.py", line 569, in get_flow_run_state
    executors.prepare_upstream_states_for_mapping(
  File "/Users/dylanhughes/miniconda3/envs/arrowstreet_flow/lib/python3.8/site-packages/prefect/utilities/executors.py", line 494, in prepare_upstream_states_for_mapping
    mapped_children[edge.upstream_task] = flatten_mapped_children(
  File "/Users/dylanhughes/miniconda3/envs/arrowstreet_flow/lib/python3.8/site-packages/prefect/utilities/executors.py", line 584, in flatten_mapped_children
    [executor.submit(lambda c: len(c._result.value), c) for c in mapped_children]
  File "/Users/dylanhughes/miniconda3/envs/arrowstreet_flow/lib/python3.8/site-packages/prefect/utilities/executors.py", line 584, in <listcomp>
    [executor.submit(lambda c: len(c._result.value), c) for c in mapped_children]
  File "/Users/dylanhughes/miniconda3/envs/arrowstreet_flow/lib/python3.8/site-packages/prefect/executors/local.py", line 28, in submit
    return fn(*args, **kwargs)
  File "/Users/dylanhughes/miniconda3/envs/arrowstreet_flow/lib/python3.8/site-packages/prefect/utilities/executors.py", line 584, in <lambda>
    [executor.submit(lambda c: len(c._result.value), c) for c in mapped_children]
TypeError: object of type 'SKIP' has no len()
[2021-05-21 10:43:14-0400] ERROR - prefect.my flow | Unexpected error occured in FlowRunner: TypeError("object of type 'SKIP' has no len()")
Out[1]: <Failed: "Unexpected error: TypeError("object of type 'SKIP' has no len()")">
```

## Proposed behavior

It would be awesome if there was a way for flatten to know that all upstream tasks were skipped and to allow the flow to continue.

**Comment by madkinsz** [comment] 2021-05-24 22:48
Duplicate of https://github.com/PrefectHQ/prefect/issues/4084

**Closed by madkinsz** 2021-05-24 22:48 UTC
Labels: enhancement
