### ISSUE TITLE
Expose task inputs to state handlers

### ISSUE THREAD

**Issue by peterroelants** [PrefectHQ/prefect#4039] opened 2021-02-01 09:06 UTC
## Current behavior
Currently a failed task state will have no references to the inputs of that task.

## Proposed behavior
Add a task's input to the failed state so the information can be used in any state/failure handlers.

## Example
E.g. I have a task that processes some data, when the task fails I would like to try sending a message over a Kafka topic and write to a database table referencing the data ID that has been part of the original Task's input.
Currently I'm dealing with this by capturing the exception myself and raising a new Signal that has a reference to the input data. This seems to be some "negative engineering" that could be done by Prefect. ([relevant Slack Thread](https://prefect-community.slack.com/archives/CL09KU1K7/p1611846885380500)).

**Comment by peterroelants** [comment] 2021-02-01 09:12
To deal with this at the moment, I created a method decorator that takes care of capturing the Exception, creating a signal hydrated with the Task's inputs, and raising the signal from the exception:

```python
import functools

from prefect.engine import signals


def hydrate_exception_with_inputs(func):
    """
    Method decorator to catch exceptions and re-reise them as a failed signal that encapsulates the exception as well
    as the task run input.
    """
    @functools.wraps(func)
    def wrapper_hydrate_exception_with_inputs(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except Exception as ex:
            fail_signal = signals.FAIL(repr(ex))
            fail_signal.task_inputs = kwargs
            fail_signal.exception = ex
            raise fail_signal from ex
    return wrapper_hydrate_exception_with_inputs
```

I then use this to annotate my Task's `run` method like so:

```python
class SomeTask(prefect.Task):
    @hydrate_exception_with_inputs
    def run(args):
         ...
```

**Comment by peterroelants** [comment] 2021-02-01 09:19
I'm not yet fully familar with the code base, however it seems that [`task_runner.py:318`](https://github.com/PrefectHQ/prefect/blob/db0f6521f9fad3891b885aaa961c0462d61f2692/src/prefect/engine/task_runner.py#L318) could be the place to add `task_inputs`.

**Comment by jcrist** [comment] 2021-05-24 20:15
Duplicate of #3921, closing.

**Closed by jcrist** 2021-05-24 20:15 UTC
Labels: enhancement
