### ISSUE TITLE
validation error for ParsingModel

### ISSUE THREAD

**Issue by mikkelduif** [PrefectHQ/prefect#6064] opened 2022-07-26 09:52 UTC
## Description
I cannot list `CANCELLED` flowruns.

## Reproduction / Example
```bash
❯ prefect flow-run ls --limit 1 --state-type CANCELLED
Traceback (most recent call last):
  File "./.venv/lib/python3.10/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "./.venv/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 193, in wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
  File "./.venv/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 140, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
  File "./.venv/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "./.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "./.pyenv/versions/3.10.5/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "./.pyenv/versions/3.10.5/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "./.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "./.venv/lib/python3.10/site-packages/prefect/cli/flow_run.py", line 55, in ls
    flow_runs = await client.read_flow_runs(
  File "./.venv/lib/python3.10/site-packages/prefect/client.py", line 1495, in read_flow_runs
    return pydantic.parse_obj_as(List[schemas.core.FlowRun], response.json())
  File "pydantic/tools.py", line 38, in pydantic.tools.parse_obj_as
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[List[prefect.orion.schemas.core.FlowRun]]
__root__
  none is not an allowed value (type=type_error.none.not_allowed)
An exception occurred.
```

**Comment by bunchesofdonald** [comment] 2022-08-08 17:49
This appears to be a duplicate of #6229, closing this one as the other has a few more details. Thanks for the report!

**Closed by bunchesofdonald** 2022-08-08 17:49 UTC
Labels: status:duplicate, v2
