### ISSUE TITLE
Allow for ShellTask to stream output with logging level is INFO

### ISSUE THREAD

**Issue by pedrounas** [PrefectHQ/prefect#4231] opened 2021-03-09 15:57 UTC
## Current behavior
The ShellTask supports output streaming using the `stream_output = True` flag and by setting the logging level to debug using the environment variable `PREFECT__LOGGING__LEVEL=DEBUG`.

## Proposed behavior
Allow for the output to be streamed when the logging level is set to info by switching the `stream_output` flag to work with INFO logging level and introducing an alternative flag like `debug_output` to stream the output in DEBUG logging level.

## Example
When calling R Scripts that contain loggers using Prefect its not ideal to have to change the debug level in Prefect as it clutters the output of the flow and can hide the R logs.

## Proposed change

```python
  with Popen(
      [self.shell, tmp.name], stdout=PIPE, stderr=STDOUT, env=current_env
  ) as sub_process:
      line = None
      lines = []
      for raw_line in iter(sub_process.stdout.readline, b""):
          line = raw_line.decode("utf-8").rstrip()

          if self.return_all:
              lines.append(line)

          if self.stream_output:
              self.logger.info(line)
         
          if self.debug_output:
              self.logger.debug(line)

      sub_process.wait()
```

**Comment by pedrounas** [comment] 2021-03-09 15:59
Relates to #3865

**Comment by madkinsz** [comment] 2021-03-09 16:02
I'm going to close this as a duplicate of #3865 as I think `stream_output` should remain a single kwarg. I think it'd be reasonable for the default to be changed to `INFO` as well. Thanks for taking the time to add to this though :) more use-case / context is valuable.

**Comment by jcrist** [comment] 2021-03-31 16:05
Actually closing :)

**Closed by jcrist** 2021-03-31 16:05 UTC
Labels: enhancement
