### ISSUE TITLE
Flow cancellation should optionally cascade down to sub-deployments - halting subflow execution

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#10947] opened 2023-10-13 01:25 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

For worker based deployments, sub-deployment patterns, and further, task-wrapped deployment patterns are common.

Ideally there is an option to cascade cancellation of the child deployments so they terminated when the parent deployment gets canceled.

For reproduction steps, head to this repo:
https://github.com/taylor-curran/sub-deployment-qa

I use a k8s worker for this example. My flow contains task-wrapped sub deployments.

`prefect deployment run task-wrapped-deployments/task-wrapped-k8s --param sleep_time_subflows=120`

Here is my flow when it is not canceled:
![image](https://github.com/PrefectHQ/prefect/assets/68969861/221e98f3-2b20-4e63-aae5-b131f9787d27)

Here is the behavior of the flow when it is canceled around 45 seconds in:
https://app.prefect.cloud/account/9b649228-0419-40e1-9e0d-44954b5c0ab6/workspace/b3b50f1c-14d4-4452-ba36-6218816cca21/flow-runs/flow-run/817545bf-b23c-4235-afe1-60c14932b55f

![image](https://github.com/PrefectHQ/prefect/assets/68969861/80174ef0-6e3b-4d78-a384-042edb3d8ab3)

The UI diagram is deceptive and inaccurate -- cancellation of the sub-deployments is shown but does not occur if you watch the execution environment:

Before cancellation of `mini-anteater` parent flow:
```
NAME                        READY   STATUS    RESTARTS   AGE
mini-anteater-x4cjd-k445z   1/1     Running   0          65s
rapid-axolotl-7cp6s-fmxtj   1/1     Running   0          53s
real-hippo-5rmwq-mggr5      1/1     Running   0          53s
urban-locust-m696w-m7slp    1/1     Running   0          53s
```
After cancellation:
```
NAME                        READY   STATUS        RESTARTS   AGE
mini-anteater-x4cjd-k445z   1/1     Terminating   0          67s
rapid-axolotl-7cp6s-fmxtj   1/1     Running       0          55s
real-hippo-5rmwq-mggr5      1/1     Running       0          55s
urban-locust-m696w-m7slp    1/1     Running       0          55s
```
2 minutes in, the subflow pods are still shown to be running:
```
NAME                        READY   STATUS    RESTARTS   AGE
rapid-axolotl-7cp6s-fmxtj   1/1     Running   0          2m9s
real-hippo-5rmwq-mggr5      1/1     Running   0          2m9s
urban-locust-m696w-m7slp    1/1     Running   0          2m9s
```
And complete at around 2 minutes 11 seconds:
```
NAME                        READY   STATUS      RESTARTS   AGE
rapid-axolotl-7cp6s-fmxtj   0/1     Completed   0          2m11s
real-hippo-5rmwq-mggr5      0/1     Completed   0          2m11s
urban-locust-m696w-m7slp    0/1     Completed   0          2m11s
```

### Describe the proposed behavior

Cascading cancellation behavior becomes an option. 

### Example Use Case

Lack of this feature has become troublesome to our users: 
> because if we are to retry the sub-flow from the UI in that time period, a new K8s pod would be created and we would have 2 pods running essentially the same flow run (and a ton of weird behavior)

### Additional context

Related: #9738

prefect version:
```
Version:             2.13.6
API version:         0.8.4
Python version:      3.10.13
Git commit:          8996e4a4
Built:               Thu, Oct 12, 2023 3:54 PM
OS/Arch:             darwin/arm64
Profile:             prefect-patterns
Server type:         cloud
```

**Comment by taylor-curran** [comment] 2023-10-13 01:27
Experimental Solution Here:
#10920

**Comment by serinamarie** [comment] 2023-10-13 22:01
Hi @taylor-curran, I believe that this is a duplicate of https://github.com/PrefectHQ/prefect/issues/10339 (which was closed).

**Comment by desertaxle** [comment] 2023-10-26 20:34
Our cancellation cleanup service marks the sub-flow runs of cancelled flow runs as `CANCELLED`. This causes workers, agents, and runners not to tear down infra because they poll for `CANCELLING` flow runs. I think updating our cancellation service to mark sub-flow runs resulting from another deployment run as `CANCELLING` will enable infrastructure cleanup to proceed as expected.

**Closed** 2023-10-30 14:55 UTC
Labels: enhancement, from:sales
