### ISSUE TITLE
Manually created `Constant` task is not returned with `flow.tasks`

### ISSUE THREAD

**Issue by AndrewLim1990** [PrefectHQ/prefect#1908] opened 2020-01-10 20:52 UTC
## Description
I have manually created a `Constant` task and added it to a `Flow`. However, the flow does not return it when I execute `flow.tasks`. Here is some code to replicate the bug:

```
from prefect import task, Flow
from prefect.tasks.core.constants import Constant

@task
def do_nothing(arg):
    pass

with Flow("constants") as flow:
    do_nothing(Constant({"x": 1, "y": [9, 10]}, name='asdf'))

flow.tasks
```

The code above returns: `{<Task: do_nothing>}`

## Expected Behavior

I expected to have `{<Task: do_nothing>, <Task: asdf>}` returned as shown in [this prefect tutorial](https://docs.prefect.io/core/tutorials/task-guide.html) in the "Auto-generation of Tasks" example

## Environment
I am using `prefect==0.8.1`

**Comment by cicdw** [comment] 2020-01-10 20:54
Thank you for the simple reproducible example @AndrewLim1990 !  I can recreate it - looking into a fix right now...

**Comment by AndrewLim1990** [comment] 2020-01-10 21:09
Thank you!

**Comment by cicdw** [comment] 2020-01-10 21:27
So I've identified what's going on: previously we autogenerated many `Constant` tasks and they ended up polluting both the Flow Visualization diagrams as well as the logs (because they were submitted for execution but obviously don't need to "run").

Consequently, we have this line of code: https://github.com/PrefectHQ/prefect/blob/master/src/prefect/core/flow.py#L818-L819

Lines are:
```python
if isinstance(t, prefect.tasks.core.constants.Constant) and not is_mapped:
    self.constants[task].update({key: t.value})
```

You can find your dictionary (unnamed) in `flow.constants`.  

There are two routes forward here:
- you can elevate your `Constant` to a `Parameter` with a default value of `{"x": 1, "y": [9, 10]}` and name of `asdf` and it will behave as you're expecting here
- we can update the code to allow for users to opt-out of this "constants unpacking" so that it shows up in your Flow's tasks 

I'd be interested to hear your thoughts / expectations here;  and either way, we should update the tutorial!

**Comment by AndrewLim1990** [comment] 2020-01-13 18:21
Thanks for the help! I ended up using the first route you mentioned above. In my mind, perhaps a good route forward is to be referenced by name w/ `flow.constants`.

**Comment by lauralorenz** [comment] 2020-04-09 18:45
Closing this for now as the OP seems to have been resolved. If you're still interested in more conversation about exposing constants by name, feel free to open a new issue. Thanks!

**Closed by lauralorenz** 2020-04-09 18:45 UTC
