### ISSUE TITLE
Tags on flow runs created without a deployment

### ISSUE THREAD

**Issue by tekumara** [PrefectHQ/prefect#10386] opened 2023-08-11 07:32 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Flow runs can only be tagged from a Deployment.

### Describe the proposed behavior

Flows that aren't run from a deployment can be tagged, eg:

```python
@flow(tags="awesome-flow")
def embed(env: str) -> None:
```

### Example Use

Allows grouping of flows by tags, when flows are run outside deployment. Makes it easier to filter by these flows in the UI.

**Comment by serinamarie** [comment] 2023-08-11 18:59
I think this may be a duplicate of https://github.com/PrefectHQ/prefect/issues/9078

**Comment by serinamarie** [comment] 2023-08-14 16:28
Hi @tekumara, thanks for the issue! This seems related to but not a duplicate of https://github.com/PrefectHQ/prefect/issues/9078
We would need to discuss this as a team to determine if this is feasible, but my hunch is that it may not be as tag is a field on deployment, not flow.

**Comment by tekumara** [comment] 2023-08-15 10:53
Hi @serinamarie, @EmilRex pointed me to [this syntax](https://docs.prefect.io/2.11.3/api-ref/prefect/context/?h=#prefect.context.tags):
```python
@flow
def my_flow():
    pass
with tags("a", "b"):
    my_flow()  # has tags: a, b
```
which tags the flow run .. so does what I want! 

The proposed syntax above (ie: via the `@flow` decorator) would still be nice for consistency with `@task`, if its possible.

**Comment by tekumara** [comment] 2023-08-15 10:55
Hi @serinamarie, @EmilRex pointed me to [this syntax](https://docs.prefect.io/2.11.3/api-ref/prefect/context/?h=#prefect.context.tags):
```python
@flow
def my_flow():
    pass
with tags("a", "b"):
    my_flow()  # has tags: a, b
```
which tags the flow run .. so does what I want! 

The proposed syntax above (ie: via the `@flow` decorator) would still be nice for consistency with `@task`, if its possible.

**Comment by OptimeeringBigya** [comment] 2023-08-15 13:33
@serinamarie Just wanted to confirm - the database table `flow` does have column `tags`. I am wondering what is that column used for if flow no longer supports tags.

**Comment by desertaxle** [comment] 2023-09-20 14:25
The duplicate issue #9078 was closed with this feature performing as designed. I am going to close this issue for the same reason. Please refer to #9078 for the reasoning.

**Closed by desertaxle** 2023-09-20 14:25 UTC
Labels: enhancement, needs:triage, from:sales
