### ISSUE TITLE
Custom flow run env variables

### ISSUE THREAD

**Issue by Bada-S** [PrefectHQ/prefect#10919] opened 2023-10-09 16:08 UTC
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently on a custom run you can set parameters, tags, and retries

### Describe the proposed behavior

It would be helpful to set env variables as well. This may be particularly useful for users that heavily rely on env variables to configure workflows from different environments and they want to debug or test flows without creating a new deployment. This feature is something that is supported in cloud 1 custom run - advanced run configurations.

### Example Use

A user has different env variables set on their dev, staging, and prod workspaces. They want to test a custom run in dev and they need to change one of their job configs.

**Comment by zzstoatzz** [comment] 2023-10-10 01:37
I believe this is a duplicate of #9893, since allowing infrastructure overrides at the flow-run level would allow you to patch the `env` on a given work pool for a given custom run - does that sound accurate @Bada-S?

**Closed** 2023-10-10 14:50 UTC
Labels: status:duplicate, enhancement
